"use client";
import {useState} from 'react';
import {Download,MapPinned} from 'lucide-react';
import type {Portfolio} from '../lib/locations';
import {buildAtakKml,makeKmz,defaultAtakOptions,type AtakRecord,type AtakOptions} from '../lib/atak';
export default function AtakExport({portfolio,records,dirty}:{portfolio:Portfolio;records:AtakRecord[];dirty:boolean}){
 const [options,setOptions]=useState(defaultAtakOptions),[format,setFormat]=useState('kmz'),[preview,setPreview]=useState<(ReturnType<typeof buildAtakKml>&{screen:string;settings:string})|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const screen=JSON.stringify(portfolio),settings=JSON.stringify(options),changed=!!preview&&(preview.screen!==screen||preview.settings!==settings);
 async function inspect(){setBusy(true);setError('');setPreview(null);setNotice('');await new Promise(resolve=>setTimeout(resolve,0));try{const result=buildAtakKml(portfolio,options,records);setPreview({...result,screen,settings});}catch(e){setError(e instanceof Error?e.message:'Export could not be prepared.');}finally{setBusy(false);}}
 function download(){if(!preview||changed)return;const blob=format==='kmz'?new Blob([makeKmz(preview.kml) as BlobPart],{type:'application/vnd.google-earth.kmz'}):new Blob([preview.kml],{type:'application/vnd.google-earth.kml+xml'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='field-desk-atak-'+preview.createdAt.replace(/[:.]/g,'-')+'.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Export download started. Transfer the file to your Android device and import it in ATAK.');}
 const fields:[keyof AtakOptions,string][]=[['locations','Location pins'],['boundaries','AOR / AOI boundaries'],['namedAreas','Named locations & areas'],['observations','Field observations'],['routes','Routes & route features'],['radio','Saved radio frequencies in location folders'],['details','Notes, source links, dates & confidence'],['addresses','Street-address labels on location pins'],['publicLayers','Currently visible public map layers']];
 return <section className="atak-content"><div className="row"><div><span className="eyebrow">PORTABLE MAP OVERLAY</span><h2>Export to ATAK</h2></div><MapPinned size={25}/></div><p>Download a KML or KMZ snapshot for ATAK’s Import Manager. No TAK server is needed. KMZ contains one self-contained KML file, with no remote icons or network links.</p><article className="backup-card"><h3>Choose what to export</h3><div className="atak-settings"><label>Study scope<select value={options.allLocations?'all':'active'} onChange={e=>setOptions({...options,allLocations:e.target.value==='all'})}><option value="active">Active location</option><option value="all">Whole study</option></select></label><label>Format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="kmz">KMZ · ATAK overlay</option><option value="kml">KML · plain XML</option></select></label></div><div className="atak-options">{fields.map(([key,label])=><label key={key}><input type="checkbox" checked={options[key]} onChange={e=>setOptions({...options,[key]:e.target.checked})}/>{label}{key==='publicLayers'&&<small>{records.length.toLocaleString()} visible records available, for the active location only.</small>}</label>)}</div><p className="help">{dirty?'Includes unsaved on-screen study edits.':'Includes the current on-screen study.'} Files contain the selected private coordinates and notes. Street-address labels are off by default; names and notes can still contain addresses. Review the scope before sharing.</p><button onClick={inspect} disabled={busy}>{busy?'Preparing overlay…':'Preview export'}</button>{error&&<p role="alert" className="notice">{error}</p>}</article>
 {preview&&<article className="backup-card"><h3>Export preview</h3><p className="help">Snapshot captured at preview time. Later public-feed refreshes do not change this file.</p><p>{preview.features.toLocaleString()} map features · {preview.vertices.toLocaleString()} coordinates · {(preview.bytes/1024).toFixed(0)} KB of KML</p><div className="backup-table"><table><thead><tr><th>Content</th><th>Count</th></tr></thead><tbody>{Object.entries(preview.counts).map(([name,count])=><tr key={name}><th>{({namedAreas:'Named areas',routeFeatures:'Route features',publicRecords:'Public records'})[name as 'namedAreas']||name}</th><td>{count}</td></tr>)}</tbody></table></div>{preview.warnings.map((w,i)=><p className="help" key={i}>{w}</p>)}{changed&&<p className="notice">Study or export settings changed. Preview again before downloading.</p>}<button className="primary" disabled={changed||busy} onClick={download}><Download size={16}/>Download {format.toUpperCase()}</button><p role="status" className="help">{notice}</p></article>}
 <article className="backup-card"><h3>Import into ATAK</h3><ol><li>Transfer the downloaded file to the Android device.</li><li>Open ATAK’s Import Manager and select the local KML/KMZ file.</li><li>Open Overlay Manager to enable and inspect the imported overlay.</li></ol><p className="help">Routes are overlay lines, rather than native navigation routes. Frequencies are folder descriptions, not transmitter pins or radio programming files. Basemap tiles, attachments, live updates and full study restoration are not included. Keep a complete backup for restoring Field Desk. Test the overlay on your installed ATAK version before relying on it in the field.</p><a href="https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/blob/main/VERSION.md" target="_blank" rel="noreferrer">ATAK KML/KMZ support</a></article></section>;
}
