"use client";
import {collectionFetch} from '../lib/collection-activity';
import {useEffect,useRef,useState} from 'react';
import {coordinateAddress,parseDirectionsLink,type RoadRoute} from '../lib/road-routing';
import {directionsUrl,type LocationEndpoint} from '../lib/location-core';
import type {Point} from '../lib/geo';
import type {StudyRoute} from '../lib/routes';
type AddressMatch={matchedAddress:string;coordinates:{x:number;y:number}};
type Side={id:string;address:string;point:Point|null;matches:AddressMatch[]};
type Candidate={road:RoadRoute;fromLabel:string;toLabel:string;fromId?:string;toId?:string;added?:boolean};
const initial=(id:string):Side=>({id,address:'',point:null,matches:[]});
export default function AutomaticRoutes({endpoints,add,limit=false,slots=100}:{endpoints:LocationEndpoint[];add:(route:StudyRoute)=>void;limit?:boolean;slots?:number}){
 const [from,setFrom]=useState<Side>(initial('home')),[to,setTo]=useState<Side>(initial('')),[candidates,setCandidates]=useState<Candidate[]>([]),[busy,setBusy]=useState(''),[error,setError]=useState(''),[link,setLink]=useState('');
 const controller=useRef<AbortController|null>(null);useEffect(()=>()=>controller.current?.abort(),[]);
 function resolve(side:Side){const location=endpoints.find(l=>l.id===side.id);return side.id==='address'?(side.point?{point:side.point,label:side.address}:null):location?.home?{point:location.home.point,label:location.name,id:location.id}:null;}
 const origin=resolve(from),destination=resolve(to);
 function edit(which:'from'|'to',side:Side){controller.current?.abort();setBusy('');setError('');setCandidates([]);(which==='from'?setFrom:setTo)(side);}
 async function findAddress(which:'from'|'to',side:Side){
  const point=coordinateAddress(side.address);if(point){edit(which,{...side,point,matches:[]});return;}
  controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy(which);setError('');
  try{const r=await collectionFetch('/api/address?'+new URLSearchParams({q:side.address}),{signal:abort.signal});const d=await r.json() as {error?:string;matches?:AddressMatch[]};if(!r.ok)throw Error(d.error||'Address lookup failed');if(!d.matches?.length)throw Error('No Census address match. Check the address or use a saved location with a verified map pin.');if(!abort.signal.aborted)(which==='from'?setFrom:setTo)({...side,matches:d.matches});}
  catch(e){if(!abort.signal.aborted)setError((e as Error).message);}finally{if(controller.current===abort)setBusy('');}
 }
 async function generate(){
  if(!origin||!destination)return;controller.current?.abort();const abort=new AbortController();controller.current=abort;setBusy('route');setError('');setCandidates([]);
  try{const r=await collectionFetch('/api/road-routes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from:origin.point,to:destination.point}),signal:abort.signal});const d=await r.json() as {routes?:RoadRoute[];error?:string};if(!r.ok)throw Error(d.error||'Routing failed');if(!abort.signal.aborted)setCandidates((d.routes||[]).map(road=>({road,fromLabel:origin.label,toLabel:destination.label,fromId:'id' in origin?origin.id:undefined,toId:'id' in destination?destination.id:undefined})));}
  catch(e){if(!abort.signal.aborted)setError((e as Error).message);}finally{if(controller.current===abort)setBusy('');}
 }
 function useLink(){try{const pair=parseDirectionsLink(link);edit('from',{id:'address',address:pair.from,point:coordinateAddress(pair.from),matches:[]});edit('to',{id:'address',address:pair.to,point:coordinateAddress(pair.to),matches:[]});}catch(e){setError((e as Error).message);}}
 return <div className="automatic-routes"><h3>Generate a driving route</h3><div className="route-addresses">{([['from','From',from],['to','To',to]] as const).map(([which,label,side])=><div key={which}><label>{label}<select value={side.id} onChange={e=>edit(which,initial(e.target.value))}><option value="">Choose location</option>{endpoints.map(l=><option key={l.id} value={l.id}>{l.name}{!l.home?' · pin needed':''}</option>)}<option value="address">Enter another address</option></select></label>{side.id==='address'&&<><label>{label} address<input maxLength={240} value={side.address} placeholder="Street address, city, state, ZIP" onChange={e=>edit(which,{...side,address:e.target.value,point:null,matches:[]})}/></label><button disabled={!side.address.trim()||!!busy} onClick={()=>findAddress(which,side)}>{busy===which?'Finding address…':`Find ${label.toLowerCase()} address`}</button>{side.matches.map(m=><button className="address-match" key={m.matchedAddress+String(m.coordinates.x)} onClick={()=>edit(which,{...side,address:m.matchedAddress,point:[m.coordinates.y,m.coordinates.x],matches:[]})}>{m.matchedAddress}</button>)}{side.point&&<p className="help">Address selected: {side.address}</p>}</>}</div>)}</div>
 <details className="directions-import"><summary>Use endpoints from a Google Maps link</summary><label>Full directions URL<input value={link} maxLength={4000} placeholder="https://www.google.com/maps/dir/…" onChange={e=>setLink(e.target.value)}/></label><button disabled={!link.trim()||!!busy} onClick={useLink}>Use these endpoints</button><p className="help">Imports the origin and destination. Select address matches if needed, then generate the road route here. Google’s selected path, stops and traffic estimates are not imported. Open shortened links in Google Maps first.</p></details>
 <div className="location-actions"><button className="primary" disabled={!origin||!destination||!!busy||limit} onClick={generate}>{busy==='route'?'Generating routes…':'Generate routes'}</button>{origin&&destination&&<a className="button" target="_blank" rel="noreferrer" href={directionsUrl(origin.point,destination.point)}>Open Google Maps directions</a>}</div>
 {busy&&<button onClick={()=>{controller.current?.abort();setBusy('');}}>Cancel</button>}{error&&<p className="notice" role="alert">{error}</p>}{limit&&<p className="notice">The study has reached its limit of 100 routes.</p>}
 {candidates.length>1&&<button disabled={limit||candidates.filter(c=>!c.added).length>slots||candidates.every(c=>c.added)} onClick={()=>{candidates.filter(c=>!c.added).forEach((c,i)=>add({id:crypto.randomUUID(),name:`${c.fromLabel} to ${c.toLabel}${i?` · alternative ${i}`:''}`.slice(0,160),destination:c.toLabel.slice(0,160),role:i===0?'Primary':'Alternate',fromLocationId:c.fromId,toLocationId:c.toId,points:c.road.points,routing:c.road.routing,notes:'',marks:[]}));setCandidates(prior=>prior.map(c=>({...c,added:true})));}}>Add all route options to study</button>}<div className="generated-routes">{candidates.map((c,i)=><article key={i}><h4>{i===0?'Suggested driving route':`Driving alternative ${i}`}</h4><p>{(c.road.routing.distanceMetres/1609.344).toFixed(1)} miles · approximately {Math.round(c.road.routing.durationSeconds/60)} minutes</p><p className="help">Road-network estimate, without live traffic or closure avoidance.</p>{Math.max(c.road.routing.snapOriginMetres,c.road.routing.snapDestinationMetres)>150&&<p className="notice">A pin is over 150 m from the routed road. Check the start/end access on the map.</p>}<button disabled={limit||c.added} onClick={()=>{add({id:crypto.randomUUID(),name:`${c.fromLabel} to ${c.toLabel}${i?` · alternative ${i}`:''}`.slice(0,160),destination:c.toLabel.slice(0,160),role:i===0?'Primary':'Alternate',fromLocationId:c.fromId,toLocationId:c.toId,points:c.road.points,routing:c.road.routing,notes:'',marks:[]});setCandidates(prior=>prior.map((x,j)=>j===i?{...x,added:true}:x));}}>{c.added?'Added to study':'Add route to study'}</button></article>)}</div>
 <p className="help">Generate sends endpoint coordinates to the configured routing service. The default is <a href="https://routing.openstreetmap.de/about.html" target="_blank" rel="noreferrer">FOSSGIS / OSRM</a> using <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a>. <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noreferrer">Fix the map</a>. Review the route before travel. Saved routes work with corridor collection.</p>
 </div>;
}
