"use client";
import {useState} from 'react';
import {Download,Upload,ShieldCheck} from 'lucide-react';
import type {Portfolio} from '../lib/locations';
import {makeBackup,parseBackup,studyCounts,archiveMerge,validateBackupSizes,MAX_BACKUP_BYTES,type Backup} from '../lib/backup';
type Saved={backup:Backup;updatedAt:string|null};
export function downloadBackup(backup:Backup,prefix='area-study-backup'){const u=URL.createObjectURL(new Blob([JSON.stringify(backup)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=`${prefix}-${backup.createdAt.replace(/[:.]/g,'-')}.json`;a.click();window.setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function api<T>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,options),d=await r.json() as T & {error?:string};if(!r.ok)throw Error(d.error||'Backup storage unavailable.');return d;}
export default function BackupPanel({portfolio,dirty,saving,restored}:{portfolio:Portfolio;dirty:boolean;saving:boolean;restored:(p:Portfolio,updatedAt:string,expectedScreen:string)=>boolean}){
 const [preview,setPreview]=useState<{backup:Backup;kind:string;sourceVersion:number;filename:string;baseline:Saved;screen:string;additions:number}|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[downloaded,setDownloaded]=useState(false),[confirmed,setConfirmed]=useState(false),[paste,setPaste]=useState('');
 const screen=JSON.stringify(portfolio),changed=!!preview&&screen!==preview.screen;
 async function backup(){setBusy(true);setNotice('');try{const s=await api('/api/backup') as Saved;downloadBackup(makeBackup(portfolio,s.backup.briefings,dirty));setNotice('Backup download started. It includes the entire on-screen study and saved briefing archive.');}catch(e){setNotice(e instanceof Error?e.message:'Backup failed.');}finally{setBusy(false);}}
 async function inspect(file:File){setPreview(null);setDownloaded(false);setConfirmed(false);setBusy(true);setNotice('');try{if(file.size>MAX_BACKUP_BYTES)throw Error('File exceeds 64 MB.');const parsed=parseBackup(await file.text());validateBackupSizes(parsed.backup);const baseline=await api('/api/backup') as Saved;const additions=archiveMerge(baseline.backup.briefings,parsed.backup.briefings).length;setPreview({...parsed,filename:file.name,baseline,screen,additions});}catch(e){setNotice(e instanceof Error?e.message:'File validation failed. No changes made.');}finally{setBusy(false);}}
 async function recovery(){if(!preview||changed)return;setBusy(true);try{const latest=await api('/api/backup') as Saved;if(latest.updatedAt!==preview.baseline.updatedAt)throw Error('The saved study changed. Preview the file again before continuing.');const additions=archiveMerge(latest.backup.briefings,preview.backup.briefings).length;downloadBackup(makeBackup(portfolio,latest.backup.briefings,dirty),'area-study-recovery');setPreview({...preview,baseline:latest,additions});setDownloaded(true);setConfirmed(false);setNotice('Recovery download started. Confirm that you saved the file before replacing your study.');}catch(e){setNotice(e instanceof Error?e.message:'Recovery backup failed.');}finally{setBusy(false);}}
 async function restore(){if(!preview||changed||!downloaded||!confirmed||saving)return;setBusy(true);setNotice('');try{const d=await api<{study:Portfolio;updatedAt:string;addedBriefings:number}>('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({backup:preview.backup,expectedUpdatedAt:preview.baseline.updatedAt})});const applied=restored(d.study,d.updatedAt,preview.screen);setPreview(null);setConfirmed(false);setDownloaded(false);setNotice(applied?`Study restored. ${d.addedBriefings} archived briefing versions added; existing archives retained.`:'Restore was saved, but newer on-screen edits were kept. Export those edits and reload to view the restored study.');}catch(e){setNotice(e instanceof Error?e.message:'Restore failed.');setDownloaded(false);setConfirmed(false);}finally{setBusy(false);}}
 const current=studyCounts(portfolio),incoming=preview&&studyCounts(preview.backup.study);
 return <section className="backup-content"><div className="row"><div><span className="eyebrow">PORTABLE STUDY / RECOVERY</span><h2>Backup & restore</h2></div><ShieldCheck size={24}/></div><p className="help">Backups contain private addresses, coordinates, evidence and plans. Keep them in a private location. Cached public feeds, credentials, hosting settings and the handbook are excluded.</p>
 <article className="backup-card"><h3>Download a complete backup</h3><p>All locations, boundaries, notes, findings, questions, service plans, scenarios, routes, review history and archived briefings.</p><p className="help">{dirty?'Unsaved on-screen edits will be included and labeled.':'Includes the current on-screen study.'} Public map data reloads from its sources after restore.</p><button disabled={busy||saving} onClick={backup}><Download size={16}/>Download backup</button></article>
 <article className="backup-card"><h3>Preview an import</h3><p>Choose a complete JSON backup, study JSON, or GeoJSON export containing a portfolio. Map features alone cannot restore the study.</p><label className="backup-file"><Upload size={16}/>Backup or study export<input type="file" accept=".json,.geojson,application/json,application/geo+json" disabled={busy||saving} onChange={e=>{const f=e.target.files?.[0];if(f)void inspect(f);e.target.value='';}}/></label><p className="help">Maximum file size: 64 MB. The saved study must fit 1.5 MB; each archived briefing must fit 2 MB.</p><details><summary>Or paste backup JSON</summary><label>Backup JSON<textarea rows={6} value={paste} onChange={e=>setPaste(e.target.value)} placeholder="Paste a complete backup or study export"/></label><button disabled={busy||saving||!paste.trim()} onClick={()=>void inspect(new File([paste],'Pasted backup.json',{type:'application/json'}))}>Validate pasted JSON</button></details></article>
 {preview&&incoming&&<article className="backup-card"><div className="row"><h3>Import preview</h3><span className="badge">Validated · no changes applied</span></div><p>{preview.filename} · {preview.kind} · study v{preview.sourceVersion} → v11</p><p className="notice">Restore replaces every location and its study content, shared routes and review history. Archived briefings are merged by ID; different versions with the same ID are rejected.</p><div className="backup-table"><table><thead><tr><th>Content</th><th>On screen</th><th>Incoming</th></tr></thead><tbody>{Object.keys(current).map(key=><tr key={key}><th>{key}</th><td>{current[key as keyof typeof current]}</td><td>{incoming[key as keyof typeof incoming]}</td></tr>)}<tr><th>Archived briefings</th><td>{preview.baseline.backup.briefings.length} retained</td><td>{preview.additions} added</td></tr></tbody></table></div><h4>Incoming locations</h4>{[{id:'home',name:'Home',home:preview.backup.study.home},...preview.backup.study.locations].map(l=><p key={l.id}><strong>{l.name}</strong> · {l.home?.address||'Address not set'}</p>)}{preview.backup.includesUnsaved&&<p className="notice">This backup includes edits that were unsaved when downloaded.</p>}{changed&&<p className="notice">The on-screen study changed after this preview. Select the file again before restoring.</p>}
 <div className="backup-actions"><button disabled={busy||saving||changed} onClick={recovery}><Download size={16}/>Download recovery backup</button><label><input type="checkbox" checked={confirmed} disabled={!downloaded||changed||busy} onChange={e=>setConfirmed(e.target.checked)}/>I saved the recovery backup and want to replace my study with this import.</label><button className="primary" disabled={busy||saving||changed||!downloaded||!confirmed} onClick={restore}>{busy?'Working…':'Restore study'}</button><button disabled={busy} onClick={()=>{setPreview(null);setNotice('Import cancelled. No data changed.');}}>Cancel import</button></div></article>}
 {notice&&<p className="notice" role="status" aria-live="polite">{notice}</p>}</section>;
}
