"use client";
import {useEffect,useRef,useState} from 'react';
import {FileText,Printer,Download,Archive,RefreshCw} from 'lucide-react';
import {makeBriefing,renderBriefing,type Briefing} from '../lib/briefing';
import type {Portfolio} from '../lib/locations';
type Archived={id:string,title:string,createdAt:string,scope:string};
export default function BriefingsPanel({portfolio,dirty,coverage}:{portfolio:Portfolio,dirty:boolean,coverage:Record<string,string>}){
 const [title,setTitle]=useState('Area study briefing'),[scope,setScope]=useState('active'),[report,setReport]=useState<Briefing|null>(null),[html,setHtml]=useState(''),[archives,setArchives]=useState<Archived[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[archiveError,setArchiveError]=useState(''),[archivedId,setArchivedId]=useState('');const frame=useRef<HTMLIFrameElement>(null);
 useEffect(()=>{const c=new AbortController();void fetch('/api/briefings',{signal:c.signal}).then(async r=>{const d=await r.json() as {error?:string,reports:Archived[]};if(!r.ok)throw Error(d.error||'Archive unavailable');if(!c.signal.aborted)setArchives(d.reports);}).catch(e=>{if(!c.signal.aborted)setArchiveError(e instanceof Error?e.message:'Archive unavailable');});return()=>c.abort();},[]);
 function show(b:Briefing){const text=renderBriefing(b);setReport(b);setHtml(text);}
 function generate(){try{show(makeBriefing(portfolio,title,scope==='all',coverage,!dirty));setArchivedId('');setNotice('Dated snapshot generated. Later study edits will not change this preview.');}catch(e){setNotice(e instanceof Error?e.message:'Briefing could not be generated.');}}
 async function refresh(){try{const r=await fetch('/api/briefings'),d=await r.json() as {error?:string,reports:Archived[]};if(!r.ok)throw Error(d.error);setArchives(d.reports);setArchiveError('');}catch(e){setArchiveError(e instanceof Error?e.message:'Archive unavailable');}}
 async function archive(){if(!report||busy)return;setBusy(true);try{const r=await fetch('/api/briefings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(report)}),d=await r.json() as {error?:string,id:string};if(!r.ok)throw Error(d.error);setArchivedId(d.id);setNotice('Briefing archived as a fixed version.');await refresh();}catch(e){setNotice(e instanceof Error?e.message:'Archive failed.');}finally{setBusy(false);}}
 async function open(id:string){if(busy)return;setBusy(true);try{const r=await fetch('/api/briefings?id='+encodeURIComponent(id)),d=await r.json() as {error?:string,briefing:Briefing};if(!r.ok)throw Error(d.error);show(d.briefing);setArchivedId(id);setNotice('Archived snapshot opened. Source data and judgments are from its generation time.');}catch(e){setNotice(e instanceof Error?e.message:'Archived report unavailable.');}finally{setBusy(false);}}
 function download(){if(!report)return;const u=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download='area-study-'+report.generatedAt.slice(0,10)+'-'+report.id.slice(0,8)+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 return <section className="briefings-content"><div className="row"><div><span className="eyebrow">DATED STUDY / FINDINGS / SOURCES</span><h2>Briefings & printable studies</h2></div><FileText size={24}/></div><p className="help">Generate a fixed report from your on-screen study. It retains original findings, confidence, assumptions, evidence dates, service alternatives, scenarios, routes and unresolved questions. It does not invent conclusions or copy unreviewed live map layers into findings.</p><div className="briefing-controls"><label>Briefing title<input maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Report scope<select value={scope} onChange={e=>setScope(e.target.value)}><option value="active">Active location</option><option value="all">Whole study · all locations</option></select></label><button onClick={generate}>Generate briefing</button></div><p className="help">Reports include private addresses, coordinates and planning details for the selected scope. {dirty?'Your study has unsaved changes; generated reports will be labeled accordingly.':'The study is marked saved.'} Source coverage statuses describe the active location’s current session only.</p>
 {notice&&<p className="notice" role="status">{notice}</p>}{report&&<><div className="briefing-actions"><span className="badge">{archivedId?'Archived version':'Generated snapshot'} · {new Date(report.generatedAt).toLocaleString()}</span><button onClick={()=>{try{frame.current?.contentWindow?.print();}catch{setNotice('Use Download HTML, open the file and print it from your browser.');}}}><Printer size={16}/>Print / save PDF</button><button onClick={download}><Download size={16}/>Download HTML</button><button disabled={busy||!!archivedId} onClick={archive}><Archive size={16}/>{busy?'Working…':archivedId?'Archived':'Archive version'}</button></div><p className="help">Choose Save as PDF in your browser’s print dialog. The HTML copy contains its own styles and schematic maps and can be opened offline. Generate again to include newer study edits.</p><iframe ref={frame} title="Printable briefing preview" sandbox="allow-same-origin allow-modals allow-popups" srcDoc={html} className="briefing-preview"/></>}
 {!report&&<div className="empty"><FileText size={32}/><b>Create a dated study briefing</b><p>Choose the active location or the whole study, then generate a report to review before printing.</p></div>}
 <div className="row"><h3>Archived briefings</h3><button disabled={busy} onClick={refresh}><RefreshCw size={15}/>Refresh archive</button></div>{archiveError&&<p className="notice">{archiveError}</p>}<p className="help">Archived snapshots preserve the data used at generation. Opening one does not refresh sources or replace your current study. The archive holds up to 30 reports; download dated copies for your own records.</p><div className="briefing-archives">{archives.map(a=><article key={a.id}><strong>{a.title}</strong><small>{a.scope} · {new Date(a.createdAt).toLocaleString()}</small><button disabled={busy} onClick={()=>open(a.id)}>Open archived briefing</button><a href={'/api/briefings?id='+encodeURIComponent(a.id)+'&download=1'}>Download HTML copy</a></article>)}</div>{!archives.length&&!archiveError&&<p className="help">No archived briefings yet.</p>}</section>;
}
