"use client";
import {collectionFetch} from '../lib/collection-activity';
import {useEffect,useMemo,useRef,useState} from 'react';
import {CalendarDays,ExternalLink,MapPin,RefreshCw} from 'lucide-react';
import {civicSources,civicBucket,centralToday,type CivicItem,type CivicSnapshot} from '../lib/civic';
import {reportDate} from '../lib/report-dates';
const dayLabel=(day:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'America/Chicago'}).format(new Date(day+'T12:00:00Z'));
export default function CivicPanel({placeNote,point}:{point?:readonly number[]|null,placeNote:(item:CivicItem)=>void}){
 const [sources,setSources]=useState<CivicSnapshot[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[agency,setAgency]=useState('all'),[period,setPeriod]=useState('upcoming'),[kind,setKind]=useState('all'),[query,setQuery]=useState(''),[today,setToday]=useState(centralToday());
 const running=useRef(false);
 async function read(signal?:AbortSignal){await Promise.resolve();if(signal?.aborted)return;if(running.current)return;running.current=true;setLoading(true);setError('');try{const r=await collectionFetch('/api/civic'+(point?'?'+new URLSearchParams({lat:String(point[0]),lng:String(point[1])}):''),{signal}),d=await r.json() as {sources?:CivicSnapshot[],error?:string};if(!r.ok||!Array.isArray(d.sources))throw Error(d.error||'Civic sources unavailable');if(!signal?.aborted){setSources(d.sources);setToday(centralToday());}}catch(e:unknown){if(!(e instanceof Error&&e.name==='AbortError'))setError(e instanceof Error?e.message:'Civic collection failed');}finally{running.current=false;if(!signal?.aborted)setLoading(false);}}
 useEffect(()=>{const c=new AbortController();queueMicrotask(()=>read(c.signal));const timer=setInterval(()=>{setToday(centralToday());if(document.visibilityState==='visible')read(c.signal);},120000);return()=>{c.abort();running.current=false;clearInterval(timer);};},[]);
 const all=useMemo(()=>sources.flatMap(s=>s.data?.items||[]),[sources]),counts={upcoming:all.filter(i=>civicBucket(i,today)==='upcoming').length,past:all.filter(i=>civicBucket(i,today)==='past').length,undated:all.filter(i=>!i.date).length};
 const items=useMemo(()=>all.filter(i=>(agency==='all'||i.sourceId===agency)&&(kind==='all'||i.kind===kind)&&(period==='all'||(period==='changed'?['Cancelled','Rescheduled','Postponed'].includes(i.status):civicBucket(i,today)===period))&&[i.title,i.location,i.summary].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{const order=(a.date||'9999').localeCompare(b.date||'9999');return period==='past'?-order:order;}),[all,agency,period,kind,query,today]);
 return <section className="community-content civic-content"><div className="row"><div><span className="eyebrow">OFFICIAL MEETINGS & PROJECT NOTICES</span><h2>Civic calendar</h2></div><button disabled={loading} onClick={()=>read()}><RefreshCw size={16}/>{loading?'Checking calendars…':'Check calendars'}</button></div><p className="community-intro">Follow the public decisions and projects that affect your area. Meeting dates, notice publication and collection times are kept separate. These agency calendars are shared across study areas; they do not confirm your home’s jurisdiction.</p>{sources.find(s=>s.sourceId==='mud')&&!sources.find(s=>s.sourceId==='mud')?.data?.items.length&&<p className="help">Wilbarger Creek MUD 1 meeting dates are not available from the connected legacy page. <a href={civicSources[3].agenda} target="_blank" rel="noreferrer">Open current district records</a>.</p>}
 <div className="civic-periods" aria-label="Calendar period">{[['upcoming','Today & upcoming',counts.upcoming],['past','Past meetings',counts.past],['undated','Undated notices',counts.undated],['changed','Cancelled & changed',all.filter(i=>['Cancelled','Postponed','Rescheduled'].includes(i.status)).length]].map(([value,label,count])=><button key={value} aria-pressed={period===value} className={period===value?'primary':''} onClick={()=>setPeriod(String(value))}>{label}<span>{count}</span></button>)}</div>
 <div className="community-filters civic-filters"><label>Search meetings & projects<input placeholder="Council, budget, Tower Road…" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Agency<select value={agency} onChange={e=>setAgency(e.target.value)}><option value="all">All agencies</option>{civicSources.filter(s=>sources.some(x=>x.sourceId===s.id)).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Record type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All record types</option><option>Meeting</option><option>Project notice</option></select></label></div>
 {error&&<p className="notice" role="alert">{error}. Previous records remain below.</p>}
 <details className="community-source-status"><summary>Source coverage & agendas · {sources.filter(s=>s.data&&!s.error).length}/{sources.length} collected</summary><div>{civicSources.filter(s=>sources.some(x=>x.sourceId===s.id)).map(s=>{const result=sources.find(x=>x.sourceId===s.id);return <article key={s.id}><div className="row"><strong>{s.name}</strong><a href={s.home} target="_blank" rel="noreferrer" aria-label={'Open '+s.name}><ExternalLink size={15}/></a></div><p className={result?.error?'feed-error':''}>{result?.error||(!result?'Not checked yet':`${result.data?.items.length||0} records returned${result.cached?' · shared cache':''}`)}</p>{result?.data?.warnings.map(w=><small key={w}>{w}</small>)}<small>{s.notice}</small><small>Last successful collection: {reportDate(result?.fetchedAt,true)}</small>{result?.checkedAt&&<small>Checked: {reportDate(result.checkedAt,true)} · next eligible: {reportDate(result.nextCheckAt,true)}</small>}{result?.error&&result.data&&<small>Source failed; showing older cached records. Verify directly.</small>}{result?.cacheWarning&&<small>{result.cacheWarning}</small>}<a className="civic-agenda" href={s.agenda} target="_blank" rel="noreferrer">{s.id==='mud'?'District records':'Official agendas / notices'} <ExternalLink size={13}/></a></article>;})}</div></details>
 <p className="help">Today is {dayLabel(today)} in Central time. “Today & upcoming” includes today’s records throughout the day, including cancelled entries with their source status. No meeting is generated from a recurring schedule. Past records are retained only within the source’s returned window. Project notices without explicit event dates appear under Undated notices.</p>
 <div className="row community-results-heading"><h3>{items.length} matching {items.length===1?'record':'records'}</h3><span className="badge">Verify the latest official agenda</span></div>
 {!items.length&&<div className="empty"><CalendarDays size={25}/><b>{loading?'Collecting official calendars…':'No matching dated records'}</b><p>Check another period or agency and review source coverage. Some agencies publish only a limited calendar or archive window. Missing records remain a coverage gap.</p></div>}
 <div className="civic-items">{items.map(i=>{const source=civicSources.find(s=>s.id===i.sourceId)!,snapshot=sources.find(s=>s.sourceId===i.sourceId);return <article key={i.id} className="civic-event"><div className="civic-date"><CalendarDays size={19}/><strong>{i.date?dayLabel(i.date):'Date not supplied'}</strong><small>{i.date?civicBucket(i,today)==='past'?'Past record':i.date===today?'Today':'Upcoming':'Project notice'}</small></div><div className="civic-event-body"><div className="row"><span className="eyebrow">{source.name} · {i.kind}</span><div className="civic-badges"><span className={'badge '+(i.status==='Cancelled'?'civic-cancelled':'')}>{i.status}</span>{snapshot?.error&&<span className="badge">Older cache</span>}</div></div><h3><a href={i.url} target="_blank" rel="noreferrer">{i.title}</a></h3><div className="civic-meta"><span>Time: {i.time||'Not supplied; check agenda'}</span><span>Venue: {i.location||'Not supplied; check original'}</span></div>{i.summary&&<p>{i.summary}</p>}{i.dateBasis&&<p className="help">{i.dateBasis}</p>}<p className="community-date">Notice published: {reportDate(i.published||undefined,true)} · Source revision: {reportDate(i.update||undefined,true)}</p><div className="community-item-actions"><a href={i.url} target="_blank" rel="noreferrer">Original record <ExternalLink size={14}/></a>{i.agendaUrl&&<a href={i.agendaUrl} target="_blank" rel="noreferrer">Agenda portal <ExternalLink size={14}/></a>}<button onClick={()=>placeNote(i)}><MapPin size={14}/>Place in field notes</button></div></div></article>;})}</div>
 </section>;
}
