'use client';
import {useState} from 'react';
import {RefreshCw,MapPin,ExternalLink} from 'lucide-react';
import {inside,type Point} from '../lib/geo';
import {reportDate} from '../lib/report-dates';
import type {CrossingRecord,CrossingStatus} from '../lib/crossing-status';
export function CrossingDetails({data}:{data:CrossingStatus}){return <><dl className="report-details"><dt>Reported status</dt><dd>{data.state} · source: {data.reported}</dd><dt>Record updated</dt><dd>{reportDate(data.recordUpdated||undefined,true)}</dd><dt>Address</dt><dd>{data.address||'Unavailable'}</dd><dt>Jurisdiction code</dt><dd>{data.jurisdiction||'Unavailable'}</dd><dt>Source comment</dt><dd>{data.comment||'None supplied'}</dd></dl><p className="help">Record update is not a confirmed inspection or status-change time. Comments may describe an earlier condition. Reported Open is not a guarantee of safe passage.</p></>;}
type Props={records:CrossingRecord[];area:Point[];areaName:string;status:string;busy:boolean;refresh:()=>void;inspect:(r:CrossingRecord)=>void};
export default function ClosuresPanel({records,area,areaName,status,busy,refresh,inspect}:Props){
 const [filter,setFilter]=useState('attention'),[selectedId,setSelectedId]=useState('');
 const local=records.filter(p=>inside([p.lat,p.lng],area)),sites=local.filter(p=>filter==='all'||filter==='attention'&&p.closure.state!=='Open'||p.closure.state===filter).sort((a,b)=>a.name.localeCompare(b.name)),selected=sites.find(p=>p.id===selectedId)||sites[0];
 return <section className="water-section closures-section"><div className="row"><div><span className="eyebrow">REPORTED CROSSING CONDITIONS</span><h2>Road crossings & closures</h2></div><button onClick={refresh} disabled={busy||area.length<3}><RefreshCw size={16}/>{busy?'Checking crossings…':'Check crossing status'}</button></div><p>ATXFloods reports for monitored locations inside your {areaName}. These are point records, not a complete road-closure inventory or a route clearance.</p>{area.length<3?<p className="help">Draw an AOR or AOI to load reported crossing statuses.</p>:<><p className="help">{status||'Waiting for crossing collection…'}</p><div className="crossing-counts">{(['Closed','Caution','Open','Unknown'] as const).map(s=><span className="badge" key={s}>{s}: {local.filter(p=>p.closure.state===s).length}</span>)}</div><label className="crossing-filter">Reported status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="attention">Closed, caution & unknown</option><option value="all">All reported statuses</option><option>Closed</option><option>Caution</option><option>Open</option><option>Unknown</option></select></label>{!sites.length?<p className="notice">{local.length?'No loaded records match this filter. Choose All reported statuses to inspect monitored locations.':'No crossing records loaded inside this boundary. Check source status and coverage.'} An empty result does not establish that roads are open.</p>:<article className="dashboard-card"><label>Choose a crossing<select value={selected.id} onChange={e=>setSelectedId(e.target.value)}>{sites.map(p=><option key={p.id} value={p.id}>{p.closure.state} · {p.name}</option>)}</select></label><div className="row"><h3>{selected.name}</h3><button onClick={()=>inspect(selected)}><MapPin size={16}/>View crossing on map</button></div>{selected.stale&&<p className="notice">Stale collection snapshot; verify the source before using the reported status.</p>}<CrossingDetails data={selected.closure}/><p className="help">Retrieved {reportDate(selected.retrievedAt,true)}</p></article>}</>}<a href="https://www.atxfloods.com/" target="_blank" rel="noreferrer">Open official ATXFloods map <ExternalLink size={14}/></a><p className="help">Shared source snapshots refresh every 2 minutes while this tab is visible. Failed checks may delay retries. Statuses reflect the last published record; floodplain maps and nearby gauges do not determine them. Map layer starts hidden; enable Crossing status in Layers.</p></section>;
}
