"use client";
import {useState} from 'react';
import {Plus,ClipboardList,Link as LinkIcon,ExternalLink,Trash2,CalendarClock} from 'lucide-react';
import {evidenceSnapshot,newQuestion,localDate,questionFlags,questionNeedsAttention,requirementFlags,unlinkQuestionArea,detachEvidence,type CollectionPlan,type StudyQuestion,type Evidence,type EvidenceRecord} from '../lib/collection';
import type {NamedArea} from '../lib/nais';
import RequirementsPanel from './requirements-panel';
import type {ServicePlan} from '../lib/dependencies';

type Props={servicePlans:ServicePlan[],openService:(id:string)=>void,plan:CollectionPlan,change:(plan:CollectionPlan)=>void,notes:EvidenceRecord[],records:EvidenceRecord[],narrative:string,changeNarrative:(text:string)=>void,areas:NamedArea[],openArea:(id:string)=>void,drawArea:()=>void,selectedId:string|null,select:(id:string|null)=>void};
export default function CollectionPanel({servicePlans,openService,plan,change,notes,records,narrative,changeNarrative,areas,openArea,drawArea,selectedId,select}:Props){
 const [filter,setFilter]=useState('All'),[search,setSearch]=useState(''),[deleteId,setDeleteId]=useState<string|null>(null),[linkTitle,setLinkTitle]=useState(''),[linkUrl,setLinkUrl]=useState(''),[linkSource,setLinkSource]=useState(''),[linkDate,setLinkDate]=useState(''),[linkError,setLinkError]=useState('');
 const q=plan.questions.find(x=>x.id===selectedId),today=localDate();
 const [activeRequirement,setActiveRequirement]=useState<string|null>(null),[matrixFilter,setMatrixFilter]=useState('All');
 const shown=plan.questions.filter(x=>filter==='All'||(filter==='Needs attention'?questionNeedsAttention(x,today):x.status===filter));
 const due=plan.questions.filter(x=>questionNeedsAttention(x,today)).length;
 const matrix=plan.questions.flatMap(question=>question.requirements.map(requirement=>({question,requirement,flags:requirementFlags(requirement,today)}))).filter(({requirement:r,flags:f})=>matrixFilter==='All'||(matrixFilter==='Active'?r.status!=='Answered'&&r.status!=='Retired':matrixFilter==='Overdue'?f.overdue:matrixFilter==='Review due'?f.reviewDue:matrixFilter==='Collection gaps'?f.gap:r.status===matrixFilter));
 const candidates=[...notes.map(r=>({record:r,kind:'Note' as const})),...records.filter(r=>!notes.some(n=>n.id===r.id)).map(r=>({record:r,kind:'Source' as const}))].filter(x=>!q?.evidence.some(e=>e.recordId===x.record.id&&e.kind===x.kind)&&(x.kind==='Note'||search.trim().length>=2)&&`${x.record.name} ${x.record.source}`.toLowerCase().includes(search.trim().toLowerCase())).slice(0,20);
 function edit(fields:Partial<StudyQuestion>){if(q)change({...plan,questions:plan.questions.map(x=>x.id===q.id?{...x,...fields}:x)});}
 function attach(e:Evidence){if(q&&q.evidence.length<30)edit({evidence:[...q.evidence,e]});}
 function addLink(){let parsed:URL;try{parsed=new URL(linkUrl.trim());if(!['https:','http:'].includes(parsed.protocol))throw Error();}catch{setLinkError('Enter a complete http or https URL.');return;}attach({id:crypto.randomUUID(),recordId:'',kind:'Link',title:linkTitle.trim(),source:linkSource.trim(),url:parsed.href,date:linkDate,capturedAt:new Date().toISOString(),detail:'',stance:'Context',provenance:'Reported by source'});setLinkTitle('');setLinkUrl('');setLinkSource('');setLinkDate('');setLinkError('');}
 return <section className="collection-content"><div className="row collection-heading"><div><span className="eyebrow"><ClipboardList size={16}/>COLLECTION PLANNER</span><h2>Questions that guide your study</h2></div><span className="badge">Needs attention: {due}</span></div>
 <label className="collection-purpose">Study purpose<textarea maxLength={2000} value={plan.purpose} onChange={e=>change({...plan,purpose:e.target.value})} placeholder="What decisions should this study help you make?"/></label>
 <details className="manual-evidence"><summary>Collection plan narrative{narrative.trim()?' · saved notes':''}</summary><label>Existing notes and additional context<textarea maxLength={50000} value={narrative} onChange={e=>changeNarrative(e.target.value)} placeholder="Keep your collection plan narrative here."/></label></details>
 <details className="collection-matrix"><summary>Collection matrix · Requirements: {plan.questions.reduce((n,q)=>n+q.requirements.length,0)}</summary><label>Matrix filter<select value={matrixFilter} onChange={e=>setMatrixFilter(e.target.value)}>{['All','Active','Overdue','Review due','Collection gaps','Answered','Retired'].map(x=><option key={x}>{x}</option>)}</select></label><div className="matrix-scroll" tabIndex={0} role="region" aria-label="Scrollable collection matrix"><table><thead><tr><th>Question and requirement</th><th>Where</th><th>Source and responsibility</th><th>Latest useful date</th><th>Status</th></tr></thead><tbody>{matrix.map(({question,requirement:r,flags:f})=><tr key={question.id+r.id}><td><small>{question.question}</small><button onClick={()=>{select(question.id);setFilter('All');setActiveRequirement(r.id);}}>{r.task}</button></td><td>{r.naiIds.map(id=>areas.find(a=>a.id===id)?.name).filter(Boolean).join(', ')||r.location||'Location not set'}</td><td>{r.source.slice(0,120)||'Source not set'}<small>{r.responsibility||'Unassigned'} · {r.method}</small></td><td>{r.neededBy||'Not set'}{r.reviewOn&&<small>Review {r.reviewOn}</small>}</td><td>{r.status}{f.overdue&&<small className="collection-warning">Overdue</small>}{f.reviewDue&&<small className="collection-warning">Review due</small>}{f.gap&&<small className="collection-warning">Collection gap</small>}</td></tr>)}</tbody></table></div>{!matrix.length&&<p className="help">No requirements match this view. Add a requirement to a study question below.</p>}</details>
 <div className="collection-layout"><div className="question-index"><div className="row"><h3>Study questions</h3><button className="primary" disabled={plan.questions.length>=100} onClick={()=>{const item=newQuestion();change({...plan,questions:[...plan.questions,item]});select(item.id);setFilter('All');setDeleteId(null);}}><Plus size={16}/>Add question</button></div><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Needs attention','Open','In progress','Answered','Blocked'].map(x=><option key={x}>{x}</option>)}</select></label>
 <div className="question-list">{shown.map(x=>{const f=questionFlags(x,today);return <button key={x.id} className={x.id===q?.id?'active':''} onClick={()=>{select(x.id);setDeleteId(null);setLinkError('');setLinkTitle('');setLinkUrl('');setLinkSource('');setLinkDate('');setSearch('');}}><strong>{x.question||'Untitled question'}</strong><span>{x.priority} priority · {x.status} · {x.scope}</span><span>{x.evidence.length} evidence {x.evidence.length===1?'item':'items'}</span>{f.overdue&&<b className="collection-warning">Answer overdue · {x.neededBy}</b>}{f.reviewDue&&<b className="collection-warning">Review due · {x.reviewOn}</b>}</button>;})}</div>{!shown.length&&<p className="help">{plan.questions.length?'No questions match this filter.':'Start with one question, such as whether flooding could block your route to medical care.'}</p>}</div>
 {q?<div className="question-editor"><h3>Question and decision</h3><label>Question<textarea maxLength={500} value={q.question} onChange={e=>edit({question:e.target.value})} placeholder="What do you need to know?"/></label><label>Decision this supports<textarea maxLength={2000} value={q.decision} onChange={e=>edit({decision:e.target.value})} placeholder="What would you do differently depending on the answer?"/></label>
 <div className="collection-fields"><label>Priority<select value={q.priority} onChange={e=>edit({priority:e.target.value as StudyQuestion['priority']})}>{['High','Normal','Low'].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={q.status} onChange={e=>edit({status:e.target.value as StudyQuestion['status']})}>{['Open','In progress','Answered','Blocked'].map(x=><option key={x}>{x}</option>)}</select></label><label>Area<select value={q.scope} onChange={e=>edit({scope:e.target.value as StudyQuestion['scope']})}>{['AOR','AOI','Route','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Location or route name<input maxLength={300} value={q.location} onChange={e=>edit({location:e.target.value})} placeholder="e.g. Wilbarger Creek crossing"/></label><label>Answer needed by<input type="date" value={q.neededBy} onChange={e=>edit({neededBy:e.target.value})}/></label><label>Next review<input type="date" value={q.reviewOn} onChange={e=>edit({reviewOn:e.target.value})}/></label></div>
 <p className="help"><CalendarClock size={15}/> The answer deadline supports a decision. The review date tells you when to check the question again, even after it is answered.</p>
 <div className="question-named-areas"><div className="row"><h3>Named areas to monitor</h3><button onClick={drawArea}>Manage on map</button></div><p className="help">Link specific locations to this question. Map locations and questions remain linked when renamed or redrawn.</p>{!areas.length&&<p className="help">No named areas yet. Place a point or draw an area in Map workspace → NAIs.</p>}<div className="nai-question-links">{areas.map(a=><label key={a.id}><input type="checkbox" checked={q.naiIds.includes(a.id)} onChange={e=>edit(e.target.checked?{naiIds:[...q.naiIds,a.id]}:unlinkQuestionArea(q,a.id))}/><span>{a.name} · {a.kind}</span></label>)}</div>{areas.filter(a=>q.naiIds.includes(a.id)).map(a=><button key={a.id} onClick={()=>openArea(a.id)}>View {a.name} on map</button>)}</div>
 <div className="question-named-areas"><h3>Linked service plans</h3>{servicePlans.filter(p=>p.questionIds.includes(q.id)).map(p=><button key={p.id} onClick={()=>openService(p.id)}>{p.name} · {p.sector}</button>)}{!servicePlans.some(p=>p.questionIds.includes(q.id))&&<p className="help">No linked service plans. Link this question from Services & infra → Dependencies & backups.</p>}</div>
 <RequirementsPanel question={q} change={requirements=>edit({requirements})} areas={areas} openArea={openArea} activeId={activeRequirement} activate={setActiveRequirement}/>
 <label>Sources and remaining information gaps<textarea maxLength={2000} value={q.sourcePlan} onChange={e=>edit({sourcePlan:e.target.value})} placeholder="What will you check, where, and what is still unavailable?"/></label>
 <h3>Current assessment</h3><label>Answer or working finding<textarea maxLength={4000} value={q.assessment} onChange={e=>edit({assessment:e.target.value})} placeholder="What does the evidence establish? What remains uncertain?"/></label><label>Assumptions to test<textarea maxLength={2000} value={q.assumptions} onChange={e=>edit({assumptions:e.target.value})}/></label><div className="collection-fields"><label>Analytic confidence<select value={q.confidence} onChange={e=>edit({confidence:e.target.value as StudyQuestion['confidence']})}>{['Unassessed','Low','Moderate','High'].map(x=><option key={x}>{x}</option>)}</select></label><label>Assessment date<input type="date" value={q.assessedOn} onChange={e=>edit({assessedOn:e.target.value})}/></label></div><label>Confidence rationale<textarea maxLength={2000} value={q.confidenceReason} onChange={e=>edit({confidenceReason:e.target.value})} placeholder="Explain source quality, independence, conflicts, and gaps."/></label><p className="help">Confidence describes this judgment. Evidence provenance describes how information was obtained. Repeated reporting may share the same original source.</p>
 <h3>Evidence <span className="count">{q.evidence.length} / 30</span></h3><p className="help">Attached records are saved snapshots. Feed refreshes and deleted field notes do not rewrite them. Excerpts are limited to 2,000 characters; retain the source link for context.</p>
 <div className="evidence-list">{q.evidence.map(e=><article key={e.id}><div className="row"><strong>{e.title}</strong><button aria-label={`Remove evidence ${e.title}`} onClick={()=>edit(detachEvidence(q,e.id))}><Trash2 size={15}/></button></div><p>{e.kind} · {e.source||'Source not specified'} · {e.provenance}</p><p>Source date: {e.date||'Unavailable'}<br/>Snapshot saved: {new Date(e.capturedAt).toLocaleString()}</p>{e.detail&&<details><summary>Saved excerpt</summary><p className="evidence-excerpt">{e.detail}</p></details>}{e.url&&<a href={e.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={14}/></a>}<label>How it relates<select value={e.stance} onChange={event=>edit({evidence:q.evidence.map(x=>x.id===e.id?{...x,stance:event.target.value as Evidence['stance']}:x)})}>{['Context','Supports','Conflicts'].map(x=><option key={x}>{x}</option>)}</select></label></article>)}</div>
 {q.evidence.length<30&&<><div className="evidence-picker"><h3>Attach a note or loaded map record</h3><label>Search by title or source<input maxLength={200} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records loaded in this session"/></label><p className="help">Saved notes appear below. Enter at least two characters to search map records; load the relevant area in Map workspace first. Showing up to 20 matches.</p>{candidates.map(({record:r,kind})=><button key={kind+r.id} onClick={()=>attach(evidenceSnapshot(r,kind))}><Plus size={15}/><span><strong>{r.name}</strong><small>{kind} · {r.source}</small></span></button>)}{!candidates.length&&<p className="help">No matching unattached records.</p>}</div>
 <details className="manual-evidence"><summary><LinkIcon size={15}/>Attach another source link</summary><label>Title<input maxLength={300} value={linkTitle} onChange={e=>setLinkTitle(e.target.value)}/></label><label>Source URL<input type="url" maxLength={1900} value={linkUrl} onChange={e=>setLinkUrl(e.target.value)} placeholder="https://"/></label><div className="collection-fields"><label>Publisher or source<input maxLength={200} value={linkSource} onChange={e=>setLinkSource(e.target.value)}/></label><label>Source date<input type="date" value={linkDate} onChange={e=>setLinkDate(e.target.value)}/></label></div>{linkError&&<p role="alert" className="collection-warning">{linkError}</p>}<button disabled={!linkTitle.trim()||!linkUrl.trim()} onClick={addLink}>Attach source</button></details></>}
 <div className="question-delete">{deleteId===q.id?<><p>Delete this question and its attached evidence? Your original notes and source records will remain.</p><button onClick={()=>{change({...plan,questions:plan.questions.filter(x=>x.id!==q.id)});select(null);setDeleteId(null);}}>Delete question</button><button onClick={()=>setDeleteId(null)}>Keep question</button></>:<button onClick={()=>setDeleteId(q.id)}><Trash2 size={15}/>Delete question</button>}</div></div>:<div className="collection-empty"><ClipboardList size={30}/><h3>Select or add a study question</h3><p>Connect information to a decision, keep its evidence, and set a review date. Use Save study to preserve your changes.</p></div>}
 </div><p className="help collection-save">Changes are part of your study. Use Save study in the header.</p></section>;
}
