"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {RefreshCw,ExternalLink,MapPin} from 'lucide-react';
import {communitySources,communityMatches,type CommunityItem,type FeedSnapshot} from '../lib/community';
import {liveAlerts,type WeatherAlert,type ConditionSnapshot} from '../lib/conditions';
import {wireGroups,matchedKeywords} from '../lib/wire';
import {reportDate,reportAgeDays} from '../lib/report-dates';
export default function CommunityPanel({placeNote,alerts,point}:{point?:readonly number[]|null,placeNote:(item:CommunityItem,source:string)=>void,alerts?:ConditionSnapshot<WeatherAlert[]>}){
 const [feeds,setFeeds]=useState<FeedSnapshot[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[keywords,setKeywords]=useState(''),[kind,setKind]=useState('all'),[sourceId,setSourceId]=useState('all'),[days,setDays]=useState('30');
 const [sourceIds,setSourceIds]=useState<string[]|null>(null);const registry=sourceIds?communitySources.filter(s=>sourceIds.includes(s.id)):communitySources;const hays=registry.some(s=>s.id==='wimberley-news')&&sourceIds!==null;
 const running=useRef(false);
 async function read(cacheOnly=false,signal?:AbortSignal){const r=await fetch('/api/community?'+new URLSearchParams({...cacheOnly?{cacheOnly:'1'}:{},...point?{lat:String(point[0]),lng:String(point[1])}:{}}),{signal}),d:any=await r.json();if(!r.ok)throw new Error(d.error||'Community feeds unavailable');if(!signal?.aborted){setFeeds(d.feeds);if(Array.isArray(d.sourceIds))setSourceIds(d.sourceIds);}}
 async function refresh(){if(running.current)return;running.current=true;setLoading(true);setError('');try{await read();}catch(e:any){setError(e.message);}finally{running.current=false;setLoading(false);}}
 useEffect(()=>{const c=new AbortController();running.current=true;setLoading(true);(async()=>{try{await read(true,c.signal);}catch{}try{await read(false,c.signal);}catch(e:any){if(e.name!=='AbortError')setError(e.message);}finally{running.current=false;if(!c.signal.aborted)setLoading(false);}})();const interval=setInterval(()=>{if(document.visibilityState==='visible')refresh();},300000);return()=>{c.abort();clearInterval(interval);};},[]);
 const byId=Object.fromEntries(registry.map(s=>[s.id,s]));
 const items=useMemo(()=>{const list=feeds.flatMap(f=>f.items).filter(i=>(sourceId==='all'||i.feedId===sourceId)&&(kind==='all'||byId[i.feedId]?.kind===kind)&&communityMatches(i,keywords)&&(days==='all'||(reportAgeDays(i.date)??Infinity)<Number(days)));return [...new Map(list.sort((a,b)=>(Date.parse(b.date||'')||0)-(Date.parse(a.date||'')||0)).map(i=>[i.url,i])).values()];},[feeds,sourceId,kind,keywords,days]);
 const groups=wireGroups(items),activeAlerts=liveAlerts(alerts?.data||[]);
 return <section className="community-content"><div className="row"><div><span className="eyebrow">PUBLIC POSTS & LOCAL UPDATES</span><h2>{alerts?"Local wire":"Community feed"}</h2></div><button disabled={loading} onClick={refresh}><RefreshCw size={16}/>{loading?'Checking feeds…':'Check feeds'}</button></div><p className="community-intro">Recent items from public boards, local news, and city announcements. Publication dates describe the post, not necessarily the event. Keyword matches do not establish a location inside your AOR or AOI.</p>
 {hays&&<p className="help">Wimberley city news plus KUT and KXAN regional context. Regional headlines are not automatically localized to this address; use keywords and verify the original. Hays-specific social-board collection is not connected.</p>}<div className="community-filters"><label>Keywords · comma separated<input maxLength={300} value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder={hays?"Wimberley, Hays, RM 12":"Manor, ShadowGlen, US 290"}/></label><label>Type<select value={kind} onChange={e=>{setKind(e.target.value);setSourceId('all');}}><option value="all">All types</option>{['Reddit','Mastodon','Lemmy','Bluesky','News','Official'].map(k=><option key={k}>{k}</option>)}</select></label><label>Source<select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="all">All sources</option>{registry.filter(s=>kind==='all'||s.kind===kind).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Published within<select value={days} onChange={e=>setDays(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">Any date in current feeds</option></select></label></div><div className="community-presets"><button onClick={()=>setKeywords(hays?'Wimberley, Hays, Woodcreek':'Manor, ShadowGlen, 78653')}>{hays?'Wimberley & Hays':'Manor & ShadowGlen'}</button><button onClick={()=>setKeywords('flood, closure, outage, fire, water, traffic')}>Disruptions</button><button onClick={()=>setKeywords('')}>All regional items</button></div>
 <p className="help">RSS headlines and short Mastodon / Bluesky post excerpts only; no comment threads or full news articles. Sources control the feed window, so the date filter cannot retrieve older items absent from a feed. Cached feeds are shared across every study area. Checks respect 30–60 minute refresh periods and source backoff.</p>
 {error&&<p className="notice" role="alert">{error} Cached items remain below.</p>}
 <details className="community-source-status"><summary>Source availability · {feeds.filter(f=>!f.error&&f.fetchedAt).length}/{registry.length} responding</summary><div>{registry.map(s=>{const f=feeds.find(f=>f.sourceId===s.id),latest=f?.items.filter(i=>i.date).sort((a,b)=>Date.parse(b.date!)-Date.parse(a.date!))[0];return <article key={s.id}><div className="row"><strong>{s.name}</strong><a href={s.home} target="_blank" rel="noreferrer" aria-label={'Open '+s.name}><ExternalLink size={14}/></a></div><p className={f?.error?'feed-error':''}>{f?.error||(!f?'Not checked yet':`${f.items.length} items in returned feed${f.cached?' · reused cache':''}`)}</p>{f?.fetchedAt&&<small>Last successful collection: {reportDate(f.fetchedAt,true)}</small>}{latest&&<small>Latest item published: {reportDate(latest.date)}</small>}{f?.checkedAt&&<small>Last checked: {reportDate(f.checkedAt,true)} · next eligible {reportDate(f.nextCheckAt,true)}</small>}{f?.error&&f.items.length>0&&<small>Showing older cached items; source refresh failed.</small>}{s.notice&&<small>{s.notice}</small>}{f?.cacheWarning&&<small>{f.cacheWarning}</small>}</article>;})}</div></details>
 {alerts&&<div className="wire-weather"><div className="row"><h3>NWS alerts at home</h3><span className="badge">Official · home point</span></div>{alerts.error&&<p className="notice">{alerts.error}. Alert collection failed; verify NWS directly.</p>}<p className="help">{alerts.fetchedAt?'Last successful collection: '+reportDate(alerts.fetchedAt,true):'No successful alert collection yet.'} Expired alerts are excluded.</p>{!activeAlerts.length&&alerts.data&&!alerts.error&&<p className="help">No unexpired alerts in this point-based source response.</p>}{activeAlerts.map(a=><details className="wire-alert" key={a.id}><summary><span className="badge">{a.severity}</span><strong>{a.headline}</strong><small>Issued {reportDate(a.sent,true)} · expires {reportDate(a.expires,true)}</small></summary><p>{a.area}</p><p className="note-detail">{a.description}</p>{a.instruction&&<p className="note-detail">{a.instruction}</p>}<a href={a.url} target="_blank" rel="noreferrer">Verify with NWS <ExternalLink size={14}/></a></details>)}</div>}
 <div className="row community-results-heading"><h3>{items.length} matching items</h3><span className="badge">Source claims · review before acting</span></div>{!items.length&&<div className="empty"><b>{loading?'Collecting public feeds…':'No items match these filters'}</b><p>Try All regional items or Any date. Check source availability above; an empty feed does not establish that nothing happened.</p></div>}
 <div className="community-items">{groups.map(({item:i,matches})=>{const s=byId[i.feedId],feed=feeds.find(f=>f.sourceId===i.feedId);return <article key={i.url}><div className="row"><span className="eyebrow">{s?.kind} · {s?.name}</span>{feed?.error&&<span className="badge">Older cache</span>}</div><h3><a href={i.url} target="_blank" rel="noreferrer">{i.title}</a></h3>{i.text&&i.text!==i.title&&<p>{i.text}</p>}{matchedKeywords(i,keywords).length>0&&<p className="wire-matched">Matched: {matchedKeywords(i,keywords).join(', ')}</p>}{matches.length>0&&<details className="wire-outlets"><summary>Matching headline from {new Set([i.feedId,...matches.map(m=>m.feedId)]).size} outlets</summary><p className="help">Headline matches are grouped for review; this is not independent verification of the reported event.</p>{matches.map(m=><a key={m.url} href={m.url} target="_blank" rel="noreferrer">{byId[m.feedId]?.name} · {reportDate(m.date)} <ExternalLink size={13}/></a>)}</details>}<p className="community-date">Published {reportDate(i.date,true)}{i.updatedDate&&i.updatedDate!==i.date?` · updated ${reportDate(i.updatedDate,true)}`:''}</p><div className="community-item-actions"><a href={i.url} target="_blank" rel="noreferrer">Read original <ExternalLink size={14}/></a><button onClick={()=>placeNote(i,s?.name||'Public feed')}><MapPin size={14}/>Place in field notes</button></div></article>;})}</div>
 <p className="help">Reddit RSS is scheduled to end November 13, 2026. <a href="https://www.reddit.com/r/modnews/comments/1wubgvt/continuing_our_infrastructure_updates_whats/" target="_blank" rel="noreferrer">Reddit announcement</a>. X, Facebook, and Nextdoor remain unconnected; private groups and login-only feeds are not collected.</p></section>;
}
