"use client";
import {useEffect,useState} from 'react';
import {fingerprint,verifyIdentity} from '../lib/sharing-auth';
import type {PeerContact} from '../lib/peer-contacts';
type Request=<T>(route:string,body?:unknown)=>Promise<T>;
function ContactRow({contact,busy,request,act}:{contact:PeerContact;busy:boolean;request:Request;act:(fn:()=>Promise<void>)=>void}){
 const [fp,setFp]=useState(''),[compared,setCompared]=useState(false);
 useEffect(()=>{let current=true;setCompared(false);void fingerprint(contact.publicKey).then(v=>{if(current)setFp(v);});return()=>{current=false;};},[contact.id,contact.publicKey,contact.status]);
 return <section className="shared-review"><div className="row"><strong>{contact.label}</strong><span className="badge">{contact.status}</span></div><p className="help">Contributor ID: {contact.id}</p><p>Fingerprint: <code>{fp}</code></p><p className="help">{contact.verifiedAt?'Verified '+new Date(contact.verifiedAt).toLocaleString():contact.status==='Verified'?'Verified earlier · verification date unavailable':'Fingerprint comparison required'}</p>{contact.status==='Pending'&&<><label className="sharing-choice"><input type="checkbox" checked={compared} disabled={busy||!contact.identity} onChange={e=>setCompared(e.target.checked)}/>I compared this fingerprint independently with this person</label><button disabled={busy||!compared||!contact.identity} onClick={()=>act(async()=>{await request('/contacts/verify',{id:contact.id,verifiedFingerprint:fp});})}>Verify contact</button>{!contact.identity&&<p>Add their signed identity card below before verifying.</p>}</>}<div className="peer-actions">{contact.status==='Blocked'?<button disabled={busy} onClick={()=>act(async()=>{await request('/contacts/unblock',{id:contact.id});})}>Unblock for verification</button>:<><button disabled={busy} onClick={()=>act(async()=>{await request('/contacts/disconnect',{id:contact.id});})}>Disconnect all connections</button><button disabled={busy} onClick={()=>act(async()=>{await request('/contacts/block',{id:contact.id});})}>Block contact</button></>}</div>{contact.status==='Blocked'&&<p className="help">Sync and imports are blocked. Unblocking requires verification again; old invitations stay revoked.</p>}</section>;
}
export default function ContactsPanel({contacts,busy,request,act}:{contacts:PeerContact[];busy:boolean;request:Request;act:(fn:()=>Promise<void>)=>void}){
 const [name,setName]=useState(''),[card,setCard]=useState(''),[valid,setValid]=useState(false),[fp,setFp]=useState('');
 useEffect(()=>{let current=true;setValid(false);setFp('');void(async()=>{try{if(card.length>3000)throw Error();const identity=await verifyIdentity(JSON.parse(card)),value=await fingerprint(identity.publicKey);if(current){setValid(true);setFp(value);}}catch{}})();return()=>{current=false;};},[card]);
 return <details className="contacts-panel"><summary>Contacts · {contacts.length}</summary><p>Contacts retain verified fingerprints independently of connections. Disconnecting all connections revokes outgoing invitations and stops incoming checks while preserving the contact. Blocking also rejects its package imports. Already merged study information remains.</p>{contacts.length?contacts.map(c=><ContactRow key={c.id} contact={c} busy={busy} request={request} act={act}/>):<p>No contacts yet. Add a public identity card to begin.</p>}<h4>Add or update a contact</h4><label>Contact label<input value={name} disabled={busy} maxLength={100} onChange={e=>setName(e.target.value)} placeholder="Name you recognize"/></label><label>Contact public identity card<textarea value={card} disabled={busy} maxLength={3000} rows={5} onChange={e=>setCard(e.target.value)}/></label>{valid&&<p>Card signature valid · fingerprint: <code>{fp}</code></p>}<button disabled={busy||!valid||!name.trim()} onClick={()=>act(async()=>{await request('/contacts/add',{label:name,identity:JSON.parse(card)});setCard('');setName('');})}>Save contact for verification</button></details>;
}
