"use client";
import {collectionFetch} from '../lib/collection-activity';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {RefreshCw,CloudSun,Radio,Zap,Droplets,ExternalLink} from 'lucide-react';
import {inAustinRegion} from '../lib/source-regions';
import HazardsPanel from './hazards-panel';
import type {NriRecord} from '../lib/hazards';
import CommunityPanel from './community-panel';
import {liveAlerts,gridUrl,droughtUrl,type Conditions,type ConditionSnapshot} from '../lib/conditions';
import type {CommunityItem} from '../lib/community';
import type {Point} from '../lib/geo';
import {reportDate} from '../lib/report-dates';
function SourceStatus({snapshot}:{snapshot?:ConditionSnapshot}){return <div className="dashboard-source">{snapshot?.error&&<p className="notice">{snapshot.error}{snapshot.data?' · older snapshot shown':' · data unavailable'}</p>}{snapshot?.fetchedAt&&<small>Collected {reportDate(snapshot.fetchedAt,true)}{snapshot.cached?' · cached':''}</small>}{snapshot?.cacheWarning&&<small>{snapshot.cacheWarning}</small>}</div>;}
export default function DashboardPanel({lifelinesPanel,environmentPanel,closuresPanel,waterPanel,home,area,areaName,riskRecords,riskStatus,riskBusy,refreshRisk,inspectRisk,placeNote}:{lifelinesPanel:ReactNode,environmentPanel:ReactNode,closuresPanel:ReactNode,waterPanel:ReactNode,home:Point|null,area:Point[],areaName:string,riskRecords:NriRecord[],riskStatus:string,riskBusy:boolean,refreshRisk:()=>void,inspectRisk:(r:NriRecord)=>void,placeNote:(item:CommunityItem,source:string)=>void}){
 const [data,setData]=useState<Conditions|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[clock,setClock]=useState(Date.now());const run=useRef(false),active=useRef('');const key=home?.join(',')||'';active.current=key;
 async function refresh(signal?:AbortSignal){if(run.current)return;run.current=true;setLoading(true);const requestKey=key;try{const r=await collectionFetch('/api/conditions'+(home?`?lat=${home[0]}&lng=${home[1]}`:''),{signal}),d:any=await r.json();if(!r.ok)throw Error(d.error||'Conditions unavailable');if(active.current===requestKey){setData(d);setError('');setClock(Date.now());}}catch(e:any){if(e.name!=='AbortError'&&active.current===requestKey)setError(e.message);}finally{run.current=false;if(!signal?.aborted)setLoading(false);}}
 useEffect(()=>{setData(null);run.current=false;const c=new AbortController();refresh(c.signal);const t=setInterval(()=>{setClock(Date.now());if(document.visibilityState==='visible')refresh(c.signal);},120000);return()=>{c.abort();clearInterval(t);};},[key]);
 const alerts=liveAlerts(data?.alerts?.data||[],clock),weeks=data?.drought.data||[],latest=weeks[weeks.length-1],grid=data?.grid.data,forecast=data?.forecast?.data;
 const droughtPoints=weeks.map((w,i)=>`${i/(Math.max(1,weeks.length-1))*500},${110-w.dsci/500*100}`).join(' ');
 const gridOld=!!grid&&(clock-Date.parse(grid.updated)>600000||!!data?.grid.error),alertOld=!!data?.alerts&&(!!data.alerts.error||clock-Date.parse(data.alerts.fetchedAt||'')>300000);
 return <section className="dashboard-content"><div className="row dashboard-title"><div><span className="eyebrow">CONDITIONS / SOURCES / INFORMATION GAPS</span><h2>Area dashboard</h2></div><button disabled={loading} onClick={()=>refresh()}><RefreshCw size={16}/>{loading?'Checking conditions…':'Check conditions'}</button></div>{error&&<p className="notice" role="alert">{error}. Older snapshots may remain below.</p>}
 <div className="dashboard-cards"><article className="dashboard-card"><span className="eyebrow"><Radio size={16}/>WEATHER ALERTS · ACTIVE LOCATION</span><h3>{!home?'Set this location':!data?.alerts?'Checking alerts…':!data.alerts.data?'Unavailable':`${alerts.length} unexpired alerts`}</h3><p>{!home?'Set the location in the map workspace to retrieve forecasts and point-based alerts.':alertOld?'Alert collection is stale or failed. Verify current warnings with NWS.':'Point-based NWS alerts; this does not cover every location in your AOI.'}</p><SourceStatus snapshot={data?.alerts}/><a href="https://www.weather.gov/alerts" target="_blank" rel="noreferrer">NWS alerts <ExternalLink size={13}/></a></article>
 <article className="dashboard-card"><span className="eyebrow"><Zap size={16}/>ERCOT · SYSTEM-WIDE SNAPSHOT</span><h3>{grid?grid.title:data?.grid.error?'Unavailable':'Checking grid…'}</h3>{grid&&<><p>{grid.note}</p><p><b>{grid.reserves.toLocaleString()} MW</b> operating reserves</p><small>Source updated {reportDate(grid.updated,true)}</small>{gridOld&&<p className="notice">Older grid reading. Verify current conditions at ERCOT.</p>}</>}<SourceStatus snapshot={data?.grid}/><a href={gridUrl} target="_blank" rel="noreferrer">ERCOT grid conditions <ExternalLink size={13}/></a><small>Grid reserves do not describe neighborhood outages or forecast future supply.</small></article>
 <article className="dashboard-card"><span className="eyebrow"><Droplets size={16}/>DROUGHT · {latest?.county||"LOCATION COUNTY"}</span><h3>{latest?`${latest.d2.toFixed(1)}% severe or worse`:data?.drought.error?'Unavailable':'Checking drought…'}</h3>{latest&&<><p>County area in D2–D4. {latest.d1.toFixed(1)}% in moderate drought or worse.</p><small>Weekly map dated {reportDate(latest.date)} · county scope</small></>}<p>Drought is a regional condition, not the status of water service at your home.</p><SourceStatus snapshot={data?.drought}/><a href={droughtUrl} target="_blank" rel="noreferrer">U.S. Drought Monitor <ExternalLink size={13}/></a></article></div>
 <div className="dashboard-middle"><article className="dashboard-card drought-history"><div className="row"><h3>12-month drought history</h3><span className="badge">{latest?.county||"County unresolved"}</span></div><p>Drought Severity and Coverage Index · 0–500</p>{weeks.length>0?<><svg viewBox="0 0 500 120" role="img" aria-label={`Weekly ${latest?.county||"county"} drought index, latest ${latest!.dsci.toFixed(1)} of 500, dated ${latest!.date}`}><line x1="0" y1="110" x2="500" y2="110" stroke="#dfe5e6"/><polyline points={droughtPoints} fill="none" stroke="#ba812e" strokeWidth="3"/></svg><div className="row"><small>{reportDate(weeks[0].date)}</small><strong>{latest!.dsci.toFixed(1)} / 500</strong><small>{reportDate(latest!.date)}</small></div><details><summary>Weekly values and interpretation</summary><p>This county index sums cumulative D0–D4 area percentages. It combines severity and coverage; it is not a forecast or a parcel-level drought rating.</p><div className="drought-table"><table><thead><tr><th>Map date</th><th>Index</th><th>D1+</th><th>D2+</th><th>D3+</th><th>D4</th></tr></thead><tbody>{[...weeks].reverse().map(w=><tr key={w.date}><td>{w.date}</td><td>{w.dsci.toFixed(1)}</td><td>{w.d1.toFixed(1)}%</td><td>{w.d2.toFixed(1)}%</td><td>{w.d3.toFixed(1)}%</td><td>{w.d4.toFixed(1)}%</td></tr>)}</tbody></table></div></details></>:<p className="help">{data?.drought.error||'Collecting weekly history…'}</p>}</article>
 <article className="dashboard-card"><h3>Official provider checks</h3><p>Bluebonnet outage observations and Manor water notices appear below. Check the official provider map for account-specific status.</p><div className="dashboard-links"><a href="https://www.bluebonnet.coop/outages" target="_blank" rel="noreferrer">Bluebonnet outage center <ExternalLink size={13}/></a><a href="https://austinenergy.com/outages" target="_blank" rel="noreferrer">Austin Energy outages <ExternalLink size={13}/></a><a href="https://www.manortx.gov/AlertCenter.aspx" target="_blank" rel="noreferrer">Manor water & traffic alerts <ExternalLink size={13}/></a></div><p className="help">A grid reading or an absence of weather alerts does not establish that local services are operating.</p></article></div>
 <article className="dashboard-card forecast-card"><div className="row"><h3><CloudSun size={18}/>7-day outlook at this location</h3>{forecast?.updated&&<small>Forecast updated {reportDate(forecast.updated,true)}</small>}</div><SourceStatus snapshot={data?.forecast}/>{!home?<p className="help">Set this location to load its NWS forecast.</p>:forecast?<div className="forecast-periods">{forecast.periods.map(p=><details key={p.start}><summary><strong>{p.name}</strong><small>{reportDate(p.start)}</small><b>{p.temperature}°{p.unit}</b><span>{p.short}</span><small>Rain: {p.rain===null?'not supplied':`${p.rain}%`} · {p.wind}</small></summary><p>{p.detail}</p></details>)}</div>:<p className="help">{data?.forecast?.error||'Collecting forecast…'}</p>}<p className="help">Published day and night periods from NWS. Expand a period for details.</p></article>
 {lifelinesPanel}
 {environmentPanel}
 {closuresPanel}
 {waterPanel}
 <HazardsPanel key={home?.join(",")||"default-travis"} home={home} area={area} areaName={areaName} records={riskRecords} areaStatus={riskStatus} areaBusy={riskBusy} refreshArea={refreshRisk} inspect={inspectRisk}/>
 {inAustinRegion(home)?<CommunityPanel placeNote={placeNote} alerts={data?.alerts}/>:<p className="notice">Local community feeds are not connected for this location. NWS alerts above follow this location’s point.</p>}
 </section>;
}
