'use client';
import {useState} from 'react';
import {Plus,Trash2,MapPin,ExternalLink} from 'lucide-react';
import {localDate,type StudyQuestion} from '../lib/collection';
import {newServicePlan,newDependency,newAlternative,resourceSnapshot,planFlags,sharedDependencies,sectors,type ServicePlan,type Dependency,type Alternative,type ResourceSnapshot,type ResourceRecord} from '../lib/dependencies';
type Props={plans:ServicePlan[];change:(plans:ServicePlan[])=>void;records:ResourceRecord[];questions:StudyQuestion[];selectedId:string|null;select:(id:string|null)=>void;inspect:(r:ResourceSnapshot)=>void;openQuestion:(id:string)=>void;narrative:()=>void};
export default function DependenciesPanel({plans,change,records,questions,selectedId,select,inspect,openQuestion,narrative}:Props){
 const [filter,setFilter]=useState('All'),[search,setSearch]=useState(''),[target,setTarget]=useState('primary'),[deleteId,setDeleteId]=useState<string|null>(null);
 const p=plans.find(p=>p.id===selectedId),today=localDate();
 const shown=plans.filter(p=>filter==='All'||(filter==='Needs verification'?planFlags(p,today).gap:planFlags(p,today).reviewDue));
 const shared=sharedDependencies(plans);
 const candidates=search.trim().length>=2?records.filter(r=>`${r.name} ${r.category} ${r.source}`.toLowerCase().includes(search.trim().toLowerCase())).slice(0,15):[];
 function edit(fields:Partial<ServicePlan>){if(p)change(plans.map(x=>x.id===p.id?{...x,...fields}:x));}
 function dependency(id:string,fields:Partial<Dependency>){if(p)edit({dependencies:p.dependencies.map(d=>d.id===id?{...d,...fields}:d)});}
 function alternative(id:string,fields:Partial<Alternative>){if(p)edit({alternatives:p.alternatives.map(a=>a.id===id?{...a,...fields}:a)});}
 function snapshot(r:ResourceSnapshot){return <article className="resource-snapshot"><strong>{r.name}</strong><p>{r.category} · {r.source}</p><p className="help">Source date: {r.date||'Unavailable'}<br/>Source updated: {r.updatedDate||'Unavailable'}<br/>Retrieved: {r.retrievedAt||'Unavailable'}<br/>Snapshot saved: {new Date(r.capturedAt).toLocaleString()}</p>{r.detail&&<details><summary>Saved source details</summary><p className="evidence-excerpt">{r.detail}</p></details>}<button onClick={()=>inspect(r)}><MapPin size={15}/>View saved location</button>{r.url&&<a href={r.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={14}/></a>}</article>;}
 function verification(r:Dependency|Alternative,change:(fields:Partial<Dependency>)=>void){return <><div className="collection-fields"><label>Verification status<select value={r.status} onChange={e=>change({status:e.target.value as Dependency['status']})}>{['Unverified','Verified','Unavailable'].map(s=><option key={s}>{s}</option>)}</select></label><label>Verification date<input type="date" value={r.verifiedOn} onChange={e=>change({verifiedOn:e.target.value})}/></label></div><label>Verification source or observation<input maxLength={1000} value={r.source} onChange={e=>change({source:e.target.value})} placeholder="Agency notice, provider contact, or dated field observation"/></label><label>Verification source URL<input type="url" maxLength={2000} value={r.sourceUrl} onChange={e=>change({sourceUrl:e.target.value})} placeholder="https://"/></label>{r.status!=='Unverified'&&(!r.source.trim()||!r.verifiedOn)&&<p role="alert" className="collection-warning">Add a source and verification date before saving this status.</p>}</>;}
 return <div className="dependencies-content"><div className="row"><div><h3>Dependencies & backup options</h3><p>Plan for interruptions to services you rely on.</p></div><button onClick={narrative}>Open infrastructure narrative</button></div><p className="help">These are your assessments, not live availability reports. “Verified” records your dated check and source. A map location alone does not establish backup capacity or suitability.</p>
 {shared.length>0&&<details className="shared-dependencies"><summary>Shared dependency labels · {shared.length}</summary><p className="help">Matching names entered in multiple plans may indicate a shared failure point. Confirm they refer to the same system; names alone do not establish a connection.</p>{shared.map(g=><div key={g.name}><strong>{g.name}</strong>{g.plans.map(p=><button key={p.id} onClick={()=>{select(p.id);setFilter('All');}}>{p.name}</button>)}</div>)}</details>}
 <div className="dependency-layout"><div className="question-index"><div className="row"><h3>Essential services</h3><button className="primary" disabled={plans.length>=100} onClick={()=>{const item=newServicePlan();change([...plans,item]);select(item.id);setFilter('All');setDeleteId(null);}}><Plus size={16}/>Add service</button></div><label>Service filter<select value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Needs verification','Review due'].map(f=><option key={f}>{f}</option>)}</select></label><div className="question-list">{shown.map(s=>{const f=planFlags(s,today);return <button key={s.id} className={p?.id===s.id?'active':''} onClick={()=>{select(s.id);setDeleteId(null);setSearch('');setTarget('primary');}}><strong>{s.name}</strong><span>{s.sector} · {s.dependencies.length} dependencies · {s.alternatives.length} backups</span>{f.gap&&<b className="collection-warning">Needs verification or planning</b>}{f.reviewDue&&<b className="collection-warning">Review due · {s.reviewOn}</b>}</button>;})}</div>{!shown.length&&<p className="help">{plans.length?'No services match this filter.':'Add an essential service, or start from a map record using Plan dependencies & backups.'}</p>}</div>
 {p?<div className="dependency-editor"><h3>Essential service</h3><label>Service or resource name<input maxLength={300} value={p.name} onChange={e=>edit({name:e.target.value})}/></label><div className="collection-fields"><label>Service type<select value={p.sector} onChange={e=>edit({sector:e.target.value as ServicePlan['sector']})}>{sectors.map(s=><option key={s}>{s}</option>)}</select></label><label>Next service review<input type="date" value={p.reviewOn} onChange={e=>edit({reviewOn:e.target.value})}/></label></div><label>Context and information gaps<textarea maxLength={4000} value={p.notes} onChange={e=>edit({notes:e.target.value})} placeholder="What do you rely on this service for? What still needs checking?"/></label>
 <h4>Primary resource snapshot</h4>{p.primary?<>{snapshot(p.primary)}<button onClick={()=>edit({primary:null})}>Detach primary snapshot</button></>:<p className="help">No map record attached. You can describe a service manually and attach a record below when available.</p>}
 <div className="row"><h4>What this service depends on</h4><button disabled={p.dependencies.length>=20} onClick={()=>edit({dependencies:[...p.dependencies,newDependency()]})}><Plus size={15}/>Add dependency</button></div>{!p.dependencies.length&&<p className="help">Identify dependencies such as electricity, purchased water, deliveries, communications, or a particular access road. Verify each relationship.</p>}{p.dependencies.map(d=><details open className="dependency-card" key={d.id}><summary>{d.name||'Unnamed dependency'} · {d.status}</summary><label>Dependency name<input maxLength={300} value={d.name} onChange={e=>dependency(d.id,{name:e.target.value})} placeholder="Use the same specific name to compare shared dependencies"/></label><label>What happens if this dependency fails?<textarea maxLength={2000} value={d.disruption} onChange={e=>dependency(d.id,{disruption:e.target.value})}/></label>{verification(d,fields=>dependency(d.id,fields))}<button onClick={()=>edit({dependencies:p.dependencies.filter(x=>x.id!==d.id)})}><Trash2 size={15}/>Remove dependency</button></details>)}
 <div className="row"><h4>Backup options</h4><button disabled={p.alternatives.length>=20} onClick={()=>edit({alternatives:[...p.alternatives,newAlternative()]})}><Plus size={15}/>Add backup</button></div>{!p.alternatives.length&&<p className="help">Add an alternative provider, resource, or practical action. Check whether it relies on the same systems as the primary.</p>}{p.alternatives.map(a=><details open className="dependency-card" key={a.id}><summary>{a.name||'Unnamed backup'} · {a.status}</summary><label>Backup name<input maxLength={300} value={a.name} onChange={e=>alternative(a.id,{name:e.target.value})}/></label><label>When would you switch to this backup?<textarea maxLength={2000} value={a.trigger} onChange={e=>alternative(a.id,{trigger:e.target.value})} placeholder="Record a decision trigger; distinguish your plan from official instructions"/></label><label>Backup dependencies and shared failure points<textarea maxLength={2000} value={a.dependencies} onChange={e=>alternative(a.id,{dependencies:e.target.value})}/></label><label>Constraints, capacity and access to check<textarea maxLength={2000} value={a.constraints} onChange={e=>alternative(a.id,{constraints:e.target.value})} placeholder="Opening hours, transport, stock, eligibility, or other limitations"/></label>{verification(a,fields=>alternative(a.id,fields))}{a.resource?<>{snapshot(a.resource)}<button onClick={()=>alternative(a.id,{resource:null})}>Detach backup snapshot</button></>:<p className="help">No source record attached. Attach one below if available.</p>}<button onClick={()=>edit({alternatives:p.alternatives.filter(x=>x.id!==a.id)})}><Trash2 size={15}/>Remove backup</button></details>)}
 <details className="manual-evidence"><summary>Attach a loaded resource or field note</summary><label>Attach record to<select value={target} onChange={e=>setTarget(e.target.value)}><option value="primary">Primary resource</option>{p.alternatives.map(a=><option key={a.id} value={a.id}>Backup · {a.name}</option>)}</select></label><label>Find a resource<input maxLength={200} value={search} onChange={e=>setSearch(e.target.value)} placeholder="At least two characters of name, category or source"/></label><p className="help">Searches loaded records and saved notes. Attachments preserve a snapshot when the AOI changes or a source refreshes.</p><div className="dependency-candidates">{candidates.map(r=><button key={r.id} onClick={()=>{const snap=resourceSnapshot(r);if(target==='primary')edit({primary:snap});else alternative(target,{resource:snap});setSearch('');}}><Plus size={15}/>{r.name} · {r.source}</button>)}</div>{search.trim().length>=2&&!candidates.length&&<p>No matching records. Load an area or add a dated field observation.</p>}</details>
 <h4>Study questions this plan supports</h4><div className="nai-question-links">{questions.map(q=><label key={q.id}><input type="checkbox" checked={p.questionIds.includes(q.id)} onChange={e=>edit({questionIds:e.target.checked?[...p.questionIds,q.id]:p.questionIds.filter(id=>id!==q.id)})}/><span>{q.question}</span></label>)}</div>{!questions.length&&<p className="help">Add a question in Area study → Collection plan to link this service to a decision.</p>}{questions.filter(q=>p.questionIds.includes(q.id)).map(q=><button key={q.id} onClick={()=>openQuestion(q.id)}>Open question · {q.question}</button>)}
 <div className="question-delete">{deleteId===p.id?<><p>Remove this service plan and its saved dependency and backup records?</p><button onClick={()=>{change(plans.filter(x=>x.id!==p.id));select(null);setDeleteId(null);}}>Delete service plan</button><button onClick={()=>setDeleteId(null)}>Keep service plan</button></>:<button onClick={()=>setDeleteId(p.id)}><Trash2 size={15}/>Remove service plan</button>}</div>
 </div>:<div className="collection-empty"><h3>Select or add an essential service</h3><p>Record what it depends on, how an interruption affects you, and what you could use instead.</p></div>}
 </div><p className="help collection-save">Plans, snapshots and question links are included in Save study and GeoJSON export. Review dates flag items here; they do not schedule background checks.</p></div>;
}
