'use client';
import {collectionFetch} from '../lib/collection-activity';
import {useCallback,useEffect,useRef,useState} from 'react';
import {RefreshCw,MapPin} from 'lucide-react';
import HazardProfile from './hazard-profile';
import type {NriRecord} from '../lib/hazards';
import type {ConditionSnapshot} from '../lib/conditions';
import {geometryContains,parcelIntersects,type Point} from '../lib/geo';
import {reportDate} from '../lib/report-dates';
type HomeProfiles={county:ConditionSnapshot<NriRecord[]>;tract?:ConditionSnapshot<NriRecord[]>};
type Props={home:Point|null;area:Point[];areaName:string;records:NriRecord[];areaStatus:string;areaBusy:boolean;refreshArea:()=>void;inspect:(record:NriRecord)=>void};
export default function HazardsPanel({home,area,areaName,records,areaStatus,areaBusy,refreshArea,inspect}:Props){
 const [data,setData]=useState<HomeProfiles|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selectedId,setSelectedId]=useState(''),[clock,setClock]=useState(()=>Date.now());
 const controller=useRef<AbortController|null>(null),url='/api/hazards'+(home?`?lat=${home[0]}&lng=${home[1]}`:'');
 const refresh=useCallback(async()=>{controller.current?.abort();const c=new AbortController();controller.current=c;try{const r=await collectionFetch(url,{signal:c.signal}),d=await r.json() as HomeProfiles&{error?:string};if(!r.ok)throw Error(d.error||'Risk profiles unavailable');if(!c.signal.aborted){setData(d);setError('');setClock(Date.now());}}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Risk profiles unavailable');}finally{if(!c.signal.aborted)setLoading(false);}},[url]);
 // Starts an external request; state updates occur after its response, not synchronously in this effect.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void refresh();const t=setInterval(()=>{if(document.visibilityState==='visible')void refresh();},120000);return()=>{clearInterval(t);controller.current?.abort();};},[refresh]);
 useEffect(()=>{const t=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(t);},[]);
 const available=area.length>=3?records.filter(r=>parcelIntersects(r.geometry,area)):[];
 const chosen=available.find(r=>r.id===selectedId)||available[0];
 const snapshot=(s:ConditionSnapshot<NriRecord[]>|undefined,title:string)=><article className="dashboard-card nri-home-card"><div className="row"><h3>{title}</h3>{s?.cached&&<span className="badge">Cached</span>}</div>{s?.error&&<p className="notice">{s.error}{s.data?' · older snapshot shown':' · profile unavailable'}</p>}{s?.fetchedAt&&<p className="help">Retrieved {reportDate(s.fetchedAt,true)}{clock-Date.parse(s.fetchedAt)>86400000?' · source check overdue':''}</p>}{s?.cacheWarning&&<p className="notice">{s.cacheWarning}</p>}{!s?.data&&<p className="help">{s?.error?'No profile available.':loading?'Loading FEMA profiles…':'No profile loaded.'}</p>}{s?.data&&s.data.length>1&&<p className="notice">This point intersects multiple published boundaries. All matches are shown; confirm the relevant geography.</p>}{s?.data?.map(r=><div key={r.id}><HazardProfile profile={r.risk}/><button onClick={()=>inspect({...r,retrievedAt:s.fetchedAt,stale:!!s.error||!!s.fetchedAt&&clock-Date.parse(s.fetchedAt)>86400000})}><MapPin size={15}/>View profile boundary</button></div>)}</article>;
 return <section className="nri-section"><div className="row"><div><span className="eyebrow">LONG-TERM HAZARD CONTEXT</span><h2>County & neighborhood profiles</h2></div><button disabled={loading} onClick={()=>{setLoading(true);void refresh();}}><RefreshCw size={16}/>{loading?'Checking profiles…':'Check FEMA profiles'}</button></div><p>Census tracts approximate local areas; they do not follow every neighborhood boundary. The county and tract comparison populations differ, so their scores are not directly interchangeable.</p>{error&&<p className="notice" role="alert">{error}. Older results may remain below.</p>}
 <div className="nri-profile-grid">{snapshot(data?.county,home?'County containing this location':'Set a location to resolve its county')}{home?snapshot(data?.tract,'Census tract at this location'):<article className="dashboard-card"><h3>Census tract at this location</h3><p>Set this location in Map workspace to resolve its published tract. County profiles follow the selected location.</p></article>}</div>
 <article className="dashboard-card nri-area-card"><div className="row"><h3>Tracts intersecting your {areaName}</h3><button disabled={areaBusy||area.length<3} onClick={refreshArea}><RefreshCw size={15}/>{areaBusy?'Loading area…':'Check area profiles'}</button></div>{area.length<3?<p>Draw an AOR or AOI to collect the tracts intersecting that area automatically.</p>:<><p>{available.length} loaded tract profiles intersect this boundary. No tract scores are averaged into an area or household score.</p><p className="help">{areaStatus||'Waiting for area profile collection…'}</p>{available.some(r=>r.stale)&&<p className="notice">Some area profiles are stale. Verify their release and source before relying on them.</p>}{available.length>0&&<><label>Choose a tract<select value={chosen?.id||''} onChange={e=>setSelectedId(e.target.value)}>{available.map(r=><option key={r.id} value={r.id}>{r.risk.tractFips} · {r.risk.county}{home&&geometryContains(r.geometry,home)?' · contains home':''}</option>)}</select></label>{chosen&&<><HazardProfile key={chosen.id} profile={chosen.risk}/><p className="help">Retrieved {chosen.retrievedAt?reportDate(chosen.retrievedAt,true):'Unavailable'}</p><button onClick={()=>inspect(chosen)}><MapPin size={15}/>View selected tract on map</button></>}</>}</>}</article>
 <details className="nri-attribution"><summary>Sources and interpretation</summary><p>Uses FEMA’s National Risk Index data and API. This app is not endorsed by FEMA. FEMA and the federal government do not verify this app’s retrieved data or derived analyses.</p><p>Release comes from each source record’s NRI_VER field. Catalog update time records the ArcGIS item modification, not the date of a hazard observation. No current observation time is supplied by this static dataset. Profile queries and overlapping area snapshots are cached for 24 hours; failed refreshes retain clearly labeled older results.</p><a href="https://www.fema.gov/sites/default/files/documents/fema_national-risk-index_technical-documentation.pdf" target="_blank" rel="noreferrer">FEMA technical documentation</a><a href="https://www.arcgis.com/home/item.html?id=9da4eeb936544335a6db0cd7a8448a51" target="_blank" rel="noreferrer">FEMA tract dataset metadata</a><p>Use a profile as context for a study question, then examine local flood mapping, routes, current alerts and verified service dependencies. A high relative score alone does not establish an active disruption.</p></details>
 </section>;
}
