"use client";
import {useEffect,useRef,useState} from 'react';
import {ExternalLink,Landmark,MapPin,Phone,RefreshCw} from 'lucide-react';
import {jurisdictionSources,jurisdictionState,jurisdictionContacts,jurisdictionNote,representativeUrl,type JurisdictionSnapshot,type JurisdictionMatch} from '../lib/jurisdictions';
import type {Point} from '../lib/geo';
import {reportDate} from '../lib/report-dates';
export default function JurisdictionsPanel({home,address,inspect,placeNote}:{home:Point|null,address:string,inspect:(match:JurisdictionMatch,snapshot:JurisdictionSnapshot)=>void,placeNote:(title:string,detail:string)=>void}){
 const [now]=useState(()=>Date.now());
 const [result,setResult]=useState<{point:Point,sources:JurisdictionSnapshot[]}|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');const generation=useRef(0);
 const key=home?JSON.stringify(home):'',current=result&&JSON.stringify(result.point)===key?result:null,sources=current?.sources||[],contacts=jurisdictionContacts(sources),registry=current?jurisdictionSources.filter(s=>sources.some(x=>x.sourceId===s.id)):[],hays=registry.some(s=>s.id.startsWith('hays-'));
 useEffect(()=>{if(!key)return;const controller=new AbortController(),n=++generation.current;queueMicrotask(()=>{if(controller.signal.aborted)return;setLoading(true);setError('');fetch('/api/jurisdictions?'+new URLSearchParams({lat:String(JSON.parse(key)[0]),lng:String(JSON.parse(key)[1])}),{signal:controller.signal}).then(async r=>{const d=await r.json() as {point:Point,sources:JurisdictionSnapshot[],error?:string};if(!r.ok||!Array.isArray(d.sources))throw Error(d.error||'Jurisdiction lookup unavailable');if(!controller.signal.aborted&&n===generation.current)setResult(d);}).catch(e=>{if(!controller.signal.aborted&&n===generation.current)setError(e instanceof Error?e.message:'Lookup unavailable');}).finally(()=>{if(!controller.signal.aborted&&n===generation.current)setLoading(false);});});return()=>controller.abort();},[key]);
 async function refresh(){if(!home||loading)return;const n=++generation.current;setLoading(true);setError('');try{const r=await fetch('/api/jurisdictions?'+new URLSearchParams({lat:String(home[0]),lng:String(home[1])})),d=await r.json() as {point:Point,sources:JurisdictionSnapshot[],error?:string};if(!r.ok||!Array.isArray(d.sources))throw Error(d.error||'Lookup unavailable');if(n===generation.current)setResult(d);}catch(e){if(n===generation.current)setError(e instanceof Error?e.message:'Lookup unavailable');}finally{if(n===generation.current)setLoading(false);}}
 return <section className="community-content jurisdiction-content"><div className="row"><div><span className="eyebrow">HOME JURISDICTIONS & CIVIC CONTACTS</span><h2>Who serves this address?</h2></div><button disabled={!home||loading} onClick={refresh}><RefreshCw size={16}/>{loading?'Checking boundaries…':'Check boundaries'}</button></div>
 <p className="community-intro">Use official published boundaries to identify relevant offices. Matches follow your home pin; nearby borders and overlapping records need review.</p>
 <div className="jurisdiction-home"><MapPin size={20}/><div><strong>{home?address||'Selected home location':'Choose a home address or map location'}</strong><p>{home?'Point-based lookup · official boundary sources · connected county coverage':'Set home using the address search or Place home on map in the left sidebar.'}</p></div></div>
 {error&&<p className="notice" role="alert">{error}. Any retained results must be verified directly.</p>}
 {!home?<div className="empty"><Landmark size={28}/><b>Your home point starts the lookup</b><p>Postal city and ZIP code alone do not establish city limits, school district, or service eligibility.</p></div>:<><div className="jurisdiction-grid">{registry.map(source=>{const snapshot=sources.find(s=>s.sourceId===source.id),matches=snapshot?.data?.matches||[];return <article className="jurisdiction-card" key={source.id}><div className="row"><h3>{source.name}</h3><span className="badge">{loading&&!current?'Checking…':jurisdictionState(snapshot)}</span></div>{snapshot?.error&&<p className="notice">{snapshot.error}{snapshot.data?' · Older cached result.':''}</p>}{matches.map(m=><div className="jurisdiction-match" key={m.id}><strong>{m.name}</strong><span>{m.role}</span><p>{m.contains?'Home pin intersects this published boundary.':'Nearby boundary only; the home pin is outside this polygon.'}{m.nearBoundary?' Within 25 m of a mapped border; confirm the address position.':''}</p><small>Record edited: {reportDate(m.recordUpdated||undefined,true)}</small><button onClick={()=>snapshot&&inspect(m,snapshot)}><MapPin size={14}/>View boundary on map</button></div>)}{snapshot?.data&&!matches.length&&<p className="help">No matching boundary returned in this source. This does not establish an unincorporated address or absence of service.</p>}<p className="help">{source.note}</p><details><summary>Source dates & verification</summary><small>Collected: {reportDate(snapshot?.fetchedAt,true)}{snapshot?.cached?' · reused point cache':''}</small><small>Service data edited: {reportDate(snapshot?.data?.serviceUpdated||undefined,true)}</small><small>Next eligible collection: {reportDate(snapshot?.nextCheckAt,true)}</small>{snapshot?.cacheWarning&&<small>{snapshot.cacheWarning}</small>}<a href={source.url} target="_blank" rel="noreferrer">Published boundary source <ExternalLink size={13}/></a><a href={source.verify} target="_blank" rel="noreferrer">Official jurisdiction check <ExternalLink size={13}/></a></details>{snapshot?.data&&<button className="jurisdiction-note" onClick={()=>placeNote(source.name+' · home lookup',jurisdictionNote(source,snapshot))}>Keep lookup in field notes</button>}</article>;})}</div>
 <p className="help">City boundaries, limited-purpose areas, and ETJs are distinct. An ETJ match does not make a home a city resident. These are home-point results, not coverage of your whole AOR/AOI. Cached matches refresh after 24 hours; moving home starts a new lookup. Source edits and collection times are not boundary effective dates.</p>
 <div className="row jurisdiction-contact-heading"><h2>Relevant office contacts</h2><span className="badge">For emergencies, call 911</span></div><p className="help">Contacts are associated with mapped matches, including clearly labeled older or ambiguous results. Phone numbers were checked on official office pages on October 7, 2026; they are a dated reference, not a live directory. Other cities, school districts and ESDs use the official directories below.</p>
 {!contacts.length&&<p className="notice">No curated office contact matches these returned boundaries. Use the official address and district directories to confirm the appropriate office.</p>}
 <div className="jurisdiction-contacts">{contacts.map(c=><article key={c.id}><h3>{c.name}</h3><p>{c.purpose}</p><p className="help">{c.context}</p>{c.phone&&<a className="jurisdiction-phone" href={'tel:+1'+c.phone.replace(/\D/g,'')}><Phone size={16}/>{c.phone}{c.extension?' · '+c.extension:''}</a>}<a href={c.url} target="_blank" rel="noreferrer">Official office page <ExternalLink size={14}/></a><small>Contact checked: {c.verified}{now-Date.parse(c.verified+'T12:00:00Z')>30*86400000?' · review due':''}</small></article>)}</div></>}
 <div className="jurisdiction-directories"><a href={hays?'https://hays-county-haysgis.hub.arcgis.com/':representativeUrl} target="_blank" rel="noreferrer">County address & representative lookup <ExternalLink size={14}/></a><a href={hays?'https://www.hayscountytx.gov/346/Emergency-Services-Districts':'https://www.traviscountytx.gov/fire-marshal/esd'} target="_blank" rel="noreferrer">Official ESD directory & viewer <ExternalLink size={14}/></a></div>
 </section>;
}
