'use client';
import {useEffect,useRef} from 'react';
import {ChevronDown,ChevronRight} from 'lucide-react';
import {CategoryIcon} from '../lib/category-icons';
import {layerGroups,toggleGroup} from '../lib/layer-groups';
function GroupCheck({name,count,total,toggle}:{name:string;count:number;total:number;toggle:()=>void}){const ref=useRef<HTMLInputElement>(null);useEffect(()=>{if(ref.current)ref.current.indeterminate=count>0&&count<total;},[count,total]);return <input ref={ref} type="checkbox" aria-label={'Toggle '+name} aria-checked={count>0&&count<total?'mixed':count===total} checked={count===total} onChange={toggle}/>;}
export default function LayerGroups({enabled,change,colors,count,collapsed,setCollapsed}:{collapsed:string[];setCollapsed:(v:string[]|((x:string[])=>string[]))=>void;enabled:string[];change:(v:string[])=>void;colors:Record<string,string>;count:(c:string)=>number}){
 return <div className="layer-groups"><div className="layer-group-actions"><button disabled={!collapsed.length} onClick={()=>setCollapsed([])}>Expand groups</button><button disabled={collapsed.length===layerGroups.length} onClick={()=>setCollapsed(layerGroups.map(g=>g.name))}>Collapse groups</button></div>{layerGroups.map((g,i)=>{const n=g.layers.filter(c=>enabled.includes(c)).length,closed=collapsed.includes(g.name);return <section className="layer-group" key={g.name}><div className="layer-group-heading"><GroupCheck name={g.name} count={n} total={g.layers.length} toggle={()=>change(toggleGroup(enabled,g.layers))}/><button aria-expanded={!closed} aria-controls={'layer-group-'+i} onClick={()=>setCollapsed(x=>closed?x.filter(n=>n!==g.name):[...x,g.name])}>{closed?<ChevronRight size={16}/>:<ChevronDown size={16}/>}<span>{g.name}<small>{n} / {g.layers.length} enabled · {g.layers.reduce((s,c)=>s+count(c),0)} records</small></span></button></div><div id={'layer-group-'+i} hidden={closed}>{g.layers.map(c=><label className="layer" key={c}><input type="checkbox" checked={enabled.includes(c)} onChange={()=>change(enabled.includes(c)?enabled.filter(y=>y!==c):[...enabled,c])}/><CategoryIcon category={c} color={colors[c]}/><span>{c}</span><small>{count(c)}</small></label>)}</div></section>;})}</div>;
}
