"use client";
import {collectionFetch} from '../lib/collection-activity';
import {localSourcePacks,haysLinks} from '../lib/local-source-packs';

import {useEffect,useState} from 'react';
import type {Point} from '../lib/geo';
import type {ConditionSnapshot} from '../lib/conditions';
import type {LocationGeography} from '../lib/location-geography';
export default function LocationContext({point}:{point:Point|null}){const [snapshot,setContext]=useState<ConditionSnapshot<LocationGeography>|null>(null);const [contextKey,setContextKey]=useState('');const key=point?.join(',')||'',context=contextKey===key?snapshot:null;useEffect(()=>{if(!key)return;const c=new AbortController();void collectionFetch('/api/location-context?lat='+key.split(',')[0]+'&lng='+key.split(',')[1],{signal:c.signal}).then(r=>r.json() as Promise<ConditionSnapshot<LocationGeography>>).then(d=>{if(!c.signal.aborted){setContext(d);setContextKey(key);}}).catch(()=>{if(!c.signal.aborted){setContext({error:'County lookup unavailable',checkedAt:'',nextCheckAt:''});setContextKey(key);}});return()=>c.abort();},[key]);if(!point)return null;return <div className="location-geography">{context?.data?<><strong>{context.data.county}, {context.data.state}</strong><small>{context.data.place}</small>{context.data.schools.map(s=><small key={s}>{s}</small>)}{!localSourcePacks.some(p=>p.countyFips===context.data!.countyFips)&&<p className="notice">Local parcel, service-boundary and civic feeds are not connected for this county. National sources still load. Add a local source pack to fill the gaps.</p>}{context.data.countyFips==='48209'&&<><p className="help">Hays source pack connected: parcels, city/county/precinct/school boundaries, road-closure points and civic calendars. Texas PUC water/sewer territories load statewide. Fire/EMS response boundaries and live utility advisories remain collection gaps.</p><details><summary>Hays / Wimberley official resources</summary>{haysLinks.map(l=><p key={l.url}><a href={l.url} target="_blank" rel="noreferrer">{l.name}</a><small>{l.note}</small></p>)}</details></>}<a href={context.data.source} target="_blank" rel="noreferrer">Census geographic lookup</a><small>Point match against Current_Current geography. Verify current service jurisdiction with the agency.</small></>:<small>{context?.error||'Resolving county and school geography…'}</small>}</div>;}
