"use client";
import {useState} from 'react';
import {Crosshair,MapPin,Pentagon,ExternalLink,Trash2} from 'lucide-react';
import type {NamedArea} from '../lib/nais';
import type {StudyQuestion} from '../lib/collection';
type Props={areas:NamedArea[],selectedId:string|null,select:(id:string)=>void,change:(area:NamedArea)=>void,draw:(kind:NamedArea['kind'],id?:string)=>void,remove:(id:string)=>void,questions:StudyQuestion[],link:(questionId:string,areaId:string,checked:boolean)=>void,openQuestion:(id:string)=>void};
export default function NaiPanel(p:Props){
 const [confirmId,setConfirmId]=useState<string|null>(null),n=p.areas.find(x=>x.id===p.selectedId);
 const links=n?p.questions.filter(q=>q.naiIds.includes(n.id)):[];
 return <div className="panel-content nai-panel"><div className="row"><h2>Named areas of interest</h2><span className="count">{p.areas.length} / 100</span></div><p className="help">Mark a specific crossing, access road, facility, or area to monitor. Link it to the questions it can help answer.</p><div className="data-actions"><button disabled={p.areas.length>=100} onClick={()=>p.draw('Point')}><MapPin size={15}/>Place a point</button><button disabled={p.areas.length>=100} onClick={()=>p.draw('Polygon')}><Pentagon size={15}/>Draw an area</button></div><p className="help">These locations do not change your AOR, AOI, or automatic data search. Locations outside those boundaries may need additional source collection.</p>
 <div className="nai-list">{p.areas.map(a=><button key={a.id} className={a.id===p.selectedId?'active':''} onClick={()=>{p.select(a.id);setConfirmId(null);}}><Crosshair size={18}/><span><strong>{a.name||'Unnamed area'}</strong><small>{a.kind} · Questions: {p.questions.filter(q=>q.naiIds.includes(a.id)).length}</small></span></button>)}</div>
 {n&&<><label>Name<input maxLength={160} value={n.name} onChange={e=>p.change({...n,name:e.target.value})}/></label><label>What to monitor<textarea maxLength={2000} value={n.notes} onChange={e=>p.change({...n,notes:e.target.value})} placeholder="Why does this location matter, and what should be checked here?"/></label><p className="help">{n.kind==='Point'?`${n.points[0][0].toFixed(5)}, ${n.points[0][1].toFixed(5)}`:`${n.points.length} polygon corners`}</p><button onClick={()=>p.draw(n.kind,n.id)}>{n.kind==='Point'?'Move point':'Redraw area'}</button><h3>Linked study questions</h3>{!p.questions.length&&<p className="help">Create a question in Area study → Collection plan, then link it here.</p>}<div className="nai-question-links">{p.questions.map(q=><label key={q.id}><input type="checkbox" checked={q.naiIds.includes(n.id)} onChange={e=>p.link(q.id,n.id,e.target.checked)}/><span>{q.question}</span></label>)}</div>{links.map(q=><button className="nai-open-question" key={q.id} onClick={()=>p.openQuestion(q.id)}><ExternalLink size={14}/><span>Open question: {q.question}</span></button>)}<div className="question-delete">{confirmId===n.id?<><p>Delete this named area and unlink its {links.length} questions? The questions and their evidence will remain.</p><button onClick={()=>{p.remove(n.id);setConfirmId(null);}}>Delete named area</button><button onClick={()=>setConfirmId(null)}>Keep named area</button></>:<button onClick={()=>setConfirmId(n.id)}><Trash2 size={15}/>Delete named area</button>}</div></>}
 {!p.areas.length&&<p className="help">Start with a location relevant to an existing question, such as a crossing on your alternate route.</p>}</div>;
}
