"use client";
import {useState} from 'react';
import type {InboxEntry,InboxSummary} from '../lib/peer-ui';
import type {SharedPackage} from '../lib/sharing-schema';
import {parseSharedPackage} from '../lib/sharing';
import {verifySignedPackage} from '../lib/sharing-auth';
type Request=<T>(route:string,body?:unknown)=>Promise<T>;
const when=(date:string|null)=>date?new Date(date).toLocaleString():'Not yet';
function Entry({entry,label,busy,dirty,request,act,receive}:{entry:InboxEntry;label:string;busy:boolean;dirty:boolean;request:Request;act:(fn:()=>Promise<void>)=>void;receive:(pkg:SharedPackage,label:string,peerId?:string)=>void}){
 const [reason,setReason]=useState(entry.reason);
 function decide(state:InboxEntry['state']){act(async()=>{await request('/inbox/review',{id:entry.id,digest:entry.digest,state,reason,expectedState:entry.state,expectedReviewedAt:entry.reviewedAt});});}
 return <details className="shared-review"><summary>{label} · {entry.state} · received {when(entry.receivedAt)}</summary><p className="help">Last seen {when(entry.lastSeenAt)} · decision {when(entry.reviewedAt)}</p>{entry.reason&&<p>Saved reason: {entry.reason}</p>}<button disabled={busy} onClick={()=>act(async()=>{const result=await request<{package:unknown;stale:boolean;peerId:string}>('/inbox-entry/'+entry.id);const pkg=parseSharedPackage(JSON.stringify(result.package));await verifySignedPackage(pkg);receive(pkg,label+(result.stale?' · older data after failed refresh':''),result.peerId);})}>Preview this update</button><label>Review reason<textarea maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why you deferred/dismissed this update, or what you verified"/></label><div className="peer-actions"><button disabled={busy||dirty} onClick={()=>decide('Merged')}>Mark merged after saving</button><button disabled={busy||!reason.trim()} onClick={()=>decide('Deferred')}>Defer</button><button disabled={busy||!reason.trim()} onClick={()=>decide('Dismissed')}>Dismiss</button>{entry.state!=='Pending'&&<button disabled={busy} onClick={()=>decide('Pending')}>Return to pending</button>}</div><p className="help">Mark merged checks that every contribution, revision, review and signature proof in this package exists in your saved study. A partial merge stays pending or can be deferred.</p>{dirty&&<p className="notice">Save study before marking this update merged.</p>}</details>;
}
export default function PeerInboxPanel({entries,summary,capacity,peers,busy,dirty,request,act,receive}:{entries:InboxEntry[];summary:InboxSummary;capacity?:{entries:number;bytes:number;maxEntries:number;maxBytes:number};peers:{id:string;label:string;groupName:string}[];busy:boolean;dirty:boolean;request:Request;act:(fn:()=>Promise<void>)=>void;receive:(pkg:SharedPackage,label:string,peerId?:string)=>void}){
 const [filter,setFilter]=useState('Pending'),[search,setSearch]=useState(''),[peer,setPeer]=useState('All'),[page,setPage]=useState(1);
 const matches=entries.filter(e=>(filter==='All'||e.state===filter)&&(peer==='All'||e.peerId===peer)&&[e.reason,peers.find(p=>p.id===e.peerId)?.label,peers.find(p=>p.id===e.peerId)?.groupName,e.state].join(' ').toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 const current=Math.min(page,Math.max(1,Math.ceil(matches.length/25))),visible=matches.slice((current-1)*25,current*25);
 return <section className="peer-inbox"><h4>Federation inbox</h4><p role="status">{summary.pending} pending · {summary.deferred} deferred · last successful sync {when(summary.lastSuccess)}</p><p className="help">Updates stay on disk across restarts. Nothing merges automatically. Identical content retains its review state even when pulled again. New content creates a separate pending entry.</p><label>Search inbox<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}} placeholder="Peer, group or decision reason"/></label><label>Inbox peer<select value={peer} onChange={e=>{setPeer(e.target.value);setPage(1);}}><option value="All">All</option>{peers.map(p=><option key={p.id} value={p.id}>{p.label} · {p.groupName}</option>)}</select></label><label>Inbox filter<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}>{['Pending','Deferred','Dismissed','Merged','All'].map(v=><option key={v}>{v}</option>)}</select></label>{visible.map(e=><Entry key={e.id+':'+e.state+':'+e.reviewedAt} entry={e} label={peers.find(p=>p.id===e.peerId)?.label+' · '+(peers.find(p=>p.id===e.peerId)?.groupName||'Shared group')} busy={busy} dirty={dirty} request={request} act={act} receive={receive}/>)}<div className="row"><button disabled={current<=1} onClick={()=>setPage(current-1)}>Previous inbox page</button><span>{matches.length} matches · page {current}/{Math.max(1,Math.ceil(matches.length/25))}</span><button disabled={current>=Math.ceil(matches.length/25)} onClick={()=>setPage(current+1)}>Next inbox page</button></div>{!visible.length&&<p>No {filter==='All'?'':filter.toLowerCase()+' '}updates.</p>}<button disabled={busy||!entries.some(e=>e.state==='Merged'||e.state==='Dismissed')} onClick={()=>act(async()=>{await request('/inbox/clear-reviewed',{});})}>Clear merged and dismissed package copies</button><p className="help">Pending and deferred updates are retained. Up to 2,048 content receipts prevent cleared updates from appearing again. The inbox holds at most 128 package copies / 64 MB; a full inbox stops new collection and retains existing updates.</p>{capacity&&<><p>{capacity.entries}/{capacity.maxEntries} copies · {(capacity.bytes/1000000).toFixed(2)} / {(capacity.maxBytes/1000000).toFixed(2)} MB used</p><progress aria-label="Inbox storage capacity" value={capacity.bytes} max={capacity.maxBytes}/></>}</section>;
}
