"use client";
import {useEffect,useState} from 'react';
export type NetworkInfo={enabled:boolean;state:string;connected:boolean;checkedAt:string;selfIPs:string[];boundHost:string;peers:{id:string;remote:boolean;visible:boolean|null;online:boolean|null}[]};
const stateLabels:Record<string,string>={NotInstalled:'Client command not found',NeedsLogin:'Sign-in needed',NeedsApproval:'Device approval needed',Stopped:'Disconnected',Unavailable:'Status unavailable',Running:'Running'};
const guidance:Record<string,string>={NotInstalled:'Install the official Tailscale client on both computers, then sign in.',NeedsLogin:'Open Tailscale and sign in on this computer.',NeedsApproval:'Ask your Tailscale administrator to approve this computer.',Stopped:'Connect Tailscale on this computer.',Unavailable:'The local Tailscale status could not be read. Confirm the client/service is installed and running.',Running:'Tailscale is running. Test the signed Field Desk connection to verify port access and peer identity.'};
export default function PeerNetworkPanel({mode,network,busy,request,act}:{mode:string;network:NetworkInfo|null;busy:boolean;request:<T>(route:string,body?:unknown)=>Promise<T>;act:(fn:()=>Promise<void>)=>void}){
 const [snapshot,setSnapshot]=useState(network);useEffect(()=>{setSnapshot(network);},[network]);
 return <details className="peer-network"><summary>Remote setup & connectivity · {mode}</summary><p>For coworkers or neighbors in different homes, run Field Desk locally and use Tailscale to connect the sync companions.</p><ol><li>Install and sign in to <a href="https://tailscale.com/download" target="_blank" rel="noreferrer">Tailscale</a> on both computers.</li><li>Share the publisher computer with the other person through Tailscale and have them accept the device invitation. For two-way sync, share each computer with the other person. Limit network access to the companion TCP peer port (default 5186) in your Tailscale access policy.</li><li>Start the companion with <code>pnpm sync --tailscale</code>. It selects your own Tailscale IPv4 address; controls and the normal app stay on localhost.</li><li>Exchange Field Desk public identity cards, compare fingerprints separately, choose a group and contributions, and exchange recipient-bound invitations. Each direction needs its own invitation.</li><li>Use Test signed connection below, then Sync now. Both computers need Tailscale and their companion running. Previously received updates remain in your local inbox while peers are offline.</li></ol><p className="help">Tailscale device access and Field Desk sharing permissions are separate. Sharing a computer does not share your whole study or authorize relaying another person's contributions.</p><button disabled={busy} onClick={()=>act(async()=>{setSnapshot(await request<NetworkInfo>('/network',{}));})}>Check Tailscale status</button>{snapshot&&<><p role="status">Tailscale: {snapshot.state==='Running'&&!snapshot.connected?'Disconnected':stateLabels[snapshot.state]||snapshot.state} · checked {new Date(snapshot.checkedAt).toLocaleString()}</p><p>{guidance[snapshot.state==='Running'&&!snapshot.connected?'Stopped':snapshot.state]||'Review your local Tailscale client status.'}</p><p className="help">Your Tailscale IPv4: {snapshot.selfIPs.join(', ')||'Unavailable'} · companion bound to {snapshot.boundHost}</p>{!snapshot.enabled&&<p className="notice">This companion is in local/LAN mode. Stop it, then run pnpm sync --tailscale before creating remote invitations.</p>}</>}<p><a href="https://tailscale.com/docs/features/sharing" target="_blank" rel="noreferrer">Device sharing guide</a> · <a href="https://tailscale.com/docs/reference/inviting-vs-sharing" target="_blank" rel="noreferrer">Sharing and access policies</a></p><p className="help">If the companion address changes, revoke its old outgoing invitations and create new ones. This version uses numeric Tailscale IPv4 addresses; IPv6 and MagicDNS names are not supported.</p></details>;
}
