"use client";
import {useState,useMemo} from 'react';
import {Radio,Plus,MapPin,Bookmark,Download,ExternalLink} from 'lucide-react';
import {channelFromRepeater,newRadioChannel,radioChannelSchema,distanceKm,radioDirectory,type RadioChannel,type RadioRepeater} from '../lib/radio';
import {reportDate} from '../lib/report-dates';
import {inLocalRegion} from '../lib/source-regions';
import type {Point} from '../lib/geo';
export default function RadioPanel({plan,change,records,home,status,busy,refresh,inspect}:{plan:RadioChannel[];change:(p:RadioChannel[])=>void;records:RadioRepeater[];home:Point|null;status:string;busy:boolean;refresh:()=>void;inspect:(id:string)=>void}){
 const [draft,setDraft]=useState<RadioChannel|null>(null),[error,setError]=useState(''),[query,setQuery]=useState('');
 const nearby=useMemo(()=>records.filter(p=>!query||[p.name,p.radio.city,p.radio.mode].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>home?distanceKm(home,[a.lat,a.lng])-distanceKm(home,[b.lat,b.lng]):a.name.localeCompare(b.name)),[records,home,query]);
 const edit=(entry:RadioChannel)=>{setDraft({...entry});setError('');};
 function commit(e:React.FormEvent){e.preventDefault();if(!draft)return;const parsed=radioChannelSchema.safeParse(draft);if(!parsed.success){setError(parsed.error.issues[0].message);return;}if(plan.length>=200&&!plan.some(p=>p.id===draft.id)){setError('This location supports up to 200 saved frequencies.');return;}change(plan.some(p=>p.id===draft.id)?plan.map(p=>p.id===draft.id?parsed.data:p):[...plan,parsed.data]);setDraft(null);setError('');}
 function exportCSV(){const fields=['name','service','receiveMHz','transmitMHz','mode','tone','callsign','source','sourceUrl','sourceDate','verification','checkedOn','notes'] as const;const csv=[fields.join(','),...plan.map(p=>fields.map(k=>'"'+(/^[=+\-@\t\r]/.test(String(p[k]))?"\'"+String(p[k]):String(p[k])).replaceAll('"','""')+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='local-radio-frequencies.csv';a.click();URL.revokeObjectURL(url);}
 return <div className="radio-workspace"><div className="row"><h3><Radio size={19}/> Local radio & frequencies</h3><button onClick={refresh} disabled={busy}>{busy?'Loading repeaters…':'Refresh repeaters'}</button></div><p className="help">Repeater searches cover an approximately 40 km margin around the area centre. Approximate directory positions are shown even outside the AOR/AOI when their layer is enabled. Location and proximity do not establish reception, operating status or permission to use a repeater.</p><p role="status" className="help">{status||'Draw an AOR or AOI to load the nearby repeater directory automatically.'}</p>
 <section className="radio-card"><div className="row"><h3>Saved frequencies · this location</h3><div className="radio-actions"><button onClick={()=>edit(newRadioChannel())} disabled={plan.length>=200}><Plus size={16}/>Add frequency</button><button onClick={exportCSV} disabled={!plan.length}><Download size={16}/>Export CSV</button></div></div><p className="help">Save weather, amateur, GMRS, broadcast or other useful channels here. Reception checks and notes belong to the active location. Use Save study to keep changes.</p>
 {draft&&<form className="radio-form" onSubmit={commit}><h4>{plan.some(p=>p.id===draft.id)?'Edit frequency':'Add frequency'}</h4><div className="radio-form-grid">{(['name','receiveMHz','transmitMHz','mode','tone','callsign','source','sourceUrl','sourceDate','checkedOn'] as const).map(k=><label key={k}>{({name:'Name',receiveMHz:'Receive / output (MHz)',transmitMHz:'Input / transmit (MHz, optional)',mode:'Mode',tone:'Tone / access code',callsign:'Call sign',source:'Source',sourceUrl:'Source link',sourceDate:'Source record date (if supplied)',checkedOn:'Reception checked on'})[k]}<input type={k==='sourceDate'||k==='checkedOn'?'date':k==='sourceUrl'?'url':'text'} required={k==='name'||k==='receiveMHz'} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Service<select value={draft.service} onChange={e=>setDraft({...draft,service:e.target.value as RadioChannel['service']})}>{['Amateur repeater','Weather radio','GMRS','Public safety','Broadcast','Other'].map(v=><option key={v}>{v}</option>)}</select></label><label>Reception at this location<select value={draft.verification} onChange={e=>setDraft({...draft,verification:e.target.value as RadioChannel['verification']})}>{['Not checked','Heard','Not heard'].map(v=><option key={v}>{v}</option>)}</select></label></div><label>Notes / net schedule / equipment<textarea value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label>{error&&<p role="alert" className="notice">{error}</p>}<div className="radio-actions"><button type="submit" className="primary">Keep frequency</button><button type="button" onClick={()=>setDraft(null)}>Cancel</button></div></form>}
 {!plan.length&&!draft&&<p>No frequencies saved for this location yet.</p>}{plan.map(p=><article className="radio-saved" key={p.id}><div><strong>{p.name}</strong><span className="radio-frequency">{p.receiveMHz} MHz</span><small>{p.service} · {p.mode||'Mode unknown'} · {p.tone||'Tone not supplied'}{p.transmitMHz?' · Input '+p.transmitMHz+' MHz':''}</small><small>{p.verification}{p.checkedOn?' · '+p.checkedOn:''} · {p.source||'Source not recorded'}{p.collectedAt?' · captured '+reportDate(p.collectedAt,true):''}</small>{p.sourceUrl&&<a href={p.sourceUrl} target="_blank" rel="noreferrer">Original source <ExternalLink size={13}/></a>}<p>{p.notes}</p></div><div className="radio-actions"><button onClick={()=>edit(p)}>Edit</button><button onClick={()=>change(plan.filter(x=>x.id!==p.id))}>Remove</button></div></article>)}</section>
 <section className="radio-card"><h3>Weather radio reference</h3><p>NOAA Weather Radio uses 162.400, 162.425, 162.450, 162.475, 162.500, 162.525 and 162.550 MHz nationwide. Check which station you can receive locally.</p><a href="https://www.weather.gov/nwr/stations" target="_blank" rel="noreferrer">Official NWS transmitter directory</a>{home&&inLocalRegion(home)&&<div className="radio-saved"><div><strong>Austin NOAA weather radio</strong><span className="radio-frequency">162.400 MHz · receive only</span><small>Published in the NWS April 2025 brochure; reception and current availability not checked.</small></div><button disabled={plan.length>=200} onClick={()=>edit({...newRadioChannel(),name:'Austin NOAA weather radio',service:'Weather radio',receiveMHz:'162.400',mode:'FM',source:'National Weather Service · April 2025 brochure',sourceUrl:'https://www.weather.gov/media/nwr/NWR_Brochure_250428.pdf',notes:'Receive-only weather broadcast. Check reception at this location and current NWS transmitter information.'})}><Bookmark size={16}/>Keep frequency</button></div>}</section>
 <section className="radio-card"><div className="row"><h3>Nearby directory repeaters · {records.length}</h3><input aria-label="Filter radio repeaters" placeholder="Call sign, city or mode" value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="help">HearHam community directory · 24-hour shared geographic cache. Source record dates are not supplied. Published input frequency is derived only when the directory supplies an offset. Empty results are a directory coverage gap, not proof that there are no repeaters.</p>{!nearby.length&&<p>No matching repeater records loaded.</p>}<div className="radio-directory">{nearby.map(p=><article key={p.id}><div><strong>{p.name}</strong><small>{p.radio.city} · {p.radio.mode||'Mode unknown'}{home?' · '+(distanceKm(home,[p.lat,p.lng])*.621371).toFixed(1)+' miles from location':''}</small><small>Input {p.radio.transmitMHz?p.radio.transmitMHz+' MHz (derived)':'not supplied'} · Encode {p.radio.encode||'unknown'} / decode {p.radio.decode||'unknown'}</small><small>Source operational flag: {p.radio.operational} · reception unverified{p.stale?' · stale cache':''}</small><small>Retrieved {reportDate(p.retrievedAt,true)} · source record date unavailable</small>{p.radio.restriction&&<p>{p.radio.restriction}</p>}</div><div className="radio-actions"><button onClick={()=>inspect(p.id)}><MapPin size={16}/>Map</button><button disabled={plan.length>=200} onClick={()=>edit(channelFromRepeater(p))}><Bookmark size={16}/>Keep</button></div></article>)}</div></section>
 <section className="reference-box"><h3>Local operators & additional directories</h3><a href={radioDirectory} target="_blank" rel="noreferrer">HearHam directory & record corrections</a><a href="https://austinhams.org/repeaters/" target="_blank" rel="noreferrer">Austin Amateur Radio Club repeaters</a><a href="https://sites.utexas.edu/n5xu/nets/" target="_blank" rel="noreferrer">UT Amateur Radio Club local nets</a><a href="https://www.repeaterbook.com/" target="_blank" rel="noreferrer">RepeaterBook directory</a><p className="help">Confirm access instructions with the operator before transmitting. Automatic RepeaterBook and Open Repeater collection is not connected; those APIs require approved access or a key. Saved entries are research notes, not a radio programming file.</p></section></div>;
}
