"use client";
import {useState} from 'react';
import {Plus,Trash2,MapPin} from 'lucide-react';
import {newRequirement,requirementFlags,type StudyQuestion,type InformationRequirement} from '../lib/collection';
import type {NamedArea} from '../lib/nais';
type Props={question:StudyQuestion,change:(requirements:InformationRequirement[])=>void,areas:NamedArea[],openArea:(id:string)=>void,activeId:string|null,activate:(id:string|null)=>void};
export default function RequirementsPanel({question:q,change,areas,openArea,activeId,activate}:Props){
 const [deleteId,setDeleteId]=useState<string|null>(null);
 function edit(id:string,fields:Partial<InformationRequirement>){change(q.requirements.map(r=>r.id===id?{...r,...fields}:r));}
 const named=areas.filter(a=>q.naiIds.includes(a.id));
 return <section className="requirements-panel"><div className="row"><h3>Specific information requirements <span className="count">{q.requirements.length} / 50</span></h3><button disabled={q.requirements.length>=50} onClick={()=>{const r=newRequirement();change([...q.requirements,r]);activate(r.id);}}><Plus size={15}/>Add requirement</button></div><p className="help">Break the question into checks you can carry out. A deadline is the latest useful date for that check; a review date is when to revisit its result. These dates do not schedule collection automatically.</p>
 {!q.requirements.length&&<p className="help">For a flood-access question, start with a check for an official closure at a named crossing.</p>}
 {q.requirements.map(r=>{const flags=requirementFlags(r);return <details key={r.id} className="requirement-card" open={activeId===r.id}><summary onClick={e=>{e.preventDefault();activate(activeId===r.id?null:r.id);}}><strong>{r.task||'Untitled requirement'}</strong><span>{r.status} · Evidence links: {r.evidenceIds.length}</span>{flags.overdue&&<b className="collection-warning">Answer overdue · {r.neededBy}</b>}{flags.reviewDue&&<b className="collection-warning">Review due · {r.reviewOn}</b>}{flags.gap&&<b className="collection-warning">Collection gap</b>}</summary>
 <label>Information to collect<textarea maxLength={500} value={r.task} onChange={e=>edit(r.id,{task:e.target.value})} placeholder="What observable fact would help answer the question?"/></label><label>Indicator to check<textarea maxLength={1000} value={r.indicator} onChange={e=>edit(r.id,{indicator:e.target.value})} placeholder="What would you expect to see if the condition is developing?"/></label><div className="collection-fields"><label>Requirement status<select value={r.status} onChange={e=>edit(r.id,{status:e.target.value as InformationRequirement['status']})}>{['Open','In progress','Answered','Blocked','Retired'].map(x=><option key={x}>{x}</option>)}</select></label><label>Collection method<select value={r.method} onChange={e=>edit(r.id,{method:e.target.value as InformationRequirement['method']})}>{['Public source','Field observation','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label>Specific location<input maxLength={300} value={r.location} onChange={e=>edit(r.id,{location:e.target.value})} placeholder="Describe where to check"/></label><label>Responsible role or collector<input maxLength={300} value={r.responsibility} onChange={e=>edit(r.id,{responsibility:e.target.value})} placeholder="e.g. Study owner"/></label><label>Latest useful date<input type="date" value={r.neededBy} onChange={e=>edit(r.id,{neededBy:e.target.value})}/></label><label>Requirement review date<input type="date" value={r.reviewOn} onChange={e=>edit(r.id,{reviewOn:e.target.value})}/></label></div><label>Planned source or collection steps<textarea maxLength={1000} value={r.source} onChange={e=>edit(r.id,{source:e.target.value})} placeholder="Source name or URL, what to check, and whether access is available"/></label>
 <h4>Named locations for this check</h4><div className="nai-question-links">{named.map(a=><label key={a.id}><input type="checkbox" checked={r.naiIds.includes(a.id)} onChange={e=>edit(r.id,{naiIds:e.target.checked?[...r.naiIds,a.id]:r.naiIds.filter(id=>id!==a.id)})}/><span>{a.name}</span></label>)}</div>{!named.length&&<p className="help">Link named areas to the parent question above to use them here, or describe a specific location.</p>}{named.filter(a=>r.naiIds.includes(a.id)).map(a=><button key={a.id} onClick={()=>openArea(a.id)}><MapPin size={14}/>View {a.name}</button>)}
 <label>Result and remaining gaps<textarea maxLength={2000} value={r.result} onChange={e=>edit(r.id,{result:e.target.value})} placeholder="Record what was found, when it applied, and what remains unresolved."/></label><h4>Evidence for this check</h4><p className="help">Choose from the saved evidence below. Evidence is shared with the parent question; answering a requirement does not automatically answer the question.</p><div className="nai-question-links">{q.evidence.map(e=><label key={e.id}><input type="checkbox" checked={r.evidenceIds.includes(e.id)} onChange={event=>edit(r.id,{evidenceIds:event.target.checked?[...r.evidenceIds,e.id]:r.evidenceIds.filter(id=>id!==e.id)})}/><span>{e.title} · {e.stance}</span></label>)}</div>{!q.evidence.length&&<p className="help">Attach a note, loaded record, or source link to the Evidence section first.</p>}{flags.gap&&<p className="collection-warning">{r.status==='Blocked'?'Resolve the access or information problem recorded above. ':''}{!r.source.trim()?'Specify an available source or collection method. ':''}{!r.location.trim()&&!r.naiIds.length?'Specify a location or named area. ':''}{!r.neededBy?'Set the latest useful date, or retire a check that is no longer needed.':''}</p>}
 <div className="question-delete">{deleteId===r.id?<><p>Delete this requirement? The parent question, named areas, and saved evidence will remain.</p><button onClick={()=>{change(q.requirements.filter(x=>x.id!==r.id));activate(null);setDeleteId(null);}}>Confirm delete requirement</button><button onClick={()=>setDeleteId(null)}>Keep requirement</button></>:<button onClick={()=>setDeleteId(r.id)}><Trash2 size={15}/>Delete requirement</button>}</div></details>;})}</section>;
}
