"use client";
import {useEffect,useMemo,useState} from 'react';
import {CalendarCheck,ClipboardList,RefreshCw,History,AlertTriangle} from 'lucide-react';
import type {Portfolio} from '../lib/locations';
import {localDate} from '../lib/collection';
import {addDays,reviewQueue,recordReview,type CurrentRecord,type ReviewItem} from '../lib/reviews';
import type {ReviewTarget} from '../lib/review-schema';
type Health={kind:string;name:string;status:string;error:boolean;partial:boolean;stale:boolean;busy:boolean};
type Props={portfolio:Portfolio;records:CurrentRecord[];health:Health[];change:(p:Portfolio)=>void;open:(target:ReviewTarget)=>void;refresh:(kind:string)=>void};
const filters=['Needs attention','Due','Source changes','Evidence','Gaps & questions','Scheduled','All items'] as const;
export default function ReviewsPanel(p:Props){
 const [whole,setWhole]=useState(false),[filter,setFilter]=useState<typeof filters[number]>('Needs attention'),[search,setSearch]=useState(''),[selected,setSelected]=useState(''),[note,setNote]=useState(''),[next,setNext]=useState(''),[message,setMessage]=useState(''),[today,setToday]=useState(localDate());
 useEffect(()=>{const tick=window.setInterval(()=>setToday(localDate()),60000);return()=>window.clearInterval(tick);},[]);
 const queue=useMemo(()=>{const stale=new Set(p.health.filter(h=>h.error||h.stale).map(h=>h.name));return reviewQueue(p.portfolio,p.records.map(r=>({...r,stale:r.stale||stale.has(r.source)})),whole,today);},[p.portfolio,p.records,p.health,whole,today]);
 const shown=queue.filter(i=>{if(search&&!`${i.title} ${i.locationName} ${i.target.type}`.toLowerCase().includes(search.toLowerCase()))return false;const kinds=i.reasons.map(r=>r.kind);return filter==='All items'||filter==='Needs attention'&&kinds.some(k=>k!=='Upcoming')||filter==='Due'&&kinds.includes('Due')||filter==='Source changes'&&kinds.includes('Source changed')||filter==='Evidence'&&kinds.some(k=>['Stale evidence','Undated evidence','Stale source'].includes(k))||filter==='Gaps & questions'&&kinds.some(k=>k==='Gap'||k==='Unresolved')||filter==='Scheduled'&&!!i.due;});
 const item=queue.find(i=>i.key===selected),health=p.health.filter(h=>h.error||h.partial||h.stale);
 function choose(i:ReviewItem){setSelected(i.key);setNext(addDays(today,p.portfolio.reviews.settings.intervalDays));setNote('');setMessage('');}
 function save(){if(!item)return;try{p.change(recordReview(p.portfolio,item,note,next));setNote('');setMessage('Review recorded. Save study to keep it. Existing assessments and evidence remain unchanged.');}catch(e){setMessage(e instanceof Error?e.message:'Could not record review.');}}
 function exportHistory(){const url=URL.createObjectURL(new Blob([JSON.stringify(p.portfolio.reviews,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`study-review-history-${today}.json`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const counts=[['Due',queue.filter(i=>i.reasons.some(r=>r.kind==='Due')).length],['Source changes',queue.filter(i=>i.reasons.some(r=>r.kind==='Source changed')).length],['Evidence',queue.filter(i=>i.reasons.some(r=>['Stale evidence','Undated evidence','Stale source'].includes(r.kind))).length],['Unresolved',queue.filter(i=>i.reasons.some(r=>r.kind==='Unresolved'||r.kind==='Gap')).length]] as const;
 return <section className="reviews-content"><div className="row"><div><span className="eyebrow">ONGOING STUDY REVIEW</span><h2>Review queue</h2></div><CalendarCheck size={24}/></div><p className="help">Review reminders appear while this app is open. Source comparisons use loaded records for the active location; missing matches remain unknown. A recorded review does not verify a source or route.</p>
 <div className="review-counts">{counts.map(([label,count])=><div key={label}><strong>{count}</strong><span>{label}</span></div>)}</div>
 <div className="review-controls"><label>Locations<select value={whole?'whole':'active'} onChange={e=>{setWhole(e.target.value==='whole');setSelected('');}}><option value="active">Active location & related routes</option><option value="whole">Whole study</option></select></label><label>Show<select value={filter} onChange={e=>setFilter(e.target.value as typeof filter)}>{filters.map(f=><option key={f}>{f}</option>)}</select></label><label>Search<input placeholder="Title, location or item type" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>
 <details className="review-settings"><summary>Review intervals & source health</summary><div className="review-controls">{([['intervalDays','Default next review (days)',1,3650],['evidenceAgeDays','Evidence age reminder (days)',1,3650],['upcomingDays','Upcoming window (days)',0,90]] as const).map(([key,label,min,max])=><label key={key}>{label}<input type="number" min={min} max={max} value={p.portfolio.reviews.settings[key]} onChange={e=>{const v=Number(e.target.value);if(Number.isInteger(v)&&v>=min&&v<=max)p.change({...p.portfolio,reviews:{...p.portfolio.reviews,settings:{...p.portfolio.reviews.settings,[key]:v}}});}}/></label>)}</div><p className="help">Age thresholds prompt a check; they do not invalidate historical evidence. Source dates remain unchanged when you record a review. Upcoming reminders include the scheduled day. Use Save study to retain these preferences.</p>{health.length?health.map(h=><article className="review-health" key={h.kind}><div><strong><AlertTriangle size={16}/>{h.name}</strong><p>{h.status}</p><small>{h.error?'Refresh failed':h.stale?'Stale coverage':'Incomplete coverage'} · active location only</small></div><button disabled={h.busy} onClick={()=>p.refresh(h.kind)}><RefreshCw size={15}/>{h.busy?'Loading…':'Refresh'}</button></article>):<p className="help">No loaded map-source failures or stale/incomplete coverage reported. Unloaded sources and other dashboards are not an all-clear.</p>}</details>
 <div className="review-layout"><div className="review-list" role="region" aria-label="Review items"><div className="row"><h3>{shown.length} items</h3><span className="help">As of {today}</span></div>{shown.length?shown.map(i=><button className={`review-list-item ${i.key===selected?'active':''}`} key={i.key} onClick={()=>choose(i)}><span className="eyebrow">{i.locationName} · {i.target.type}</span><strong>{i.title}</strong><span className="review-tags">{[...new Set(i.reasons.map(r=>r.kind))].slice(0,4).map(r=><span key={r}>{r}</span>)}{!i.reasons.length&&<span>Scheduled</span>}</span><small>{i.due?`Next review ${i.due}`:'No review scheduled'}{i.lastReview?` · checked ${new Date(i.lastReview.recordedAt).toLocaleDateString()}`:''}</small></button>):<div className="empty"><ClipboardList size={28}/><b>No items in this view</b><p>{queue.length?'Choose another filter to see scheduled reviews and other items.':'Add collection questions, scenarios, service plans or routes to begin tracking reviews.'}</p></div>}</div>
 <div className="review-detail">{item?<><div className="row"><span className="eyebrow">{item.locationName} · {item.target.type}</span><button onClick={()=>p.open(item.target)}>Open item</button></div><h3>{item.title}</h3>{item.reasons.map((r,index)=><article className="review-reason" key={index}><strong>{r.kind}</strong><p>{r.text}</p>{r.before!==undefined&&<div className="review-diff"><div><b>Captured evidence</b><pre>{r.before}</pre></div><div><b>Loaded record</b><pre>{r.after}</pre></div></div>}</article>)}{!item.reasons.length&&<p className="help">No current reminder for this item. Next review: {item.due}.</p>}{item.comparable>0&&<p className="help">{item.sourceCheck?`${item.matched} of ${item.comparable} captured records matched by exact ID and source in the current loaded data.`:'Activate this location to compare its captured evidence with loaded source records.'} Unmatched records need an original-source check. Only captured fields are compared. External links are not fetched by this queue.</p>}{item.lastReview&&<div className="review-last"><strong>Last review · {new Date(item.lastReview.recordedAt).toLocaleString()}</strong><p>{item.lastReview.note}</p></div>}
 <form onSubmit={e=>{e.preventDefault();save();}}><h4>Record your review</h4><label>What did you check? What remains uncertain?<textarea required maxLength={1000} rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Record the sources checked, outcome and follow-up work."/></label><label>Next review date<input required type="date" min={addDays(today,1)} value={next} onInput={e=>setNext(e.currentTarget.value)} onChange={e=>setNext(e.target.value)}/></label><button className="primary" disabled={!note.trim()||!next||p.portfolio.reviews.history.length>=300}><CalendarCheck size={16}/>Record review</button><p className="help">This sets the next review date and acknowledges the source differences shown here. Unresolved questions, evidence-age warnings and planning gaps remain until you update the underlying item.</p></form><p role="status" aria-live="polite">{message}</p></>:<div className="empty"><CalendarCheck size={28}/><b>Select an item to review</b><p>Inspect its reminders and source differences, open the original plan, or record your check with a next review date.</p></div>}</div></div>
 <details className="review-history"><summary><History size={17}/>Review history · {p.portfolio.reviews.history.length} / 300</summary><button onClick={exportHistory}>Download review history</button><p className="help">The full study export also includes schedules and review history. Removed items keep their historical review entries.</p>{[...p.portfolio.reviews.history].reverse().filter(e=>whole||e.target.locationId===p.portfolio.activeLocationId||e.target.type==='Route').map(e=><article key={e.id}><strong>{e.title} · {e.target.type}</strong><small>{new Date(e.recordedAt).toLocaleString()} · next review {e.nextReview}</small><p>{e.note}</p></article>)}</details></section>;
}
