"use client";
import RouteCorridor from './route-corridor';
import AutomaticRoutes from './automatic-routes';
import type {LocationEndpoint} from '../lib/location-core';
import type {CorridorRecord,CorridorReport} from '../lib/route-corridor';
import {useMemo,useState} from 'react';
import {Plus,Route,X,MapPin} from 'lucide-react';
import {routeFindings,routeMiles,sharedRouteMarks,type StudyRoute,type TerrainRecord,type RouteMark} from '../lib/routes';
import {reportDate} from '../lib/report-dates';
import {containsPolygon,type Point} from '../lib/geo';
type Props={endpoints:LocationEndpoint[];generated:(r:StudyRoute)=>void;corridorRows:CorridorRecord[];corridorLoaded:boolean;collect:(id:string,report:CorridorReport,rows:CorridorRecord[])=>void;inspectRecord:(record:CorridorRecord)=>void;routes:StudyRoute[],selectedId:string|null,select:(id:string|null)=>void,change:(r:StudyRoute)=>void,remove:(id:string)=>void,draw:(id?:string,fromHome?:boolean)=>void,home:Point|null,records:TerrainRecord[],ready:boolean,area:Point[],inspect:(id:string)=>void,mark:(id:string)=>void};
export default function RoutesPanel(p:Props){
 const route=p.routes.find(r=>r.id===p.selectedId),[deleteId,setDeleteId]=useState<string|null>(null);
 const findings=useMemo(()=>route?routeFindings(route,p.records):null,[route,p.records]);
 const others=route?p.routes.filter(r=>r.id!==route.id):[],sharedCrossings=findings?.crossings.filter(c=>others.some(r=>routeFindings(r,[c]).crossings.length))||[];
 const within=route&&p.area.length>=3&&route.points.slice(1).every((b,i)=>containsPolygon(p.area,[route.points[i],b]));
 function edit(fields:Partial<StudyRoute>){if(route)p.change({...route,...fields});}
 return <div className="panel-content routes-panel"><div className="row"><h2>Routes & alternatives</h2><span className="count">{p.routes.length}</span></div><p className="help">Generate road routes or trace custom waypoints. Collect information along each trip and compare primary, alternate, contingency and emergency options.</p><details className="route-generator"><summary>Generate route from addresses or saved locations</summary><AutomaticRoutes endpoints={p.endpoints} add={p.generated} slots={100-p.routes.length} limit={p.routes.length>=100}/></details><div className="data-actions"><button className="primary" disabled={p.routes.length>=100||!p.home} onClick={()=>p.draw(undefined,true)}><Plus size={15}/>Draw from active location</button><button disabled={p.routes.length>=100} onClick={()=>p.draw()}>Draw route</button></div>
 <div className="route-list">{p.routes.map(r=><button className={r.id===p.selectedId?'active':''} key={r.id} onClick={()=>p.select(r.id)}><Route size={17}/><span><strong>{r.name}</strong><small>{r.role} · {r.destination||'Destination not set'} · {(r.routing?r.routing.distanceMetres/1609.344:routeMiles(r.points)).toFixed(2)} mi {r.routing?'road route':'traced'}</small></span></button>)}</div>
 {route&&findings&&<>{route.routing&&<article className="route-provenance"><strong>{route.routing.provider} · {route.routing.profile}</strong><p>{(route.routing.distanceMetres/1609.344).toFixed(1)} miles · about {Math.round(route.routing.durationSeconds/60)} minutes</p><p className="help">Generated {reportDate(route.routing.generatedAt,true)}. Road-network estimate; live traffic, closures and evacuation orders are not included.</p><p className="help">Road snap: start {Math.round(route.routing.snapOriginMetres)} m · end {Math.round(route.routing.snapDestinationMetres)} m. Verify access from each pin.</p><a href={route.routing.sourceUrl} target="_blank" rel="noreferrer">Routing source</a> · <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a> · <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noreferrer">Fix the map</a></article>}<label>Route name<input maxLength={160} value={route.name} onChange={e=>edit({name:e.target.value})}/></label><label>Destination<input maxLength={160} placeholder="e.g. Grocery store or meeting location" value={route.destination} onChange={e=>edit({destination:e.target.value})}/></label><label>Role<select value={route.role} onChange={e=>edit({role:e.target.value as StudyRoute['role']})}><option>Primary</option><option>Alternate</option><option>Contingency</option><option>Emergency</option></select></label><p className="help">Solid teal: primary. Purple dash patterns: alternate, contingency and emergency. Orange segments touch a loaded floodplain.</p><button onClick={()=>p.draw(route.id)}>Redraw route</button>
 <RouteCorridor key={route.id+JSON.stringify(route.points)} route={route} loaded={p.corridorLoaded} finish={(report,rows)=>p.collect(route.id,report,rows)}/><h3>Resources & incidents along corridor</h3><p className="help">{p.corridorRows.filter(r=>!r.geometry&&!r.closure&&!r.crossing).length} point records. Showing up to 100; click a record for its source and dates. Nearby facilities need access and availability checks.</p>{p.corridorRows.filter(r=>!r.geometry&&!r.closure&&!r.crossing).slice(0,100).map(r=><button className="route-finding" key={r.id} onClick={()=>p.inspectRecord(r as CorridorRecord)}>{r.name}<small>{(r as CorridorRecord).category} · {r.source} · retrieved {reportDate(r.retrievedAt,true)}</small></button>)}<h3>Mapped terrain along route</h3><p className="help">{p.corridorLoaded?'Corridor findings are loaded for this route. Check each source’s section counts above for stale, incomplete or unavailable coverage.':!within?'AOI records cover only part of this trip. Use full route corridor collection above.':!p.ready?'AOI terrain collection is pending, stale, or incomplete.':'Showing available AOI terrain records. Collect the corridor for full-trip coverage.'}</p>
 <p className="help">{findings.floods.filter(f=>f.source==='FEMA NFHL').length} FEMA polygons · {findings.floods.filter(f=>f.source==='FloodPro Austin model').length} Austin model polygons. No intersection in loaded data does not establish that a road is safe.</p>
 {findings.floods.map(f=><button className="route-finding" key={f.id} onClick={()=>p.inspect(f.id)}>{f.name}<small>{f.flood?.model} · view source dates</small></button>)}
 <h3>Nearby low-water crossings</h3><p className="help">{findings.crossings.length} inventory locations within 100 m of the traced line. Proximity does not confirm that your route uses the crossing; current closure status is unavailable.</p>{findings.crossings.map(c=><button className="route-finding" key={c.id} onClick={()=>p.inspect(c.id)}>{c.name}{sharedCrossings.some(x=>x.id===c.id)&&<small>Also near another saved route</small>}</button>)}
 <h3>Reported crossing statuses near route</h3><p className="help">Loaded ATXFloods locations within 100 m. Proximity does not confirm use of a crossing. Records cover only the collected sections; no match does not clear the route. Verify all route segments and source status before travel.</p>{findings.closures.map(c=><button className="route-finding" key={c.id} onClick={()=>p.inspect(c.id)}>{c.closure?.state} · {c.name}<small>Record updated {reportDate(c.closure?.recordUpdated||undefined,true)} · retrieved {reportDate(c.retrievedAt,true)}{c.stale?" · stale snapshot":""}</small></button>)}
 <h3>Exits, bridges & bottlenecks</h3><p className="help">Place markers on the map. Use the same type and name on another route to identify a shared dependency.</p><button disabled={route.marks.length>=50} onClick={()=>p.mark(route.id)}><MapPin size={15}/>Mark a route feature</button>{route.marks.map(m=><div className="route-mark" key={m.id}><label>Feature name<input maxLength={160} value={m.name} onChange={e=>edit({marks:route.marks.map(x=>x.id===m.id?{...x,name:e.target.value}:x)})}/></label><label>Type<select value={m.kind} onChange={e=>edit({marks:route.marks.map(x=>x.id===m.id?{...x,kind:e.target.value as RouteMark['kind']}:x)})}><option>Exit</option><option>Bridge</option><option>Bottleneck</option></select></label>{sharedRouteMarks(route,p.routes).some(x=>x.id===m.id)&&<p className="notice">Shared with another saved route</p>}<button onClick={()=>edit({marks:route.marks.filter(x=>x.id!==m.id)})}><X size={14}/>Remove feature</button></div>)}
 <label>Route notes<textarea maxLength={20000} value={route.notes} onChange={e=>edit({notes:e.target.value})} placeholder="Road names, access restrictions, conditions to verify, and alternatives if an exit or bridge is unavailable."/></label><a className="source-link" href="https://www.atxfloods.com/" target="_blank" rel="noreferrer">Check current road closures</a><p className="help">Generated distances use the routing provider; traced distances follow your waypoints. Verify road access and current conditions before travel.</p>{deleteId===route.id?<div className="data-actions"><button onClick={()=>{p.remove(route.id);setDeleteId(null);}}>Delete this route</button><button onClick={()=>setDeleteId(null)}>Keep route</button></div>:<button onClick={()=>setDeleteId(route.id)}>Remove route</button>}</>}
 {!p.routes.length&&<p className="help">Start with your usual neighborhood exit and a route to groceries or medical care. Add an alternate to compare dependencies.</p>}</div>;
}
