"use client";
import {useState} from 'react';
import {Plus,ClipboardList,History,Route,ShieldAlert} from 'lucide-react';
import {newScenario,newIndicator,scenarioTemplates,scenarioFlags,scenarioMissingLinks,archiveScenario,removeScenarioEvidence,evidenceForScenario,type Scenario,type ScenarioOptions} from '../lib/scenarios';
import {evidenceSnapshot,localDate,type EvidenceRecord,type StudyQuestion,type Evidence} from '../lib/collection';
import type {ServicePlan} from '../lib/dependencies';
type Props={initialSelectedId?:string;scenarios:Scenario[],change:(v:Scenario[])=>void,options:ScenarioOptions,records:EvidenceRecord[],questions:StudyQuestion[],services:ServicePlan[],openQuestion:(id:string)=>void,openArea:(id:string)=>void,openService:(id:string)=>void,openRoute:(id:string)=>void,createQuestion:(scenarioId:string,text:string)=>void};
export default function ScenariosPanel(p:Props){
 const [selected,setSelected]=useState(p.initialSelectedId||''),[filter,setFilter]=useState('all'),[recordId,setRecordId]=useState(''),[evidenceId,setEvidenceId]=useState(''),[message,setMessage]=useState(''),[exerciseDate,setExerciseDate]=useState(localDate()),[outcome,setOutcome]=useState(''),[gaps,setGaps]=useState('');
 const flags=(s:Scenario)=>({...scenarioFlags(s,localDate()),gaps:scenarioFlags(s,localDate()).gaps||p.questions.some(q=>s.questionIds.includes(q.id)&&q.status!=='Answered')});
 const shown=p.scenarios.filter(s=>{if(filter==='all')return true;if(filter==='review')return flags(s).reviewDue;if(filter==='gaps')return flags(s).gaps||scenarioMissingLinks(s,p.options).length>0;return s.status==='Retired';}),s=p.scenarios.find(s=>s.id===selected)||shown[0];
 function put(next:Scenario){p.change(p.scenarios.map(x=>x.id===next.id?next:x));setMessage('');}
 const patch=(value:Partial<Scenario>)=>s&&put({...s,...value});
 function add(template?:typeof scenarioTemplates[number]){const n=newScenario(template);p.change([...p.scenarios,n]);setSelected(n.id);setFilter('all');setMessage('');}
 const records=[...new Map(p.records.map(r=>[r.id,r])).values()],questionEvidence=p.questions.flatMap(q=>q.evidence.map(e=>({key:q.id+'/'+e.id,title:q.question+' · '+e.title,e})));
 function field(key:'title'|'hazard'|'scope'|'status'|'description'|'exposure'|'likelihood'|'impact'|'assessmentReason'|'confidence'|'confidenceReason'|'assumptions'|'assessedOn'|'reviewOn',label:string,options?:string[],type='text',max=4000){if(!s)return null;return <label>{label}{options?<select value={s[key]} onChange={e=>patch({[key]:e.target.value})}>{options.map(v=><option key={v}>{v}</option>)}</select>:type==='textarea'?<textarea rows={3} maxLength={max} value={s[key]} onChange={e=>patch({[key]:e.target.value})}/>:<input type={type} maxLength={max} value={s[key]} onInput={type==='date'?e=>patch({[key]:e.currentTarget.value}):undefined} onChange={e=>patch({[key]:e.target.value})}/>}</label>;}
 function links(key:'questionIds'|'naiIds'|'servicePlanIds'|'routeIds',label:string,items:{id:string;label:string}[],open:(id:string)=>void){if(!s)return null;return <div className="scenario-links"><h4>{label}</h4>{items.length?items.map(x=><div key={x.id}><label><input type="checkbox" checked={s[key].includes(x.id)} onChange={e=>patch({[key]:e.target.checked?[...s[key],x.id]:s[key].filter(id=>id!==x.id)})}/>{x.label}</label><button onClick={()=>open(x.id)}>Open</button></div>):<p className="help">None saved at this location yet.</p>}{s[key].filter(id=>!items.some(x=>x.id===id)).map(id=><p className="notice" key={id}>Linked item unavailable · {id}<button onClick={()=>patch({[key]:s[key].filter(x=>x!==id)})}>Remove missing link</button></p>)}</div>;}
 return <section className="scenarios-content"><div className="row"><div><span className="eyebrow">SCENARIOS / DECISIONS / ALTERNATIVES</span><h2>Prepare for disruptions</h2></div><button disabled={p.scenarios.length>=50} onClick={()=>add()}><Plus size={16}/>New scenario</button></div><p className="help">A scenario is a planning hypothesis. Source records do not automatically establish a disruption, activate a trigger or change your assessment. Templates start with unknown likelihood and impact.</p>
 <details className="scenario-starters"><summary>Start from a planning prompt</summary><div>{scenarioTemplates.map(t=><button key={t.title} disabled={p.scenarios.length>=50} onClick={()=>add(t)}>{t.title}</button>)}</div></details>
 <div className="scenario-workspace"><aside className="scenario-list"><label>Show scenarios<select value={filter} onChange={e=>{setFilter(e.target.value);setSelected('');}}><option value="all">All scenarios</option><option value="review">Review due</option><option value="gaps">Information gaps</option><option value="retired">Retired</option></select></label>{shown.map(x=><button className={s?.id===x.id?'active':''} key={x.id} onClick={()=>{setSelected(x.id);setMessage('');}}><strong>{x.title}</strong><small>{x.status} · {x.hazard}</small><small>{flags(x).reviewDue?'Review due · ':''}{flags(x).gaps||scenarioMissingLinks(x,p.options).length?'Information gaps':'Review documented'}</small></button>)}{!shown.length&&<p className="help">No scenarios match. Create one or change the filter.</p>}</aside>
 {s?<div className="scenario-editor" key={s.id}><div className="row"><h3>{s.title}</h3><span className="badge">{s.status}</span></div>{message&&<p className="notice" role="status">{message}</p>}{(flags(s).gaps||scenarioMissingLinks(s,p.options).length>0)&&<p className="notice">This plan has unresolved information. Check evidence, indicator support, actions, ratings, dates and linked resources before relying on it.</p>}
 <div className="scenario-fields">{field('title','Scenario name',undefined,'text',160)}{field('hazard','Hazard / disruption',undefined,'text',100)}{field('scope','Study scope',['AOR','AOI','Route','Other'])}{field('status','Planning status',['Draft','Reviewed','Retired'])}</div>{field('description','What could happen?',undefined,'textarea')}{field('exposure','Exposed people, places and services',undefined,'textarea')}
 <details open className="scenario-section"><summary><ShieldAlert size={17}/>Assessment & assumptions</summary><div className="scenario-fields">{field('likelihood','Likelihood',['Unknown','Unlikely','Possible','Likely'])}{field('impact','Impact',['Unknown','Minor','Moderate','Severe'])}{field('confidence','Analytic confidence',['Unassessed','Low','Moderate','High'])}{field('assessedOn','Assessed on',undefined,'date')}{field('reviewOn','Review on',undefined,'date')}</div>{field('assessmentReason','Likelihood / impact rationale',undefined,'textarea')}{field('confidenceReason','Why this confidence?',undefined,'textarea',2000)}{field('assumptions','Assumptions & unresolved questions',undefined,'textarea')}<p className="help">Reviewed status requires dates and rationale. Unknown inputs stay unknown; this is not a neighborhood safety score.</p><button disabled={s.history.length>=20} onClick={()=>{try{put(archiveScenario(s,[...p.options.questions.filter(q=>s.questionIds.includes(q.id)).map(q=>'Question: '+q.question),...p.options.areas.filter(a=>s.naiIds.includes(a.id)).map(a=>'Area: '+a.name),...p.services.filter(a=>s.servicePlanIds.includes(a.id)).map(a=>'Service: '+a.name+'; backups: '+a.alternatives.map(b=>b.name+' ('+b.status+')').join(', ')),...p.options.routes.filter(r=>s.routeIds.includes(r.id)).map(r=>'Route: '+r.role+' · '+r.name)]));setMessage('Assessment version recorded. Earlier evidence and rationale are preserved.');}catch(e){setMessage(e instanceof Error?e.message:'Version could not be recorded');}}}><History size={16}/>Record assessment version</button></details>
 <details open className="scenario-section"><summary><ClipboardList size={17}/>Evidence & warning indicators</summary><div className="scenario-evidence-add"><label>Saved observation or loaded source<select value={recordId} onChange={e=>setRecordId(e.target.value)}><option value="">Choose a record</option>{records.map(r=><option key={r.id} value={r.id}>{r.name} · {r.source}</option>)}</select></label><button disabled={!records.some(r=>r.id===recordId)||s.evidence.length>=30} onClick={()=>{const r=records.find(r=>r.id===recordId)!;patch({evidence:[...s.evidence,evidenceSnapshot(r,r.source==='Your observation'?'Note':'Source')]});}}>Capture evidence</button><label>Evidence from a study question<select value={evidenceId} onChange={e=>setEvidenceId(e.target.value)}><option value="">Choose question evidence</option>{questionEvidence.map(e=><option key={e.key} value={e.key}>{e.title}</option>)}</select></label><button disabled={!questionEvidence.some(e=>e.key===evidenceId)||s.evidence.length>=30} onClick={()=>put(evidenceForScenario(s,questionEvidence.find(e=>e.key===evidenceId)!.e))}>Copy evidence snapshot</button><button disabled={s.evidence.length>=30} onClick={()=>patch({evidence:[...s.evidence,{...evidenceSnapshot({id:'manual',name:'Source link',source:'User-supplied source'},'Source'),kind:'Link'}]})}>Add source link</button></div>
 {s.evidence.map(e=><article className="scenario-card" key={e.id}><strong>{e.title}</strong><p className="help">{e.source} · source date {e.date||'unknown'} · captured {new Date(e.capturedAt).toLocaleString()}</p>{e.kind==='Link'&&<div className="scenario-fields">{(['title','source','url','date'] as const).map(k=><label key={k}>{k==='date'?'Source date':k}<input maxLength={k==='title'?300:k==='source'?200:k==='date'?100:2000} value={e[k]} onChange={ev=>patch({evidence:s.evidence.map(x=>x.id===e.id?{...x,[k]:ev.target.value}:x)})}/></label>)}</div>}<label>Relation to this scenario<select value={e.stance} onChange={ev=>patch({evidence:s.evidence.map(x=>x.id===e.id?{...x,stance:ev.target.value as Evidence['stance']}:x)})}>{['Supports','Conflicts','Context'].map(v=><option key={v}>{v}</option>)}</select></label>{e.detail&&<p className="help">{e.detail}</p>}{e.url&&/^https?:\/\//i.test(e.url)&&<a href={e.url} target="_blank" rel="noreferrer">Original source</a>}<button onClick={()=>put(removeScenarioEvidence(s,e.id))}>Remove evidence</button></article>)}
 <button disabled={s.indicators.length>=20} onClick={()=>patch({indicators:[...s.indicators,newIndicator()]})}>Add warning indicator / trigger</button>{s.indicators.map(i=><article className="scenario-card" key={i.id}><label>Indicator name<input maxLength={300} value={i.name} onChange={e=>patch({indicators:s.indicators.map(x=>x.id===i.id?{...x,name:e.target.value}:x)})}/></label><label>Condition / decision trigger<textarea rows={2} maxLength={2000} value={i.condition} onChange={e=>patch({indicators:s.indicators.map(x=>x.id===i.id?{...x,condition:e.target.value}:x)})}/></label><div className="scenario-fields"><label>Trigger basis<select value={i.basis} onChange={e=>patch({indicators:s.indicators.map(x=>x.id===i.id?{...x,basis:e.target.value as typeof i.basis}:x)})}><option>User plan</option><option>Official instruction</option></select></label>{(['source','sourceUrl','sourceDate'] as const).map(k=><label key={k}>{k==='source'?'Instruction / source reference':k==='sourceUrl'?'Official source URL':'Source date'}<input onInput={k==='sourceDate'?e=>patch({indicators:s.indicators.map(x=>x.id===i.id?{...x,[k]:e.currentTarget.value}:x)}):undefined} type={k==='sourceDate'?'date':'text'} maxLength={k==='source'?1000:2000} value={i[k]} onChange={e=>patch({indicators:s.indicators.map(x=>x.id===i.id?{...x,[k]:e.target.value}:x)})}/></label>)}</div><p className="help">Official instructions require a source, URL and date. A user-defined threshold is a planning choice. Select supporting or conflicting evidence below.</p>{s.evidence.map(e=><label className="scenario-check" key={e.id}><input type="checkbox" checked={i.evidenceIds.includes(e.id)} onChange={v=>patch({indicators:s.indicators.map(x=>x.id===i.id?{...x,evidenceIds:v.target.checked?[...x.evidenceIds,e.id]:x.evidenceIds.filter(id=>id!==e.id)}:x)})}/>{e.title} · {e.stance}</label>)}<button onClick={()=>patch({indicators:s.indicators.filter(x=>x.id!==i.id)})}>Remove indicator</button></article>)}</details>
 <details open className="scenario-section"><summary><Route size={17}/>Actions, resources & routes</summary><button disabled={s.actions.length>=20} onClick={()=>patch({actions:[...s.actions,{id:crypto.randomUUID(),action:'New planned action',when:'',responsibility:'',constraints:''}]})}>Add planned action</button>{s.actions.map(a=><article className="scenario-card" key={a.id}>{(['action','when','responsibility','constraints'] as const).map(k=><label key={k}>{({action:'Planned action',when:'When / associated trigger',responsibility:'Responsible person or role',constraints:'Constraints & fallback'})[k]}<textarea rows={2} maxLength={k==='responsibility'?300:k==='constraints'?2000:1000} value={a[k]} onChange={e=>patch({actions:s.actions.map(x=>x.id===a.id?{...x,[k]:e.target.value}:x)})}/></label>)}<button onClick={()=>patch({actions:s.actions.filter(x=>x.id!==a.id)})}>Remove action</button></article>)}
 {links('naiIds','Named areas / exposed locations',p.options.areas.map(a=>({id:a.id,label:a.name})),p.openArea)}{links('servicePlanIds','Resource and backup plans',p.services.map(a=>({id:a.id,label:a.name+' · '+a.sector})),p.openService)}{p.services.filter(a=>s.servicePlanIds.includes(a.id)).map(a=><p className="help" key={a.id}>{a.name}: {a.alternatives.length?a.alternatives.map(b=>b.name+' · '+b.status+(b.verifiedOn?' · checked '+b.verifiedOn:'')).join('; '):'No backup options documented.'}</p>)}{links('routeIds','Saved PACE routes',p.options.routes.map(r=>({id:r.id,label:r.role+' · '+r.name})),p.openRoute)}{links('questionIds','Collection questions',p.questions.map(q=>({id:q.id,label:q.question})),p.openQuestion)}</details>
 <details className="scenario-section"><summary>Tabletop exercises & follow-up</summary><p className="help">Walk through the plan without activating it. Record what failed, then create a question to close the gap.</p><label>Exercise date<input type="date" value={exerciseDate} onInput={e=>setExerciseDate(e.currentTarget.value)} onChange={e=>setExerciseDate(e.target.value)}/></label><label>Outcome<textarea maxLength={2000} value={outcome} onChange={e=>setOutcome(e.target.value)}/></label><label>Failures / unresolved gaps<textarea maxLength={4000} value={gaps} onChange={e=>setGaps(e.target.value)}/></label><button disabled={!outcome.trim()||!exerciseDate||s.exercises.length>=20} onClick={()=>{patch({exercises:[...s.exercises,{id:crypto.randomUUID(),date:exerciseDate,outcome:outcome.trim(),gaps}]});setOutcome('');setGaps('');}}>Record tabletop exercise</button>{s.exercises.map(e=><article className="scenario-card" key={e.id}><strong>{e.date||'Date unknown'}</strong><p>{e.outcome}</p><p>{e.gaps}</p><button disabled={!e.gaps.trim()||p.questions.length>=100||s.questionIds.length>=100} onClick={()=>p.createQuestion(s.id,e.gaps)}>Create follow-up question</button></article>)}</details>
 <details className="scenario-section"><summary>Assessment history · {s.history.length} versions</summary><p className="help">Versions preserve the scenario, evidence and linked-item labels at recording time. They do not display today’s cached source values.</p>{[...s.history].reverse().map(v=><details className="scenario-card" key={v.id}><summary>{new Date(v.recordedAt).toLocaleString()} · assessed {v.snapshot.assessedOn}</summary><p>{v.snapshot.title} · {v.snapshot.likelihood} likelihood · {v.snapshot.impact} impact · {v.snapshot.confidence} confidence</p><p>{v.snapshot.assessmentReason}</p><p>{v.snapshot.confidenceReason}</p><p>Assumptions: {v.snapshot.assumptions||'Not documented'}</p>{v.linkLabels.map((l,i)=><p className="help" key={i}>{l}</p>)}{v.snapshot.evidence.map(e=><p className="help" key={e.id}>{e.stance}: {e.title} · {e.source} · {e.date||'date unknown'} · {e.detail}{e.url&&/^https?:\/\//i.test(e.url)&&<a href={e.url} target="_blank" rel="noreferrer"> Original source</a>}</p>)}<p className="help">Triggers: {v.snapshot.indicators.map(i=>i.name+': '+i.condition+' ('+i.basis+')').join('; ')||'Not documented'}</p><p className="help">Actions: {v.snapshot.actions.map(a=>a.action+' — '+a.when).join('; ')||'Not documented'}</p>{v.snapshot.exercises.map(e=><p className="help" key={e.id}>Exercise {e.date}: {e.outcome} · {e.gaps}</p>)}</details>)}</details>
 </div>:<div className="empty"><ShieldAlert size={30}/><b>Build a plan for a disruption</b><p>Create a scenario or choose a planning prompt, then connect your evidence, resources and routes.</p></div>}</div></section>;
}
