import {pucSources,pucViewer,haysLinks} from '../lib/local-source-packs';
import {useState} from 'react';
import type {ReactNode} from 'react';
import {CategoryIcon} from '../lib/category-icons';
import {geometryContains,type Point,type ParcelGeometry} from '../lib/geo';
import {serviceLayers,serviceRoot} from '../lib/services';
type RecordItem={id:string;name:string;category:string;source:string;detail?:string;geometry?:ParcelGeometry;updatedDate?:string;lat:number;lng:number};
const groups=['Fire stations','EMS stations','Police & sheriff','Medical','Water providers','Wastewater providers','Power & communications','Food & supplies','Fuel'];
export default function ServicesPanel({records,home,status,busy,load,inspect,view,setView,children}:{records:RecordItem[];home:Point|null;status:Record<string,string>;busy:Record<string,boolean>;load:(kind:string)=>void;inspect:(id:string)=>void;view:string;setView:(view:string)=>void;children:ReactNode}){
 const [group,setGroup]=useState('All services');
 const matching=home?records.filter(p=>p.geometry&&['Emergency districts','Water providers','Wastewater providers'].includes(p.category)&&geometryContains(p.geometry,home)):[];
 const visible=records.filter(p=>[...groups,'Emergency districts'].includes(p.category)&&(group==='All services'||p.category===group));
 return <section className="sources-content services-content"><h2>Emergency services & infrastructure</h2><div className="service-view-tabs" role="group" aria-label="Services view"><button className={view==='directory'?'active':''} onClick={()=>setView('directory')}>Facility directory</button><button className={view==='dependencies'?'active':''} onClick={()=>setView('dependencies')}>Dependencies & backups</button></div>{view==='dependencies'?children:<><p>Call <a href="tel:911">911</a> for an emergency. Facility locations and provider boundaries support your study; they do not report live availability.</p>
 <div className="reference-box"><h3>Published boundaries at home</h3>{!home?<p>Set your home point to check district and utility boundaries.</p>:<>{matching.map(p=><button key={p.id} onClick={()=>inspect(p.id)}>{p.category} · {p.name}</button>)}{!matching.length&&<p>No intersection in loaded boundary records. This does not establish who serves your address.</p>}<p className="help">Confirm the current provider using your bill or the provider’s address lookup. CCN areas describe certificated service territories; they are not pipe maps. Emergency districts are separate from police jurisdictions.</p></>}</div>
 <div className="service-sources">{Object.entries(serviceLayers).map(([kind,s])=><article className="source-card" key={kind}><div><h3>{s.label}</h3>{["water","sewer"].includes(kind)&&<p className="help">Current statewide PUC water / sewer CCN service areas. Layer edit dates appear in record details; verify current account eligibility with the provider.</p>}{kind==="esd"&&<p className="help">Metadata cites May 2016 boundaries. Verify current jurisdiction.</p>}<small>{status[kind]||'Draw an AOR or AOI to load records automatically.'}</small><a href={kind==='water'||kind==='sewer'?pucSources[kind]:serviceRoot+s.path} target="_blank" rel="noreferrer">County source metadata</a></div><button disabled={busy[kind]} onClick={()=>load(kind)}>{busy[kind]?'Loading…':'Refresh'}</button></article>)}</div>
 <label>Show facilities and providers<select value={group} onChange={e=>setGroup(e.target.value)}>{['All services',...groups,'Emergency districts'].map(g=><option key={g}>{g}</option>)}</select></label><p>{visible.length} loaded records intersect your selected area. Police, medical, power, communications, food and fuel locations use community-maintained OpenStreetMap; coverage varies.</p>
 <div className="service-directory">{visible.map(p=><button key={p.id} className="service-item" onClick={()=>inspect(p.id)}><CategoryIcon category={p.category}/><span><strong>{p.name}</strong><small>{p.category} · {p.source}</small><small>{p.updatedDate?`Source record updated ${new Date(p.updatedDate).toLocaleDateString()}`:'Source record date unavailable'}</small></span></button>)}</div>{!visible.length&&<p className="help">No matching records loaded. Check source results above and widen your AOI to include alternatives.</p>}
 <div className="reference-box"><h3>Hays / Wimberley official resources</h3><p className="help">Regional directory; confirm the agency for your address. Fire / EMS locations in Hays use OpenStreetMap community coverage; official response polygons and live availability are not connected.</p>{haysLinks.map(l=><p key={l.url}><a href={l.url} target="_blank" rel="noreferrer">{l.name}</a><small>{l.note}</small></p>)}</div><div className="reference-box"><h3>Contacts & current information</h3><div><a href={pucViewer} target="_blank" rel="noreferrer">Current PUC water / sewer CCN viewer</a><a href="https://www.manortx.gov/284/Utility" target="_blank" rel="noreferrer">Manor water / sewer contacts & notices</a><a href="https://warncentraltexas.org/" target="_blank" rel="noreferrer">Register for regional emergency alerts</a><a href="https://www.traviscountytx.gov/emergency-services" target="_blank" rel="noreferrer">Travis County emergency services</a><a href="https://www.atxfloods.com/" target="_blank" rel="noreferrer">Current road closures</a></div><p className="help">Shelter activation, backup capacity, and current facility availability are not supplied by these layers. Confirm those details with the responsible agency and record a dated source in your study.</p></div>
 </>}</section>;
}
