'use client';
import {useEffect,useState} from 'react';
import {RefreshCw,MapPin,ExternalLink} from 'lucide-react';
import GaugeReadings from './gauge-readings';
import {readingAge,type GaugeRecord} from '../lib/water-gauges';
import {inside,type Point} from '../lib/geo';
import {reportDate} from '../lib/report-dates';
type Props={records:GaugeRecord[];area:Point[];areaName:string;status:string;busy:boolean;refresh:()=>void;inspect:(r:GaugeRecord)=>void};
export default function WaterPanel({records,area,areaName,status,busy,refresh,inspect}:Props){
 const [selectedId,setSelectedId]=useState(''),[clock,setClock]=useState(()=>Date.now());
 useEffect(()=>{const t=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(t);},[]);
 const sites=[...records].sort((a,b)=>Number(inside([b.lat,b.lng],area))-Number(inside([a.lat,a.lng],area))||a.name.localeCompare(b.name)),selected=sites.find(r=>r.id===selectedId)||sites[0];
 const recent=sites.filter(s=>s.water.readings.some(r=>readingAge(r,clock)==='Recent observation')).length;
 return <section className="water-section"><div className="row"><div><span className="eyebrow">OBSERVATIONS / STREAMS / PRECIPITATION</span><h2>Nearby water monitoring</h2></div><button disabled={busy||area.length<3} onClick={refresh}><RefreshCw size={16}/>{busy?'Checking gauges…':'Check USGS gauges'}</button></div><p>Latest reported sensor values, including readings that may be old. These do not establish flooding, a road closure, or a safe crossing.</p>{area.length<3?<p className="help">Draw an AOR or AOI to collect gauge observations around your area.</p>:<><p className="help">Search includes your {areaName} bounding box with a nearby margin of up to 0.08° per side (roughly 5 miles). Very large areas use their original bounding box. Nearby does not mean upstream or connected to the same waterway.</p><p className="help">{status||'Waiting for gauge collection…'}</p><p>{sites.length} stations loaded · {recent} with a usable observation no more than 2 hours old. This is an app freshness flag, not an operational status.</p>{!sites.length&&<p className="notice">No gauge records loaded. Check collection status and coverage; an empty result does not establish an absence of flood exposure.</p>}{selected&&<article className="dashboard-card"><label>Choose a monitoring station<select value={selected.id} onChange={e=>setSelectedId(e.target.value)}>{sites.map(s=><option key={s.id} value={s.id}>{s.name} · {inside([s.lat,s.lng],area)?'inside '+areaName:'nearby / outside '+areaName}</option>)}</select></label><div className="row"><h3>{selected.name}</h3><button onClick={()=>inspect(selected)}><MapPin size={15}/>View gauge on map</button></div><p className="help">{selected.water.siteId} · {inside([selected.lat,selected.lng],area)?'Inside':'Outside'} {areaName}<br/>Retrieved {selected.retrievedAt?reportDate(selected.retrievedAt,true):'Unavailable'}</p>{selected.stale&&<p className="notice">Older collection snapshot. Verify the latest source before using these readings.</p>}<GaugeReadings data={selected.water} clock={clock}/><a href={selected.url} target="_blank" rel="noreferrer">Original USGS station <ExternalLink size={14}/></a><p className="help">Provisional and qualified observations can be revised. A recent zero is a reported measurement; an unavailable value is not zero. Different sensors at the same station may have different observation times.</p></article>}</>}
 <div className="water-links"><a href="https://www.atxfloods.com/" target="_blank" rel="noreferrer">Check official crossing closures <ExternalLink size={14}/></a><a href="https://hydromet.lcra.org/" target="_blank" rel="noreferrer">Regional LCRA rainfall and river maps <ExternalLink size={14}/></a><a href="https://api.waterdata.usgs.gov/" target="_blank" rel="noreferrer">USGS API documentation <ExternalLink size={14}/></a></div><p className="help">USGS observations refresh through a 5-minute area cache while this tab is visible. Public API limits and source failures are shown in collection status. Closure decisions and alert thresholds remain with the responsible agency.</p>
 </section>;
}
