"use client";
import {useEffect,useRef,useState} from 'react';
import {collectionFetch} from '../lib/collection-activity';
import {heatClasses,aqiClass,datedOld,pollutants,pollutantNames,type Pollutant,type AirFeed,type AirReading,type SmokeFeed,type SmokeArea,type HeatImage} from '../lib/weather-environment';
import type {ConditionSnapshot} from '../lib/conditions';
const date=(s?:string)=>s?new Date(s).toLocaleString():'Unavailable';
type Props={map:any;L:any;active:boolean;mode:string;extent:string;refresh:number;onEnabled:(v:boolean)=>void;openControls:(v:boolean)=>void};
function useSource<T>(kind:string,enabled:boolean,active:boolean,extent:string,refresh:number,extra=''){
 const [snapshot,setSnapshot]=useState<ConditionSnapshot<T>>(),[busy,setBusy]=useState(false),scope=useRef('');
 useEffect(()=>{if(!enabled||!active||!extent)return;const key=extent+extra;if(scope.current!==key){setSnapshot(undefined);scope.current=key;}const c=new AbortController();let working=false;const load=async()=>{if(working||document.visibilityState==='hidden')return;working=true;setBusy(true);try{const r=await collectionFetch('/api/weather-map?kind='+kind+'&bbox='+encodeURIComponent(extent)+extra,{signal:c.signal}),d=await r.json();if(!r.ok)throw Error(d.error||'Weather source unavailable.');if(!c.signal.aborted)setSnapshot(d[kind]);}catch(e){if(!c.signal.aborted)setSnapshot(prior=>({...prior,checkedAt:new Date().toISOString(),nextCheckAt:'',error:(e as Error).message}));}finally{working=false;if(!c.signal.aborted)setBusy(false);}};const debounce=setTimeout(load,800),timer=setInterval(load,600000);return()=>{c.abort();clearTimeout(debounce);clearInterval(timer);};},[kind,enabled,active,extent,refresh,extra]);
 return {snapshot,busy};
}
export default function WeatherEnvironment({map,L,active,mode,extent,refresh,onEnabled,openControls}:Props){
 const [heatOn,setHeatOn]=useState(false),[smokeOn,setSmokeOn]=useState(false),[airOn,setAirOn]=useState(false),[day,setDay]=useState(1),[opacity,setOpacity]=useState(.4),[pollutant,setPollutant]=useState<Pollutant>('PM25'),[imageState,setImageState]=useState(''),[selectedAir,setSelectedAir]=useState<AirReading>(),[selectedSmoke,setSelectedSmoke]=useState<SmokeArea>(),[clock,setClock]=useState(Date.now());
 const detail=useRef<HTMLElement>(null),airDetail=useRef<HTMLElement>(null),heatLayer=useRef<any>(null);
 const heat=useSource<HeatImage>('heat',heatOn,active,extent,refresh,'&day='+day),smoke=useSource<SmokeFeed>('smoke',smokeOn,active,extent,refresh),air=useSource<AirFeed>('airquality',airOn,active,extent,refresh);
 useEffect(()=>{onEnabled(heatOn||smokeOn||airOn);},[heatOn,smokeOn,airOn,onEnabled]);
 useEffect(()=>{setSelectedAir(undefined);setSelectedSmoke(undefined);},[extent]);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(selectedAir)airDetail.current?.scrollIntoView({block:'nearest'});if(selectedSmoke)detail.current?.scrollIntoView({block:'nearest'});},[selectedAir,selectedSmoke]);
 useEffect(()=>{if(!map||!L)return;for(const [name,z] of [['weather-heat',330],['weather-smoke',460],['weather-air',650]] as const){if(!map.getPane(name))map.createPane(name);map.getPane(name).style.zIndex=String(z);}map.getPane('weather-heat').style.pointerEvents='none';},[map,L]);
 useEffect(()=>{if(!map||!L||!active||!heatOn||!heat.snapshot?.data)return;const d=heat.snapshot.data;setImageState('Loading forecast image…');const layer=L.imageOverlay(d.url,d.bounds,{pane:'weather-heat',opacity,attribution:'NOAA / NWS experimental HeatRisk'}).on('load',()=>setImageState('Forecast image loaded.')).on('error',()=>setImageState('Forecast image failed to load. Refresh to retry.')).addTo(map);heatLayer.current=layer;return()=>{layer.remove();layer.off();heatLayer.current=null;};},[map,L,active,heatOn,heat.snapshot?.data]);
 useEffect(()=>{heatLayer.current?.setOpacity(opacity);},[opacity]);
 useEffect(()=>{if(!map||!L||!active||!smokeOn||!smoke.snapshot?.data)return;const group=L.layerGroup().addTo(map);for(const s of smoke.snapshot.data.rows){const label=document.createElement('span');label.textContent=s.density+' satellite smoke · observed through '+date(s.end);L.geoJSON(s.geometry,{pane:'weather-smoke',style:{color:s.density==='Heavy'?'#87506d':s.density==='Medium'?'#a7734c':'#8a8c76',weight:2,fillOpacity:s.density==='Heavy'?.3:s.density==='Medium'?.2:.1,dashArray:datedOld(s.end,24,clock)?'6 4':undefined},interactive:!mode,bubblingMouseEvents:false}).bindTooltip(label).on('click',()=>{if(!mode){openControls(true);setSelectedSmoke(s);}}).addTo(group);}return()=>{group.clearLayers();group.remove();};},[map,L,active,mode,smokeOn,smoke.snapshot,clock,openControls]);
 useEffect(()=>{if(!map||!L||!active||!airOn||!air.snapshot?.data)return;const group=L.layerGroup().addTo(map);for(const r of air.snapshot.data.rows){const v=r.values[pollutant],c=aqiClass(v?.aqi),pin=document.createElement('div');pin.className='weather-air-pin'+(datedOld(r.observedAt,3,clock)?' is-stale':'');pin.style.borderColor=c.color;pin.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 8h12a3 3 0 1 0-3-3M3 12h17M3 16h12a3 3 0 1 1-3 3" fill="none" stroke="currentColor" stroke-width="2"/></svg>';const value=document.createElement('span');value.textContent=v?.aqi===undefined?'—':String(v.aqi);pin.append(value);const label=document.createElement('span');label.textContent=r.name+' · '+pollutantNames[pollutant]+' AQI '+(v?.aqi??'unavailable')+' · '+date(r.observedAt);L.marker([r.lat,r.lng],{pane:'weather-air',interactive:!mode,bubblingMouseEvents:false,icon:L.divIcon({html:pin,className:'',iconSize:[48,30],iconAnchor:[24,15]})}).bindTooltip(label).on('click',()=>{if(!mode){openControls(true);setSelectedAir(r);}}).addTo(group);}return()=>{group.clearLayers();group.remove();};},[map,L,active,mode,airOn,air.snapshot,pollutant,clock,openControls]);
 const status=(s:ConditionSnapshot<any>|undefined,busy:boolean)=><><p aria-live="polite">{busy?'Checking source…':s?.error||''}{s?.cacheWarning}</p>{s?.fetchedAt&&<small>Retrieved {date(s.fetchedAt)}{s.error||datedOld(s.fetchedAt,1,clock)?' · stale snapshot':''}</small>}</>;
 return <><label className="weather-toggle"><input type="checkbox" checked={heatOn} onChange={e=>setHeatOn(e.target.checked)}/>HeatRisk forecast</label><label className="weather-toggle"><input type="checkbox" checked={smokeOn} onChange={e=>setSmokeOn(e.target.checked)}/>Satellite smoke outlines</label><label className="weather-toggle"><input type="checkbox" checked={airOn} onChange={e=>setAirOn(e.target.checked)}/>Air quality monitors</label>
 {heatOn&&<section><strong>Daily HeatRisk</strong>{status(heat.snapshot,heat.busy)}<label>Forecast day<select value={day} onChange={e=>setDay(Number(e.target.value))}>{Array.from({length:7},(_,i)=><option key={i} value={i+1}>Day {i+1}{heat.snapshot?.data?.days.find(d=>d.day===i+1)?' · '+heat.snapshot.data.days.find(d=>d.day===i+1)!.validAt.slice(0,10)+' UTC':''}</option>)}</select></label>{heat.snapshot?.data&&<><small>Valid date {heat.snapshot.data.selected.validAt.slice(0,10)} UTC · issued {date(heat.snapshot.data.selected.issuedAt)}{datedOld(heat.snapshot.data.selected.issuedAt,36,clock)?' · old or unknown issue time':''}</small><small>Source ingested {date(heat.snapshot.data.selected.ingestedAt)}</small><label>HeatRisk opacity · {Math.round(opacity*100)}%<input aria-label="HeatRisk opacity" type="range" min=".1" max=".8" step=".05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><small>{imageState}</small></>}<div className="weather-risk-legend">{heatClasses.map((c,i)=><span key={i}><i style={{background:c.color}}/>{i} · {c.name}</span>)}</div><p className="help">Experimental heat-impact forecast for the contiguous US. Supplements official warnings; colors are risk categories, not temperatures. Blank imagery may indicate missing coverage.</p><a href="https://www.wpc.ncep.noaa.gov/heatrisk/" target="_blank" rel="noreferrer">NOAA HeatRisk guidance</a></section>}
 {smokeOn&&<section><strong>Satellite-detected smoke</strong>{status(smoke.snapshot,smoke.busy)}{smoke.snapshot?.data&&<><small>{smoke.snapshot.data.rows.length} outlines intersecting this view{smoke.snapshot.data.invalid?' · malformed records omitted':''}</small>{smoke.snapshot.data.rows.some(r=>datedOld(r.end,24,clock))&&<small>Some outlines have old or unknown observation times (dashed).</small>}</>}<div className="weather-risk-legend">{[{name:"Light",color:"#8a8c76"},{name:"Medium",color:"#a7734c"},{name:"Heavy",color:"#87506d"}].map(c=><span key={c.name}><i style={{background:c.color}}/>{c.name}</span>)}</div><p className="help">Light, medium and heavy describe smoke seen from satellites. These outlines do not measure smoke at ground level or establish local AQI. An empty map does not establish clear air.</p><a href="https://www.ospo.noaa.gov/products/land/hms.html" target="_blank" rel="noreferrer">NOAA Hazard Mapping System</a>{selectedSmoke&&<article ref={detail} className="weather-alert-detail"><strong>{selectedSmoke.density} smoke · {selectedSmoke.satellite}</strong><small>Observation start {date(selectedSmoke.start)}</small><small>Observation end {date(selectedSmoke.end)}</small><button onClick={()=>setSelectedSmoke(undefined)}>Close smoke details</button></article>}</section>}
 {airOn&&<section><strong>AirNow monitor observations</strong>{status(air.snapshot,air.busy)}<label>Map pollutant<select value={pollutant} onChange={e=>setPollutant(e.target.value as Pollutant)}>{pollutants.map(p=><option key={p} value={p}>{pollutantNames[p]} AQI</option>)}</select></label>{air.snapshot?.data&&<><small>{air.snapshot.data.rows.length} monitors in view{air.snapshot.data.partial?" · capped at 400; zoom in for complete coverage":""} · file hour {date(air.snapshot.data.fileAt)}{datedOld(air.snapshot.data.fileAt,3,clock)?' · old file':''}</small><small>File updated {date(air.snapshot.data.modifiedAt)}{air.snapshot.data.invalid?' · malformed records omitted':''}</small>{air.snapshot.data.rows.map(r=><button key={r.id} className="weather-alert-item" onClick={()=>{setSelectedAir(r);}}>{r.name}<small>{pollutantNames[pollutant]} AQI {r.values[pollutant]?.aqi??'unavailable'} · {date(r.observedAt)}{datedOld(r.observedAt,3,clock)?' · stale / unknown time':''}</small></button>)}<a href={air.snapshot.data.url} target="_blank" rel="noreferrer">Source monitor file</a></>}<div className="weather-risk-legend">{[0,51,101,151,201,301].map(n=>{const c=aqiClass(n);return <span key={n}><i style={{background:c.color}}/>{c.name}</span>;})}</div><p className="help">Preliminary monitor data, not a reading at your home. Ozone and particle AQIs are NowCast values; NO₂ is hourly. Dashed pins have observations older than 3 hours or unknown dates. A dash means the selected pollutant is unavailable.</p><a href="https://www.airnow.gov/aqi/aqi-basics/" target="_blank" rel="noreferrer">AirNow AQI guide</a>{selectedAir&&<article ref={airDetail} className="weather-alert-detail"><strong>{selectedAir.name}</strong><small>Monitor {selectedAir.id} · {selectedAir.agency}</small><small>Observation hour began {date(selectedAir.observedAt)} (displayed in local time)</small><small>Source UTC timestamp {selectedAir.observedAt||"Unavailable"}</small>{pollutants.map(p=><p key={p}>{pollutantNames[p]}: AQI {selectedAir.values[p]?.aqi??'unavailable'} · {aqiClass(selectedAir.values[p]?.aqi).name}<br/>Concentration {selectedAir.values[p]?.concentration??'unavailable'} {selectedAir.values[p]?.unit||''}</p>)}<button onClick={()=>setSelectedAir(undefined)}>Close monitor details</button></article>}</section>}</>;
}
