"use client";
import {useEffect,useRef,useState} from 'react';
import {CloudRain,Play,Pause,RefreshCw} from 'lucide-react';
import {collectionFetch} from '../lib/collection-activity';
import {activeMapAlerts,alertColor,radarTileUrl,type MapAlert,type RadarManifest,type AlertFeed} from '../lib/weather-map';
import type {ConditionSnapshot} from '../lib/conditions';
const date=(s?:string|number)=>s?new Date(typeof s==='number'?s*1000:s).toLocaleString():'Unavailable';
export default function WeatherMap({map,L,active,mode}:{map:any;L:any;active:boolean;mode:string}){
 const [open,setOpen]=useState(false),[radarOn,setRadarOn]=useState(false),[alertsOn,setAlertsOn]=useState(false),[playing,setPlaying]=useState(false),[frame,setFrame]=useState(0),[opacity,setOpacity]=useState(.55),[alertOpacity,setAlertOpacity]=useState(.12);
 const [radar,setRadar]=useState<ConditionSnapshot<RadarManifest>>(),[alerts,setAlerts]=useState<ConditionSnapshot<AlertFeed>>(),[radarBusy,setRadarBusy]=useState(false),[alertsBusy,setAlertsBusy]=useState(false),[tileError,setTileError]=useState(false),[tileBusy,setTileBusy]=useState(false),[selected,setSelected]=useState<MapAlert|null>(null),[refresh,setRefresh]=useState(0),[clock,setClock]=useState(Date.now()),[extent,setExtent]=useState('');
 const radarLayer=useRef<any>(null),alertLayer=useRef<any>(null),serial=useRef(0),responseScope=useRef('');
 useEffect(()=>{if(!map)return;const update=()=>{const b=map.getBounds();setExtent([Math.max(-90,b.getSouth()),Math.max(-180,b.getWest()),Math.min(90,b.getNorth()),Math.min(180,b.getEast())].map(n=>n.toFixed(4)).join(','));};update();map.on('moveend',update);return()=>{map.off('moveend',update);};},[map]);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!radarOn||!active)return;const c=new AbortController();let working=false;async function load(){if(working||document.visibilityState==='hidden')return;working=true;setRadarBusy(true);try{const r=await collectionFetch('/api/weather-map?kind=radar',{signal:c.signal});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'Radar unavailable');if(c.signal.aborted)return;setRadar(d.radar);if(d.radar.data)setFrame(d.radar.data.frames.length-1);}catch(e){if(!c.signal.aborted)setRadar(s=>({...s,checkedAt:new Date().toISOString(),nextCheckAt:'',error:(e as Error).message}));}finally{working=false;if(!c.signal.aborted)setRadarBusy(false);}}void load();const timer=setInterval(load,300000);return()=>{c.abort();clearInterval(timer);};},[radarOn,active,refresh]);
 useEffect(()=>{if(!alertsOn||!active||!extent)return;const c=new AbortController();if(responseScope.current!==extent){setAlerts(undefined);responseScope.current=extent;}let working=false;async function load(){if(working||document.visibilityState==='hidden')return;working=true;setAlertsBusy(true);try{const r=await collectionFetch('/api/weather-map?kind=alerts&bbox='+encodeURIComponent(extent),{signal:c.signal});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'Alerts unavailable');if(!c.signal.aborted)setAlerts(d.alerts);}catch(e){if(!c.signal.aborted)setAlerts(s=>({...s,checkedAt:new Date().toISOString(),nextCheckAt:'',error:(e as Error).message}));}finally{working=false;if(!c.signal.aborted)setAlertsBusy(false);}}const debounce=setTimeout(load,600),timer=setInterval(load,120000);return()=>{c.abort();clearTimeout(debounce);clearInterval(timer);};},[alertsOn,active,extent,refresh]);
 useEffect(()=>{if(!map||!L)return;for(const [name,z] of [['weather-radar',350],['weather-alerts',450]] as const){if(!map.getPane(name))map.createPane(name);map.getPane(name).style.zIndex=String(z);}map.getPane('weather-radar').style.pointerEvents='none';},[map,L]);
 const manifest=radar?.data,current=manifest?.frames[Math.min(frame,manifest.frames.length-1)];
 useEffect(()=>{if(!map||!L||!active||!radarOn||!manifest||!current)return;const sequence=++serial.current;setTileError(false);setTileBusy(true);const layer=L.tileLayer(radarTileUrl(manifest,current),{pane:'weather-radar',opacity,maxNativeZoom:7,maxZoom:19,minZoom:0,updateWhenIdle:true,keepBuffer:0,attribution:'Weather data by <a href="https://www.rainviewer.com/">RainViewer</a>'});radarLayer.current=layer;layer.on('loading',()=>{if(serial.current===sequence)setTileBusy(true);});layer.on('load',()=>{if(serial.current===sequence)setTileBusy(false);});layer.on('tileerror',()=>{if(serial.current===sequence){setTileError(true);setTileBusy(false);setPlaying(false);}});layer.addTo(map);return()=>{layer.off();layer.remove();radarLayer.current=null;};},[map,L,active,radarOn,manifest,current?.path]);
 useEffect(()=>{radarLayer.current?.setOpacity(opacity);},[opacity]);
 const currentAlerts=activeMapAlerts(alerts?.data?.rows||[],clock);
 useEffect(()=>{if(!map||!L||!active||!alertsOn)return;const group=L.layerGroup().addTo(map);alertLayer.current=group;for(const a of currentAlerts){const label=document.createElement('span');label.textContent=a.event+' · expires '+date(a.expires);L.geoJSON(a.geometry,{pane:'weather-alerts',style:{color:alertColor(a),weight:2,fillOpacity:alertOpacity,dashArray:a.event.includes('Watch')?'6 4':undefined},interactive:!mode,bubblingMouseEvents:false}).addTo(group).bindTooltip(label).on('click',()=>{if(!mode){setSelected(a);setOpen(true);}});}return()=>{group.clearLayers();group.remove();alertLayer.current=null;};},[map,L,active,alertsOn,alerts,clock,alertOpacity,mode]);
 useEffect(()=>{if(!active||!radarOn)setPlaying(false);},[active,radarOn]);
 useEffect(()=>{if(!playing||!active||!radarOn||!manifest)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')setFrame(f=>(f+1)%manifest.frames.length);},8000);return()=>clearInterval(timer);},[playing,active,radarOn,manifest]);
 const shown=selected&&currentAlerts.find(a=>a.id===selected.id),oldRadar=!!manifest&&(!!radar?.error||clock-manifest.frames.at(-1)!.time*1000>1800000),oldAlerts=!!alerts&&(!!alerts.error||!!alerts.fetchedAt&&clock-Date.parse(alerts.fetchedAt)>300000);
 return <details className="weather-map-controls" open={open} onToggle={e=>setOpen(e.currentTarget.open)} style={{display:active?'block':'none'}}><summary><CloudRain size={17}/>Weather overlays <span>{radarOn||alertsOn?'On':'Off'}</span></summary><div className="weather-map-body"><label className="weather-toggle"><input type="checkbox" checked={radarOn} onChange={e=>setRadarOn(e.target.checked)}/>Precipitation radar</label><label className="weather-toggle"><input type="checkbox" checked={alertsOn} onChange={e=>setAlertsOn(e.target.checked)}/>NWS alerts · current map view</label><button onClick={()=>setRefresh(r=>r+1)} disabled={radarBusy||alertsBusy||(!radarOn&&!alertsOn)}><RefreshCw size={14}/>Refresh weather</button>
 {radarOn&&<section><strong>Radar history</strong><p aria-live="polite">{radarBusy?'Checking radar timeline…':radar?.error||''}{radar?.cacheWarning}</p>{manifest&&current&&<><small>Frame generated {date(current.time)}{oldRadar?' · latest feed is stale':current.time!==manifest.frames.at(-1)!.time?' · history frame':''}</small><small>Retrieved {date(radar?.fetchedAt)}</small><label>Radar opacity · {Math.round(opacity*100)}%<input aria-label="Radar opacity" type="range" min=".1" max=".9" step=".05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><div className="weather-playback"><button aria-label={playing?'Pause radar':'Play radar history'} disabled={tileError||manifest.frames.length<2} onClick={()=>setPlaying(p=>!p)}>{playing?<Pause size={15}/>:<Play size={15}/>}</button><input aria-label="Radar history frame" type="range" min="0" max={manifest.frames.length-1} value={Math.min(frame,manifest.frames.length-1)} onChange={e=>{setPlaying(false);setFrame(Number(e.target.value));}}/><button onClick={()=>{setPlaying(false);setFrame(manifest.frames.length-1);}}>Latest</button></div><small>{date(manifest.frames[0].time)} → {date(manifest.frames.at(-1)?.time)}</small><p className="help">{tileError?'Radar tiles failed to load. Playback paused; refresh to retry.':tileBusy?'Loading radar tiles…':'Radar frame loaded.'}</p></>}<p className="help">Past imagery, not a forecast. Regional resolution enlarged at street zoom. Blank imagery may indicate missing coverage. Frames combine observations from different times.</p><a href="https://www.rainviewer.com/" target="_blank" rel="noreferrer">Weather data by RainViewer</a></section>}
 {alertsOn&&<section><strong>NWS alert polygons</strong><p aria-live="polite">{alertsBusy?'Checking map-view alerts…':alerts?.error||''}{alerts?.cacheWarning}</p>{alerts?.data&&<><small>{currentAlerts.length} unexpired mapped alerts · retrieved {date(alerts.fetchedAt)}{oldAlerts?' · stale snapshot':''}</small><label>Alert fill opacity · {Math.round(alertOpacity*100)}%<input aria-label="Alert fill opacity" type="range" min="0" max=".5" step=".02" value={alertOpacity} onChange={e=>setAlertOpacity(Number(e.target.value))}/></label><div className="weather-alert-legend"><span style={{color:'#d34242'}}>Warning</span><span style={{color:'#d99c24'}}>Watch</span><span style={{color:'#6e67b4'}}>Other alert</span></div>{currentAlerts.map(a=><button className="weather-alert-item" key={a.id} onClick={()=>{setSelected(a);if(map&&L)map.fitBounds(L.geoJSON(a.geometry).getBounds(),{padding:[30,30],maxZoom:12});}}>{a.event}<small>Expires {date(a.expires)}</small></button>)}</>}<p className="help">Shows published polygons intersecting the map view, including watches and advisories. Alerts without polygons are omitted; {alerts?.data?.invalid?'some malformed records were excluded. ':''}check the Dashboard’s point-based alerts and NWS. No polygons does not establish safe weather.</p><a href="https://www.weather.gov/" target="_blank" rel="noreferrer">National Weather Service</a>{shown&&<article className="weather-alert-detail"><strong>{shown.headline}</strong><a href={shown.url} target="_blank" rel="noreferrer">Official alert</a><small>{shown.severity} · sent {date(shown.sent)}</small><small>Onset {date(shown.onset)} · expires {date(shown.expires)}</small><p>{shown.description}</p>{shown.instruction&&<p>{shown.instruction}</p>}<button onClick={()=>setSelected(null)}>Close alert details</button></article>}</section>}
 <p className="help">Weather layers refresh while the map is visible. Live weather overlays are not included in ATAK exports or saved briefings.</p></div></details>;
}
