"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {collectionFetch} from '../lib/collection-activity';
import {outlookProduct,outlookExpired,outlookRowsInView,outlookMatches,stormHazards,stormClasses,rainClasses,type OutlookFeed,type OutlookKind,type StormHazard,type OutlookLocation,type OutlookRoute,type OutlookArea} from '../lib/weather-outlooks';
import {validWeatherBounds} from '../lib/weather-map';
import type {ConditionSnapshot} from '../lib/conditions';
const date=(s?:string)=>s?new Date(s).toLocaleString():'Unavailable';
type Props={map:any;L:any;active:boolean;mode:string;extent:string;refresh:number;locations:OutlookLocation[];routes:OutlookRoute[];onEnabled:(v:boolean)=>void;openControls:(v:boolean)=>void};
function useOutlook(kind:OutlookKind,on:boolean,active:boolean,day:number,hazard:StormHazard,refresh:number){
 const [snapshot,setSnapshot]=useState<ConditionSnapshot<OutlookFeed>>(),[busy,setBusy]=useState(false),scope=useRef(''),key=kind+day+hazard;
 useEffect(()=>{if(!on||!active)return;if(scope.current!==key){setSnapshot(undefined);scope.current=key;}const c=new AbortController();let working=false;
 const load=async()=>{if(working||document.visibilityState==='hidden')return;working=true;setBusy(true);try{const r=await collectionFetch('/api/weather-map?'+new URLSearchParams({kind,day:String(day),hazard}),{signal:c.signal}),d=await r.json();if(!r.ok)throw Error(d.error||'Forecast outlook unavailable.');if(!c.signal.aborted)setSnapshot(d[kind]);}catch(e){if(!c.signal.aborted)setSnapshot(s=>({...s,checkedAt:new Date().toISOString(),nextCheckAt:'',error:(e as Error).message}));}finally{working=false;if(!c.signal.aborted)setBusy(false);}};
 void load();const timer=setInterval(load,600000);return()=>{c.abort();clearInterval(timer);};},[kind,on,active,day,hazard,refresh]);return {snapshot:scope.current===key?snapshot:undefined,busy};
}
export default function WeatherOutlooks({map,L,active,mode,extent,refresh,locations,routes,onEnabled,openControls}:Props){
 const [stormsOn,setStormsOn]=useState(false),[rainOn,setRainOn]=useState(false),[stormDay,setStormDay]=useState(1),[rainDay,setRainDay]=useState(1),[hazard,setHazard]=useState<StormHazard>('cat'),[opacity,setOpacity]=useState(.12),[selected,setSelected]=useState<{product:string;area:OutlookArea}>(),[clock,setClock]=useState(Date.now());
 const storm=useOutlook('storms',stormsOn,active,stormDay,hazard,refresh),rain=useOutlook('rainoutlook',rainOn,active,rainDay,'cat',refresh),detail=useRef<HTMLElement>(null);
 useEffect(()=>{onEnabled(stormsOn||rainOn);},[stormsOn,rainOn,onEnabled]);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{setSelected(undefined);},[stormDay,rainDay,hazard]);
 useEffect(()=>{if(selected)detail.current?.scrollIntoView({block:'nearest'});},[selected]);
 const feeds=useMemo(()=>[{on:stormsOn,result:storm,kind:'storms' as const,day:stormDay,hazard},{on:rainOn,result:rain,kind:'rainoutlook' as const,day:rainDay,hazard:'cat' as const}],[stormsOn,rainOn,storm.snapshot,storm.busy,rain.snapshot,rain.busy,stormDay,rainDay,hazard]);
 useEffect(()=>{if(!map||!L||!active)return;const bbox=extent.split(',').map(Number);if(!validWeatherBounds(bbox))return;const pane='weather-outlooks';if(!map.getPane(pane))map.createPane(pane);map.getPane(pane).style.zIndex='440';const group=L.layerGroup().addTo(map);
 for(const f of feeds){const feed=f.result.snapshot?.data;if(!f.on||!feed)continue;for(const area of outlookRowsInView(feed,bbox,clock)){const label=document.createElement('span');label.textContent=feed.product.name+' · '+area.label+' · valid '+date(feed.validFrom)+' → '+date(feed.validThrough);L.geoJSON(area.geometry,{pane,attribution:feed.product.kind==="storms"?"NOAA / NWS Storm Prediction Center":"NOAA / NWS Weather Prediction Center",style:{color:area.color,weight:2,fillOpacity:opacity,dashArray:!feed.periodKnown||f.result.snapshot?.error?'6 4':feed.validFrom&&Date.parse(feed.validFrom)>clock?'3 3':undefined},interactive:!mode,bubblingMouseEvents:false}).bindTooltip(label).on('click',()=>{if(!mode){openControls(true);setSelected({product:feed.product.key,area});}}).addTo(group);}}
 return()=>{group.clearLayers();group.remove();};},[map,L,active,mode,extent,feeds,clock,opacity,openControls]);
 const section=(f:typeof feeds[number])=>{const snapshot=f.result.snapshot,feed=snapshot?.data,product=outlookProduct(f.kind,f.day,f.hazard),expired=feed&&outlookExpired(feed,clock),stale=!!snapshot?.error||!!snapshot?.fetchedAt&&clock-Date.parse(snapshot.fetchedAt)>1800000,matches=feed?outlookMatches(feed,locations,routes,clock):undefined,bbox=extent.split(',').map(Number),rows=feed&&validWeatherBounds(bbox)?outlookRowsInView(feed,bbox,clock):[],legend=f.kind==='rainoutlook'?rainClasses:f.hazard==='cat'?stormClasses:[...new Map(feed?.rows.map(r=>[r.rank,{rank:r.rank,label:r.label,color:r.color}])||[]).values()].sort((a,b)=>a.rank-b.rank),shown=feed&&selected?.product===feed.product.key&&feed.rows.find(r=>r.id===selected.area.id);
 return <section key={f.kind}><strong>{f.kind==='storms'?'SPC severe-weather outlook':'WPC excessive-rainfall outlook'}</strong><p aria-live="polite">{f.result.busy?'Checking forecast…':snapshot?.error||''}{snapshot?.cacheWarning}</p><label>{f.kind==='storms'?'Storm outlook day':'Rainfall outlook day'}<select aria-label={f.kind==='storms'?'Storm outlook day':'Rainfall outlook day'} value={f.day} onChange={e=>{const day=Number(e.target.value);if(f.kind==='storms'){setStormDay(day);if(day===3)setHazard('cat');}else setRainDay(day);}}>{Array.from({length:f.kind==='storms'?3:5},(_,i)=><option key={i} value={i+1}>Day {i+1}</option>)}</select></label>{f.kind==='storms'&&<label>Storm hazard<select aria-label="Storm hazard" value={hazard} onChange={e=>setHazard(e.target.value as StormHazard)}>{Object.entries(stormHazards).map(([key,name])=><option key={key} value={key} disabled={stormDay===3&&key!=='cat'}>{name}</option>)}</select>{stormDay===3&&<small>Day 3 provides overall risk in this layer.</small>}</label>}
 {feed&&<><small>Times displayed in your local time.</small><small>Issued {date(feed.issuedAt)}</small><small>Valid {date(feed.validFrom)} → {date(feed.validThrough)}{feed.validFrom&&Date.parse(feed.validFrom)>clock?' · upcoming period':''}{expired?' · expired; polygons hidden':''}</small><small>Retrieved {date(snapshot?.fetchedAt)}{stale?' · stale snapshot':''}</small>{(!feed.periodKnown||feed.invalid>0)&&<p className="notice">{!feed.periodKnown?'Forecast period unknown; location and route checks unavailable. ':''}{feed.invalid?`${feed.invalid} malformed polygons omitted; coverage incomplete.`:''}</p>}{feed.sourceMessage&&<p className="help">Publisher message: {feed.sourceMessage}</p>}<small>{rows.length} outlook polygons intersect the current map view.</small>{feed.rows.length>0&&!expired&&<button onClick={()=>{if(map&&L)map.fitBounds(L.geoJSON({type:"FeatureCollection",features:feed.rows.map(r=>({type:"Feature",properties:{},geometry:r.geometry}))}).getBounds(),{padding:[30,30],maxZoom:7});}}>View outlook areas</button>}</>}
 <div className="weather-risk-legend">{legend.map(c=><span key={c.rank}><i style={{background:c.color}}/>{c.label}</span>)}</div><p className="help">{f.kind==='rainoutlook'?'Forecast probability of rainfall exceeding flash-flood guidance within 25 miles of a point. These are regional outlooks, not flood depths or road closures.':f.hazard==='cat'?'Regional thunderstorm and severe-weather risk categories. These outlooks are separate from NWS watches and warnings.':'Forecast probability of the selected hazard within 25 miles of a point during the valid period. This is not a probability of damage to your property.'}</p><a href={product.officialUrl} target="_blank" rel="noreferrer">{f.kind==='storms'?'Official SPC outlook':'Official WPC outlook'}</a>
 {matches&&<details className="weather-outlook-matches"><summary>Saved locations & routes</summary>{!matches.available?<p className="help">Checks unavailable for an expired or undated forecast.</p>:<><small>{feed?.validFrom&&Date.parse(feed.validFrom)>clock?'Upcoming forecast period. ':''}{stale?'Based on older cached polygons. ':''}Checks cover saved location points and route lines nationwide, including those outside the map view.</small>{!matches.locations.length&&!matches.routes.length&&<p className="help">Add a location point or saved route to compare it with the forecast.</p>}{matches.locations.map(l=><p key={l.id}><strong>{l.name}</strong><br/>{l.labels.join('; ')||'No intersection with published outlook polygons.'}</p>)}{matches.routes.map(r=><p key={r.id}><strong>Route · {r.name}</strong><br/>{r.labels.join('; ')||'No intersection with published outlook polygons.'}</p>)}<p className="help">No intersection does not establish safe conditions. Risk areas are broad forecasts; check current warnings and local conditions.</p></>}</details>}
 {shown&&<article ref={detail} className="weather-alert-detail"><strong>{feed!.product.name}</strong><p>{shown.label}</p><small>Issued {date(feed!.issuedAt)}</small><small>Valid {date(feed!.validFrom)} → {date(feed!.validThrough)}</small>{expired&&<p className="notice">This forecast period has expired.</p>}<button onClick={()=>setSelected(undefined)}>Close outlook details</button></article>}</section>;};
 return <><label className="weather-toggle"><input type="checkbox" checked={stormsOn} onChange={e=>setStormsOn(e.target.checked)}/>Severe-weather outlooks</label><label className="weather-toggle"><input type="checkbox" checked={rainOn} onChange={e=>setRainOn(e.target.checked)}/>Excessive-rainfall outlooks</label>{(stormsOn||rainOn)&&<label>Outlook fill opacity · {Math.round(opacity*100)}%<input aria-label="Outlook fill opacity" type="range" min="0" max=".4" step=".02" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label>}{feeds.filter(f=>f.on).map(section)}</>;
}
