"use client";
import {useEffect,useRef,useState} from 'react';
import {collectionFetch} from '../lib/collection-activity';
import {rainPeriods,stationStale,rainSourceOld,type RainfallImage,type StationFeed,type StationReading} from '../lib/weather-measurements';
import type {ConditionSnapshot} from '../lib/conditions';
const date=(s?:string)=>s?new Date(s).toLocaleString():'Unavailable';
const number=(n?:number,unit='')=>n===undefined?'Not supplied':n.toFixed(1)+unit;
const wind=(s:StationReading)=>s.windMph===0?'Calm':`${number(s.windMph,' mph')} · ${s.direction===undefined?'direction not supplied':s.direction==='Variable'?'variable direction':`${s.direction}° from true north`}`;
export default function WeatherMeasurements({map,L,active,mode,extent,refresh,onEnabled,openControls}:{map:any;L:any;active:boolean;mode:string;extent:string;refresh:number;onEnabled:(on:boolean)=>void;openControls:(open:boolean)=>void}){
 const [rainOn,setRainOn]=useState(false),[stationsOn,setStationsOn]=useState(false),[period,setPeriod]=useState('24h'),[opacity,setOpacity]=useState(.5),[rain,setRain]=useState<ConditionSnapshot<RainfallImage>>(),[stations,setStations]=useState<ConditionSnapshot<StationFeed>>(),[rainBusy,setRainBusy]=useState(false),[stationBusy,setStationBusy]=useState(false),[imageError,setImageError]=useState(false),[imageBusy,setImageBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[clock,setClock]=useState(Date.now());
 const rainLayer=useRef<any>(null),rainScope=useRef(''),stationScope=useRef(''),detail=useRef<HTMLElement>(null);
 useEffect(()=>{onEnabled(rainOn||stationsOn);},[rainOn,stationsOn,onEnabled]);
 useEffect(()=>{const t=setInterval(()=>setClock(Date.now()),30000);return()=>clearInterval(t);},[]);
 useEffect(()=>{if(!active||!extent||!rainOn)return;const c=new AbortController(),key=extent+':'+period;if(rainScope.current!==key){setRain(undefined);rainScope.current=key;}let working=false;async function load(){if(working||document.visibilityState==='hidden')return;working=true;setRainBusy(true);try{const r=await collectionFetch('/api/weather-map?'+new URLSearchParams({kind:'rainfall',bbox:extent,period}),{signal:c.signal});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Rainfall unavailable');if(!c.signal.aborted)setRain(d.rainfall);}catch(e){if(!c.signal.aborted)setRain(s=>({...s,checkedAt:new Date().toISOString(),nextCheckAt:'',error:(e as Error).message}));}finally{working=false;if(!c.signal.aborted)setRainBusy(false);}}const debounce=setTimeout(load,800),timer=setInterval(load,900000);return()=>{c.abort();clearTimeout(debounce);clearInterval(timer);};},[active,extent,rainOn,period,refresh]);
 useEffect(()=>{if(!active||!extent||!stationsOn)return;const c=new AbortController();if(stationScope.current!==extent){setStations(undefined);stationScope.current=extent;}let working=false;async function load(){if(working||document.visibilityState==='hidden')return;working=true;setStationBusy(true);try{const r=await collectionFetch('/api/weather-map?'+new URLSearchParams({kind:'stations',bbox:extent}),{signal:c.signal});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Stations unavailable');if(!c.signal.aborted)setStations(d.stations);}catch(e){if(!c.signal.aborted)setStations(s=>({...s,checkedAt:new Date().toISOString(),nextCheckAt:'',error:(e as Error).message}));}finally{working=false;if(!c.signal.aborted)setStationBusy(false);}}const debounce=setTimeout(load,800),timer=setInterval(load,600000);return()=>{c.abort();clearTimeout(debounce);clearInterval(timer);};},[active,extent,stationsOn,refresh]);
 useEffect(()=>{if(!map||!L||!active||!rainOn||!rain?.data)return;const pane='weather-rainfall';if(!map.getPane(pane))map.createPane(pane);map.getPane(pane).style.zIndex='340';map.getPane(pane).style.pointerEvents='none';setImageError(false);setImageBusy(true);const layer=L.imageOverlay(rain.data.url,rain.data.bounds,{pane,opacity,interactive:false,attribution:'Rainfall estimates © NOAA/NWS'});rainLayer.current=layer;layer.on('load',()=>setImageBusy(false));layer.on('error',()=>{setImageError(true);setImageBusy(false);});layer.addTo(map);return()=>{layer.remove();layer.off();rainLayer.current=null;};},[map,L,active,rainOn,rain]);
 useEffect(()=>{rainLayer.current?.setOpacity(opacity);},[opacity]);
 useEffect(()=>{if(!map||!L||!active||!stationsOn||!stations?.data)return;const group=L.layerGroup().addTo(map);for(const s of stations.data.rows){const icon=document.createElement('span');icon.className='weather-station-pin';if(stationStale(s,clock))icon.classList.add('weather-station-old');const text=document.createElement('span');text.textContent=s.temperatureF===undefined?'—':Math.round(s.temperatureF)+'°';icon.innerHTML='<svg width="16" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M9 14V5a3 3 0 0 1 6 0v9a5 5 0 1 1-6 0M12 9v9"/></svg>';icon.append(text);const label=document.createElement('span');label.textContent=`${s.id} · ${s.name}\n${number(s.temperatureF,'°F')} · wind ${wind(s)}\nObserved ${date(s.observedAt)}${stationStale(s,clock)?' · stale / date unknown':''}`;L.marker([s.lat,s.lng],{icon:L.divIcon({className:'weather-station-marker',html:icon,iconSize:[58,30],iconAnchor:[29,15]}),interactive:!mode,bubblingMouseEvents:false,title:'Weather station '+s.id,alt:'Weather station '+s.id}).addTo(group).bindTooltip(label).on('click',()=>{if(!mode){setSelected(s.id);openControls(true);}});}return()=>{group.clearLayers();group.remove();};},[map,L,active,stationsOn,stations,clock,mode]);
 const shown=stationsOn&&stations?.data?.rows.find(s=>s.id===selected),oldRain=!!rain&&(!!rain.error||!!rain.fetchedAt&&clock-Date.parse(rain.fetchedAt)>1800000),oldStations=!!stations&&(!!stations.error||!!stations.fetchedAt&&clock-Date.parse(stations.fetchedAt)>1200000);
 useEffect(()=>{if(shown)detail.current?.scrollIntoView({block:'nearest'});},[shown&&shown.id]);
 return <><label className="weather-toggle"><input type="checkbox" checked={rainOn} onChange={e=>setRainOn(e.target.checked)}/>Rainfall accumulation</label><label className="weather-toggle"><input type="checkbox" checked={stationsOn} onChange={e=>setStationsOn(e.target.checked)}/>Weather station observations</label>
 {rainOn&&<section><strong>Estimated rainfall · inches</strong><label>Accumulation period<select aria-label="Rainfall accumulation period" value={period} onChange={e=>setPeriod(e.target.value)}>{rainPeriods.map(p=><option key={p.key} value={p.key}>{p.name}</option>)}</select></label><p aria-live="polite">{rainBusy?'Loading rainfall estimate…':rain?.error||''}{rain?.cacheWarning}</p>{rain?.data&&<><small>Metadata retrieved {date(rain.fetchedAt)}{oldRain?' · stale snapshot':''}</small>{rain.data.references.map((r,i)=><small key={i}>Reference time {date(r.referenceAt)} · ingested {date(r.ingestedAt)}</small>)}{rainSourceOld(rain.data,clock)&&<p className="help">Source reference time is older than expected or unknown; verify the NOAA product.</p>}{rain.data.warning&&<p className="help">{rain.data.warning}</p>}<label>Rainfall opacity · {Math.round(opacity*100)}%<input aria-label="Rainfall opacity" type="range" min=".1" max=".9" step=".05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><p className="help">{imageError?'Rainfall image failed to load. Refresh to retry.':imageBusy?'Loading rainfall image…':'Rainfall image loaded.'}</p><details><summary>Rainfall legend · inches</summary><div className="rainfall-legend">{rain.data.legend.map((l,i)=><div key={i}><img src={l.image} alt="" width="20" height="20"/><span>{l.label}</span></div>)}</div></details></>}<p className="help">NOAA radar/gauge/satellite estimates on roughly 4 km cells. Multi-day periods use daily analyses ending at 12:00 UTC; hourly products update hourly. These are rainfall estimates, not flood depths or road conditions. Blank imagery may mean missing coverage. Images load directly from NOAA; reference times are from the last metadata check.</p><a href="https://water.noaa.gov/about/precipitation-data-access" target="_blank" rel="noreferrer">NOAA precipitation data</a></section>}
 {stationsOn&&<section><strong>Station observations · °F / mph</strong><p aria-live="polite">{stationBusy?'Checking weather stations…':stations?.error||''}{stations?.cacheWarning}</p>{stations?.data&&<><small>{stations.data.rows.length} stations in view · retrieved {date(stations.fetchedAt)}{oldStations?' · stale snapshot':''}</small>{stations.data.partial&&<p className="help">Station response is capped or contains malformed reports; some observations may be missing.</p>}<div className="weather-station-list">{stations.data.rows.map(s=><button key={s.id} onClick={()=>{setSelected(s.id);openControls(true);map?.panTo([s.lat,s.lng]);}}>{s.id} · {number(s.temperatureF,'°F')}<small>Observed {date(s.observedAt)}{stationStale(s,clock)?' · stale / unknown date':''}</small></button>)}</div></>}<p className="help">NOAA airport METAR reports; coverage varies. Stations are not readings at your house. Pins older than two hours or without usable observation dates are marked stale. Missing gusts mean “not supplied”, not zero.</p><a href="https://aviationweather.gov/data/api/" target="_blank" rel="noreferrer">NOAA Aviation Weather Center</a>{shown&&<article ref={detail} className="weather-alert-detail"><strong>{shown.id} · {shown.name}</strong><small>Observed {date(shown.observedAt)}{stationStale(shown,clock)?' · stale / unknown date':''}</small><small>Received by source {date(shown.receivedAt)}</small><dl className="report-details"><dt>Temperature</dt><dd>{number(shown.temperatureF,'°F')}</dd><dt>Dew point</dt><dd>{number(shown.dewpointF,'°F')}</dd><dt>Relative humidity</dt><dd>{shown.humidityEstimate===undefined?'Not supplied':shown.humidityEstimate+'% · estimated from temperature/dew point'}</dd><dt>Wind</dt><dd>{wind(shown)}</dd><dt>Gust</dt><dd>{number(shown.gustMph,' mph')}</dd></dl><p>{shown.raw}</p><a href={shown.url} target="_blank" rel="noreferrer">Original station report</a><button onClick={()=>setSelected(null)}>Close station details</button></article>}</section>}
 </>;
}
