import {briefingSchema,renderBriefing} from '../../../lib/briefing';
import {storage} from '../../../lib/storage';
const headers={'Cache-Control':'no-store'};
export async function GET(request:Request){
 try{const q=new URL(request.url).searchParams,id=q.get('id');if(id){if(!/^[\da-f-]{36}$/i.test(id))return Response.json({error:'Invalid report ID.'},{status:400});const row=await storage().prepare('SELECT snapshot FROM briefings WHERE id=?').bind(id).first<{snapshot:string}>();if(!row)return Response.json({error:'Archived briefing not found.'},{status:404});const briefing=briefingSchema.parse(JSON.parse(row.snapshot));if(q.get('download')==='1')return new Response(renderBriefing(briefing),{headers:{...headers,'Content-Type':'text/html; charset=utf-8','Content-Disposition':`attachment; filename="area-study-${briefing.generatedAt.slice(0,10)}-${briefing.id.slice(0,8)}.html"`,'X-Content-Type-Options':'nosniff'}});return Response.json({briefing},{headers});}
 const result=await storage().prepare('SELECT id,title,created_at AS createdAt,scope FROM briefings ORDER BY created_at DESC,id DESC LIMIT 30').all();return Response.json({reports:result.results},{headers});
 }catch{ return Response.json({error:'Briefing archive is unavailable. You can still generate, print and download a briefing.'},{status:503});}
}
export async function POST(request:Request){
 try{const body=await request.text();if(new TextEncoder().encode(body).length>2000000)return Response.json({error:'Briefing exceeds the 2 MB archive limit. Generate one location at a time; HTML download remains available.'},{status:413});let parsed:unknown;try{parsed=JSON.parse(body);}catch{return Response.json({error:'Invalid briefing JSON.'},{status:400});}const result=briefingSchema.safeParse(parsed);if(!result.success)return Response.json({error:'Briefing snapshot is invalid. Generate a new briefing before archiving.'},{status:400});const b=result.data,content=JSON.stringify(b),db=storage(),prior=await db.prepare('SELECT snapshot FROM briefings WHERE id=?').bind(b.id).first<{snapshot:string}>();if(prior)return prior.snapshot===content?Response.json({id:b.id},{headers}):Response.json({error:'An archived report cannot be overwritten. Generate a new version.'},{status:409});
 const r=await db.prepare('INSERT INTO briefings (id,title,created_at,scope,snapshot) SELECT ?,?,?,?,? WHERE (SELECT COUNT(*) FROM briefings)<30 ON CONFLICT(id) DO NOTHING').bind(b.id,b.title,b.generatedAt,b.scope,content).run();if(!r.meta.changes){const existing=await db.prepare('SELECT snapshot FROM briefings WHERE id=?').bind(b.id).first<{snapshot:string}>();return existing?.snapshot===content?Response.json({id:b.id},{headers}):Response.json({error:existing?'An archived report cannot be overwritten.':'Archive is full (30 reports). Download your dated copies; you can still generate and print briefings.'},{status:409});}return Response.json({id:b.id},{status:201,headers});
 }catch{return Response.json({error:'Briefing could not be archived. The preview remains available to print or download.'},{status:503});}
}
