import {z} from 'zod';
import {locationContextSchema} from './study-schema';
import {routesSchema} from './route-schema';
import type {Portfolio} from './locations';
import {areaSqMiles,type Point} from './geo';
import {routeMiles} from './routes';
import {providerNames} from './lifelines';
import type {Evidence} from './collection';
const reportLocation=locationContextSchema.extend({id:z.string().min(1).max(100),name:z.string().min(1).max(160),kind:z.string().max(100)});
export const briefingSchema=z.object({formatVersion:z.literal(1),id:z.string().uuid(),title:z.string().trim().min(1).max(160),generatedAt:z.string().datetime(),scope:z.enum(['Active location','Whole study']),studySaved:z.boolean(),locations:z.array(reportLocation).min(1).max(21),routes:routesSchema,routeLabels:z.record(z.string().max(160)),coverage:z.array(z.object({name:z.string().max(200),status:z.string().max(2000)})).max(40),coverageLocation:z.string().max(160)});
export type Briefing=z.infer<typeof briefingSchema>;
export function makeBriefing(p:Portfolio,title:string,all=false,coverage:Record<string,string>={},studySaved=true):Briefing{
 const contexts=[{...p,id:'home',name:'Home',kind:'Home'},...p.locations];const selected=all?contexts:contexts.filter(c=>c.id===p.activeLocationId),ids=new Set(selected.map(c=>c.id)),linkedRoutes=new Set(selected.flatMap(c=>c.scenarios.flatMap(s=>s.routeIds)));
 const routes=p.routes.filter(r=>all||linkedRoutes.has(r.id)||ids.has(r.fromLocationId||'')||ids.has(r.toLocationId||''));
 // Unassigned manual routes cannot be attributed to a location; include them only in Whole study.
 const routeLabels=Object.fromEntries(contexts.filter(c=>routes.some(r=>r.fromLocationId===c.id||r.toLocationId===c.id)).map(c=>[c.id,c.name]));
 return briefingSchema.parse({formatVersion:1,id:crypto.randomUUID(),title:title.trim()||'Area study briefing',generatedAt:new Date().toISOString(),scope:all?'Whole study':'Active location',studySaved,locations:selected,routes,routeLabels,coverage:Object.entries(coverage).map(([name,status])=>({name,status})),coverageLocation:contexts.find(c=>c.id===p.activeLocationId)?.name||'Active location'});
}
export const escapeHtml=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const h=escapeHtml;
const prose=(v:unknown)=>`<p>${h(typeof v==='string'&&v.trim()?v:'Not documented.')}</p>`;
function safeUrl(v:string){try{const u=new URL(v);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.toString():'';}catch{return '';}}
const link=(v:string,label='Original source')=>safeUrl(v)?`<a href="${h(safeUrl(v))}" target="_blank" rel="noreferrer">${h(label)}</a>`:'Source URL unavailable.';
function meta(values:Record<string,unknown>){return `<dl>${Object.entries(values).map(([k,v])=>`<div><dt>${h(k)}</dt><dd>${h(v===undefined||v===null||v===''?'Not supplied':v)}</dd></div>`).join('')}</dl>`;}
function table(headers:string[],rows:unknown[][]){return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(v=>`<th>${h(v)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${h(v===undefined||v===null||v===''?'Not supplied':v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:prose('None documented.');}
function evidence(e:Evidence){return `<article><h4>${h(e.stance)} · ${h(e.title)}</h4>${meta({'Source':e.source,'Source date':e.date,'Captured at':e.capturedAt,'Provenance':e.provenance,'Record ID':e.recordId})}${prose(e.detail)}${link(e.url)}</article>`;}
const roleColor={Primary:'#08766b',Alternate:'#6b4aa0',Contingency:'#b46b15',Emergency:'#b54242'};
export function briefingMap(c:Briefing['locations'][number],routes:Briefing['routes']){
 const points:Point[]=[...(c.home?[c.home.point]:[]),...c.areas.aor,...c.areas.aoi,...c.nais.flatMap(n=>n.points),...routes.flatMap(r=>r.points)];if(!points.length)return prose('No mapped locations, boundaries or assigned routes.');
 let south=90,north=-90,west=180,east=-180;for(const p of points){south=Math.min(south,p[0]);north=Math.max(north,p[0]);west=Math.min(west,p[1]);east=Math.max(east,p[1]);}
 const cos=Math.max(.05,Math.cos((south+north)/2*Math.PI/180)),dx=Math.max((east-west)*cos,.002),dy=Math.max(north-south,.002),scale=Math.min(700/dx,340/dy),cx=(east+west)/2,cy=(north+south)/2;
 const xy=(p:Point)=>[(400+(p[1]-cx)*cos*scale).toFixed(2),(205-(p[0]-cy)*scale).toFixed(2)],path=(p:Point[])=>p.map(x=>xy(x).join(',')).join(' ');
 const areas=(['aoi','aor'] as const).filter(k=>c.areas[k].length>=3).map(k=>`<polygon points="${path(c.areas[k])}" fill="${k==='aoi'?'#d6eee8':'#e8def3'}" fill-opacity=".5" stroke="${k==='aoi'?'#08766b':'#6b4aa0'}" stroke-width="2"/>`).join('');
 const lines=routes.map(r=>`<polyline points="${path(r.points)}" fill="none" stroke="${roleColor[r.role]}" stroke-width="2.5" ${r.role==='Primary'?'':'stroke-dasharray="6 4"'}/>`).join('');
 const named=c.nais.map((n,i)=>`${n.kind==='Polygon'?`<polygon points="${path(n.points)}" fill="#f8e7c2" stroke="#a47116" stroke-width="1.5"/>`:''}<circle cx="${xy(n.points[0])[0]}" cy="${xy(n.points[0])[1]}" r="5" fill="#a47116"/><text x="${Number(xy(n.points[0])[0])+8}" y="${Number(xy(n.points[0])[1])-8}">${i+1}</text>`).join('');
 const home=c.home?`<circle cx="${xy(c.home.point)[0]}" cy="${xy(c.home.point)[1]}" r="7" fill="#183b49" stroke="white" stroke-width="2"/>`:'';
 return `<figure><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 420" role="img" aria-label="Schematic study boundaries and saved routes"><rect width="800" height="420" fill="#f4f7f7"/>${areas}${lines}${named}${home}<path d="M760 50 V20 M751 31 L760 20 L769 31" fill="none" stroke="#183b49" stroke-width="2"/><text x="754" y="70">N</text></svg><figcaption>Schematic WGS84 overview · no road basemap. Dark point: location; green: AOI; purple: AOR; numbered amber areas: NAIs. Routes: Primary green, Alternate purple, Contingency amber, Emergency red. Approximate geometry; no current passability is established.</figcaption></figure>`;
}
export function renderBriefing(raw:Briefing):string{
 const b=briefingSchema.parse(raw);const sections:string[]=[];
 for(const c of b.locations){
  const selectedRoutes=b.routes.filter(r=>r.fromLocationId===c.id||r.toLocationId===c.id||c.scenarios.some(s=>s.routeIds.includes(r.id))),questions=c.collection.questions,open=questions.filter(q=>q.status!=='Answered'),today=b.generatedAt.slice(0,10);
  const routeNames=(ids:string[])=>ids.map(id=>{const r=b.routes.find(r=>r.id===id);return r?r.role+' · '+r.name:'Missing route: '+id;}).join('; ');
  const names=(ids:string[],items:{id:string,name:string}[])=>ids.map(id=>items.find(x=>x.id===id)?.name||'Missing linked item: '+id).join('; ');
  sections.push(`<section class="location"><h2>${h(c.name)} · ${h(c.kind)}</h2>${meta({'Address / label':c.home?.address,'Coordinates':c.home?.point.join(', '),'Address source':c.home?.sourceNote,'AOR sq mi':c.areas.aor.length>=3?areaSqMiles(c.areas.aor).toFixed(2):'Not defined','AOI sq mi':c.areas.aoi.length>=3?areaSqMiles(c.areas.aoi).toFixed(2):'Not defined','Electricity provider (user selection)':providerNames[c.utilityProviders.electricity],'Water provider (user selection)':providerNames[c.utilityProviders.water]})}<h3>Study purpose</h3>${prose(c.collection.purpose)}${briefingMap(c,selectedRoutes)}<h3>Key judgments & review priorities</h3>${table(['Question / judgment','Status / confidence','Assessment / review','Remaining uncertainty'],questions.map(q=>[q.question+'\n'+(q.assessment||'No assessment recorded'),q.status+' · '+q.confidence,q.assessedOn+' / '+q.reviewOn,q.assumptions||'Assumptions not documented']))}<p class="caution">${open.length} unanswered questions. ${questions.filter(q=>q.reviewOn&&q.reviewOn<=today).length} question reviews due as of the report date. Narrative findings remain user-written; unsourced statements are not verified conclusions.</p><h3>Named areas</h3>${table(['Map number / area','Kind','Notes'],c.nais.map((n,i)=>[i+1+' · '+n.name,n.kind,n.notes]))}
  <h3>Findings by study section</h3>${Object.entries(c.sections).filter(([,v])=>v.trim()).map(([name,text])=>`<article><h4>${h(name)}</h4>${prose(text)}</article>`).join('')||prose('No narrative findings recorded.')}
  <h3>Questions, evidence & collection gaps</h3>${questions.map(q=>`<article><h4>${h(q.question)}</h4>${meta({'Priority':q.priority,'Status':q.status,'Scope':q.scope,'Relevant location':q.location,'Needed by':q.neededBy,'Assessed on':q.assessedOn,'Review on':q.reviewOn,'Confidence':q.confidence})}<h5>Decision & assessment</h5>${prose(q.decision)}${prose(q.assessment)}<h5>Confidence rationale & assumptions</h5>${prose(q.confidenceReason)}${prose(q.assumptions)}<h5>Collection plan</h5>${prose(q.sourcePlan)}${table(['Requirement / indicator','Source / method','Responsibility','Deadline / review','Status / result'],q.requirements.map(r=>[r.task+'\n'+r.indicator,r.source+'\n'+r.method,r.responsibility,r.neededBy+' / '+r.reviewOn,r.status+'\n'+r.result]))}${q.evidence.map(evidence).join('')||prose('No supporting, conflicting or context evidence captured.')}</article>`).join('')||prose('No collection questions recorded.')}
  <h3>Essential services & alternatives</h3>${c.servicePlans.map(p=>`<article><h4>${h(p.name)} · ${h(p.sector)}</h4>${meta({'Review on':p.reviewOn,'Primary resource':p.primary?.name,'Primary source':p.primary?.source,'Source date':p.primary?.date,'Source updated':p.primary?.updatedDate,'Retrieved':p.primary?.retrievedAt,'Captured':p.primary?.capturedAt})}${p.primary?link(p.primary.url):''}${prose(p.notes)}${table(['Dependency','Failure consequence','Verification','Source / checked date'],p.dependencies.map(d=>[d.name,d.disruption,d.status,d.source+' · '+d.verifiedOn]))}${p.dependencies.map(d=>d.sourceUrl?`<p>${h(d.name)}: ${link(d.sourceUrl)}</p>`:'').join('')}${p.alternatives.map(a=>`<div class="backup"><h5>Backup: ${h(a.name)} · ${h(a.status)}</h5>${meta({'Switch trigger':a.trigger,'Dependencies':a.dependencies,'Constraints':a.constraints,'Verification source':a.source,'Verified on':a.verifiedOn,'Mapped resource':a.resource?.name,'Resource source':a.resource?.source,'Resource date':a.resource?.date,'Resource captured':a.resource?.capturedAt})}${link(a.sourceUrl)} ${a.resource?link(a.resource.url,'Resource source'):''}</div>`).join('')||prose('No backup options documented.')}</article>`).join('')||prose('No essential-service plans recorded.')}
  <h3>Scenarios & contingencies</h3>${c.scenarios.map(s=>`<article><h4>${h(s.title)} · ${h(s.status)}</h4>${meta({'Hazard / scope':s.hazard+' · '+s.scope,'Likelihood / impact':s.likelihood+' / '+s.impact,'Confidence':s.confidence,'Assessed on':s.assessedOn,'Review on':s.reviewOn,'Named areas':names(s.naiIds,c.nais),'Service plans':names(s.servicePlanIds,c.servicePlans),'Routes':routeNames(s.routeIds),'Question links':s.questionIds.map(id=>questions.find(q=>q.id===id)?.question||'Missing question: '+id).join('; '),'Recorded assessment versions':s.history.length})}<h5>Situation & exposure</h5>${prose(s.description)}${prose(s.exposure)}<h5>Assessment rationale, confidence & assumptions</h5>${prose(s.assessmentReason)}${prose(s.confidenceReason)}${prose(s.assumptions)}${s.indicators.map(i=>`<div class="backup"><h5>Indicator: ${h(i.name)} · ${h(i.basis)}</h5>${prose(i.condition)}${meta({'Instruction/source':i.source,'Source date':i.sourceDate,'Evidence':i.evidenceIds.map(id=>s.evidence.find(e=>e.id===id)?.title||'Missing evidence: '+id).join('; ')})}${link(i.sourceUrl)}</div>`).join('')||prose('No warning indicators recorded.')}${table(['Planned action','When / trigger','Responsibility','Constraints'],s.actions.map(a=>[a.action,a.when,a.responsibility,a.constraints]))}${s.evidence.map(evidence).join('')||prose('No scenario evidence captured.')}${table(['Exercise date','Outcome','Unresolved gaps'],s.exercises.map(e=>[e.date,e.outcome,e.gaps]))}</article>`).join('')||prose('No scenarios recorded.')}
  <h3>Local radio frequencies</h3>${table(['Name / service','Receive / input MHz','Mode / tones','Reception check','Source / date'],c.radioPlan.map(r=>[r.name+' / '+r.service,r.receiveMHz+' / '+(r.transmitMHz||'Not supplied'),r.mode+' / '+r.tone,r.verification+' '+r.checkedOn,r.source+' / '+r.sourceDate]))}${c.radioPlan.map(r=>`<article><h4>${h(r.name)}</h4>${link(r.sourceUrl)}${prose(r.notes)}</article>`).join('')}
  <h3>Field observations</h3>${c.notes.map(n=>`<article><h4>${h(n.name)}</h4>${meta({'Source':n.source,'Observation / record date':n.date,'Provenance':n.confidence,'Coordinates':n.lat+', '+n.lng,'Status at capture':n.status})}${prose(n.detail)}${n.url?link(n.url):''}</article>`).join('')||prose('No field observations recorded.')}</section>`);
 }
 const routes=`<section><h2>Route comparison & corridor coverage</h2><p class="caution">Saved road-network estimates exclude live traffic, closures and evacuation restrictions. A corridor search is not a route verification. Unassigned manual routes appear only in Whole study reports unless linked to a selected scenario.</p>${table(['PACE role / route','Endpoints / destination','Geometry distance','Sourced travel estimate','Source / generated date'],b.routes.map(r=>[r.role+' · '+r.name,(b.routeLabels[r.fromLocationId||'']||'Unassigned')+' → '+(b.routeLabels[r.toLocationId||'']||r.destination||'Unassigned'),routeMiles(r.points).toFixed(1)+' traced miles',r.routing?Math.round(r.routing.durationSeconds/60)+' min · '+(r.routing.distanceMetres/1609.344).toFixed(1)+' road miles':'Not supplied',r.routing?r.routing.provider+' · '+r.routing.generatedAt:'Manual geometry']))}${b.routes.map(r=>`<article><h3>${h(r.role)} · ${h(r.name)}</h3>${prose(r.notes)}${r.routing?link(r.routing.sourceUrl,'Routing provider'):''}${table(['Mapped feature','Type','Coordinates'],r.marks.map(m=>[m.name,m.kind,m.point.join(', ')]))}${r.corridor?`${meta({'Corridor collected':r.corridor.collectedAt,'Width each side':r.corridor.width+' m','Records at collection':r.corridor.count})}${table(['Source','Completed / total sections','Stale / unsupported / failed','Warnings'],r.corridor.sources.map(s=>[s.name,s.complete+' / '+s.total,s.stale+' / '+s.unsupported+' / '+s.failed,s.warnings.join(' ')]))}`:prose('No saved corridor collection summary. Travel constraints remain unverified.')}</article>`).join('')}</section>`;
 const coverage=`<section><h2>Source coverage at generation</h2><p>Session source statuses below describe ${h(b.coverageLocation)} only. Other selected locations are not inferred to have the same coverage. Only saved notes and captured evidence are included as records; uncaptured live map layers and weather cards are not added as findings.</p>${table(['Source','Session status'],b.coverage.map(c=>[c.name,c.status]))}<p>Query completion does not establish agency coverage or absence of hazards. Missing dates remain unknown. Source publication, observation, retrieval, assessment and report-generation times are distinct. External URLs may change; this report preserves captured text and provenance, not complete source documents.</p></section>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"><title>${h(b.title)}</title><style>${briefingCss}</style></head><body><header><span class="kicker">AREA STUDY / DATED BRIEFING</span><h1>${h(b.title)}</h1>${meta({'Generated at (UTC)':b.generatedAt,'Report ID':b.id,'Scope':b.scope,'Locations':b.locations.map(c=>c.name).join(', '),'Input state':b.studySaved?'Study marked saved at generation':'Includes unsaved on-screen edits'})}<p class="caution">Private study information · addresses and planning details are included. This is a fixed planning snapshot; it does not certify current conditions or replace official instructions.</p></header><nav><strong>Contents</strong><p>${b.locations.map(c=>h(c.name)).join(' · ')} · Route comparison · Source coverage</p></nav>${sections.join('')}${routes}${coverage}<footer>Generated from user-authored study material and captured sources. No automatic summary rewrites the user’s judgments. Keep this dated copy for comparison; generate a new briefing after reviewing changes.</footer></body></html>`;
}
const briefingCss=`@page{size:letter;margin:0.65in}*{box-sizing:border-box}body{font:14px/1.55 system-ui,Arial,sans-serif;color:#20343e;background:#fff;margin:0;padding:36px;max-width:1050px;margin-inline:auto}h1{font-size:30px;line-height:1.2;margin:12px 0 20px}h2{font-size:23px;padding-bottom:8px;border-bottom:2px solid #19786e;margin:30px 0 16px}h3{font-size:18px;margin:24px 0 12px}h4{font-size:16px;margin:0 0 12px}h5{font-size:14px;margin:16px 0 8px}.kicker{letter-spacing:2px;font-size:11px;font-weight:700;color:#19786e}p{white-space:pre-wrap;overflow-wrap:anywhere;margin:10px 0}article{border:1px solid #d5dfe2;border-radius:6px;padding:16px;margin:14px 0}article article{border-left:3px solid #829ba7;margin:12px 0}.backup{padding:10px 14px;background:#f5f7f8;margin:10px 0}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px 24px;font-size:12px;margin:16px 0}dl>div{min-width:0}dt{color:#617580}dd{margin:2px 0 0;white-space:pre-wrap;overflow-wrap:anywhere}a{color:#13695f;overflow-wrap:anywhere}table{border-collapse:collapse;width:100%;font-size:12px;margin:14px 0;table-layout:fixed}th,td{padding:9px;text-align:left;vertical-align:top;border:1px solid #d5dfe2;white-space:pre-wrap;overflow-wrap:anywhere}th{background:#eef4f3}.caution{background:#fff7e6;border-left:3px solid #b58a2e;padding:10px 14px;font-size:12px}figure{margin:22px 0}svg{display:block;width:100%;height:auto;max-height:420px;border:1px solid #d5dfe2}svg text{font:14px system-ui;fill:#20343e}figcaption,footer{font-size:11px;color:#617580;margin-top:8px}nav{border-block:1px solid #d5dfe2;padding:14px 0}footer{border-top:1px solid #d5dfe2;padding-top:16px}@media print{body{padding:0;max-width:none;font-size:11px}h2,h3,h4,h5{break-after:avoid}tr,dl>div{break-inside:avoid}thead{display:table-header-group}figure{break-inside:avoid}a{color:inherit;text-decoration:underline}section.location+section.location{break-before:page}header{break-after:page}article{box-decoration-break:clone}svg{max-height:3.8in}.caution,.backup,th{-webkit-print-color-adjust:exact;print-color-adjust:exact}}@media(max-width:600px){body{padding:18px}dl{grid-template-columns:1fr}table{font-size:11px}}`;
