import {plainText} from './community';
import type {ConditionSnapshot} from './conditions';
export type CivicItem={id:string,sourceId:string,title:string,kind:'Meeting'|'Project notice',date:string|null,time:string|null,location:string|null,status:string,url:string,agendaUrl?:string,published:string|null,update:string|null,summary?:string,dateBasis?:string};
export type CivicData={items:CivicItem[],warnings:string[]};
export type CivicSnapshot=ConditionSnapshot<CivicData>&{sourceId:string};
const manorAgendas='https://meetings.municode.com/PublishPage/index?cid=MANORTX&p=1&ppid=e12611c2-0cb3-4b57-8637-b359e513146c';
export const civicSources=[
 {id:'manor',name:'Manor council & commissions',url:'https://www.manortx.gov/RSSFeed.aspx?ModID=58&CID=City-Council-26',home:'https://www.manortx.gov/Calendar.aspx',agenda:manorAgendas,notice:'Published calendar window only; confirm the latest agenda before attending.'},
 {id:'travis',name:'Travis County Commissioners Court',url:'https://traviscotx.api.civicclerk.com/v1/',home:'https://traviscotx.portal.civicclerk.com/',agenda:'https://traviscotx.portal.civicclerk.com/',notice:'Rolling window: 90 days back and 180 days forward. Times follow the official portal’s Central clock; verify the agenda.'},
 {id:'isd',name:'Manor ISD board',url:'https://www.manorisd.net/about-us/board-of-trustees/agendasboardbook',home:'https://www.manorisd.net/about-us/board-of-trustees/meeting-notices',agenda:'https://www.manorisd.net/about-us/board-of-trustees/agendasboardbook',notice:'Dated meeting archive. The separate notice schedule omits years, so it is not used to generate future meetings.'},
 {id:'mud',name:'Wilbarger Creek MUD 1',url:'https://wilbargercreekmud1.org/board.html',home:'https://crossroadsus.com/districts/wilbarger-creek-municipal-utility-district-001',agenda:'https://abaustin.sharefile.com/d-sd538f44a2d14aa28',notice:'Legacy district website is scheduled to close in November 2026. Use current district records for notices.'},
 {id:'roads',name:'Manor road & project notices',url:'https://www.manortx.gov/RSSFeed.aspx?ModID=63&CID=All-0',home:'https://www.manortx.gov/AlertCenter.aspx',agenda:'https://www.manortx.gov/AlertCenter.aspx',notice:'City alert feed filtered for road/project titles. Notice publication is not a project start or completion date; other agencies are not connected.'}
];
civicSources.push(
 {id:'wimberley',name:'Wimberley council & commissions',url:'https://wimberleytx.api.civicclerk.com/v1/',home:'https://wimberleytx.portal.civicclerk.com/',agenda:'https://wimberleytx.portal.civicclerk.com/',notice:'Official current portal; 90 days back and 180 days forward. Times follow the portal clock; verify the latest agenda.'},
 {id:'hays-court',name:'Hays County Commissioners Court',url:'https://public.destinyhosted.com/agenda_publish.cfm?id=42972',home:'https://public.destinyhosted.com/agenda_publish.cfm?id=42972',agenda:'https://public.destinyhosted.com/agenda_publish.cfm?id=42972',notice:'Dates listed in the official agenda index only. Unpublished agendas and missing meeting times remain explicit; confirm before attending.'}
);
export function civicSourcesForCounty(fips:string){return fips==='48209'?civicSources.filter(s=>['wimberley','hays-court'].includes(s.id)):fips==='48453'?civicSources.filter(s=>!['wimberley','hays-court'].includes(s.id)):[];}
export function civicText(s:string){return plainText(plainText(s)).slice(0,1400);}
function field(s:string,tag:string){return civicText(s.match(new RegExp('<'+tag+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+tag+'>','i'))?.[1]||'');}
export function explicitDay(s:string){const m=s.match(/\b(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{1,2}),?\s+(20\d{2})\b/i);if(!m)return null;const month=['january','february','march','april','may','june','july','august','september','october','november','december'].indexOf(m[1].toLowerCase())+1;return validDay(`${m[3]}-${String(month).padStart(2,'0')}-${m[2].padStart(2,'0')}`);}
function validDay(s:string){if(!/^20\d{2}-\d{2}-\d{2}$/.test(s))return null;const d=new Date(s+'T12:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s?s:null;}
function stamp(s:unknown){return typeof s==='string'&&s.trim()&&Number.isFinite(Date.parse(s))?new Date(s).toISOString():null;}
export function civicStatus(title:string){return /cancel(?:led|ed|lation)/i.test(title)?'Cancelled':/postpon/i.test(title)?'Postponed':/reschedul/i.test(title)?'Rescheduled':'Published';}
function officialLink(raw:string,base:string){const u=new URL(raw,base);if(u.protocol!=='https:'||u.origin!==new URL(base).origin||u.username||u.password)throw Error('Unexpected official item link');return u.toString();}
function rssItems(xml:string){if(xml.length>2000000||!/\<rss[\s>]/i.test(xml)||!/<\/rss>\s*$/i.test(xml)||/<!DOCTYPE|<!ENTITY/i.test(xml))throw Error('Official RSS response incomplete or unsupported');const rows=[...xml.matchAll(/<item(?:\s[^>]*)?>([\s\S]*?)<\/item>/gi)];if(rows.length!==[...xml.matchAll(/<item[\s>]/gi)].length)throw Error('Incomplete event records');if(rows.length>200)throw Error('Official feed exceeds collection limit');return rows.map(x=>x[1]);}
export function parseManor(xml:string,roads=false):CivicData{const items:CivicItem[]=[];for(const row of rssItems(xml)){const title=field(row,'title');if(!title)throw Error('Meeting title unavailable');if(roads&&!/road|traffic|construction|closure|project|street|bridge/i.test(title))continue;const url=officialLink(field(row,'link'),'https://www.manortx.gov/');items.push({id:url,sourceId:roads?'roads':'manor',title,kind:roads?'Project notice':'Meeting',date:roads?null:explicitDay(field(row,'calendarEvent:EventDates')),time:roads?null:field(row,'calendarEvent:EventTimes')||null,location:field(row,'calendarEvent:Location')||null,status:roads?'Notice':civicStatus(title),url,...(!roads?{agendaUrl:manorAgendas}:{}),published:stamp(field(row,'pubDate')),update:null,summary:roads?field(row,'description'):undefined});}return {items,warnings:roads?['Project dates are not supplied as structured events. Review the original for scope and completion updates.']:['Feed window is controlled by the city; missing entries do not establish that a meeting was cancelled.']};}
function anchors(html:string){if(html.length>2000000||!/<\/html>/i.test(html))throw Error('Official page incomplete');const clean=html.replace(/<!--[\s\S]*?-->/g,'');return [...clean.matchAll(/<a\b([^>]*)>([\s\S]*?)<\/a>/gi)].map(m=>({attributes:m[1],title:civicText(m[2]),href:m[1].match(/\bhref\s*=\s*["']([^"']+)["']/i)?.[1]||''}));}
export function parseIsd(html:string):CivicData{if(!/Agendas\/Boardbook/i.test(civicText(html)))throw Error('School meeting archive unavailable');const items:CivicItem[]=[];for(const a of anchors(html)){if(!/fsPostLink/i.test(a.attributes)||!/meeting|workshop/i.test(a.title))continue;const date=explicitDay(a.title);if(!date)continue;items.push({id:'isd:'+date+':'+a.title,sourceId:'isd',title:a.title,kind:'Meeting',date,time:null,location:null,status:civicStatus(a.title),url:civicSources[2].url,published:null,update:null,dateBasis:'Date from the district meeting archive; open the listed meeting to access its BoardBook agenda.'});}if(!items.length)throw Error('No dated school meeting records found');const unique=[...new Map(items.map(i=>[i.id,i])).values()].sort((a,b)=>b.date!.localeCompare(a.date!));return {items:unique.slice(0,120),warnings:['Archive titles supply dates, but individual times, venues, publication and revision dates are not supplied. Future schedules with no year are excluded.',...(unique.length>120?['Archive limited to the latest 120 dated records.']:[])]};}
export function parseMud(html:string):CivicData{if(!/Wilbarger Creek MUD #?1/i.test(civicText(html)))throw Error('District identity unavailable');const items:CivicItem[]=[];for(const a of anchors(html)){const m=a.href.match(/\/WC1_AGENDA_(\d{2})(\d{2})(\d{2})\.pdf$/i);if(!m)continue;const date=validDay(`20${m[3]}-${m[1]}-${m[2]}`);if(!date)continue;const url=officialLink(a.href,'https://wilbargercreekmud1.org/');items.push({id:url,sourceId:'mud',title:'Wilbarger Creek MUD 1 board agenda',kind:'Meeting',date,time:null,location:null,status:'Published',url,agendaUrl:url,published:null,update:null,dateBasis:'Date encoded in the district agenda filename; verify meeting details in the PDF.'});}return {items,warnings:items.length?['Agenda filename dates only. Times, venues and cancellation status require the original notice.']:['No dated agendas on the legacy board page. Current meeting dates are a collection gap; open District records. Meetings are not generated from the usual recurrence.']};}
type CountyRow={id:number,categoryName:string,eventName:string,startDateTime:string,eventNotice?:string,eventLocation?:{address1?:string|null,address2?:string|null,city?:string|null,state?:string|null,zipCode?:string|null},publishedFiles?:{type:string,publishOn?:string}[]};
type CountyPayload={items:CountyRow[],hasMore:boolean};
export function parseTravis(input:unknown):CivicData{const data=input as CountyPayload|null;if(!Array.isArray(data?.items)||typeof data.hasMore!=='boolean'||data.items.length>200)throw Error('County calendar response unavailable or oversized');const items:CivicItem[]=data.items.filter((r:CountyRow)=>r.categoryName==='Commissioners Court').map((r:CountyRow)=>{if(!Number.isInteger(r.id)||typeof r.eventName!=='string'||!validDay(String(r.startDateTime).slice(0,10)))throw Error('Invalid county meeting record');const agenda=Array.isArray(r.publishedFiles)?r.publishedFiles.find((f:{type:string,publishOn?:string})=>f.type==='Agenda'):undefined;const loc=r.eventLocation;return {id:'travis:'+r.id,sourceId:'travis',title:r.eventName,kind:'Meeting',date:validDay(r.startDateTime.slice(0,10)),time:/T\d{2}:\d{2}/.test(r.startDateTime)?r.startDateTime.slice(11,16)+' Central · portal clock':null,location:loc?[loc.address1,loc.address2,loc.city,loc.state,loc.zipCode].filter(Boolean).join(', ')||null:null,status:civicStatus(r.eventName+' '+(r.eventNotice||'')),url:`https://traviscotx.portal.civicclerk.com/event/${r.id}`,agendaUrl:agenda?`https://traviscotx.portal.civicclerk.com/event/${r.id}`:undefined,published:null,update:null,summary:civicText(r.eventNotice||''),dateBasis:agenda?.publishOn?'Agenda posting time as supplied: '+agenda.publishOn+' (source clock). This is not the meeting time or a confirmed revision.':undefined};});return {items,warnings:data.hasMore?['County response is incomplete: more events exist beyond the returned page. Open the official calendar for the full window.']:[]};}
export function centralToday(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);}
export function civicBucket(item:CivicItem,today=centralToday()){return !item.date?'undated':item.date<today?'past':'upcoming';}
export async function civicFetch(url:string,fetcher:typeof fetch=fetch){let target=url;for(let n=0;n<3;n++){const r=await fetcher(target,{redirect:'manual',signal:AbortSignal.timeout(20000),headers:{Accept:'application/json,application/rss+xml,text/html','User-Agent':'ManorAreaStudy/1.0 (public civic calendars)'}});if([301,302,303,307,308].includes(r.status)){const location=r.headers.get('location');if(!location)throw Error('Official redirect unavailable');target=officialLink(location,target);continue;}if(!r.ok)throw Error('Official source returned HTTP '+r.status);const body=await r.text();if(body.length>2000000)throw Error('Official response exceeds collection limit');return body;}throw Error('Too many official redirects');}
export async function collectCivic(sourceId:string,fetcher:typeof fetch=fetch,now=new Date()):Promise<CivicData>{const s=civicSources.find(s=>s.id===sourceId);if(!s)throw Error('Unknown civic source');if(sourceId==='wimberley'){const from=new Date(now.getTime()-90*86400000).toISOString().slice(0,10),to=new Date(now.getTime()+180*86400000).toISOString().slice(0,10),u=new URL(s.url+'Events');u.search=new URLSearchParams({'$filter':`startDateTime ge ${from} and startDateTime le ${to}`,'$orderby':'startDateTime desc','$top':'200'}).toString();const rows:CountyRow[]=[],seen=new Set<number>();let target:string|null=u.toString();for(let page=0;page<14&&target;page++){const d=JSON.parse(await civicFetch(target,fetcher));parseWimberley(d);for(const r of d.value){if(seen.has(r.id))throw Error('Wimberley pagination repeated records');seen.add(r.id);rows.push(r);}if(rows.length>200){rows.length=200;target='capped';break;}target=d['@odata.nextLink']?officialLink(d['@odata.nextLink'],s.url):null;if(target&&(!new URL(target).pathname.startsWith('/v1/Events')||target.includes('capped')))throw Error('Unexpected calendar continuation');}return parseWimberley({value:rows,...target?{'@odata.nextLink':'More records remain'}:{}});}if(sourceId==='hays-court')return parseHaysCourt(await civicFetch(s.url,fetcher));if(sourceId==='travis'){const from=new Date(now.getTime()-90*86400000).toISOString().slice(0,10),to=new Date(now.getTime()+180*86400000).toISOString().slice(0,10);const rows:CountyRow[]=[];let cursor=0,hasMore=true;for(let page=0;page<12&&hasMore;page++){const data=JSON.parse(await civicFetch(s.url+`Events/GetEventsList(fromDate='${from}',toDate='${to}',categoryIds=[],skip=0,sortDescending=false,cursorId=${cursor})`,fetcher));parseTravis(data);if(data.items.some((r:CountyRow)=>rows.some(old=>old.id===r.id)))throw Error('County pagination repeated records');rows.push(...data.items);hasMore=data.hasMore;if(rows.length>200){rows.length=200;hasMore=true;break;}if(hasMore){const next=data.items.at(-1)?.id;if(!Number.isInteger(next)||next===cursor)throw Error('County pagination cursor unavailable');cursor=next;}}return parseTravis({items:rows,hasMore});}const text=await civicFetch(s.url,fetcher);return sourceId==='manor'?parseManor(text):sourceId==='roads'?parseManor(text,true):sourceId==='isd'?parseIsd(text):parseMud(text);}
export function civicNote(item:CivicItem){return [`Source: ${item.url}`,`Event date: ${item.date||'Not supplied'}`,`Time: ${item.time||'Not supplied'}`,`Venue: ${item.location||'Not supplied'}`,`Source status: ${item.status}`,`Notice published: ${item.published||'Not supplied'}`,`Source update: ${item.update||'Not supplied'}`,item.agendaUrl?'Agenda/portal: '+item.agendaUrl:'',item.dateBasis||'',item.summary||'','Location chosen manually; verify the latest official notice.'].filter(Boolean).join('\n');}

export function parseWimberley(raw:unknown):CivicData{
 const d=raw as {value:CountyRow[],'@odata.nextLink'?:string};if(!Array.isArray(d?.value)||d.value.length>200)throw Error('Wimberley calendar response unavailable');
 const result=parseTravis({items:d.value.map(r=>({...r,categoryName:'Commissioners Court'})),hasMore:!!d['@odata.nextLink']});
 return {items:result.items.map(i=>({...i,id:i.id.replace('travis:','wimberley:'),sourceId:'wimberley',url:i.url.replace('traviscotx.','wimberleytx.'),agendaUrl:i.agendaUrl?.replace('traviscotx.','wimberleytx.')})),warnings:[...result.warnings,'Wimberley portal window only; dates are not generated from recurring schedules.']};
}
export function parseHaysCourt(html:string):CivicData{
 if(html.length>2000000||!/<\/html>/i.test(html)||!html.includes('42972'))throw Error('Hays agenda index unavailable');const items:CivicItem[]=[];
 for(const [,row] of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){const cells=[...row.matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(m=>m[1]);if(cells.length<2||!/Commissioners Court/i.test(civicText(cells[1])))continue;const date=explicitDay(civicText(cells[0]));if(!date)continue;const raw=cells[0].match(/<a\b[^>]*href=["']([^"']+)["']/i)?.[1];const url=raw?officialLink(plainText(raw),'https://public.destinyhosted.com/'):civicSources.find(s=>s.id==='hays-court')!.url;items.push({id:'hays-court:'+date,sourceId:'hays-court',title:'Hays County '+civicText(cells[1]),kind:'Meeting',date,time:null,location:null,status:raw?'Agenda published':'Listed · agenda not published',url,...(raw?{agendaUrl:url}:{}),published:null,update:null,dateBasis:'Explicit date from the official county agenda index. Times, venues and revision dates are not supplied by this index.'});}
 if(!items.length)throw Error('No dated Hays court entries found');return {items,warnings:['Official agenda-index window only; verify the meeting time, venue and latest agenda. No meetings are inferred from recurrence.']};
}
