import {z} from 'zod';

const date=z.string().refine(v=>v===''||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v),'Choose a valid date');
const url=z.string().max(2000).refine(v=>{if(!v)return true;try{return ['https:','http:'].includes(new URL(v).protocol);}catch{return false;}},'Use an http or https source URL');
export const evidenceSchema=z.object({status:z.string().max(200).optional(),id:z.string().min(1).max(100),recordId:z.string().max(100),kind:z.enum(['Note','Source','Link']),title:z.string().min(1).max(300),source:z.string().max(200),url,date:z.string().max(100),capturedAt:z.string().datetime(),detail:z.string().max(2000),stance:z.enum(['Supports','Conflicts','Context']),provenance:z.string().max(100)});
export const requirementSchema=z.object({id:z.string().min(1).max(100),task:z.string().trim().min(1).max(500),indicator:z.string().max(1000),location:z.string().max(300),naiIds:z.array(z.string().min(1).max(100)).max(100),source:z.string().max(1000),method:z.enum(['Public source','Field observation','Other']),responsibility:z.string().max(300),status:z.enum(['Open','In progress','Answered','Blocked','Retired']),neededBy:date,reviewOn:date,result:z.string().max(2000),evidenceIds:z.array(z.string().min(1).max(100)).max(30),createdAt:z.string().datetime()});
export const questionSchema=z.object({requirements:z.array(requirementSchema).max(50).default([]),naiIds:z.array(z.string().min(1).max(100)).max(100).default([]),id:z.string().min(1).max(100),question:z.string().min(1).max(500),decision:z.string().max(2000),priority:z.enum(['High','Normal','Low']),scope:z.enum(['AOR','AOI','Route','Other']),location:z.string().max(300),status:z.enum(['Open','In progress','Answered','Blocked']),neededBy:date,reviewOn:date,sourcePlan:z.string().max(2000),assessment:z.string().max(4000),assumptions:z.string().max(2000),confidence:z.enum(['Unassessed','Low','Moderate','High']),confidenceReason:z.string().max(2000),assessedOn:date,evidence:z.array(evidenceSchema).max(30),createdAt:z.string().datetime()}).superRefine((q,ctx)=>{if(new Set(q.requirements.map(r=>r.id)).size!==q.requirements.length)ctx.addIssue({code:z.ZodIssueCode.custom,path:["requirements"],message:"Duplicate requirement IDs"});const areas=new Set(q.naiIds),evidence=new Set(q.evidence.map(e=>e.id));if(q.requirements.some(r=>r.naiIds.some(id=>!areas.has(id))||r.evidenceIds.some(id=>!evidence.has(id))))ctx.addIssue({code:z.ZodIssueCode.custom,path:["requirements"],message:"A requirement links to an area or evidence outside this question"});});
export const collectionSchema=z.object({purpose:z.string().max(2000),questions:z.array(questionSchema).max(100).refine(q=>new Set(q.map(x=>x.id)).size===q.length,'Duplicate question IDs')}).default({purpose:'',questions:[]});
export type CollectionPlan=z.infer<typeof collectionSchema>;
export type StudyQuestion=z.infer<typeof questionSchema>;
export type Evidence=z.infer<typeof evidenceSchema>;
export type InformationRequirement=z.infer<typeof requirementSchema>;
export type EvidenceRecord={status?:string;id:string,name:string,source:string,url?:string,date?:string,detail?:string,confidence?:string};
export function localDate(now=new Date()){return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;}
export function questionFlags(q:StudyQuestion,today=localDate()){return {overdue:!!q.neededBy&&q.neededBy<today&&q.status!=='Answered',reviewDue:!!q.reviewOn&&q.reviewOn<=today};}
export function newQuestion():StudyQuestion{return {requirements:[],naiIds:[],id:crypto.randomUUID(),question:'New study question',decision:'',priority:'Normal',scope:'AOI',location:'',status:'Open',neededBy:'',reviewOn:'',sourcePlan:'',assessment:'',assumptions:'',confidence:'Unassessed',confidenceReason:'',assessedOn:'',evidence:[],createdAt:new Date().toISOString()};}
export function evidenceSnapshot(r:EvidenceRecord,kind:'Note'|'Source'):Evidence{return {...(r.status?{status:r.status.slice(0,200)}:{}),id:crypto.randomUUID(),recordId:r.id.slice(0,100),kind,title:r.name.slice(0,300),source:r.source.slice(0,200),url:r.url&&/^https?:\/\//i.test(r.url)?r.url.slice(0,2000):'',date:(r.date||'').slice(0,100),capturedAt:new Date().toISOString(),detail:(r.detail||'').slice(0,2000),stance:'Context',provenance:(r.confidence||'Reported by source').slice(0,100)};}
export function newRequirement():InformationRequirement{return {id:crypto.randomUUID(),task:'New information requirement',indicator:'',location:'',naiIds:[],source:'',method:'Public source',responsibility:'',status:'Open',neededBy:'',reviewOn:'',result:'',evidenceIds:[],createdAt:new Date().toISOString()};}
export function requirementFlags(r:InformationRequirement,today=localDate()){return {overdue:r.status!=='Retired'&&r.status!=='Answered'&&!!r.neededBy&&r.neededBy<today,reviewDue:r.status!=='Retired'&&!!r.reviewOn&&r.reviewOn<=today,gap:r.status!=='Retired'&&(r.status==='Blocked'||!r.source.trim()||(!r.location.trim()&&!r.naiIds.length)||!r.neededBy)};}
export function questionNeedsAttention(q:StudyQuestion,today=localDate()){const f=questionFlags(q,today);return f.overdue||f.reviewDue||q.requirements.some(r=>{const g=requirementFlags(r,today);return g.overdue||g.reviewDue||g.gap;});}
export function unlinkQuestionArea(q:StudyQuestion,id:string):StudyQuestion{return {...q,naiIds:q.naiIds.filter(x=>x!==id),requirements:q.requirements.map(r=>({...r,naiIds:r.naiIds.filter(x=>x!==id)}))};}
export function detachEvidence(q:StudyQuestion,id:string):StudyQuestion{return {...q,evidence:q.evidence.filter(e=>e.id!==id),requirements:q.requirements.map(r=>({...r,evidenceIds:r.evidenceIds.filter(x=>x!==id)}))};}
