export type ConditionSnapshot<T=any>={data?:T,fetchedAt?:string,checkedAt:string,nextCheckAt:string,error?:string,cached?:boolean,cacheWarning?:string};
export type WeatherAlert={id:string,event:string,headline:string,severity:string,area:string,sent?:string,onset?:string,expires?:string,ends?:string,description?:string,instruction?:string,url:string};
export type Forecast={updated?:string,periods:{name:string,start:string,end:string,temperature:number,unit:string,wind:string,short:string,detail:string,rain:number|null}[]};
export type DroughtWeek={date:string,county:string,d0:number,d1:number,d2:number,d3:number,d4:number,dsci:number};
export type GridCondition={title:string,note:string,state:string,reserves:number,updated:string};
export type Conditions={forecast?:ConditionSnapshot<Forecast>,alerts?:ConditionSnapshot<WeatherAlert[]>,drought:ConditionSnapshot<DroughtWeek[]>,grid:ConditionSnapshot<GridCondition>};
export const gridUrl='https://www.ercot.com/gridmktinfo/dashboards/gridconditions';
export const droughtUrl='https://droughtmonitor.unl.edu/';
export async function sourceJson(url:string,fetcher:typeof fetch=fetch){const origin=new URL(url).origin;let target=url;for(let attempt=0;attempt<3;attempt++){const r=await fetcher(target,{redirect:'manual',headers:{'User-Agent':'ManorAreaStudy/1.0 (personal weather dashboard)','Accept':'application/geo+json,application/json'},signal:AbortSignal.timeout(15000)});if([301,302,307,308].includes(r.status)){const location=r.headers.get('location');if(!location)throw Error('Source redirect unavailable');const next=new URL(location,target);if(next.origin!==origin||next.username||next.password)throw Error('Source redirected outside its official host');target=next.toString();continue;}if(!r.ok)throw new Error(`Source returned HTTP ${r.status}`);const text=await r.text();if(text.length>2000000)throw new Error('Source response exceeds collection limit');return JSON.parse(text);}throw Error('Source redirected too many times');}
export function parseForecast(data:any):Forecast{const p=data?.properties;if(!Array.isArray(p?.periods)||!p.periods.length)throw Error('Forecast periods unavailable');return {updated:p.updateTime,periods:p.periods.slice(0,14).map((x:any)=>{if(!Number.isFinite(x.temperature)||!Number.isFinite(Date.parse(x.startTime)))throw Error('Invalid forecast period');return {name:String(x.name||'Forecast'),start:x.startTime,end:x.endTime,temperature:x.temperature,unit:x.temperatureUnit,wind:[x.windSpeed,x.windDirection].filter(Boolean).join(' '),short:String(x.shortForecast||''),detail:String(x.detailedForecast||''),rain:Number.isFinite(x.probabilityOfPrecipitation?.value)?x.probabilityOfPrecipitation.value:null};})};}
export function parseAlerts(data:any):WeatherAlert[]{if(!Array.isArray(data?.features))throw Error('Alert feed unavailable');return data.features.slice(0,100).map((f:any)=>{const p=f.properties;if(!p||typeof p.event!=='string')throw Error('Invalid weather alert');return {id:String(f.id||p.id),event:p.event,headline:p.headline||p.event,severity:p.severity||'Unknown',area:p.areaDesc||'Area not supplied',sent:p.sent,onset:p.onset,expires:p.expires,ends:p.ends,description:p.description,instruction:p.instruction,url:'https://www.weather.gov/alerts'};});}
export function liveAlerts(alerts:WeatherAlert[],now=Date.now()){return alerts.filter(a=>{const end=Math.min(...[a.ends,a.expires].filter(x=>x&&Number.isFinite(Date.parse(x))).map(x=>Date.parse(x!)));return end>now;});}
export function parseDrought(rows:any,countyFips='48453'):DroughtWeek[]{if(!Array.isArray(rows)||!rows.length)throw Error('Drought history unavailable');return rows.map((r:any)=>{const v=['d0','d1','d2','d3','d4'].map(k=>r[k]);if(String(r.fips)!==countyFips||r.statisticFormatID!==1||v.some(n=>typeof n!=='number'||n<0||n>100)||v.some((n,i)=>i>0&&n>v[i-1]+.01)||!/^\d{4}-\d{2}-\d{2}/.test(r.mapDate||''))throw Error('Invalid cumulative county drought data');return {date:r.mapDate.slice(0,10),county:String(r.county),d0:v[0],d1:v[1],d2:v[2],d3:v[3],d4:v[4],dsci:v.reduce((s,n)=>s+n,0)};}).sort((a,b)=>a.date.localeCompare(b.date));}
export function parseGrid(data:any):GridCondition{const p=data?.current_condition,reserves=Number(String(p?.prc_value??'').replace(/,/g,''));if(!p||p.prc_value===undefined||p.prc_value===null||p.prc_value===''||!Number.isFinite(p.datetime)||!Number.isFinite(reserves)||typeof p.title!=='string'||!p.title.trim())throw Error('Grid condition unavailable');return {title:p.title,note:String(p.condition_note||''),state:String(p.state||'unknown'),reserves,updated:new Date(p.datetime*1000).toISOString()};}
export async function collectForecast(lat:number,lng:number,fetcher:typeof fetch=fetch){const p=await sourceJson(`https://api.weather.gov/points/${lat},${lng}`,fetcher),url=p.properties?.forecast;if(typeof url!=='string'||!/^https:\/\/api\.weather\.gov\/gridpoints\/[A-Z]{3}\/\d+,\d+\/forecast$/.test(url))throw Error('NWS forecast location unavailable');return parseForecast(await sourceJson(url,fetcher));}
export async function collectAlerts(lat:number,lng:number,fetcher:typeof fetch=fetch){return parseAlerts(await sourceJson(`https://api.weather.gov/alerts/active?point=${lat},${lng}`,fetcher));}
export async function collectDrought(fetcher:typeof fetch=fetch,now=new Date(),countyFips='48453'){const start=new Date(now);start.setUTCFullYear(start.getUTCFullYear()-1);const u=new URL('https://usdmdataservices.unl.edu/api/CountyStatistics/GetDroughtSeverityStatisticsByAreaPercent');u.search=new URLSearchParams({aoi:countyFips,startdate:start.toISOString().slice(0,10),enddate:now.toISOString().slice(0,10),statisticsType:'1'}).toString();return parseDrought(await sourceJson(u.toString(),fetcher),countyFips);}
export async function collectGrid(fetcher:typeof fetch=fetch){return parseGrid(await sourceJson('https://www.ercot.com/api/1/services/read/dashboards/daily-prc.json',fetcher));}
export async function refreshCondition<T>(prior:ConditionSnapshot<T>|undefined,collect:()=>Promise<T>,ttl:number,now=new Date()):Promise<ConditionSnapshot<T>>{if(prior&&Date.parse(prior.nextCheckAt)>now.getTime())return {...prior,cached:true};try{return {data:await collect(),fetchedAt:now.toISOString(),checkedAt:now.toISOString(),nextCheckAt:new Date(now.getTime()+ttl).toISOString(),cached:false};}catch(e){return {data:prior?.data,fetchedAt:prior?.fetchedAt,checkedAt:now.toISOString(),nextCheckAt:new Date(now.getTime()+300000).toISOString(),error:e instanceof Error?e.message:'Source unavailable',cached:!!prior?.data};}}
