import type {Bounds} from './area-cache';
export const crimeSource='https://maps.austintexas.gov/arcgis/rest/services/CrimeViewer_new/APD_Reported_Crimes_new/FeatureServer';
export const crimeGroups=['Homicide','Robbery','Aggravated assault','Burglary','Auto theft','Theft','Arson','Compelling prostitution','Involuntary servitude','Part II crimes'];
export function occurrenceDate(epoch:any,time:any){if(!Number.isFinite(epoch))return undefined;const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(epoch));const part=(k:string)=>parts.find(p=>p.type===k)?.value;const day=`${part('year')}-${part('month')}-${part('day')}`;if(time===null||time===undefined||time==='')return day+'T00:00:00';const n=Number(time),h=Math.floor(n/100),m=n%100;return Number.isInteger(n)&&h>=0&&h<24&&m>=0&&m<60?`${day}T${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:00`:day+'T00:00:00';}
export function crimeRow(f:any,layer:number){const p=f.attributes,g=f.geometry;if(!p||!Number.isFinite(p.OBJECTID)||!Number.isFinite(g?.x)||!Number.isFinite(g?.y)||g.y<29.5||g.y>31||g.x<-98.5||g.x>-96.5)return null;return {id:`apd:${layer}:${p.OBJECTID}`,name:p.CRIME_DESCRIPTION||crimeGroups[layer],lat:g.y,lng:g.x,category:'Crime reports',source:'Austin Police',date:occurrenceDate(p.OCCURRENCE_DATE,p.OCCURRENCE_TIME),updatedDate:Number.isFinite(p.MODIFIED_DATE)?new Date(p.MODIFIED_DATE).toISOString():undefined,url:`${crimeSource}/${layer}`,crime:{group:crimeGroups[layer],mapId:String(p.OBJECTID),block:[p.ADDRESS_BLOCK===null||p.ADDRESS_BLOCK===undefined?'':`${p.ADDRESS_BLOCK} block`,p.STREET_NAME,p.STREET_TYPE].filter(Boolean).join(' '),locationType:p.LOCATION_DESCRIPTION,sector:p.SECTOR,district:p.DISTRICT,attempt:p.ATTEMPT_COMPLETE_FLG==='A'?'Attempted':p.ATTEMPT_COMPLETE_FLG==='C'?'Completed':'Unavailable'}};}
export async function fetchCrime(bbox:Bounds,request:typeof fetch=fetch,now=Date.now()){
 const since=new Date(now-90*86400000).toISOString().slice(0,10),rows:any[]=[],limit=4000*crimeGroups.length;let next=0,complete=true;
 async function worker(){while(next<crimeGroups.length){const layer=next++;for(let offset=0;offset<4000;offset+=1000){const u=new URL(`${crimeSource}/${layer}/query`);u.search=new URLSearchParams({f:'json',where:`OCCURRENCE_DATE >= TIMESTAMP '${since} 00:00:00'`,geometry:[bbox[1],bbox[0],bbox[3],bbox[2]].join(','),geometryType:'esriGeometryEnvelope',inSR:'4326',outSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'OBJECTID,OCCURRENCE_DATE,OCCURRENCE_TIME,ADDRESS_BLOCK,STREET_NAME,STREET_TYPE,SECTOR,DISTRICT,ATTEMPT_COMPLETE_FLG,CRIME_DESCRIPTION,LOCATION_DESCRIPTION,MODIFIED_DATE',returnGeometry:'true',orderByFields:'OCCURRENCE_DATE DESC,OBJECTID ASC',resultRecordCount:'1000',resultOffset:String(offset)}).toString();const r=await request(u,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error(`APD crime map returned HTTP ${r.status}`);const d:any=await r.json();if(d.error||!Array.isArray(d.features))throw Error('APD crime map could not return records.');const valid=d.features.map((f:any)=>crimeRow(f,layer));if(valid.some((p:any)=>!p))complete=false;rows.push(...valid.filter(Boolean));if(!d.exceededTransferLimit)break;if(offset===3000)complete=false;}}}
 await Promise.all([worker(),worker(),worker()]);return {rows:[...new Map(rows.map(r=>[r.id,r])).values()],limit,complete,fetchedAt:new Date(now).toISOString(),provider:'Austin Police official crime map'};
}
