import {z} from 'zod';
export const sectors=['Water','Wastewater','Electricity','Communications','Food','Fuel','Medical','Emergency services','Shelter','Transportation','Other'] as const;
const date=z.string().refine(v=>v===''||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T00:00:00Z'))&&new Date(v+'T00:00:00Z').toISOString().slice(0,10)===v),'Choose a valid date');
const url=z.string().max(2000).refine(v=>{if(!v)return true;try{return ['http:','https:'].includes(new URL(v).protocol);}catch{return false;}},'Use an http or https source URL');
const id=z.string().min(1).max(100);
export const resourceSnapshotSchema=z.object({status:z.string().max(200).optional(),id,name:z.string().min(1).max(300),category:z.string().max(100),source:z.string().max(200),url,date:z.string().max(100),updatedDate:z.string().max(100),retrievedAt:z.string().max(100),capturedAt:z.string().datetime(),detail:z.string().max(2000),lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)});
const verification={status:z.enum(['Unverified','Verified','Unavailable']),source:z.string().max(1000),sourceUrl:url,verifiedOn:date};
export const dependencySchema=z.object({id,name:z.string().trim().min(1).max(300),disruption:z.string().max(2000),...verification}).superRefine((r,ctx)=>{if(r.status!=='Unverified'&&(!r.source.trim()||!r.verifiedOn))ctx.addIssue({code:z.ZodIssueCode.custom,path:['status'],message:'A verified or unavailable item needs a source and verification date'});});
export const alternativeSchema=z.object({id,name:z.string().trim().min(1).max(300),resource:resourceSnapshotSchema.nullable(),trigger:z.string().max(2000),dependencies:z.string().max(2000),constraints:z.string().max(2000),...verification}).superRefine((r,ctx)=>{if(r.status!=='Unverified'&&(!r.source.trim()||!r.verifiedOn))ctx.addIssue({code:z.ZodIssueCode.custom,path:['status'],message:'A verified or unavailable backup needs a source and verification date'});});
const unique=(items:{id:string}[])=>new Set(items.map(x=>x.id)).size===items.length;
export const servicePlanSchema=z.object({id,name:z.string().trim().min(1).max(300),sector:z.enum(sectors),primary:resourceSnapshotSchema.nullable(),dependencies:z.array(dependencySchema).max(20).refine(unique,'Duplicate dependency IDs'),alternatives:z.array(alternativeSchema).max(20).refine(unique,'Duplicate backup IDs'),questionIds:z.array(id).max(100).refine(ids=>new Set(ids).size===ids.length,'Duplicate question links'),reviewOn:date,notes:z.string().max(4000),createdAt:z.string().datetime()});
export const servicePlansSchema=z.array(servicePlanSchema).max(100).refine(unique,'Duplicate service plan IDs').default([]);
export type ServicePlan=z.infer<typeof servicePlanSchema>;
export type Dependency=z.infer<typeof dependencySchema>;
export type Alternative=z.infer<typeof alternativeSchema>;
export type ResourceSnapshot=z.infer<typeof resourceSnapshotSchema>;
export type ResourceRecord={status?:string;id:string;name:string;category:string;source:string;url?:string;date?:string;updatedDate?:string;retrievedAt?:string;detail?:string;lat:number;lng:number};
export function resourceSnapshot(r:ResourceRecord):ResourceSnapshot{return {...(r.status?{status:r.status.slice(0,200)}:{}),id:r.id.slice(0,100),name:r.name.slice(0,300),category:r.category.slice(0,100),source:r.source.slice(0,200),url:r.url&&/^https?:\/\//i.test(r.url)?r.url.slice(0,2000):'',date:(r.date||'').slice(0,100),updatedDate:(r.updatedDate||'').slice(0,100),retrievedAt:(r.retrievedAt||'').slice(0,100),capturedAt:new Date().toISOString(),detail:(r.detail||'').slice(0,2000),lat:r.lat,lng:r.lng};}
export function newServicePlan(r?:ResourceRecord):ServicePlan{return {id:crypto.randomUUID(),name:r?.name.slice(0,300)||'New essential service',sector:r?.category==='Power outages'?'Electricity':r?.category==='Medical'?'Medical':r?.category==='Fuel'?'Fuel':r?.category==='Food & supplies'?'Food':r?.category==='Water providers'?'Water':r?.category==='Wastewater providers'?'Wastewater':['Fire stations','EMS stations','Police & sheriff','Emergency districts'].includes(r?.category||'')?'Emergency services':'Other',primary:r?resourceSnapshot(r):null,dependencies:[],alternatives:[],questionIds:[],reviewOn:'',notes:'',createdAt:new Date().toISOString()};}
export function newDependency():Dependency{return {id:crypto.randomUUID(),name:'New dependency',disruption:'',status:'Unverified',source:'',sourceUrl:'',verifiedOn:''};}
export function newAlternative():Alternative{return {id:crypto.randomUUID(),name:'New backup option',resource:null,trigger:'',dependencies:'',constraints:'',status:'Unverified',source:'',sourceUrl:'',verifiedOn:''};}
export function planFlags(p:ServicePlan,today:string){return {reviewDue:!!p.reviewOn&&p.reviewOn<=today,gap:!p.dependencies.length||!p.alternatives.length||p.dependencies.some(d=>d.status!=='Verified')||p.alternatives.every(a=>a.status!=='Verified')||p.alternatives.some(a=>!a.trigger.trim())};}
export function retainQuestionLinks(plans:ServicePlan[],questionIds:string[]){const ids=new Set(questionIds);return plans.map(p=>({...p,questionIds:p.questionIds.filter(id=>ids.has(id))}));}
// These are exact user labels, not inferred infrastructure relationships.
export function sharedDependencies(plans:ServicePlan[]){const groups=new Map<string,{name:string;plans:ServicePlan[]}>();for(const p of plans){for(const d of p.dependencies){const key=d.name.trim().toLowerCase().replace(/\s+/g,' ');if(!key)continue;const g=groups.get(key)||{name:d.name,plans:[]};if(!g.plans.some(x=>x.id===p.id))g.plans.push(p);groups.set(key,g);}}return [...groups.values()].filter(g=>g.plans.length>1);}
