import type {Bounds} from './area-cache';
import type {ParcelGeometry} from './geo';
export const floodSource='https://maps.austintexas.gov/arcgis/rest/services/FloodPro/FloodPro/MapServer';
export const crossingSource='https://feature.geographic.texas.gov/arcgis/rest/services/Basemap/Low_Water_Crossing/MapServer/0';
export const nationalFloodSource='https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28';
export function nationalFloodRow(f:any){const p=f.properties;const row=floodRow({...f,properties:{...p,FLOOD_ZONE:p.FLD_ZONE,FLOODWAY:p.ZONE_SUBTY,FIRM_PANEL:undefined,SOURCE_CITATION:p.SOURCE_CIT}},'fema');return {...row,id:'nfhl:'+p.OBJECTID,source:'FEMA NFHL',url:nationalFloodSource,flood:{...row.flood,panel:undefined,county:undefined,effectiveDate:undefined,model:'FEMA NFHL published flood hazard zones',citation:[p.SOURCE_CIT,p.ZONE_SUBTY,p.DFIRM_ID?'DFIRM '+p.DFIRM_ID:''].filter(Boolean).join(' · ')}};}
async function queryNationalFlood(endpoint:string,bbox:Bounds,request:typeof fetch){const rows:ReturnType<typeof nationalFloodRow>[]=[];let complete=false;for(let offset=0;offset<3000;offset+=1000){const u=new URL(endpoint+'/query');u.search=new URLSearchParams({f:'geojson',where:"SFHA_TF = 'T' OR ZONE_SUBTY = '0.2 PCT ANNUAL CHANCE FLOOD HAZARD'",geometry:[bbox[1],bbox[0],bbox[3],bbox[2]].join(','),geometryType:'esriGeometryEnvelope',inSR:'4326',outSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'OBJECTID,FLD_ZONE,ZONE_SUBTY,DFIRM_ID,SOURCE_CIT,SFHA_TF',returnGeometry:'true',geometryPrecision:'6',orderByFields:'OBJECTID ASC',resultOffset:String(offset),resultRecordCount:'1000'}).toString();const r=await request(endpoint+'/query',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:u.search.slice(1),signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error('FEMA NFHL returned HTTP '+r.status);const d=await r.json() as any;if(d.error||!Array.isArray(d.features))throw Error('FEMA flood hazard zones unavailable');rows.push(...d.features.map(nationalFloodRow));if(!(d.exceededTransferLimit||d.properties?.exceededTransferLimit)){complete=true;break;}}return {rows,complete,limit:3000,fetchedAt:new Date().toISOString(),provider:'FEMA National Flood Hazard Layer',warning:'Published special flood hazard and 0.2% annual-chance zones only. Empty results do not establish that the area has been mapped or is flood-free. Effective dates are not supplied by this layer.'};}
export const esriFloodSource='https://services5.arcgis.com/7weheFjxuNkGGiZi/arcgis/rest/services/USA_Flood_Hazard_Areas_view/FeatureServer/0';
export async function fetchNationalFlood(bbox:Bounds,request:typeof fetch=fetch){
 try{return await queryNationalFlood(nationalFloodSource,bbox,request);}catch(directError){
  const r=await request('https://www.arcgis.com/sharing/rest/content/items/ccd29fb4bd5e4b44a2d61638829a5d7e?f=json',{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('National flood sources unavailable');const meta=await r.json() as any;if(meta.owner!=='esri_landscapes'||meta.access!=='public'||meta.url+'/0'!==esriFloodSource)throw Error('Esri flood publisher could not be verified');const release=String(meta.description||'').replace(/<[^>]+>/g,' ').match(/derived from the ([A-Za-z]+ \d{1,2}, \d{4}) version/i)?.[1]||'Date unavailable';const result=await queryNationalFlood(esriFloodSource,bbox,request);return {...result,provider:'Esri USA Flood Hazard Areas · FEMA-derived snapshot',rows:result.rows.map(row=>({...row,id:row.id.replace('nfhl:','nfhl-esri:'),url:esriFloodSource,flood:{...row.flood,model:'FEMA NFHL · Esri snapshot '+release,citation:[row.flood.citation,'Esri dataset date: '+release].filter(Boolean).join(' · ')},detail:'Published by esri_landscapes. Dataset derived from FEMA NFHL dated '+release+'. Catalog edit time is not a flood-map effective date.'})),warning:'Direct FEMA collection unavailable ('+(directError instanceof Error?directError.message:'source failed')+'). Showing Esri’s FEMA-derived snapshot dated '+release+'. Verify current maps at FEMA. '+result.warning};
 }
}

export function floodRow(f:any,kind:string){const p=f.properties,g=f.geometry as ParcelGeometry;if(!p||!Number.isFinite(p.OBJECTID)||!g||!['Polygon','MultiPolygon'].includes(g.type))throw Error('Flood source returned invalid geometry.');const rings=g.type==='Polygon'?[g.coordinates]:g.coordinates;const b=rings.flatMap(r=>r[0]).reduce((a:number[],v:number[])=>[Math.min(a[0],v[1]),Math.min(a[1],v[0]),Math.max(a[2],v[1]),Math.max(a[3],v[0])],[Infinity,Infinity,-Infinity,-Infinity]);if(b.some((n:number)=>!Number.isFinite(n)))throw Error('Flood source returned invalid coordinates.');const fema=kind==='fema';return {id:kind+':'+p.OBJECTID,name:`${fema?'FEMA':'Austin modeled'} · ${p.FLOOD_ZONE||'Zone unavailable'}`,lat:(b[0]+b[2])/2,lng:(b[1]+b[3])/2,geometry:g,category:fema?'FEMA floodplains':'Austin modeled floodplains',source:fema?'FloodPro FEMA':'FloodPro Austin model',url:`${floodSource}/${fema?8:9}`,flood:{zone:p.FLOOD_ZONE,floodway:p.FLOODWAY,panel:p.FIRM_PANEL,county:p.COUNTY?.trim(),effectiveDate:typeof p.EFFECTIVE_DATE==='number'?new Date(p.EFFECTIVE_DATE).toISOString().slice(0,10):undefined,citation:p.SOURCE_CITATION,model:fema?'FEMA effective floodplain':'City of Austin fully developed floodplain'},updatedDate:typeof p.MODIFIED_DATE==='number'?new Date(p.MODIFIED_DATE).toISOString():undefined};}
export function crossingRow(f:any){const p=f.properties,g=f.geometry;if(!p||!Number.isFinite(p.objectid)||g?.type!=='Point'||!Number.isFinite(g.coordinates[0])||!Number.isFinite(g.coordinates[1]))throw Error('Crossing source returned invalid coordinates.');return {id:'tx-crossing:'+p.objectid,name:p.road||p.location_1||'Low-water crossing',lat:g.coordinates[1],lng:g.coordinates[0],category:'Low-water crossings',source:'Texas crossing inventory',url:crossingSource,crossing:{county:p.county,road:p.road,waterway:p.flowsource,type:p.lwx_type,location:p.location_1,attribution:p.source,condition:'Current closure status unavailable'}};}
export async function fetchFlood(kind:string,bbox:Bounds,request:typeof fetch=fetch){
 const crossing=kind==='crossings',endpoint=crossing?crossingSource:`${floodSource}/${kind==='fema'?8:9}`,rows:any[]=[];let complete=false;const limit=3000;
 for(let offset=0;offset<limit;offset+=1000){const u=new URL(endpoint+'/query');u.search=new URLSearchParams({f:'geojson',where:kind==='fema'?"FLOOD_ZONE <> 'AREA NOT INCLUDED'":'1=1',geometry:[bbox[1],bbox[0],bbox[3],bbox[2]].join(','),geometryType:'esriGeometryEnvelope',inSR:'4326',outSR:'4326',spatialRel:'esriSpatialRelIntersects',outFields:'*',returnGeometry:'true',geometryPrecision:'6',orderByFields:crossing?'objectid ASC':'OBJECTID ASC',resultOffset:String(offset),resultRecordCount:'1000'}).toString();const r=await request(u,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(`${crossing?'Texas crossings':'FloodPro'} returned HTTP ${r.status}`);const d:any=await r.json();if(d.error||!Array.isArray(d.features))throw Error(`${crossing?'Texas crossing inventory':'FloodPro'} could not return records.`);rows.push(...d.features.map((f:any)=>crossing?crossingRow(f):floodRow(f,kind)));if(!(d.exceededTransferLimit||d.properties?.exceededTransferLimit)){complete=true;break;}}
 return {rows,complete,limit,fetchedAt:new Date().toISOString(),provider:crossing?'Texas Geographic Information Office':'City of Austin FloodPro'};
}
