import type {Bounds} from './area-cache';
import {validJurisdictionGeometry} from './jurisdictions';
import {arcgisArea,type ArcgisFeature} from './arcgis-area';
import {haysSources,pucSources,pucViewer} from './local-source-packs';
const text=(v:unknown)=>typeof v==='string'?v.trim():typeof v==='number'?String(v):'';
const num=(v:unknown)=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):undefined;
function center(f:ArcgisFeature){if(!validJurisdictionGeometry(f.geometry)||!Number.isInteger(f.properties?.OBJECTID))throw Error('Invalid official polygon');const vertices=f.geometry.type==='Polygon'?f.geometry.coordinates.flat():f.geometry.coordinates.flat(2);let w=Infinity,s=Infinity,e=-Infinity,n=-Infinity;for(const v of vertices){w=Math.min(w,v[0]);e=Math.max(e,v[0]);s=Math.min(s,v[1]);n=Math.max(n,v[1]);}return {lat:(s+n)/2,lng:(w+e)/2};}
export function haysParcelRow(f:ArcgisFeature,updatedDate?:string){
 const point=center(f),p=f.properties,address=[p.situs_num,p.situs_street_prefx,p.situs_street,p.situs_street_sufix].map(text).filter(Boolean).join(' '),id=text(p.prop_id_text)||text(p.prop_id)||'object:'+p.OBJECTID;
 // This feed does not supply appraised/assessed values or building year. Never infer them from market value.
 return {id:'hcad:'+id,name:address||'Hays parcel '+id,...point,category:'Property records',source:'Hays County parcels',url:haysSources.parcels,geometry:f.geometry,updatedDate,property:{id,geoId:text(p.geo_id),owner:text(p.file_as_name),address,city:text(p.situs_city),zip:text(p.situs_zip),acres:num(p.legal_acreage),marketValue:num(p.market),legal:[p.legal_desc,p.legal_desc2,p.legal_desc3].map(text).filter(Boolean).join(' '),subdivision:text(p.abs_subdv_cd),deedNumber:text(p.Number),deedBook:text(p.Volume),deedPage:text(p.Page),deedDate:/^\d{4}-\d{2}-\d{2}$/.test(text(p.Deed_Date))?text(p.Deed_Date):undefined,appraisalYear:null,taxYear:num(p.owner_tax_yr),county:'Hays'},detail:'Hays County GIS / appraisal-district compilation. Tax-roll year is distinct from layer edit date. Verify ownership, values and deeds in official records; outlines are not surveys.'};
}
export async function fetchHaysParcels(b:Bounds,request:typeof fetch=fetch){const d=await arcgisArea(haysSources.parcels,b,'OBJECTID,prop_id_text,prop_id,owner_tax_yr,file_as_name,legal_acreage,legal_desc,legal_desc2,legal_desc3,abs_subdv_cd,geo_id,situs_num,situs_street_prefx,situs_street,situs_street_sufix,situs_city,situs_zip,market,Deed_Date,Volume,Page,Number',request);const {features,...meta}=d;return {...meta,rows:features.map(f=>haysParcelRow(f,d.updatedDate)),provider:'Hays County GIS'};}
export function pucRow(f:ArcgisFeature,kind:'water'|'sewer',updatedDate?:string){const point=center(f),p=f.properties,name=text(p.UTILITY)||text(p.DBA_NAME)||'Utility name unavailable';return {id:'puc-'+kind+':'+p.OBJECTID,name,...point,category:kind==='water'?'Water providers':'Wastewater providers',source:'Texas PUC '+(kind==='water'?'water':'sewer')+' CCN',url:pucViewer,geometry:f.geometry,updatedDate,detail:[text(p.CCN_NO)&&'CCN '+text(p.CCN_NO),text(p.STATUS)&&'Source classification: '+text(p.STATUS),'Statewide PUC certificated territory; not pipe locations or confirmed service eligibility. Confirm the provider from your bill or an address check. Layer edit date is not the boundary effective date.'].filter(Boolean).join('\n'),status:'Account service and current operating status unavailable'};}
export async function fetchPuc(kind:'water'|'sewer',b:Bounds,request:typeof fetch=fetch){const d=await arcgisArea(pucSources[kind],b,'*',request);const {features,...meta}=d;return {...meta,rows:features.map(f=>pucRow(f,kind,d.updatedDate)),provider:'Texas Public Utility Commission'};}
export function haysClosureRow(f:ArcgisFeature){const p=f.properties,g=f.geometry;if(!Number.isInteger(p?.OBJECTID)||g?.type!=='Point'||!Array.isArray(g.coordinates)||!g.coordinates.slice(0,2).every(Number.isFinite))throw Error('Invalid Hays closure point');const stamp=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)&&v>0?new Date(v).toISOString():null;const active=text(p.activeincid).toLowerCase()==='yes',state=active?'Closed' as const:'Unknown' as const,comment=[p.direction,p.reason,p.accessallowed,p.description].map(text).filter(Boolean).join(' · '),recordUpdated=stamp(p.last_edited_date),closure={reported:active?'Active road closure/block':'Activity not confirmed',state,jurisdiction:'Hays County public road-closure map',address:text(p.street),comment,recordUpdated};return {id:'hays-closure:'+p.OBJECTID,name:text(p.street)||'Hays road closure/block',lat:g.coordinates[1],lng:g.coordinates[0],category:'Crossing status',source:'Hays County road closures',url:'https://www.haysinformed.com/maps/roadclosuresmaps',closure,detail:['Official road closure/block point, not necessarily a water crossing.',comment,'Scheduled start: '+(stamp(p.starttime)||'Unavailable'),'Scheduled end: '+(stamp(p.endtime)||'Unavailable'),'Inactive records do not establish that a road is open. Line closures, detours and road hazards are available on the official map; this point feed is incomplete travel coverage.'].join('\n')};}
export async function fetchHaysClosures(b:Bounds,request:typeof fetch=fetch){const d=await arcgisArea(haysSources.closures,b,'*',request);const {features,...meta}=d;return {...meta,rows:features.map(haysClosureRow),provider:'Hays County public road-closure map',warning:'Hays closure/block points only. Consult the official map for line closures, detours and road hazards; empty results do not certify travel conditions.'};}
