import {haysRoot} from './local-source-packs';
import {geometryContains,type ParcelGeometry,type Point} from './geo';
import {sourceJson,type ConditionSnapshot} from './conditions';
const root='https://gis.traviscountytx.gov/server1/rest/services/Boundaries_and_Jurisdictions/';
export const representativeUrl='https://www.traviscountytx.gov/find-your-representative';
export const jurisdictionSources=[
 {id:'municipal',name:'City limits & ETJ',url:'https://taxmaps.traviscountytx.gov/arcgis/rest/services/City/FeatureServer/0',field:'CIT',verify:representativeUrl,note:'County Tax Office municipal map. Full, limited-purpose and ETJ boundaries remain separate. Source record edits do not establish a legal annexation date.'},
 {id:'county',name:'County',url:root+'Travis_County_Boundary_Polygon/MapServer/1',field:'NAME',verify:representativeUrl,note:'Travis County boundary only. Other metro counties are not connected; an unmatched point is outside this published coverage or requires verification.'},
 {id:'commissioner',name:'County commissioner precinct',url:root+'Travis_County_Commissioner_Precincts/MapServer/0',field:'NAME',verify:representativeUrl,note:'County metadata describes the 2022 precinct plan, effective January 1, 2022. GIS officeholder names are excluded; use current official office pages.'},
 {id:'school',name:'School district',url:root+'School_Districts/MapServer/0',field:'SCH',verify:representativeUrl,note:'County Tax Office district boundaries. A district match does not assign a campus or confirm enrollment eligibility.'},
 {id:'esd',name:'Emergency-service district',url:'https://services1.arcgis.com/HGcSYZ5bvjRswoCb/arcgis/rest/services/Emergency_Service_Districts_agol/FeatureServer/1',field:'ESD_Name',verify:'https://www.traviscountytx.gov/fire-marshal/esd',note:'Layer linked by the county ESD viewer. Description cites August 2016 boundaries and a May 2021 update. Service edits are newer, but current response assignments need confirmation.'}
];
jurisdictionSources.push(
 {id:'hays-municipal',name:'City limits',url:haysRoot+'Hays_County_City_Boundaries/FeatureServer/5',field:'MUNI_NM',verify:'https://hays-county-haysgis.hub.arcgis.com/',note:'Hays County published city limits. ETJs are not supplied; a postal city does not establish incorporation.'},
 {id:'hays-county',name:'County',url:haysRoot+'Hays_County_Boundary/FeatureServer/0',field:'NAME',verify:'https://www.hayscountytx.gov/',note:'Hays County published boundary. Verify current jurisdiction with the county.'},
 {id:'hays-commissioner',name:'County commissioner precinct',url:haysRoot+'HaysCountyCommissionerPrecincts/FeatureServer/0',field:'CommPrcnt',verify:'https://www.hayscountytx.gov/',note:'Hays County commissioner precincts. GIS officeholder names are excluded; consult current county offices.'},
 {id:'hays-school',name:'School district',url:haysRoot+'Hays_County_School_Districts/FeatureServer/0',field:'NAME',verify:'https://hays-county-haysgis.hub.arcgis.com/',note:'Published school district boundaries; metadata edits date to 2022. Campus and enrollment eligibility require district verification.'},
 {id:'hays-esd',name:'Emergency-service district',url:'https://www.hayscountytx.gov/346/Emergency-Services-Districts',field:'',verify:'https://www.hayscountytx.gov/346/Emergency-Services-Districts',note:'Automatic Hays response-district matching is not connected. Use official county fire/EMS maps and confirm the address with the agency. Fire-marshal inspection boundaries are not response districts.'}
);
export function jurisdictionSourcesForCounty(fips:string){return fips==='48209'?jurisdictionSources.filter(s=>s.id.startsWith('hays-')):jurisdictionSources.filter(s=>!s.id.startsWith('hays-'));}
export type JurisdictionMatch={id:string,sourceId:string,name:string,role:string,code:string|null,contains:boolean,nearBoundary:boolean,recordUpdated:string|null,geometry:ParcelGeometry};
export type JurisdictionData={matches:JurisdictionMatch[],serviceUpdated:string|null};
export type JurisdictionSnapshot=ConditionSnapshot<JurisdictionData>&{sourceId:string};
type Feature={properties:Record<string,unknown>,geometry:ParcelGeometry};
function text(v:unknown){return typeof v==='string'?v.trim():'';}
function timestamp(v:unknown){return typeof v==='number'&&v>0&&Number.isFinite(v)&&v<8640000000000000?new Date(v).toISOString():null;}
export function municipalRole(name:string){return /\bETJ\b|extraterritorial|development agreement/i.test(name)?'ETJ / development agreement':/limited/i.test(name)?'Limited-purpose city boundary':'City boundary';}
function rings(g:ParcelGeometry):number[][][]{return g.type==='Polygon'?g.coordinates:g.coordinates.flat();}
export function validJurisdictionGeometry(raw:unknown):raw is ParcelGeometry{const g=raw as ParcelGeometry;if(!g||!['Polygon','MultiPolygon'].includes(g.type)||!Array.isArray(g.coordinates)||!g.coordinates.length)return false;try{const polygons=g.type==='Polygon'?[g.coordinates]:g.coordinates;if(polygons.some(p=>!Array.isArray(p)||!p.length)||!rings(g).length)return false;return rings(g).every(r=>Array.isArray(r)&&r.length>=4&&r.every(p=>Array.isArray(p)&&p.length>=2&&typeof p[0]==='number'&&typeof p[1]==='number'&&Number.isFinite(p[0])&&Number.isFinite(p[1])&&p[0]>=-180&&p[0]<=180&&p[1]>=-90&&p[1]<=90)&&r[0][0]===r.at(-1)![0]&&r[0][1]===r.at(-1)![1]);}catch{return false;}}
export function boundaryDistance(point:Point,g:ParcelGeometry){const scaleX=111320*Math.cos(point[0]*Math.PI/180),scaleY=111320;let distance=Infinity;for(const ring of rings(g))for(let i=1;i<ring.length;i++){const a=ring[i-1],b=ring[i],ax=(a[0]-point[1])*scaleX,ay=(a[1]-point[0])*scaleY,bx=(b[0]-point[1])*scaleX,by=(b[1]-point[0])*scaleY,dx=bx-ax,dy=by-ay,t=Math.max(0,Math.min(1,-(ax*dx+ay*dy)/(dx*dx+dy*dy||1)));distance=Math.min(distance,Math.hypot(ax+t*dx,ay+t*dy));}return distance;}
export function parseJurisdictions(raw:unknown,sourceId:string,point:Point):JurisdictionMatch[]{const source=jurisdictionSources.find(s=>s.id===sourceId);if(!source)throw Error('Unknown jurisdiction source');const data=raw as {type?:string,error?:unknown,features?:Feature[],exceededTransferLimit?:boolean,properties?:{exceededTransferLimit?:boolean}};if(data?.error||data?.type!=='FeatureCollection'||!Array.isArray(data.features))throw Error('Official boundary records unavailable');if(data.features.length>30||data.exceededTransferLimit||data.properties?.exceededTransferLimit)throw Error('Boundary query incomplete; verify in the official viewer');const seen=new Set<string>();return data.features.map(f=>{if(!f?.properties||!Number.isInteger(f.properties.OBJECTID)||!validJurisdictionGeometry(f.geometry))throw Error('Invalid official boundary geometry');const p=f.properties,name=text(p[source.field]);if(!name)throw Error('Boundary name unavailable');const id=sourceId+':'+p.OBJECTID;if(seen.has(id))throw Error('Repeated boundary records');seen.add(id);return {id,sourceId,name:sourceId.endsWith('county')?(name.endsWith('County')?name:name+' County'):sourceId==='hays-commissioner'?'Precinct '+name:name,role:sourceId.endsWith('municipal')?municipalRole(name):source.name,code:sourceId.endsWith('commissioner')?String(p.PRECINCT||p.CommPrcnt||'')||null:sourceId==='esd'?text(p.County_ESD_Code)||null:null,contains:geometryContains(f.geometry,point),nearBoundary:boundaryDistance(point,f.geometry)<=25,recordUpdated:timestamp(p.LastEditedOn)||timestamp(p.DATE_MODIF)||timestamp(p.LAST_MOD),geometry:f.geometry};}).filter(m=>m.contains||m.nearBoundary);}
export async function collectJurisdictions(sourceId:string,point:Point,fetcher:typeof fetch=fetch):Promise<JurisdictionData>{const source=jurisdictionSources.find(s=>s.id===sourceId);if(!source)throw Error('Unknown jurisdiction source');const u=new URL(source.url+'/query'),dx=40/(111320*Math.cos(point[0]*Math.PI/180)),dy=40/111320;u.search=new URLSearchParams({f:'geojson',where:'1=1',outFields:'*',outSR:'4326',resultRecordCount:'30',returnGeometry:'true',geometry:[point[1]-dx,point[0]-dy,point[1]+dx,point[0]+dy].join(','),geometryType:'esriGeometryEnvelope',inSR:'4326',spatialRel:'esriSpatialRelIntersects'}).toString();const raw=await sourceJson(u.toString(),fetcher),matches=parseJurisdictions(raw,sourceId,point);let serviceUpdated:string|null=null;try{const info=await sourceJson(source.url+'?f=json',fetcher);serviceUpdated=timestamp(info?.editingInfo?.dataLastEditDate)||timestamp(info?.editingInfo?.lastEditDate);}catch{/* Keep valid query results when metadata is unavailable. */}return {matches,serviceUpdated};}
export function jurisdictionState(s:JurisdictionSnapshot|undefined){if(!s?.data)return s?.error?'Unavailable':'Not checked';if(s.error)return 'Older cache · verify';const hits=s.data.matches.filter(m=>m.contains);if(s.data.matches.some(m=>m.nearBoundary)||hits.length>1)return s.sourceId==='esd'&&hits.length>1?'Overlapping districts · verify':'Boundary ambiguity · verify';return hits.length?'Mapped match':'No mapped match';}
export type CivicContact={id:string,name:string,purpose:string,url:string,phone?:string,extension?:string,verified:string,context:string};
const verified='2026-10-07';
const officeWords=['one','two','three','four'];
export function jurisdictionContacts(sources:JurisdictionSnapshot[]):CivicContact[]{const all=sources.flatMap(s=>(s.data?.matches||[]).filter(m=>m.contains).map(m=>({...m,stale:!!s.error,ambiguous:s.data!.matches.some(x=>x.nearBoundary)||s.data!.matches.filter(x=>x.contains).length>1})));const contacts:CivicContact[]=[];const context=(m:typeof all[number])=>`${m.name} · ${m.stale?'older cached match':m.ambiguous?'ambiguous mapped match':'mapped association'}${m.role.includes('ETJ')?' · ETJ context, not city residency':''}`;
 for(const m of all){if(m.sourceId.startsWith('hays-')){if(m.sourceId==='hays-county')contacts.push({id:'hays-sheriff',name:'Hays County Sheriff · non-emergency',purpose:'County non-emergency contact; confirm the response agency',url:'https://cityofwimberley.com/QuickLinks.aspx?CID=45',phone:'512-393-7896',verified,context:context(m)});if(m.sourceId==='hays-municipal'&&/Wimberley/i.test(m.name))contacts.push({id:'wimberley-city',name:'Wimberley City Hall',purpose:'City services and boundary inquiries',url:'https://cityofwimberley.com/QuickLinks.aspx?CID=45',phone:'512-847-0025',verified,context:context(m)});continue;}if(m.sourceId==='municipal'&&/\bManor\b/i.test(m.name)){contacts.push({id:'manor-city',name:'Manor City Hall',purpose:'City services, boundaries and municipal inquiries',url:'https://www.manortx.gov/149/Departments',phone:'512-272-5555',verified,context:context(m)});if(m.role==='City boundary')contacts.push({id:'manor-police',name:'Manor Police · non-emergency dispatch',purpose:'Non-emergency dispatch; confirm the appropriate response agency',url:'https://www.manortx.gov/280/Compliments-Complaints',phone:'512-974-0845',extension:'Option 3',verified,context:context(m)});}
 if(m.sourceId==='commissioner'&&/^[1-4]$/.test(m.code||'')){const n=Number(m.code);contacts.push({id:'commissioner-'+n,name:'Travis County Commissioner · Precinct '+n,purpose:'Precinct office and constituent services',url:'https://www.traviscountytx.gov/commissioners-court/precinct-'+officeWords[n-1],phone:['512-854-9111','512-854-9222','512-854-9333','512-854-9444'][n-1],verified,context:context(m)});}
 if(m.sourceId==='school'&&/^Manor ISD$/i.test(m.name))contacts.push({id:'manor-isd',name:'Manor ISD district office',purpose:'District information; verify enrollment and campus assignment',url:'https://www.manorisd.net/',phone:'512-278-4000',verified,context:context(m)});
 if(m.sourceId==='esd'&&m.code==='E12')contacts.push({id:'esd12',name:'Travis County ESD 12',purpose:'General, non-emergency district inquiries',url:'https://www.tcesd12.com/contact-us',phone:'512-272-4502',verified,context:context(m)+' · boundary description cites older data'});
 if(m.sourceId==='county')contacts.push({id:'sheriff',name:'Travis County Sheriff · non-emergency dispatch',purpose:'County non-emergency contact; does not assign the response agency',url:'https://www.tcsheriff.org/about/about-tcso/contact-us',phone:'512-974-0845',extension:'Option 3',verified,context:context(m)});
 }return [...new Map(contacts.map(c=>[c.id,c])).values()];}
export function jurisdictionNote(source:typeof jurisdictionSources[number],s:JurisdictionSnapshot){return [`Source: ${source.url}`,`Category: ${source.name}`,`Lookup status: ${jurisdictionState(s)}`,`Collected: ${s.fetchedAt||'Unavailable'}`,`Service data edited: ${s.data?.serviceUpdated||'Unavailable'}`,...(s.data?.matches||[]).map(m=>`${m.name} — ${m.role}; ${m.contains?'home point intersects':'nearby only'}${m.nearBoundary?'; within 25 m of a boundary':''}; record edited ${m.recordUpdated||'Unavailable'}`),source.note,'Mapped home-point result; verify the address and current jurisdiction with the official office.'].join('\n');}
