import {z} from 'zod';
export const utilityProvidersSchema=z.object({electricity:z.enum(['unknown','bluebonnet','austinenergy','pec','other']).default('unknown'),water:z.enum(['unknown','manor','manville','austinwater','wilbargercreekmud1','wimberleywater','aquatexas','other']).default('unknown')}).default({electricity:'unknown',water:'unknown'});
export type UtilityProviders=z.infer<typeof utilityProvidersSchema>;
export const providerNames:Record<string,string>={unknown:'Not confirmed',bluebonnet:'Bluebonnet Electric',austinenergy:'Austin Energy',manor:'City of Manor water',manville:'Manville WSC',austinwater:'Austin Water',wilbargercreekmud1:'Wilbarger Creek MUD 1',pec:'Pedernales Electric Cooperative',wimberleywater:'Wimberley Water Supply',aquatexas:'Aqua Texas',other:'Other provider'};
export const providerLinks:Record<string,string>={pec:'https://www.pec.coop/',wimberleywater:'https://wimberleywatersupplycorp.com/',aquatexas:'https://www.aquawater.com/about-aqua/states-we-serve/aqua-texas',bluebonnet:'https://outage.bluebonnetelectric.coop/',austinenergy:'https://outagemap.austinenergy.com/',manor:'https://www.manortx.gov/AlertCenter.aspx',manville:'https://manvillewsc.org/alerts',wilbargercreekmud1:'https://crossroadsus.com/districts/wilbarger-creek-municipal-utility-district-001',austinwater:'https://www.austintexas.gov/water/austin-water-emergency-information'};
export type PowerOutage={id:string;name:string;lat:number;lng:number;category:string;source:string;url:string;detail:string;power:{start:string|null;updated:string|null;restoration:string|null;customers:number|null;crew:string;verified:boolean|null;planned:boolean|null};updatedDate?:string;retrievedAt?:string;stale?:boolean};
export type PowerSummary={customersOut:number|null;customersServed:number|null;updated:string;rows:PowerOutage[]};
const stamp=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v))?new Date(v).toISOString():null;
const count=(v:unknown)=>typeof v==='number'&&Number.isSafeInteger(v)&&v>=0?v:null;
export function powerRow(p:Record<string,unknown>):PowerOutage{
 const g=p.outagePoint as {lat?:number;lng?:number}|undefined,id=p.outageRecID;
 if(typeof id!=='string'||!id||!g||!Number.isFinite(g.lat)||!Number.isFinite(g.lng)||Math.abs(g.lat!)>90||Math.abs(g.lng!)>180)throw Error('Invalid Bluebonnet outage record');
 const power={start:stamp(p.outageStartTime),updated:stamp(p.outageModifiedTime),restoration:stamp(p.estimatedTimeOfRestoral),customers:count(p.customersOutNow),crew:typeof p.outageWorkStatus==='string'?p.outageWorkStatus:'',verified:typeof p.verified==='boolean'?p.verified:null,planned:typeof p.isPlanned==='boolean'?p.isPlanned:null};
 return {id:'bluebonnet:'+id,name:typeof p.outageName==='string'&&p.outageName.trim()?p.outageName:'Bluebonnet reported outage '+id,lat:g.lat!,lng:g.lng!,category:'Power outages',source:'Bluebonnet outage map',url:providerLinks.bluebonnet,updatedDate:power.updated||undefined,power,detail:['Outage ID: '+id,'Customers reported out: '+(power.customers??'Unavailable'),'Started: '+(power.start||'Unavailable'),'Record updated: '+(power.updated||'Unavailable'),'Estimated restoration: '+(power.restoration||'Unavailable'),power.crew,'Published point is approximate; it does not identify affected meters or confirm home impact.'].filter(Boolean).join('\n')};
}
async function json(path:string,request:typeof fetch){const r=await request('https://outage.bluebonnetelectric.coop/data/'+path,{redirect:'manual',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Bluebonnet returned HTTP '+r.status);const t=await r.text();if(t.length>3000000)throw Error('Bluebonnet response exceeds limit');return JSON.parse(t);}
export async function fetchBluebonnet(request:typeof fetch=fetch):Promise<PowerSummary>{
 const [s,d]=await Promise.all([json('outageSummary.json',request),json('outages.json',request)]);const updated=stamp(s.updateTime);
 if(!updated||!Array.isArray(d)||d.length>5000||count(s.customersOutNow)===null||count(s.customersServed)===null)throw Error('Bluebonnet outage summary or records unavailable');
 const rows=d.map(powerRow);if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Bluebonnet returned duplicate outages');
 return {updated,customersOut:count(s.customersOutNow),customersServed:count(s.customersServed),rows};
}
export type WaterNotice={id:string;title:string;url:string;published:string|null;excerpt:string;label:string};
function plain(v:string){return v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g,' ').trim();}
function tag(v:string,key:string){return v.match(new RegExp('<'+key+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+key+'>','i'))?.[1]||'';}
export function noticeLabel(title:string){return /lifted|rescinded|rescind|cancelled|canceled/i.test(title)?'Published lift / rescission':/boil/i.test(title)?'Published boil-water notice · review status':'Published water advisory · review status';}
export function parseWaterFeed(xml:string):WaterNotice[]{if(xml.length>2000000||/<!DOCTYPE|<!ENTITY/i.test(xml)||!/<rss\b/i.test(xml)||!/<\/rss>/i.test(xml))throw Error('Manor water feed is incomplete or invalid');const chunks=[...xml.matchAll(/<item\b[^>]*>([\s\S]*?)<\/item>/gi)];if(chunks.length>100)throw Error('Manor water feed exceeds limit');return chunks.map(([,v])=>{const title=plain(tag(v,'title')),url=new URL(plain(tag(v,'link')));if(!title||url.origin!=='https://www.manortx.gov'||url.username||url.password)throw Error('Invalid Manor water notice');return {id:url.toString(),title,url:url.toString(),published:stamp(plain(tag(v,'pubDate'))),excerpt:plain(tag(v,'description')).slice(0,1000),label:noticeLabel(title)};});}
export async function fetchManorWater(request:typeof fetch=fetch){const feeds=['BOIL-WATER-NOTICE-6','Boil-Water-Notice-5'];const batches=await Promise.all(feeds.map(async id=>{const r=await request('https://www.manortx.gov/RSSFeed.aspx?ModID=63&CID='+id,{redirect:'manual',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('Manor water feed returned HTTP '+r.status);return parseWaterFeed(await r.text());}));return {notices:[...new Map(batches.flat().map(n=>[n.id,n])).values()]};}

export type DistrictResources={links:{label:string;url:string}[]};
export function parseDistrictResources(html:string):DistrictResources{if(html.length>2000000)throw Error('District page exceeds limit');const title=plain((html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1]||'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,''));if(title!=='Wilbarger Creek Municipal Utility District No. 1')throw Error('District page identity could not be verified');const labels=['Current Water Restrictions','Annual Water Quality Report','Drought Contingency Plan'];const links=[];for(const label of labels){for(const [,attrs,body] of html.matchAll(/<a\b([^>]*?)>([\s\S]*?)<\/a>/gi)){if(!plain(body).includes(label))continue;const raw=attrs.match(/\bhref="([^"]+)"/i)?.[1];if(!raw)continue;const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password||!['tmc.tritoncg.com','ccr.crossroadsus.com'].includes(u.hostname))throw Error('District resource left official document hosts');links.push({label,url:u.toString()});break;}}if(!links.length)throw Error('Published district resource links unavailable');return {links};}
export async function fetchDistrictResources(request:typeof fetch=fetch){const r=await request(providerLinks.wilbargercreekmud1,{redirect:'manual',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('District operator page returned HTTP '+r.status);return parseDistrictResources(await r.text());}
