import {chooseRecordBatch,knownRecordsSchema,signScopeBatches} from './peer-batches.mjs';
import {MAX_GROUP_RECORDS} from './sharing-limits.ts';
import {PEER_CAPABILITIES,LEGACY_CAPABILITIES,peerCapabilitiesSchema,requirePackageCapabilities,PeerCompatibilityError} from './peer-capabilities.ts';
import {permissionsView} from './peer-permissions.ts';
import {tailscaleIPv4,readTailscaleStatus,requireTailscalePeer,selectTailscaleHost,RemoteNetworkError} from './tailscale-network.mjs';
import {openPeerInbox} from './peer-inbox.mjs';
import {contactsSchema,assessPackageTrust} from './peer-contacts.ts';
// Optional Node-only transport. Never imported by the app or hosted runtime.
import {createServer} from 'node:http';
import {createHash,createCipheriv,createDecipheriv,hkdfSync,randomBytes,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile,rename,open,unlink} from 'node:fs/promises';
import path from 'node:path';
import {z} from 'zod';
import {identityCard,loadSigningIdentity,bindSigningIdentity,signValue,verifyValue,signSavedPackage} from './signing-identity.mjs';
import {identityCardSchema,publicKeySchema,canonical,verifyIdentity,verifySignedPackage,fingerprint} from './sharing-auth.ts';
import {restorePortfolio} from './locations.ts';
import {makeSharedPackage,outboundRecords,parseSharedPackage,MAX_SHARED_BYTES} from './sharing.ts';

const uuid=z.string().uuid(),secret=z.string().regex(/^[A-Za-z0-9_-]{43}$/),label=z.string().trim().min(1).max(100);
const inviteBase={format:z.literal('field-desk-peer-invite'),endpoint:z.string().max(200),grantId:uuid,groupId:uuid,groupName:z.string().min(1).max(160),secret};
const member=z.object({id:uuid,name:z.string().min(1).max(100)}).strict();
const inviteSchema=z.discriminatedUnion('version',[z.object({...inviteBase,version:z.literal(1)}).strict(),z.object({...inviteBase,version:z.literal(2),publisher:member,recipientId:uuid,policy:z.literal('pairwise-v1')}).strict(),z.object({...inviteBase,version:z.literal(3),publisher:member,recipientId:uuid,policy:z.literal('pairwise-signed-v1'),publisherIdentity:identityCardSchema,recipientIdentity:identityCardSchema,capabilities:peerCapabilitiesSchema.optional(),signature:z.string().regex(/^[A-Za-z0-9_-]{86}$/)}).strict()]);
const boxSchema=z.object({iv:z.string().regex(/^[A-Za-z0-9_-]{16}$/),tag:z.string().regex(/^[A-Za-z0-9_-]{22}$/),data:z.string().regex(/^[A-Za-z0-9_-]+$/).max(Math.ceil((MAX_SHARED_BYTES+3000)*4/3))}).strict();
const configSchema=z.object({version:z.literal(1),grants:z.array(z.object({id:uuid,groupId:uuid,label,secret,recordIds:z.array(uuid).min(1).max(MAX_GROUP_RECORDS),policy:z.enum(['pairwise-v1','pairwise-signed-v1']).optional(),publisherKey:publicKeySchema.optional(),recipientKey:publicKeySchema.optional(),publisherId:uuid.optional(),recipientId:uuid.optional(),createdAt:z.string().datetime()})).max(32),peers:z.array(z.object({id:uuid,label,invite:inviteSchema,automatic:z.boolean().default(false)})).max(16),contacts:contactsSchema.default([]),pins:z.record(uuid,publicKeySchema).refine(v=>Object.keys(v).length<=64).default({})}).strict();
export async function validatePeerConfiguration(value){const result=configSchema.parse(value);for(const peer of result.peers){parsePeerInvite(JSON.stringify(peer.invite));if(peer.invite.version===3)await verifyInvitation(peer.invite);}for(const contact of result.contacts)if(contact.identity){const card=await verifyIdentity(contact.identity);if(card.member.id!==contact.id||card.publicKey!==contact.publicKey)throw Error('Contact card binding is invalid.');}return result;}
const MAX_WIRE=Math.ceil((MAX_SHARED_BYTES+3000)*4/3)+1000;
export function privateHost(host){
 if(host==='localhost'||host==='127.0.0.1')return '127.0.0.1';
 const parts=host.split('.');if(parts.length!==4||parts.some(v=>!/^\d{1,3}$/.test(v)||Number(v)>255||String(Number(v))!==v))throw Error('Use a loopback or private LAN IPv4 address.');
 const [a,b]=parts.map(Number);if(a!==10&&!(a===172&&b>=16&&b<=31)&&!(a===192&&b===168))throw Error('Only loopback and private LAN IPv4 addresses are supported.');return host;
}
export function peerEndpoint(text){const u=new URL(text);if(u.protocol!=='http:'||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('Use an HTTP endpoint with no path or credentials.');const host=tailscaleIPv4(u.hostname)?u.hostname:privateHost(u.hostname),port=Number(u.port||80);if(port<1024||port>65535)throw Error('Choose a peer port from 1024–65535.');return `http://${host}:${port}`;}
export function parsePeerInvite(text){if(typeof text!=='string'||Buffer.byteLength(text)>3000)throw Error('Invalid peer invitation.');let v;try{v=inviteSchema.parse(JSON.parse(text));}catch{throw Error('Invalid peer invitation. Use the complete JSON invitation.');}return {...v,endpoint:peerEndpoint(v.endpoint)};}
function keyFor(secret,direction){return Buffer.from(hkdfSync('sha256',Buffer.from(secret,'base64url'),Buffer.from('field-desk-peer-v1'),Buffer.from(direction),32));}
export function sealPeer(value,key,direction,context){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',keyFor(key,direction),iv);cipher.setAAD(Buffer.from(context));const plain=Buffer.from(JSON.stringify(value));if(plain.length>MAX_SHARED_BYTES+3000)throw Error('Sync payload is too large.');const data=Buffer.concat([cipher.update(plain),cipher.final()]);return {iv:iv.toString('base64url'),tag:cipher.getAuthTag().toString('base64url'),data:data.toString('base64url')};}
export function openPeer(box,key,direction,context){box=boxSchema.parse(box);const decipher=createDecipheriv('aes-256-gcm',keyFor(key,direction),Buffer.from(box.iv,'base64url'),{authTagLength:16});decipher.setAAD(Buffer.from(context));decipher.setAuthTag(Buffer.from(box.tag,'base64url'));const plain=Buffer.concat([decipher.update(Buffer.from(box.data,'base64url')),decipher.final()]);if(plain.length>MAX_SHARED_BYTES+3000)throw Error('Sync payload is too large.');return JSON.parse(plain.toString('utf8'));}
async function body(req,max){let size=0,parts=[];for await(const chunk of req){size+=chunk.length;if(size>max)throw Error('Request exceeds the size limit.');parts.push(chunk);}return JSON.parse(Buffer.concat(parts).toString('utf8'));}
async function boundedResponse(response,max){const reader=response.body?.getReader();if(!reader)throw Error('Empty peer response.');let size=0,parts=[];try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max)throw Error('Peer response exceeds the size limit.');parts.push(Buffer.from(value));}}catch(e){await reader.cancel();throw e;}finally{reader.releaseLock();}return JSON.parse(Buffer.concat(parts).toString('utf8'));}
export async function pullPeer(invite,fetcher=fetch,identity,remoteGuard,capabilities=PEER_CAPABILITIES,known=[]){
 invite=parsePeerInvite(JSON.stringify(invite));await verifyInvitation(invite);if(!invite.capabilities)throw new PeerCompatibilityError('Peer update required. Update both instances and exchange renewed invitations.');if(!identity||identity.publicKey!==invite.recipientIdentity.publicKey)throw Error('This invitation requires its recipient signing key.');if(tailscaleIPv4(new URL(invite.endpoint).hostname)){if(!remoteGuard)throw new RemoteNetworkError('Restart your companion with pnpm sync --tailscale to connect to remote peers.');await remoteGuard(new URL(invite.endpoint).hostname);}const requestId=randomUUID(),context=`v1:${invite.grantId}:${invite.groupId}`,requestValue={operation:'pull',requestId,sentAt:Date.now(),capabilities:peerCapabilitiesSchema.parse(capabilities),...(invite.capabilities.features.includes('record-batches-v1')&&capabilities.features.includes('record-batches-v1')?{known:knownRecordsSchema.parse(known)}:{})};const box=sealPeer({...requestValue,signature:signValue(identity,'field-desk-pull-v1',{context,...requestValue})},invite.secret,'request',context);
 const response=await fetcher(`${invite.endpoint}/v1/pull/${invite.grantId}`,{method:'POST',redirect:'manual',headers:{'Content-Type':'application/json'},body:JSON.stringify(box),signal:AbortSignal.timeout(15000)});
 if(!response.ok)throw Error(response.status===404?'Invitation revoked or unavailable.':`Peer returned HTTP ${response.status}.`);
 const envelope=await boundedResponse(response,MAX_WIRE),value=openPeer(envelope,invite.secret,'response',context+':'+requestId);
 if(value.requestId!==requestId||!Number.isFinite(value.sentAt)||Math.abs(Date.now()-value.sentAt)>120000)throw Error('Peer response is expired or does not match this request.');
 if(value.error)throw value.code==='compatibility'?new PeerCompatibilityError(String(value.error).slice(0,240)):Error(String(value.error).slice(0,200));const pkg=parseSharedPackage(JSON.stringify(value.package));await verifySignedPackage(pkg);requirePackageCapabilities(pkg,capabilities);checkAuthors(pkg,invite.publisherIdentity.publicKey,invite.recipientId,identity.publicKey);if(pkg.formatVersion!==2||pkg.group.id!==invite.groupId||pkg.sender.id!==invite.publisher.id||pkg.auth.publisher.publicKey!==invite.publisherIdentity.publicKey)throw Error('Peer returned a different group or contributor.');return pkg;
}
export async function verifyInvitation(invite){if(invite.version!==3)throw Error('Legacy invitation disabled. Ask for a signed invitation.');await verifyIdentity(invite.publisherIdentity);await verifyIdentity(invite.recipientIdentity);const {signature,...body}=invite;if(invite.publisherIdentity.member.id!==invite.publisher.id||invite.recipientIdentity.member.id!==invite.recipientId||!verifyValue(invite.publisherIdentity.publicKey,'field-desk-invite-v1',body,signature))throw Error('Invitation signature or identity binding is invalid.');}
function checkAuthors(pkg,publisherKey,recipientId,recipientKey){for(const r of pkg.records)for(const kind of ['revision','review'])for(const e of kind==='revision'?r.revisions:r.reviews){const author=kind==='revision'?r.member.id:e.member.id,expected=author===pkg.sender.id?publisherKey:author===recipientId?recipientKey:null;if(!expected||pkg.auth?.events[r.id+':'+e.id]?.publicKey!==expected)throw Error('Contribution signing key does not match its direct author identity.');}}
function send(res,status,value,extra={}){res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra});res.end(JSON.stringify(value));}
function listen(server,port,host){return new Promise((resolve,reject)=>{server.once('error',reject);server.listen(port,host,()=>{server.off('error',reject);resolve();});});}

export async function startPeerSync({directory,studyReader,host='127.0.0.1',port=5186,controlPort=5185,fetcher=fetch,pollMs=60000,tailscale=false,tailscaleRunner}){
 host=tailscale?await selectTailscaleHost(host==='127.0.0.1'?undefined:host,tailscaleRunner):privateHost(host);if(![port,controlPort].every(p=>Number.isInteger(p)&&p>=0&&p<=65535)||port===controlPort&&port!==0)throw Error('Choose different valid listener ports.');
 directory=path.resolve(directory);try{await readFile(path.join(directory,'field-desk-retired.json'));throw Error('This federation identity directory is retired. Start the app and companion with your replacement data directory.');}catch(e){if(e.code!=='ENOENT')throw e;}await mkdir(directory,{recursive:true});const lockPath=path.join(directory,'peer-sync.lock');let lock;
 try{lock=await open(lockPath,'wx',0o600);await lock.writeFile(String(process.pid));}catch{throw Error('Another sync service may be using this data directory. If a previous service crashed, stop it and remove only peer-sync.lock.');}
 const configPath=path.join(directory,'peer-sync.json');let config;
 try{config=configSchema.parse(JSON.parse(await readFile(configPath,'utf8')));for(const peer of config.peers)parsePeerInvite(JSON.stringify(peer.invite));}catch(e){if(e.code==='ENOENT')config={version:1,grants:[],peers:[],pins:{},contacts:[]};else{await lock.close();await unlink(lockPath);throw Error('Sync configuration is invalid; original file was kept.');}}
 for(const [id,key] of Object.entries(config.pins)){if(!config.contacts.some(c=>c.id===id)){const peer=config.peers.find(p=>p.invite.version===3&&p.invite.publisher.id===id);config.contacts.push({id,publicKey:key,label:peer?.label||'Previously verified contact',identity:peer?.invite.publisherIdentity,status:'Verified',verifiedAt:null,updatedAt:new Date().toISOString()});}}
 let initialPortfolio;try{initialPortfolio=restorePortfolio(await studyReader());}catch{}
 let identity;try{identity=await loadSigningIdentity(directory,Object.keys(config.pins).length>0||config.grants.some(g=>g.policy==='pairwise-signed-v1')||!!initialPortfolio?.sharing.groups.some(g=>Object.keys(g.signatures).length>0));}catch(e){await lock.close();await unlink(lockPath);throw e;}
 let localMember=initialPortfolio?.sharing.member||null;
 if(localMember)try{await bindSigningIdentity(directory,identity,localMember);}catch(e){await lock.close();await unlink(lockPath);throw e;}
 let identityChain=Promise.resolve();function bindMember(member){if(closed)throw Error('Sync service is stopping.');const run=identityChain.then(()=>{if(closed)throw Error('Sync service is stopping.');return bindSigningIdentity(directory,identity,member);});identityChain=run.catch(()=>{});return run;}
 function pin(c,id,key){if(c.contacts.some(v=>(v.id===id||v.publicKey===key)&&v.status==='Blocked'))throw Error('Contact is blocked.');if(c.pins[id]&&c.pins[id]!==key)throw Error('Signing key changed. Existing pin retained; investigate before reconnecting.');if(id===identity.memberId&&key!==identity.publicKey)throw Error('A peer cannot claim this instance identity.');if(c.contacts.some(v=>v.publicKey===key&&v.id!==id))throw Error('This key already belongs to another contact ID.');if(key===identity.publicKey&&id!==identity.memberId)throw Error('This key belongs to the local identity.');c.pins[id]=key;}
 let durableInbox;try{durableInbox=openPeerInbox(directory);await durableInbox.validate(config.peers);}catch(e){durableInbox?.close();await lock.close();await unlink(lockPath);throw e;}
 let chain=Promise.resolve(),closed=false;const status=durableInbox.checks(),busy=new Set(),replays=new Map(),rates=new Map();
 function inboxMutation(fn){if(closed)throw Error('Sync service is stopping.');const run=chain.then(()=>{if(closed)throw Error('Sync service is stopping.');return fn();});chain=run.catch(()=>{});return run;}
 function inboxEntries(){return durableInbox.entries().filter(e=>config.peers.some(p=>p.id===e.peerId));}
 function inboxSummary(){const entries=inboxEntries(),checks=[...status.values()];return {pending:entries.filter(e=>e.state==='Pending').length,deferred:entries.filter(e=>e.state==='Deferred').length,lastSuccess:checks.map(c=>c.receivedAt).filter(Boolean).sort().at(-1)||null,errors:checks.filter(c=>c.error).length};}
 async function verifiedInbox(id){const entry=durableInbox.get(id),peer=config.peers.find(p=>p.id===entry?.peerId);if(!entry||!peer||peer.invite.version!==3)throw Error('Inbox entry no longer available.');const pkg=entry.package;await verifySignedPackage(pkg);checkAuthors(pkg,peer.invite.publisherIdentity.publicKey,peer.invite.recipientId,identity.publicKey);if(pkg.group.id!==peer.invite.groupId||pkg.sender.id!==peer.invite.publisher.id||pkg.auth.publisher.publicKey!==peer.invite.publisherIdentity.publicKey)throw Error('Inbox does not match its connection.');const trust=await trustPackage(pkg);if(!trust.trusted)throw Error(trust.reason);if(!config.peers.some(p=>p.id===peer.id))throw Error('Peer disconnected during verification.');return entry;}
 function mutate(fn){if(closed)throw Error('Sync service is stopping.');const run=chain.then(async()=>{if(closed)throw Error('Sync service is stopping.');const next=structuredClone(config),result=await fn(next);configSchema.parse(next);await writeFile(configPath+'.tmp',JSON.stringify(next),{mode:0o600});await rename(configPath+'.tmp',configPath);config=next;return result;});chain=run.catch(()=>{});return run;}
 let networkSnapshot=null;
 async function networkCheck(){const snapshot=await readTailscaleStatus(tailscaleRunner);networkSnapshot={enabled:tailscale,state:snapshot.state,connected:snapshot.state==='Running'&&snapshot.selfOnline,checkedAt:snapshot.checkedAt,selfIPs:snapshot.selfIPs,boundHost:host,peers:config.peers.map(p=>{const ip=new URL(p.invite.endpoint).hostname,remote=tailscaleIPv4(ip),found=snapshot.peers.find(v=>v.ip===ip);return {id:p.id,remote,visible:remote?!!found:null,online:remote?found?.online??null:null};})};return networkSnapshot;}
 async function remoteGuard(ip){if(!tailscale)throw new RemoteNetworkError('Restart your companion with pnpm sync --tailscale to connect to remote peers.');const snapshot=await readTailscaleStatus(tailscaleRunner);if(snapshot.state!=='Running'||!snapshot.selfOnline)throw new RemoteNetworkError('Tailscale is unavailable or disconnected. Open Tailscale, sign in and connect, then retry.');if(!snapshot.selfIPs.includes(host))throw new RemoteNetworkError('This companion address no longer belongs to Tailscale. Restart pnpm sync --tailscale and renew changed-address invitations.');requireTailscalePeer(snapshot,ip);}
 function publicState(){return {online:true,capabilities:PEER_CAPABILITIES,networkMode:tailscale?'Tailscale':'Local/LAN',network:networkSnapshot,inbox:inboxEntries(),inboxSummary:inboxSummary(),inboxCapacity:durableInbox.capacity(),contacts:config.contacts,identity:localMember?identityCard(identity,localMember):null,endpoint:`http://${host}:${peerServer.address().port}`,controlPort:controlServer.address().port,grants:config.grants.map(g=>({id:g.id,label:g.label,groupId:g.groupId,records:g.recordIds.length,createdAt:g.createdAt,recipientId:g.recipientId,needsRenewal:g.policy!=='pairwise-signed-v1'||!g.recipientKey||!g.publisherKey})),peers:config.peers.map(p=>({id:p.id,label:p.label,endpoint:p.invite.endpoint,groupId:p.invite.groupId,groupName:p.invite.groupName,automatic:p.automatic,memberId:p.invite.version>=2?p.invite.publisher.id:undefined,publicKey:p.invite.version===3?p.invite.publisherIdentity.publicKey:undefined,needsRenewal:p.invite.version!==3||!p.invite.capabilities,busy:busy.has(p.id),...status.get(p.id)}))};}
 function rememberVerified(c,card,name){pin(c,card.member.id,card.publicKey);const contact=c.contacts.find(v=>v.id===card.member.id);if(contact&&contact.publicKey!==card.publicKey)throw Error('Contact signing key changed.');if(contact){Object.assign(contact,{identity:card,status:'Verified',verifiedAt:contact.verifiedAt||new Date().toISOString(),updatedAt:new Date().toISOString()});}else c.contacts.push({id:card.member.id,label:name||card.member.name,publicKey:card.publicKey,identity:card,status:'Verified',verifiedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}
 function requireContact(id,key){const c=config.contacts.find(c=>c.id===id);if(config.contacts.some(c=>(c.id===id||c.publicKey===key)&&c.status==='Blocked'))throw Error('Contact is blocked.');if(c&&c.publicKey!==key)throw Error('Contact signing key changed.');if(config.contacts.some(c=>c.publicKey===key&&c.id!==id))throw Error('This key already belongs to another contact ID.');if(key===identity.publicKey&&id!==identity.memberId)throw Error('This key belongs to the local identity.');}
 async function trustPackage(pkg){const p=restorePortfolio(await studyReader());if(p.sharing.member){await bindMember(p.sharing.member);localMember=p.sharing.member;}const current=config,result=await assessPackageTrust(pkg,p.sharing.member?.id||null,identity.publicKey,current.contacts,current.pins);if(current!==config)return {trusted:false,status:'Unavailable',reason:'Contacts changed during verification. Check again.'};return result;}
 async function sync(id,full=false){
  const peer=config.peers.find(p=>p.id===id);if(!peer)throw Error('Peer no longer exists.');if(busy.has(id))throw Error('This peer is already syncing.');busy.add(id);const started=Date.now();let known=full?[]:durableInbox.known(id),received=false;
  try{
   const study=restorePortfolio(await studyReader());if(peer.invite.version!==3||study.sharing.member?.id!==peer.invite.recipientId)throw Error('Recipient identity does not match.');requireContact(peer.invite.publisher.id,peer.invite.publisherIdentity.publicKey);await bindMember(study.sharing.member);
   for(let batch=0;batch<50;batch++){
    if(Date.now()-started>90000)throw Error('Sync time budget reached. Received batches were retained; retry to continue.');
    const pkg=await pullPeer(peer.invite,fetcher,identity,remoteGuard,PEER_CAPABILITIES,known);if(!config.peers.some(p=>p.id===id))return;
    const trust=await trustPackage(pkg);if(!trust.trusted)throw Error(trust.reason);if(!config.peers.some(p=>p.id===id))return;
    await inboxMutation(()=>{
     if(!config.peers.some(p=>p.id===id))return;requireContact(peer.invite.publisher.id,peer.invite.publisherIdentity.publicKey);
     if(pkg.records.length){durableInbox.receive(id,pkg);received=true;}
     const value={checkedAt:new Date().toISOString(),receivedAt:received?new Date().toISOString():status.get(id)?.receivedAt,records:pkg.exchange?.total??pkg.records.length,error:null};durableInbox.check(id,value);status.set(id,value);
    });
    if(!config.peers.some(p=>p.id===id))return;
    const current=new Map(known.map(r=>[r.id,r]));for(const r of durableInbox.known(id))if(!full||pkg.records.some(record=>record.id===r.id))current.set(r.id,r);known=[...current.values()];
    if(!pkg.exchange?.remaining)return;
    if(!pkg.records.length)throw Error('Peer advertised remaining updates without making progress.');
   }
   throw Error('Sync batch limit reached. Received batches were retained; retry to continue.');
  }catch(e){
   if(config.peers.some(p=>p.id===id)){const value={...status.get(id),checkedAt:new Date().toISOString(),error:e instanceof RemoteNetworkError||e instanceof PeerCompatibilityError?e.message+' Older received data was retained.':String(e.message||'Sync failed.').slice(0,160)+' Check connectivity, invitation, clocks, capacity and companion status. Received data was retained.'};await inboxMutation(()=>{if(config.peers.some(p=>p.id===id)){durableInbox.check(id,value);status.set(id,value);}});}throw e instanceof RemoteNetworkError||e instanceof PeerCompatibilityError?e:Error('Could not finish syncing this peer. Received batches were retained; check connectivity, capacity and clocks, then retry.');
  }finally{busy.delete(id);}
 }
 const peerServer=createServer({maxHeaderSize:8192},async(req,res)=>{
  let grant,requestId,context;try{
   if(req.method!=='POST'||!/^\/v1\/pull\/[a-f0-9-]{36}$/.test(req.url||'')||req.headers.origin) return send(res,404,{error:'Unavailable'});
   const remote=req.socket.remoteAddress||'',now=Date.now(),limit=rates.get(remote)||{at:now,count:0};if(now-limit.at>60000){limit.at=now;limit.count=0;}if(++limit.count>60)return send(res,429,{error:'Rate limit'});rates.set(remote,limit);if(rates.size>1024)rates.delete(rates.keys().next().value);
   grant=config.grants.find(g=>g.id===req.url.split('/').at(-1));if(!grant||grant.policy!=='pairwise-signed-v1'||!grant.recipientKey||grant.publisherKey!==identity.publicKey)return send(res,404,{error:'Unavailable'});context=`v1:${grant.id}:${grant.groupId}`;
   const value=z.object({operation:z.literal('pull'),requestId:uuid,sentAt:z.number().finite(),capabilities:peerCapabilitiesSchema.optional(),known:knownRecordsSchema.optional(),signature:z.string().regex(/^[A-Za-z0-9_-]{86}$/)}).strict().parse(openPeer(await body(req,100000),grant.secret,'request',context));requestId=value.requestId;
   const {signature,...signedRequest}=value;if(!verifyValue(grant.recipientKey,'field-desk-pull-v1',{context,...signedRequest},signature))throw Error('Recipient signature invalid');
   if(value.operation!=='pull'||!Number.isFinite(value.sentAt)||Math.abs(now-value.sentAt)>120000)throw Error('Expired request');
   for(const [key,expiry]of replays)if(expiry<now)replays.delete(key);const replay=grant.id+':'+requestId;if(replays.has(replay)||replays.size>=5000)throw Error('Replayed request');replays.set(replay,now+300000);
   let pkg;try{
    const portfolio=restorePortfolio(await studyReader());if(portfolio.sharing.member?.id!==grant.publisherId)throw Error('Publisher identity changed.');await bindMember(portfolio.sharing.member);localMember=portfolio.sharing.member;
    const group=portfolio.sharing.groups.find(g=>g.id===grant.groupId);if(!group||grant.recordIds.some(id=>!group.records.some(r=>r.id===id)))throw Error('Shared saved scope is unavailable.');
    const records=outboundRecords(portfolio,group,grant.recordIds,grant.recipientId),capabilities=value.capabilities||LEGACY_CAPABILITIES;
    requirePackageCapabilities({records},capabilities);
    const incremental=capabilities.features.includes('record-batches-v1')&&!!value.known;
    if(value.known&&!capabilities.features.includes('record-batches-v1'))throw new PeerCompatibilityError('Peer update required for incremental exchange.');
    const batch=incremental?chooseRecordBatch(records,value.known):{recordIds:grant.recordIds};
    pkg=await signSavedPackage(portfolio,grant.groupId,batch.recordIds,grant.recipientId,identity,batch.exchange);checkAuthors(pkg,identity.publicKey,grant.recipientId,grant.recipientKey);
   }catch(e){return send(res,200,sealPeer({requestId,sentAt:Date.now(),error:e instanceof PeerCompatibilityError?e.message:'Shared saved data is unavailable or an individual signed record is too large. Save the selected scope and check capacity; history was not trimmed.',...(e instanceof PeerCompatibilityError?{code:'compatibility'}:{})},grant.secret,'response',context+':'+requestId));}
   // Recheck revocation after awaited storage read.
   if(!config.grants.some(g=>g.id===grant.id)||config.contacts.find(c=>c.id===grant.recipientId)?.status==='Blocked')return send(res,404,{error:'Unavailable'});
   try{requirePackageCapabilities(pkg,value.capabilities||LEGACY_CAPABILITIES);}catch(e){return send(res,200,sealPeer({requestId,sentAt:Date.now(),error:e instanceof PeerCompatibilityError?e.message:'Invalid peer capabilities. Update both instances.',code:'compatibility'},grant.secret,'response',context+':'+requestId));}
   send(res,200,sealPeer({requestId,sentAt:Date.now(),package:pkg},grant.secret,'response',context+':'+requestId));
  }catch{send(res,404,{error:'Unavailable'});}
 });
 const controlServer=createServer({maxHeaderSize:8192},async(req,res)=>{
  let cors={};try{
   const expected=`127.0.0.1:${controlServer.address().port}`;if(![expected,`localhost:${controlServer.address().port}`].includes(req.headers.host))return send(res,403,{error:'Local control only.'});
   let origin;try{origin=new URL(req.headers.origin);}catch{return send(res,403,{error:'Open controls in your local Field Desk app.'});}
   if(origin.protocol!=='http:'||!['127.0.0.1','localhost'].includes(origin.hostname)||origin.origin!==req.headers.origin||req.headers['sec-fetch-site']==='cross-site')return send(res,403,{error:'Local control only.'});
   cors={'Access-Control-Allow-Origin':origin.origin,'Vary':'Origin'};
   if(req.method==='OPTIONS')return send(res,200,{}, {...cors,'Access-Control-Allow-Methods':'GET, POST','Access-Control-Allow-Headers':'Content-Type, X-Field-Desk-Sync'});
   if(req.headers['x-field-desk-sync']!=='1')return send(res,403,{error:'Local control header required.'},cors);
   if(req.method==='GET'&&req.url==='/state')return send(res,200,publicState(),cors);
   if(req.method==='GET'&&req.url==='/permissions'){const portfolio=restorePortfolio(await studyReader()),snapshot=config,entries=[];for(const peer of snapshot.peers){const last=inboxEntries().filter(e=>e.peerId===peer.id).sort((a,b)=>b.receivedAt.localeCompare(a.receivedAt))[0];if(last)entries.push(await verifiedInbox(last.id));}if(snapshot!==config)throw Error('Contact settings changed. Refresh permissions again.');return send(res,200,permissionsView(portfolio,snapshot,entries),cors);}
   if(req.method==='GET'&&req.url==='/inbox-status')return send(res,200,inboxSummary(),cors);
   if(req.method==='GET'&&/^\/inbox-entry\/[a-f0-9-]{36}$/.test(req.url||'')){const entry=await verifiedInbox(req.url.split('/').at(-1));return send(res,200,{...entry,stale:!!status.get(entry.peerId)?.error},cors);}
   if(req.method==='GET'&&/^\/inbox\/[a-f0-9-]{36}$/.test(req.url||'')){const peerId=req.url.split('/').at(-1),last=inboxEntries().find(e=>e.peerId===peerId);if(!last)return send(res,404,{error:'No received package. Sync this peer first.'},cors);const entry=await verifiedInbox(last.id);return send(res,200,{...entry,receivedAt:status.get(peerId)?.receivedAt||entry.receivedAt,stale:!!status.get(peerId)?.error},cors);}
   if(req.method!=='POST')return send(res,404,{error:'Unavailable'},cors);
   const v=await body(req,req.url==='/verify-package'?MAX_SHARED_BYTES+1000:24000);
   if(req.url==='/network')return send(res,200,await networkCheck(),cors);
   if(req.url==='/diagnostics'){
    const id=uuid.parse(v.id),peer=config.peers.find(p=>p.id===id);if(!peer)throw Error('Peer not found.');if(busy.has(id))throw Error('This peer is already being checked.');busy.add(id);
    try{const study=restorePortfolio(await studyReader());if(peer.invite.version!==3||study.sharing.member?.id!==peer.invite.recipientId)throw Error('Recipient mismatch');requireContact(peer.invite.publisher.id,peer.invite.publisherIdentity.publicKey);await bindMember(study.sharing.member);const pkg=await pullPeer(peer.invite,fetcher,identity,remoteGuard),trust=await trustPackage(pkg);if(!trust.trusted||!config.peers.some(p=>p.id===id))throw Error('Trust or connection changed');return send(res,200,{ok:true,checkedAt:new Date().toISOString(),message:'Authenticated connection succeeded. A signed contribution batch verified; nothing merged or queued.'},cors);}catch(e){return send(res,200,{ok:false,checkedAt:new Date().toISOString(),message:e instanceof RemoteNetworkError||e instanceof PeerCompatibilityError?e.message:'Connection test failed. Confirm both companions are running, Tailscale device sharing is accepted, TCP peer-port access is allowed, the invitation is valid and clocks are accurate.'},cors);}finally{busy.delete(id);}
   }
   if(req.url==='/inbox/clear-reviewed'){const count=await inboxMutation(()=>durableInbox.clearReviewed());return send(res,200,{count},cors);}
   if(req.url==='/inbox/review'){
    const id=uuid.parse(v.id),entry=await verifiedInbox(id),verifiedConfig=config;
    const expected={state:z.enum(['Pending','Deferred','Dismissed','Merged']).parse(v.expectedState),reviewedAt:z.string().datetime().nullable().parse(v.expectedReviewedAt)};
    if(v.state==='Merged'){
     const study=restorePortfolio(await studyReader()),group=study.sharing.groups.find(g=>g.id===entry.package.group.id);
     for(const record of entry.package.records){const saved=group?.records.find(r=>r.id===record.id);if(!saved||canonical(saved.member)!==canonical(record.member))throw Error('Save all contributions from this package before marking it merged.');for(const [events,stored] of [[record.revisions,saved.revisions],[record.reviews,saved.reviews]])for(const event of events){const old=stored.find(e=>e.id===event.id);if(!old||canonical(old)!==canonical(event)||group.signatures[record.id+':'+event.id]?.publicKey!==entry.package.auth.events[record.id+':'+event.id]?.publicKey)throw Error('Save all contributions and signature proofs before marking this package merged.');}}
    }
    const decision=await inboxMutation(()=>{if(config!==verifiedConfig)throw Error('Contact or connection settings changed. Refresh before deciding.');if(!config.peers.some(p=>p.id===entry.peerId))throw Error('Peer disconnected.');requireContact(entry.package.sender.id,entry.package.auth.publisher.publicKey);return durableInbox.decide(id,v.digest,v.state,v.reason,expected);});return send(res,200,{entry:{id:decision.id,state:decision.state}},cors);
   }
   if(req.url==='/verify-package'){const pkg=parseSharedPackage(JSON.stringify(v.package));return send(res,200,await trustPackage(pkg),cors);}
   if(req.url==='/contacts/add'){const card=await verifyIdentity(v.identity),name=label.parse(v.label),owner=restorePortfolio(await studyReader()).sharing.member;if(!owner)throw Error('Set your contributor name and Save study first.');await bindMember(owner);if(card.member.id===owner.id||card.member.id===identity.memberId)throw Error('This is your own identity.');await mutate(c=>{requireContact(card.member.id,card.publicKey);if(c.pins[card.member.id]&&c.pins[card.member.id]!==card.publicKey)throw Error('Pinned key changed.');const previous=c.contacts.find(x=>x.id===card.member.id);if(previous){previous.label=name;previous.identity=card;previous.updatedAt=new Date().toISOString();}else c.contacts.push({id:card.member.id,label:name,publicKey:card.publicKey,identity:card,status:'Pending',verifiedAt:null,updatedAt:new Date().toISOString()});});return send(res,200,{ok:true},cors);}
   if(req.url==='/contacts/verify'){const id=uuid.parse(v.id);await mutate(async c=>{const contact=c.contacts.find(x=>x.id===id);if(!contact||contact.status==='Blocked'||!contact.identity)throw Error('Add a valid identity card before verifying.');if(v.verifiedFingerprint!==await fingerprint(contact.publicKey))throw Error('Compare the complete fingerprint independently.');rememberVerified(c,await verifyIdentity(contact.identity),contact.label);});return send(res,200,{ok:true},cors);}
   if(req.url==='/contacts/block'||req.url==='/contacts/disconnect'||req.url==='/contacts/unblock'){const id=uuid.parse(v.id);let removed=[];await mutate(c=>{const contact=c.contacts.find(x=>x.id===id);if(!contact)throw Error('Contact not found.');if(req.url==='/contacts/unblock'){if(contact.status!=='Blocked')throw Error('Contact is not blocked.');contact.status='Pending';contact.verifiedAt=null;}else{removed=c.peers.filter(p=>p.invite.version>=2&&p.invite.publisher.id===id).map(p=>p.id);c.peers=c.peers.filter(p=>!removed.includes(p.id));c.grants=c.grants.filter(g=>g.recipientId!==id);if(req.url==='/contacts/block')contact.status='Blocked';}contact.updatedAt=new Date().toISOString();});for(const peer of removed){durableInbox.removePeer(peer);status.delete(peer);}return send(res,200,{ok:true},cors);}
   if(req.url==='/identity'){const portfolio=restorePortfolio(await studyReader());if(!portfolio.sharing.member)throw Error('Set your contributor name and Save study first.');await bindMember(portfolio.sharing.member);localMember=portfolio.sharing.member;return send(res,200,{identity:identityCard(identity,localMember),fingerprint:await fingerprint(identity.publicKey)},cors);}
   if(req.url==='/preview'||req.url==='/grants'){
    const input=z.object({groupId:uuid,label:req.url==='/preview'?label.default('Preview'):label,recordIds:z.array(uuid).min(1).max(MAX_GROUP_RECORDS),recipientId:uuid,recipientIdentity:identityCardSchema,verifiedFingerprint:z.string().min(1).max(100)}).strict().parse(v),portfolio=restorePortfolio(await studyReader());if(input.recipientId===portfolio.sharing.member?.id)throw Error('Choose another contributor as recipient.');const recipientIdentity=await verifyIdentity(input.recipientIdentity);if(recipientIdentity.member.id!==input.recipientId||input.verifiedFingerprint!==await fingerprint(recipientIdentity.publicKey))throw Error('Compare the recipient fingerprint and identity before publishing.');if(config.pins[input.recipientId]&&config.pins[input.recipientId]!==recipientIdentity.publicKey)throw Error('Recipient signing key changed. Existing pin retained; investigate before reconnecting.');requireContact(input.recipientId,recipientIdentity.publicKey);await bindMember(portfolio.sharing.member);localMember=portfolio.sharing.member;const scope=await signScopeBatches(portfolio,input.groupId,input.recordIds,input.recipientId,identity);for(const pkg of scope.packages)checkAuthors(pkg,identity.publicKey,input.recipientId,recipientIdentity.publicKey);requireContact(input.recipientId,recipientIdentity.publicKey);if(req.url==='/preview')return send(res,200,{package:scope.packages[0],packages:scope.packages,excluded:input.recordIds.length-scope.records.length},cors);if(scope.records.length!==new Set(input.recordIds).size)throw Error('Selection includes third-party or unknown-origin records. Review the filtered preview and select only eligible contributions.');
    if(tailscale){const snapshot=await readTailscaleStatus(tailscaleRunner);if(snapshot.state!=='Running'||!snapshot.selfOnline||!snapshot.selfIPs.includes(host))throw new RemoteNetworkError('Tailscale is disconnected or its address changed. Restart remote sync before creating an invitation.');}
    const grant={id:randomUUID(),groupId:input.groupId,label:input.label,recipientId:input.recipientId,policy:'pairwise-signed-v1',publisherKey:identity.publicKey,recipientKey:recipientIdentity.publicKey,publisherId:portfolio.sharing.member.id,recordIds:[...new Set(input.recordIds)],secret:randomBytes(32).toString('base64url'),createdAt:new Date().toISOString()};await mutate(c=>{rememberVerified(c,recipientIdentity,input.label);c.grants.push(grant);});
    const group=portfolio.sharing.groups.find(g=>g.id===input.groupId),invite={format:'field-desk-peer-invite',version:3,policy:'pairwise-signed-v1',publisher:portfolio.sharing.member,publisherIdentity:identityCard(identity,portfolio.sharing.member),recipientIdentity,recipientId:grant.recipientId,endpoint:publicState().endpoint,grantId:grant.id,groupId:grant.groupId,groupName:group.name,secret:grant.secret,capabilities:PEER_CAPABILITIES};return send(res,200,{invite:{...invite,signature:signValue(identity,'field-desk-invite-v1',invite)}},cors);
   }
   if(req.url==='/scope/preview'||req.url==='/scope/replace'){
    const input=z.object({id:uuid,recordIds:z.array(uuid).min(1).max(MAX_GROUP_RECORDS).refine(ids=>new Set(ids).size===ids.length),previewHash:z.string().regex(/^[a-f0-9]{64}$/).optional()}).strict().parse(v);
    const portfolio=restorePortfolio(await studyReader()),grant=config.grants.find(g=>g.id===input.id),contact=config.contacts.find(c=>c.id===grant?.recipientId);
    if(!grant||grant.policy!=='pairwise-signed-v1'||!contact?.identity||contact.status!=='Verified'||contact.publicKey!==grant.recipientKey||grant.publisherKey!==identity.publicKey||portfolio.sharing.member?.id!==grant.publisherId)throw Error('Verified active invitation and saved publisher identity required.');
    requireContact(contact.id,contact.publicKey);await bindMember(portfolio.sharing.member);
    const snapshotHash=(study,g,c)=>createHash('sha256').update(canonical({study,grant:g,contact:c,recordIds:[...input.recordIds].sort()})).digest('hex');
    const hash=snapshotHash(portfolio,grant,contact),scope=await signScopeBatches(portfolio,grant.groupId,input.recordIds,grant.recipientId,identity);
    for(const pkg of scope.packages)checkAuthors(pkg,identity.publicKey,grant.recipientId,grant.recipientKey);
    if(scope.records.length!==input.recordIds.length)throw Error('Selection includes third-party or unknown-origin content. Nothing changed.');
    if(req.url==='/scope/preview')return send(res,200,{hash,package:scope.packages[0],packages:scope.packages,added:input.recordIds.filter(id=>!grant.recordIds.includes(id)),removed:grant.recordIds.filter(id=>!input.recordIds.includes(id))},cors);
    if(input.previewHash!==hash)throw Error('Saved study or sharing permissions changed. Preview this scope again.');
    if(tailscale){const snapshot=await readTailscaleStatus(tailscaleRunner);if(snapshot.state!=='Running'||!snapshot.selfOnline||!snapshot.selfIPs.includes(host))throw new RemoteNetworkError('Restart remote sync before renewing an invitation.');}
    const replacement={...grant,id:randomUUID(),recordIds:input.recordIds,secret:randomBytes(32).toString('base64url'),createdAt:new Date().toISOString()};
    const recipientIdentity=await verifyIdentity(contact.identity),group=portfolio.sharing.groups.find(g=>g.id===grant.groupId);
    const invite={format:'field-desk-peer-invite',version:3,policy:'pairwise-signed-v1',publisher:portfolio.sharing.member,publisherIdentity:identityCard(identity,portfolio.sharing.member),recipientIdentity,recipientId:grant.recipientId,endpoint:publicState().endpoint,grantId:replacement.id,groupId:grant.groupId,groupName:group.name,secret:replacement.secret,capabilities:PEER_CAPABILITIES};
    await mutate(async c=>{const current=c.grants.find(g=>g.id===input.id),currentContact=c.contacts.find(x=>x.id===grant.recipientId),saved=restorePortfolio(await studyReader());if(!current||!currentContact||snapshotHash(saved,current,currentContact)!==input.previewHash)throw Error('Saved study or permissions changed. Preview this scope again.');c.grants=c.grants.map(g=>g.id===input.id?replacement:g);});
    return send(res,200,{invite:{...invite,signature:signValue(identity,'field-desk-invite-v1',invite)}},cors);
   }
   if(req.url==='/revoke'){const id=uuid.parse(v.id);await mutate(c=>{c.grants=c.grants.filter(g=>g.id!==id);});return send(res,200,{ok:true},cors);}
   if(req.url==='/peers'){const invite=parsePeerInvite(v.invitation),name=label.parse(v.label);const portfolio=restorePortfolio(await studyReader());if(!portfolio.sharing.member)throw Error('Set your contributor name and Save study first.');await bindMember(portfolio.sharing.member);await verifyInvitation(invite);if(!invite.capabilities)throw new PeerCompatibilityError('Peer update required. Ask for a renewed invitation from an updated instance.');if(v.verifiedFingerprint!==await fingerprint(invite.publisherIdentity.publicKey))throw Error('Compare the publisher fingerprint before connecting.');if(invite.recipientIdentity.publicKey!==identity.publicKey)throw Error('Invitation belongs to a different signing key.');if(config.pins[invite.publisher.id]&&config.pins[invite.publisher.id]!==invite.publisherIdentity.publicKey)throw Error('Publisher signing key changed. Existing pin retained; investigate before reconnecting.');if(portfolio.sharing.member?.id!==invite.recipientId)throw Error('This invitation belongs to another contributor. Check your contributor ID.');const id=await mutate(c=>{rememberVerified(c,invite.publisherIdentity,name);if(c.peers.some(p=>p.invite.grantId===invite.grantId&&p.invite.endpoint===invite.endpoint))throw Error('This invitation is already connected.');const id=randomUUID();c.peers.push({id,label:name,invite,automatic:false});return id;});return send(res,200,{id},cors);}
   if(req.url==='/automatic'){const id=uuid.parse(v.id),automatic=z.boolean().parse(v.enabled);await mutate(c=>{const peer=c.peers.find(p=>p.id===id);if(!peer)throw Error('Peer not found.');peer.automatic=automatic;});return send(res,200,{ok:true},cors);}
   if(req.url==='/forget'){const id=uuid.parse(v.id);await mutate(c=>{c.peers=c.peers.filter(p=>p.id!==id);});durableInbox.removePeer(id);status.delete(id);return send(res,200,{ok:true},cors);}
   if(req.url==='/sync'){const id=uuid.parse(v.id),full=v.full===undefined?false:z.boolean().parse(v.full);await sync(id,full);return send(res,200,{ok:true},cors);}
   send(res,404,{error:'Unavailable'},cors);
  }catch(e){send(res,400,{error:e instanceof z.ZodError?'Check the input format and limits.':String(e.message||'Sync action failed.').slice(0,250)},cors);}
 });
 for(const server of [peerServer,controlServer]){server.requestTimeout=20000;server.headersTimeout=10000;server.maxHeadersCount=30;server.keepAliveTimeout=1000;}
 try{await listen(controlServer,controlPort,'127.0.0.1');await listen(peerServer,port,host);}catch(e){controlServer.close();peerServer.close();durableInbox.close();await lock.close();await unlink(lockPath);throw e;}
 const timer=setInterval(()=>{if(!closed)for(const p of config.peers)if(p.automatic&&!busy.has(p.id))void sync(p.id).catch(()=>{});},pollMs);timer.unref();
 return {state:publicState,sync,pull:(invite,transport=fetcher)=>pullPeer(invite,transport,identity,remoteGuard),async close(){closed=true;clearInterval(timer);for(const server of [peerServer,controlServer]){server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}await chain;await identityChain;durableInbox.close();await lock.close();await unlink(lockPath);}};
}
