import {z} from 'zod';
import {validPoint} from './location-core';
import type {Bounds} from './area-cache';
export const radioDirectory='https://hearham.com/repeaters/';
export const radioApi='https://hearham.com/api/repeaters/v1';
const mhz=z.string().trim().max(24).refine(s=>/^\d+(?:\.\d{1,6})?$/.test(s)&&Number(s)>0&&Number(s)<=10000,'Use a frequency in MHz');
const optionalMHz=z.union([z.literal(''),mhz]);
const date=z.string().refine(s=>!s||/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s,'Use a valid date');
const url=z.string().max(2000).refine(s=>{if(!s)return true;try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password;}catch{return false;}},'Use an http/https source link');
export const radioChannelSchema=z.object({id:z.string().min(1).max(100),name:z.string().trim().min(1).max(160),service:z.enum(['Amateur repeater','Weather radio','GMRS','Public safety','Broadcast','Other']),receiveMHz:mhz,transmitMHz:optionalMHz.default(''),mode:z.string().max(60).default(''),tone:z.string().max(100).default(''),callsign:z.string().max(60).default(''),source:z.string().max(200).default(''),sourceUrl:url.default(''),sourceDate:date.default(''),collectedAt:z.string().datetime().optional(),verification:z.enum(['Not checked','Heard','Not heard']).default('Not checked'),checkedOn:date.default(''),notes:z.string().max(4000).default('')}).superRefine((r,c)=>{if(r.verification!=='Not checked'&&!r.checkedOn)c.addIssue({code:z.ZodIssueCode.custom,path:['checkedOn'],message:'Record when reception was checked'});});
export const radioPlanSchema=z.array(radioChannelSchema).max(200).default([]).refine(v=>new Set(v.map(r=>r.id)).size===v.length,'Use unique radio entry IDs');
export type RadioChannel=z.infer<typeof radioChannelSchema>;
export type RadioRepeater={id:string;name:string;lat:number;lng:number;category:'Radio repeaters';source:'HearHam repeaters';url:string;detail:string;radio:{receiveMHz:string;transmitMHz?:string;offsetMHz?:number;mode:string;encode:string;decode:string;callsign:string;city:string;operational:string;restriction:string};retrievedAt?:string;stale?:boolean};
export function newRadioChannel():RadioChannel{return {id:crypto.randomUUID(),name:'',service:'Other',receiveMHz:'',transmitMHz:'',mode:'',tone:'',callsign:'',source:'',sourceUrl:'',sourceDate:'',verification:'Not checked',checkedOn:'',notes:''};}
export function radioBounds(b:Bounds):Bounds{const lat=(b[0]+b[2])/2,lng=(b[1]+b[3])/2,dy=40/111.32,dx=40/(111.32*Math.max(.6,Math.cos(lat*Math.PI/180)));return [Math.max(-90,lat-dy),Math.max(-180,lng-dx),Math.min(90,lat+dy),Math.min(180,lng+dx)];}
export function distanceKm(a:[number,number],b:[number,number]){const r=Math.PI/180,dlat=(b[0]-a[0])*r,dlng=(b[1]-a[1])*r,h=Math.sin(dlat/2)**2+Math.cos(a[0]*r)*Math.cos(b[0]*r)*Math.sin(dlng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(Math.max(0,1-h)));}
export function parseRepeaters(data:unknown,b:Bounds){if(!Array.isArray(data)||data.length<1||data.length>100000)throw Error('Repeater directory returned an invalid or empty bulk response');const rows:RadioRepeater[]=[];let invalid=0;const seen=new Set<string>();
 for(const x of data){if(!x||typeof x!=='object'||!Number.isFinite(x.latitude)||!Number.isFinite(x.longitude)||Math.abs(x.latitude)>90||Math.abs(x.longitude)>180||!Number.isFinite(x.frequency)||x.frequency<=0||x.frequency>1e10||!['string','number'].includes(typeof x.id)){invalid++;continue;}if(x.latitude<b[0]||x.latitude>b[2]||x.longitude<b[1]||x.longitude>b[3])continue;
 const id='hearham:'+x.id;if(seen.has(id))continue;seen.add(id);const receiveMHz=(x.frequency/1e6).toFixed(6).replace(/0+$/,'').replace(/\.$/,'');const offset=Number.isFinite(x.offset)?x.offset/1e6:undefined;const transmit=offset!==undefined&&x.frequency+x.offset>0?(x.frequency/1e6+offset).toFixed(6).replace(/0+$/,'').replace(/\.$/,''):undefined;
 const text=(v:unknown,max=200)=>typeof v==='string'?v.slice(0,max):'';const callsign=text(x.callsign,60),mode=text(x.mode,60),city=text(x.city),encode=text(x.encode,100),decode=text(x.decode,100),restriction=text(x.restriction,500);const radio={receiveMHz,transmitMHz:transmit,offsetMHz:offset,mode,city,callsign,encode,decode,operational:x.operational===undefined?'Not supplied':String(x.operational).slice(0,60),restriction};
 rows.push({id,name:(callsign||'Repeater')+' · '+receiveMHz+' MHz',lat:x.latitude,lng:x.longitude,category:'Radio repeaters',source:'HearHam repeaters',url:radioDirectory,radio,detail:`${city} · Receive ${receiveMHz} MHz${transmit?' · Input '+transmit+' MHz (derived from published offset)':''} · ${mode||'Mode not supplied'} · Source encode: ${encode||'not supplied'} / decode: ${decode||'not supplied'} · ${text(x.description,1200)} · Approximate directory coordinates; reception and access not verified. Source record date unavailable.`});}
 if(invalid===data.length)throw Error('Repeater directory fields no longer match the expected format');return {rows,invalid};}
export async function fetchRadioCell(b:Bounds,fetcher:typeof fetch=fetch){const r=await fetcher(radioApi,{headers:{Accept:'application/json','User-Agent':'FieldDesk/0.1 (+local-area-study)'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('HearHam directory returned HTTP '+r.status);const {rows,invalid}=parseRepeaters(await r.json(),b);return {rows,invalid};}
export function channelFromRepeater(p:RadioRepeater):RadioChannel{return {...newRadioChannel(),name:p.name,service:'Amateur repeater',receiveMHz:p.radio.receiveMHz,transmitMHz:p.radio.transmitMHz||'',mode:p.radio.mode,callsign:p.radio.callsign,tone:`Source encode ${p.radio.encode||'unknown'} / decode ${p.radio.decode||'unknown'}`,source:p.source,sourceUrl:p.url,collectedAt:p.retrievedAt,notes:p.detail};}

export function validRadioBounds(b:number[]){return b.length===4&&validPoint(b[0],b[1])&&validPoint(b[2],b[3])&&b[0]<b[2]&&b[1]<b[3]&&b[2]-b[0]<=1&&b[3]-b[1]<=1.5;}
