import {z} from 'zod';
import {evidenceSchema,type Evidence} from './collection';
const id=z.string().min(1).max(100);
const day=z.string().refine(v=>v===''||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v),'Choose a valid date');
const url=z.string().max(2000).refine(v=>{if(!v)return true;try{return ['https:','http:'].includes(new URL(v).protocol);}catch{return false;}},'Use an http or https source URL');
const links=z.array(id).max(100).refine(v=>new Set(v).size===v.length,'Duplicate links');
const unique=(v:{id:string}[])=>new Set(v.map(x=>x.id)).size===v.length;
export const indicatorSchema=z.object({id,name:z.string().trim().min(1).max(300),condition:z.string().max(2000),basis:z.enum(['User plan','Official instruction']),source:z.string().max(1000),sourceUrl:url,sourceDate:day,evidenceIds:links}).superRefine((s,c)=>{if(s.basis==='Official instruction'&&(!s.source.trim()||!s.sourceUrl||!s.sourceDate))c.addIssue({code:z.ZodIssueCode.custom,path:['basis'],message:'Official instructions need a source, URL and source date'});});
const actionSchema=z.object({id,action:z.string().trim().min(1).max(1000),when:z.string().max(1000),responsibility:z.string().max(300),constraints:z.string().max(2000)});
const exerciseSchema=z.object({id,date:day,outcome:z.string().trim().min(1).max(2000),gaps:z.string().max(4000)});
export const scenarioCoreSchema=z.object({id,title:z.string().trim().min(1).max(160),hazard:z.string().max(100),status:z.enum(['Draft','Reviewed','Retired']),scope:z.enum(['AOR','AOI','Route','Other']),description:z.string().max(4000),exposure:z.string().max(4000),likelihood:z.enum(['Unknown','Unlikely','Possible','Likely']),impact:z.enum(['Unknown','Minor','Moderate','Severe']),assessmentReason:z.string().max(4000),confidence:z.enum(['Unassessed','Low','Moderate','High']),confidenceReason:z.string().max(2000),assumptions:z.string().max(4000),assessedOn:day,reviewOn:day,questionIds:links,naiIds:links,servicePlanIds:links,routeIds:links,evidence:z.array(evidenceSchema).max(30).refine(unique,'Duplicate evidence IDs'),indicators:z.array(indicatorSchema).max(20).refine(unique,'Duplicate indicator IDs'),actions:z.array(actionSchema).max(20).refine(unique,'Duplicate action IDs'),exercises:z.array(exerciseSchema).max(20).refine(unique,'Duplicate exercise IDs'),createdAt:z.string().datetime()});
const versionSchema=z.object({id,recordedAt:z.string().datetime(),snapshot:scenarioCoreSchema,linkLabels:z.array(z.string().max(500)).max(400)});
export const scenarioSchema=scenarioCoreSchema.extend({history:z.array(versionSchema).max(20).refine(unique,'Duplicate assessment versions')}).superRefine((s,c)=>{const ids=new Set(s.evidence.map(e=>e.id));if(s.indicators.some(i=>i.evidenceIds.some(id=>!ids.has(id))))c.addIssue({code:z.ZodIssueCode.custom,path:['indicators'],message:'Indicator evidence must belong to this scenario'});if(s.status==='Reviewed'&&(!s.assessedOn||!s.reviewOn||!s.assessmentReason.trim()||s.confidence==='Unassessed'||!s.confidenceReason.trim()))c.addIssue({code:z.ZodIssueCode.custom,path:['status'],message:'Reviewed scenarios need assessment/review dates, rationale and assessed confidence'});});
export const scenariosSchema=z.array(scenarioSchema).max(50).refine(unique,'Duplicate scenario IDs').default([]);
export type Scenario=z.infer<typeof scenarioSchema>;
export type Indicator=z.infer<typeof indicatorSchema>;
export const scenarioTemplates=[
 {title:'Flooding disrupts access',hazard:'Flooding',description:'Assess access between this location and essential destinations during flooding.',indicator:'Access crossing changes status',condition:'Review official closure reports and the alternate route before travel.'},
 {title:'Severe heat with power loss',hazard:'Heat / electricity',description:'Plan cooling, communications and essential-service alternatives during heat and a power interruption.',indicator:'Cooling or power unavailable',condition:'Define your household-specific threshold and verify cooling destinations.'},
 {title:'Water advisory or supply interruption',hazard:'Water',description:'Plan alternate water supplies and affected service dependencies.',indicator:'Provider issues an advisory',condition:'Check the advisory’s affected addresses, dates and instructions.'},
 {title:'Wildfire smoke or evacuation',hazard:'Wildfire',description:'Assess smoke exposure, official evacuation instructions and destination alternatives.',indicator:'Official conditions change',condition:'Review current official alerts, orders and route constraints.'},
 {title:'Winter weather interrupts services',hazard:'Winter weather',description:'Plan for limited road access, heating, power and water disruptions.',indicator:'Travel or essential service disrupted',condition:'Define a sourced decision trigger and check alternatives.'},
];
export function newIndicator():Indicator{return {id:crypto.randomUUID(),name:'New warning indicator',condition:'',basis:'User plan',source:'',sourceUrl:'',sourceDate:'',evidenceIds:[]};}
export function newScenario(template?:typeof scenarioTemplates[number]):Scenario{return {id:crypto.randomUUID(),title:template?.title||'New scenario',hazard:template?.hazard||'Other',status:'Draft',scope:'AOI',description:template?.description||'',exposure:'',likelihood:'Unknown',impact:'Unknown',assessmentReason:'',confidence:'Unassessed',confidenceReason:'',assumptions:'',assessedOn:'',reviewOn:'',questionIds:[],naiIds:[],servicePlanIds:[],routeIds:[],evidence:[],indicators:template?[{...newIndicator(),name:template.indicator,condition:template.condition}]:[],actions:[],exercises:[],history:[],createdAt:new Date().toISOString()};}
export function removeScenarioEvidence(s:Scenario,id:string):Scenario{return {...s,evidence:s.evidence.filter(e=>e.id!==id),indicators:s.indicators.map(i=>({...i,evidenceIds:i.evidenceIds.filter(x=>x!==id)}))};}
export type ScenarioOptions={questions:{id:string;question:string}[],areas:{id:string;name:string}[],services:{id:string;name:string}[],routes:{id:string;name:string;role:string}[]};
export function scenarioMissingLinks(s:Scenario,o:ScenarioOptions){return ([['questionIds',o.questions],['naiIds',o.areas],['servicePlanIds',o.services],['routeIds',o.routes]] as const).flatMap(([key,items])=>s[key].filter(id=>!items.some(x=>x.id===id)).map(id=>({key,id})));}
export function scenarioFlags(s:Scenario,today:string){return {reviewDue:s.status!=='Retired'&&!!s.reviewOn&&s.reviewOn<=today,gaps:s.status!=='Retired'&&(!s.evidence.length||!s.indicators.length||s.indicators.some(i=>!i.condition.trim()||!i.evidenceIds.length)||!s.actions.length||s.actions.some(a=>!a.when.trim())||!s.exposure.trim()||!s.assumptions.trim()||(s.scope==='Route'&&!s.routeIds.length)||s.likelihood==='Unknown'||s.impact==='Unknown'||!s.reviewOn||!s.assessedOn||!s.assessmentReason.trim()||!s.confidenceReason.trim()||s.confidence==='Unassessed')};}
export function archiveScenario(s:Scenario,linkLabels:string[]=[]):Scenario{const parsed=scenarioSchema.parse(s);if(!parsed.assessedOn||!parsed.assessmentReason.trim())throw Error('Add an assessment date and rationale before recording a version.');if(parsed.history.length>=20)throw Error('Assessment history is full (20 versions). Export before starting a new scenario.');const {history,...snapshot}=parsed;return {...parsed,history:[...history,{id:crypto.randomUUID(),recordedAt:new Date().toISOString(),snapshot:structuredClone(snapshot),linkLabels:linkLabels.map(s=>s.slice(0,500)).slice(0,400)}]};}
export function evidenceForScenario(s:Scenario,e:Evidence):Scenario{return {...s,evidence:[...s.evidence,{...e,id:crypto.randomUUID(),capturedAt:new Date().toISOString()}]};}
