import type {Bounds} from './area-cache';
import {parcelInBounds,type ParcelGeometry} from './geo';
import {validPoint} from './location-core';
import {weatherJson,weatherPolygon,validWeatherBounds} from './weather-map';
export const heatService='https://mapservices.weather.noaa.gov/experimental/rest/services/NWS_HeatRisk/ImageServer';
export const smokeService='https://services2.arcgis.com/C8EMgrsFcRFL6LrL/arcgis/rest/services/NOAA_Satellite_Smoke_Detection_(v1)/FeatureServer/0';
export const heatClasses=[{name:'Little / no risk',color:'#6ebd45'},{name:'Minor',color:'#ffff00'},{name:'Moderate',color:'#ff9900'},{name:'Major',color:'#ff0000'},{name:'Extreme',color:'#ff00ff'}];
export type HeatDay={id:number;day:number;validAt:string;issuedAt?:string;ingestedAt?:string};
export type HeatImage={days:HeatDay[];selected:HeatDay;url:string;bounds:[[number,number],[number,number]]};
export type SmokeArea={id:string;density:'Light'|'Medium'|'Heavy';satellite:string;start?:string;end?:string;geometry:ParcelGeometry};
export type SmokeFeed={rows:SmokeArea[];invalid:number};
export const pollutants=['PM25','OZONE','PM10','NO2'] as const;
export type Pollutant=typeof pollutants[number];
export const pollutantNames:Record<Pollutant,string>={PM25:'PM2.5',OZONE:'Ozone',PM10:'PM10',NO2:'NO₂'};
export type AirReading={id:string;name:string;lat:number;lng:number;observedAt?:string;agency:string;values:Partial<Record<Pollutant,{aqi?:number;concentration?:number;unit?:string}>>};
export type AirFeed={rows:AirReading[];fileAt:string;modifiedAt?:string;url:string;invalid:number;partial?:boolean};
const iso=(v:any)=>typeof v==='number'&&Number.isFinite(v)&&v>0&&v<8640000000000000?new Date(v).toISOString():undefined;
const check=(d:any)=>{if(d?.error)throw Error('Weather service: '+(d.error.message||'request failed'));return d;};
export const datedOld=(s?:string,hours=3,now=Date.now())=>!s||!Number.isFinite(Date.parse(s))||now-Date.parse(s)>hours*3600000||Date.parse(s)>now+600000;
export function parseHeatDays(data:any):HeatDay[]{
 check(data);if(!Array.isArray(data?.features)||data.exceededTransferLimit||data.features.length>100)throw Error('HeatRisk forecast catalog incomplete.');
 const days=new Map<number,HeatDay>();
 for(const f of data.features){const a=f.attributes,m=/^HeatRisk_([1-7])_Mercator/.exec(a?.name||''),valid=iso(a?.idp_validtime);if(!m)continue;if(!Number.isSafeInteger(a.objectid)||a.objectid<1||!valid)throw Error('HeatRisk forecast date or raster ID unavailable.');const day=Number(m[1]);if(days.has(day))throw Error('HeatRisk forecast catalog has duplicate days.');days.set(day,{id:a.objectid,day,validAt:valid,issuedAt:iso(a.idp_filedate),ingestedAt:iso(a.idp_ingestdate)});}
 if(!days.size)throw Error('HeatRisk forecast grids unavailable.');return [...days.values()].sort((a,b)=>a.day-b.day);
}
export function heatParams(bbox:Bounds,day:HeatDay){if(!validWeatherBounds(bbox)||bbox[0]<-85||bbox[2]>85||!Number.isSafeInteger(day.id)||day.id<1)throw Error('Invalid HeatRisk map view or raster.');return new URLSearchParams({bbox:[bbox[1],bbox[0],bbox[3],bbox[2]].join(','),bboxSR:'4326',imageSR:'3857',size:'768,768',format:'png32',mosaicRule:JSON.stringify({mosaicMethod:'esriMosaicLockRaster',lockRasterIds:[day.id],mosaicOperation:'MT_FIRST'}),renderingRule:JSON.stringify({rasterFunction:'heatrisk.rft'})});}
export function imageBounds(data:any):[[number,number],[number,number]]{check(data);const e=data?.extent;if(!e||![3857,102100].includes(e.spatialReference?.latestWkid||e.spatialReference?.wkid)||[e.xmin,e.ymin,e.xmax,e.ymax].some(v=>typeof v!=='number'||!Number.isFinite(v)||Math.abs(v)>21000000)||e.xmin>=e.xmax||e.ymin>=e.ymax)throw Error('Weather image extent unavailable.');const p=(x:number,y:number):[number,number]=>[(2*Math.atan(Math.exp(y/6378137))-Math.PI/2)*180/Math.PI,x/6378137*180/Math.PI];return [p(e.xmin,e.ymin),p(e.xmax,e.ymax)];}
export async function fetchHeat(bbox:Bounds,day:number,fetcher:typeof fetch=fetch):Promise<HeatImage>{
 const days=parseHeatDays(await weatherJson(heatService+'/query?'+new URLSearchParams({f:'json',where:'1=1',outFields:'objectid,name,idp_validtime,idp_filedate,idp_ingestdate',returnGeometry:'false',resultRecordCount:'100'}),fetcher));const selected=days.find(d=>d.day===day);if(!selected)throw Error('Selected HeatRisk forecast day unavailable.');const p=heatParams(bbox,selected);p.set('f','json');const bounds=imageBounds(await weatherJson(heatService+'/exportImage?'+p,fetcher));p.set('f','image');return {days,selected,url:heatService+'/exportImage?'+p,bounds};
}
export function smokeTime(value:any){const m=/^(\d{4})(\d{3}) (\d{2})(\d{2})$/.exec(value||'');if(!m)return undefined;const [y,d,h,min]=m.slice(1).map(Number),max=new Date(Date.UTC(y,1,29)).getUTCMonth()===1?366:365;if(y<2000||y>2200||d<1||d>max||h>23||min>59)return undefined;return new Date(Date.UTC(y,0,d,h,min)).toISOString();}
export function parseSmoke(features:any[],bbox:Bounds):SmokeFeed{const rows:SmokeArea[]=[],seen=new Set<string>();let invalid=0;for(const f of features){const a=f?.properties,g=weatherPolygon(f?.geometry);if(!a||!Number.isSafeInteger(a.FID)||!['Light','Medium','Heavy'].includes(a.Density)||!g){invalid++;continue;}if(!parcelInBounds(g,bbox)||seen.has(String(a.FID)))continue;seen.add(String(a.FID));rows.push({id:String(a.FID),density:a.Density,satellite:String(a.Satellite||'Unknown').slice(0,100),start:smokeTime(a.Start),end:smokeTime(a.End_),geometry:g});}return {rows,invalid};}
export async function fetchSmoke(bbox:Bounds,fetcher:typeof fetch=fetch){const features:any[]=[];for(let page=0;page<4;page++){const p=new URLSearchParams({f:'geojson',where:'1=1',geometry:[bbox[1],bbox[0],bbox[3],bbox[2]].join(','),geometryType:'esriGeometryEnvelope',inSR:'4326',outSR:'4326',outFields:'FID,Satellite,Start,End_,Density',orderByFields:'FID ASC',resultOffset:String(page*500),resultRecordCount:'500'});const d=check(await weatherJson(smokeService+'/query?'+p,fetcher));if(!Array.isArray(d.features)||d.features.length>500)throw Error('Smoke polygon response invalid.');features.push(...d.features);if(!d.exceededTransferLimit&&!d.properties?.exceededTransferLimit&&d.features.length<500)return parseSmoke(features,bbox);}throw Error('Smoke polygons exceeded the 2,000-record limit; coverage incomplete.');}
export function csvRows(text:string){if(text.length>8000000)throw Error('AirNow monitor file exceeds size limit.');const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&(c===','||c==='\n')){row.push(cell.replace(/\r$/,''));cell='';if(c==='\n'){if(row.some(v=>v))rows.push(row);row=[];if(rows.length>20000)throw Error('AirNow monitor row limit exceeded.');}}else cell+=c;}if(quoted)throw Error('AirNow file has an unfinished quoted field.');if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row);}return rows;}
function airTime(date:string,time:string){const m=/^(\d{2})\/(\d{2})\/(\d{2}|\d{4})$/.exec(date),t=/^(\d{2}):(\d{2})$/.exec(time);if(!m||!t)return undefined;const month=+m[1],d=+m[2],y=m[3].length===2?2000+ +m[3]:+m[3],h=+t[1],min=+t[2];if(h>23||min>59)return undefined;const dt=new Date(Date.UTC(y,month-1,d,h,min));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===month-1&&dt.getUTCDate()===d?dt.toISOString():undefined;}
export function parseAirFile(text:string):{rows:AirReading[];invalid:number}{const csv=csvRows(text.replace(/^\uFEFF/,'')),header=csv.shift();if(!header||!['AQSID','SiteName','Status','Latitude','Longitude','ValidDate','ValidTime','DataSource',...pollutants.map(p=>p+'_AQI')].every(k=>header.includes(k)))throw Error('AirNow monitor columns changed.');const rows=new Map<string,AirReading>();let invalid=0;for(const cells of csv){if(cells.length!==header.length){invalid++;continue;}const a=Object.fromEntries(header.map((k,i)=>[k,cells[i]]));if(a.Status!=='Active')continue;const lat=a.Latitude.trim()?Number(a.Latitude):NaN,lng=a.Longitude.trim()?Number(a.Longitude):NaN;if(!/^[\w-]{3,25}$/.test(a.AQSID)||!validPoint(lat,lng)){invalid++;continue;}const values:AirReading['values']={};for(const p of pollutants){const raw=a[p+'_AQI'],aq=raw?.trim()?Number(raw):NaN,rawc=a[p],c=rawc?.trim()?Number(rawc):NaN;values[p]={aqi:Number.isFinite(aq)&&aq>=0&&aq<=500?aq:undefined,concentration:Number.isFinite(c)&&c!==-999?c:undefined,unit:a[p+'_Unit']?.slice(0,30)||undefined};}const r:AirReading={id:a.AQSID,name:a.SiteName.slice(0,200),lat,lng,agency:a.DataSource.slice(0,250),observedAt:airTime(a.ValidDate,a.ValidTime),values},prior=rows.get(r.id);if(!prior||Date.parse(r.observedAt||'')>Date.parse(prior.observedAt||'')||!prior.observedAt&&r.observedAt)rows.set(r.id,r);}return {rows:[...rows.values()],invalid};}
export function latestAirFile(xml:string,prefix:string){if(xml.length>1000000||/<IsTruncated>\s*true\s*<\/IsTruncated>/.test(xml))throw Error('AirNow file directory incomplete.');if(!xml.includes('<ListBucketResult'))throw Error('AirNow file directory changed format.');const entries:{key:string;fileAt:string;modifiedAt?:string}[]=[];for(const m of xml.matchAll(/<Contents>([\s\S]*?)<\/Contents>/g)){const key=/<Key>([^<]+)<\/Key>/.exec(m[1])?.[1],modified=/<LastModified>([^<]+)<\/LastModified>/.exec(m[1])?.[1];if(!key?.startsWith(prefix))continue;const t=/^airnow\/\d{4}\/\d{8}\/HourlyAQObs_(\d{4})(\d{2})(\d{2})(\d{2})\.dat$/.exec(key);if(!t)continue;const date=airTime(`${t[2]}/${t[3]}/${t[1]}`,`${t[4]}:00`);if(date)entries.push({key,fileAt:date,modifiedAt:modified&&Number.isFinite(Date.parse(modified))?modified:undefined});}return entries.sort((a,b)=>b.fileAt.localeCompare(a.fileAt))[0];}
async function sourceText(url:string,fetcher:typeof fetch,limit:number){const r=await fetcher(url,{redirect:'error',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error('AirNow returned HTTP '+r.status);const s=await r.text();if(s.length>limit)throw Error('AirNow response exceeds size limit.');return s;}
export async function fetchAirMonitors(fetcher:typeof fetch=fetch,now=new Date()):Promise<AirFeed>{for(let back=0;back<2;back++){const d=new Date(now.getTime()-back*86400000),stamp=d.toISOString().slice(0,10).replace(/-/g,''),prefix=`airnow/${stamp.slice(0,4)}/${stamp}/HourlyAQ`;const latest=latestAirFile(await sourceText('https://s3-us-west-1.amazonaws.com/files.airnowtech.org/?'+new URLSearchParams({prefix}),fetcher,1000000),prefix);if(!latest)continue;const url='https://files.airnowtech.org/'+latest.key;return {...parseAirFile(await sourceText(url,fetcher,8000000)),fileAt:latest.fileAt,modifiedAt:latest.modifiedAt,url};}throw Error('No recent AirNow monitor file is published.');}
export function scopeAir(feed:AirFeed,bbox:Bounds):AirFeed{const rows=feed.rows.filter(r=>r.lat>=bbox[0]&&r.lat<=bbox[2]&&r.lng>=bbox[1]&&r.lng<=bbox[3]);return {...feed,rows:rows.slice(0,400),partial:rows.length>400};}
export function aqiClass(aqi?:number){if(aqi===undefined)return {name:'Unavailable',color:'#8d9aa6'};return aqi<=50?{name:'Good',color:'#00e400'}:aqi<=100?{name:'Moderate',color:'#ffff00'}:aqi<=150?{name:'Unhealthy for sensitive groups',color:'#ff7e00'}:aqi<=200?{name:'Unhealthy',color:'#ff0000'}:aqi<=300?{name:'Very unhealthy',color:'#8f3f97'}:{name:'Hazardous',color:'#7e0023'};}
