import assert from 'node:assert/strict';
import {lineIntersectsGeometry} from '../lib/geo.ts';
import {routeFindings,distanceToRoute,routeFeature,sharedRouteMarks,routeMiles} from '../lib/routes.ts';
import {routesSchema} from '../lib/route-schema.ts';
const box={type:'Polygon',coordinates:[[[0,0],[4,0],[4,4],[0,4],[0,0]],[[1,1],[1,3],[3,3],[3,1],[1,1]]]};
assert.equal(lineIntersectsGeometry([[2,1.5],[2,2.5]],box),false,'line wholly in hole');
assert.equal(lineIntersectsGeometry([[2,-1],[2,5]],box),true,'endpoints outside but line crosses');
assert.equal(lineIntersectsGeometry([[0,-1],[0,5]],box),true,'boundary touch');
assert.equal(lineIntersectsGeometry([[-1,-1],[-1,5]],box),false);
assert.equal(lineIntersectsGeometry([[0.5,0.5],[0.5,0.6]],box),true);
const multi={type:'MultiPolygon',coordinates:[box.coordinates,[[[10,10],[11,10],[11,11],[10,11],[10,10]]]]};
assert.equal(lineIntersectsGeometry([[10.5,9],[10.5,12]],multi),true);
const points=[[30.35,-97.56],[30.35,-97.54]];
assert(distanceToRoute([30.3505,-97.55],points)<100);
assert(distanceToRoute([30.352,-97.55],points)>100);
assert(distanceToRoute([30.35,-97.57],points)>100,'clamp beyond endpoint');
assert(Number.isFinite(distanceToRoute(points[0],[points[0],points[0]])));
assert(routeMiles(points)>1&&routeMiles(points)<1.3);
const route={id:'r1',name:'Grocery',destination:'Store',role:'Primary',points,notes:'Check bridge',marks:[{id:'m',name:' Main exit ',kind:'Exit',point:points[0]}]};
const flood={id:'f',name:'Zone AE',lat:30.35,lng:-97.55,source:'FloodPro FEMA',flood:{model:'FEMA'},geometry:{type:'Polygon',coordinates:[[[-97.555,30.349],[-97.545,30.349],[-97.545,30.351],[-97.555,30.351],[-97.555,30.349]]]}};
const cross={id:'c',name:'Crossing',lat:30.3505,lng:-97.55,source:'Inventory',crossing:{}};
const findings=routeFindings(route,[flood,cross,{...cross,id:'far',lat:30.36}]);
assert.equal(findings.floods.length,1);assert.equal(findings.segments[0].floods.length,1);assert.deepEqual(findings.crossings.map(x=>x.id),['c']);
assert.deepEqual(routeFeature(route).geometry.coordinates,[[-97.56,30.35],[-97.54,30.35]]);
const alternate={...route,id:'r2',role:'Alternate',marks:[{...route.marks[0],name:'main EXIT'}]};
assert.equal(sharedRouteMarks(route,[route,alternate]).length,1);assert.equal(sharedRouteMarks(route,[route]).length,0);
assert.deepEqual(routesSchema.parse(undefined),[],'backward compatible old studies');
assert.deepEqual(JSON.parse(JSON.stringify(routesSchema.parse([route,alternate]))),[route,alternate],'roundtrip preserves geometry, notes, marks');
assert.equal(routesSchema.safeParse([{...route,points:[points[0],points[0]]}]).success,false);
assert.equal(routesSchema.safeParse([{...route,points:[[95,0],points[1]]}]).success,false);
assert.equal(routesSchema.safeParse([{...route,points:[points[0]]}]).success,false);
console.log('Route geometry, nearby crossings, shared dependencies, GeoJSON and backward-compatible storage validation passed.');
