import assert from 'node:assert/strict';
import {hazardNames,nriRow,metricNumber,collectHomeRisk,fetchRiskArea} from '../lib/hazards.ts';
const geometry={type:'Polygon',coordinates:[[[-97.56,30.36],[-97.54,30.36],[-97.54,30.38],[-97.56,30.36]]]};
const properties={NRI_ID:'T48453042400',NRI_VER:'Example release',COUNTY:'Travis',STCOFIPS:'48453',TRACTFIPS:'48453042400',HAIL_RISKS:90,HAIL_RISKR:'Relatively High',HAIL_EALT:1000,HWAV_RISKS:null,HWAV_EALT:-9999,AVLN_RISKS:0,AVLN_RISKR:'No Rating'};
const row=nriRow({properties,geometry},'tract','2026-10-07T00:00:00Z');
assert.equal(row.risk.hazards.length,18);assert.equal(Object.keys(hazardNames).length,18);
assert.equal(row.risk.hazards.find(h=>h.code==='HWAV').score,null);assert.equal(row.risk.hazards.find(h=>h.code==='HWAV').expectedAnnualLoss,null);
assert.equal(row.risk.hazards.find(h=>h.code==='AVLN').score,0);assert.equal(metricNumber('90'),null);assert.equal(metricNumber(101,100),null);
assert.equal(row.risk.tractFips,'48453042400');assert.equal(row.risk.version,'Example release');assert.match(row.detail,/not probabilities or current alerts/);
assert.throws(()=>nriRow({properties:{...properties,TRACTFIPS:''},geometry},'tract',null));
assert.throws(()=>nriRow({properties,geometry:{type:'Point',coordinates:[-97.5,30.3]}},'tract',null));
const requests=[];
const fake=async url=>{const u=new URL(url);requests.push(u);if(u.pathname.includes('/content/items/'))return Response.json({owner:'FEMA_NationalRiskIndex',url:'https://services.arcgis.com/XG15cJAlne2vxtgt/arcgis/rest/services/National_Risk_Index_Census_Tracts/FeatureServer',modified:1791331200000});return Response.json({features:[{properties,geometry}],exceededTransferLimit:false});};
const matches=await collectHomeRisk('tract',[30.37,-97.55],fake);assert.equal(matches.length,1);assert.equal(requests[1].searchParams.get('geometry'),'-97.55,30.37');assert.equal(requests[1].searchParams.get('inSR'),'4326');
let pages=0;const capped=await fetchRiskArea([30.36,-97.56,30.38,-97.54],async url=>String(url).includes('/content/items/')?fake(url):(pages++,Response.json({features:[{properties,geometry}],exceededTransferLimit:true})));
assert.equal(pages,5);assert.equal(capped.complete,false);
await assert.rejects(()=>collectHomeRisk('tract',[30.37,-97.55],async url=>String(url).includes('/content/items/')?fake(url):Response.json({features:[]})),/No FEMA profile/);
await assert.rejects(()=>collectHomeRisk('tract',[30.37,-97.55],async()=>Response.json({owner:'Unverified publisher'})),/metadata could not be verified/);
console.log('FEMA profiles: geographic IDs, release provenance, missing vs zero metrics, point lookup, caps and source failures passed.');
