import assert from 'node:assert/strict';
import {buildAtakKml,makeKmz,defaultAtakOptions} from '../lib/atak.ts';
import {emptyContext,restorePortfolio,newLocation} from '../lib/locations.ts';
import {newRadioChannel} from '../lib/radio.ts';
const work={...newLocation('Other test location','Work'),id:'work',home:{address:'PRIVATE OTHER ADDRESS',point:[39.5,-77.5]}};
const p=restorePortfolio({...emptyContext(),schemaVersion:12,home:{address:'PRIVATE ACTIVE ADDRESS',point:[38.9,-77.04]},areas:{aor:[[38.8,-77.1],[39,-77.1],[39,-77]],aoi:[]},notes:[{id:'n',name:'Note <script>',category:'Observation',source:'Test source',lat:38.91,lng:-77.02,detail:'Unsafe <script>alert(1)</script> & text \u0000'}],locations:[work],routes:[{id:'r',name:'Connected route',fromLocationId:'home',toLocationId:'work',role:'Primary',destination:'Test destination',points:[[38.9,-77.04],[39.5,-77.5]],notes:'Unverified',marks:[{id:'m',name:'Bridge',kind:'Bridge',point:[39,-77.1]}]},{id:'manual',name:'Unassigned route',role:'Alternate',destination:'',points:[[38.9,-77.04],[38.91,-77.05]],notes:'',marks:[]}],radioPlan:[{...newRadioChannel(),name:'Weather test',service:'Weather radio',receiveMHz:'162.400'}]});
const a=buildAtakKml(p,defaultAtakOptions,[],'2026-10-08T12:00:00Z');assert.equal(a.counts.locations,1);assert.equal(a.counts.routes,1);assert.equal(a.counts.routeFeatures,1);assert.equal(a.counts.frequencies,1);assert(a.kml.includes('-77.04,38.9,0'));assert(!a.kml.includes('PRIVATE ACTIVE ADDRESS'));assert(!a.kml.includes('PRIVATE OTHER ADDRESS'));assert(!a.kml.includes('Unassigned route'));assert(a.warnings.some(w=>w.includes('entire path')));assert(!a.kml.includes('<script>'));assert(!a.kml.includes('\u0000'));assert(!a.kml.includes('<NetworkLink'));assert(!a.kml.includes('<href>'));assert(a.kml.includes('162.400'));
const all=buildAtakKml(p,{...defaultAtakOptions,allLocations:true,addresses:true});assert.equal(all.counts.locations,2);assert.equal(all.counts.routes,2);assert(all.kml.includes('PRIVATE OTHER ADDRESS'));
const record={id:'poly',name:'Public polygon',lat:38.9,lng:-77.04,category:'Parcel',source:'Fixture',retrievedAt:'2026-10-01T00:00:00Z',stale:true,geometry:{type:'MultiPolygon',coordinates:[[[[-77.1,38.8],[-77,38.8],[-77,39],[-77.1,38.8]],[[-77.08,38.82],[-77.06,38.82],[-77.06,38.84],[-77.08,38.82]]],[[[-77.3,38.6],[-77.2,38.6],[-77.2,38.7],[-77.3,38.6]]]]}};
const layers=buildAtakKml(p,{...defaultAtakOptions,publicLayers:true},[record,record]);assert.equal(layers.counts.publicRecords,1);assert(layers.kml.includes('<innerBoundaryIs>'));assert(layers.kml.includes('<MultiGeometry>'));assert(layers.kml.includes('Stale snapshot'));assert(layers.kml.includes('2026-10-01'));
assert.throws(()=>buildAtakKml(p,{...defaultAtakOptions,locations:false,boundaries:false,namedAreas:false,observations:false,routes:false,radio:false}));assert.throws(()=>buildAtakKml(p,{...defaultAtakOptions,publicLayers:true},[{...record,geometry:undefined,lat:999}]));
const archive=makeKmz(layers.kml);assert.equal(new DataView(archive.buffer).getUint32(0,true),0x04034b50);assert(archive.length>layers.bytes);if(process.env.ATAK_FIXTURE_PATH){const {writeFileSync}=await import('node:fs');writeFileSync(process.env.ATAK_FIXTURE_PATH,archive);}
console.log('ATAK passed: active/whole-study privacy, linked and unassigned routes, WGS84 coordinate order, XML/HTML escaping, holes/multipolygons, source dates, deduplication, empty/invalid selections and KMZ creation.');
