import assert from 'node:assert/strict';
import {parseAlpr,fetchAlpr,alprQuery,alprLimit} from '../lib/alpr.ts';
import {cacheView} from '../lib/area-cache.ts';
import {categories,layerGroups} from '../lib/layer-groups.ts';
import {readFileSync} from 'node:fs';
import {activityName} from '../lib/collection-activity.ts';
const bbox=[30,-98,30.5,-97.5];
const node={type:'node',id:10,lat:30.2,lon:-97.8,timestamp:'2026-01-01T12:00:00Z',tags:{'surveillance:type':'ALPR',manufacturer:'Flock Safety',operator:'Synthetic operator',direction:'90'}};
const d=parseAlpr({elements:[node,node,{...node,id:11,lat:40},{type:'way',id:12,center:{lat:30.3,lon:-97.7},tags:{'surveillance:type':'ALPR'}}]},bbox);
assert.equal(d.rows.length,2);assert.equal(d.complete,true);assert.equal(d.rows[0].updatedDate,node.timestamp);assert.equal(d.rows[0].date,undefined);assert.match(d.rows[0].detail,/OSM edit/);assert.match(d.rows[0].detail,/ODbL/);assert.match(d.rows[1].detail,/Approximate centre/);assert.equal(d.rows[1].updatedDate,undefined);
assert.equal(parseAlpr({elements:[]},bbox).complete,true);
assert.equal(parseAlpr({elements:[{...node,lat:NaN}]},bbox).complete,false);
assert.equal(parseAlpr({elements:[{...node,lat:null,lon:null}]},bbox).rows.length,0);
assert.equal(parseAlpr({elements:Array(alprLimit).fill(node)},bbox).complete,false);
assert.throws(()=>parseAlpr({remark:'timed out',elements:[]},bbox),/incomplete/);
assert.throws(()=>parseAlpr({},bbox),/Invalid/);
assert.throws(()=>alprQuery([0,0,90,180]),/smaller/);
assert.match(alprQuery(bbox),/out meta center 2000/);
let calls=0;
const live=await fetchAlpr(bbox,async()=>{calls++;return calls===1?new Response('',{status:429}):Response.json({elements:[node]});});
assert.equal(calls,2);assert.equal(live.rows.length,1);
await assert.rejects(fetchAlpr(bbox,async()=>Response.json({remark:'failed',elements:[]})),/does not mean/);
const snap={bbox,rows:d.rows,complete:true,fetchedAt:'2026-01-01T00:00:00Z'};
const fresh=cacheView('alpr',[30.1,-97.9,30.25,-97.75],[snap],Date.parse('2026-01-01T01:00:00Z'));
assert.equal(fresh.coverage,100);assert.equal(fresh.rows.length,1);
const stale=cacheView('alpr',bbox,[snap],Date.parse('2026-01-03T00:00:00Z'));
assert.equal(stale.partial,true);assert.equal(stale.rows[0].stale,true);
assert.equal(cacheView('alpr',[40,-98,40.2,-97.8],[snap]).rows.length,0);
assert.ok(categories.includes('ALPR cameras'));assert.ok(layerGroups.some(g=>g.name==='Cameras & surveillance'));
assert.match(readFileSync(new URL('../lib/category-icons.tsx',import.meta.url),'utf8'),/'ALPR cameras':/);assert.match(activityName('/api/data?kind=alpr'),/ALPR/);
console.log('ALPR parser, bounds, provider fallback, failure, cache and UI integration checks passed');
