import assert from 'node:assert/strict';
import {reviewQueue,recordReview,reviewKey,dateAge} from '../lib/reviews.ts';
import {emptyContext,newLocation,restorePortfolio,portfolioExport,updateActive} from '../lib/locations.ts';
import {newQuestion,newRequirement,evidenceSnapshot} from '../lib/collection.ts';
import {newScenario} from '../lib/scenarios.ts';
import {newServicePlan} from '../lib/dependencies.ts';
import {isOlderStudyWrite} from '../lib/study-schema.ts';
const today='2026-10-07',now=new Date(today+'T12:00:00Z');
const source={id:'crossing',name:'Public crossing report',source:'Public agency',category:'Public services',url:'https://example.org/crossing',date:'2026-10-01',detail:'Reported open',lat:30,lng:-98};
const q={...newQuestion(),id:'same-id',question:'Is access available?',status:'Answered',assessment:'Unknown until checked',assessedOn:'2026-10-01',reviewOn:today,evidence:[evidenceSnapshot(source,'Source')]};
const r={...newRequirement(),task:'Check alternate access',reviewOn:today,evidenceIds:[q.evidence[0].id]};q.requirements=[r];
const work={...newLocation('Work','Work'),id:'work',collection:{purpose:'',questions:[{...newQuestion(),id:q.id,question:'Work access?',reviewOn:'2026-10-06',evidence:[evidenceSnapshot(source,'Source')]}]}};
let p=restorePortfolio({...emptyContext(),schemaVersion:9,collection:{purpose:'Access study',questions:[q]},scenarios:[newScenario()],servicePlans:[newServicePlan(source)],routes:[{id:'route',name:'Access route',role:'Primary',destination:'Public test destination',notes:'Unverified',marks:[],points:[[30,-98],[30.01,-98.01]]}],locations:[work],activeLocationId:'home'});
assert.equal(p.schemaVersion,12);assert.equal(p.reviews.settings.intervalDays,90);assert.equal(p.reviews.history.length,0);assert(isOlderStudyWrite(9,10));
const changed={...source,detail:'Reported closed',retrievedAt:'2026-10-07T12:00:00Z'};
let queue=reviewQueue(p,[changed],false,today);let item=queue.find(i=>i.target.type==='Question');
assert(item.reasons.some(r=>r.kind==='Due'));assert(item.reasons.some(r=>r.kind==='Source changed'&&r.before.includes('Reported open')&&r.after.includes('Reported closed')));assert.equal(item.matched,1);assert(!queue.some(i=>i.target.locationId==='work'));assert(queue.some(i=>i.target.type==='Route'));
assert(!reviewQueue(p,[{...source,retrievedAt:'2030-01-01'}],false,today).find(i=>i.key===item.key).reasons.some(r=>r.kind==='Source changed'),'Retrieval times are not source changes');
assert(!reviewQueue(p,[{...changed,source:'Other agency'}],false,today).find(i=>i.key===item.key).reasons.some(r=>r.kind==='Source changed'),'Source identity must match');
assert.equal(reviewQueue(p,[],false,today).find(i=>i.key===item.key).matched,0,'Absence does not mean removal');
const all=reviewQueue(p,[changed],true,today),workItem=all.find(i=>i.target.locationId==='work'&&i.target.type==='Question');assert.equal(workItem.matched,0);assert.equal(workItem.sourceCheck,false);assert.notEqual(workItem.key,item.key,'Same IDs at different locations remain separate');
assert.throws(()=>recordReview(p,item,'', '2027-01-05',now));assert.throws(()=>recordReview(p,item,'Checked official source',today,now));
p=recordReview(p,item,'Checked official source; closure needs a route assessment.','2027-01-05',now);
assert.equal(p.collection.questions[0].assessment,q.assessment);assert.equal(p.collection.questions[0].assessedOn,q.assessedOn);assert.equal(p.collection.questions[0].status,'Answered');assert.equal(p.collection.questions[0].evidence[0].detail,'Reported open');assert.equal(p.locations[0].collection.questions[0].reviewOn,'2026-10-06');
queue=reviewQueue(p,[changed],false,today);item=queue.find(i=>i.target.type==='Question');assert(!item.reasons.some(r=>r.kind==='Due'||r.kind==='Source changed'),'Reviewed differences acknowledged without rewriting captured evidence');assert(item.lastReview.note.includes('closure needs'));
assert(reviewQueue(p,[{...changed,detail:'Caution reported'}],false,today).find(i=>i.key===item.key).reasons.some(r=>r.kind==='Source changed'),'Later changes reappear');
assert(reviewQueue(p,[{...changed,stale:true}],false,today).find(i=>i.key===item.key).reasons.some(r=>r.kind==='Stale source'));
p=recordReview(p,workItem,'Check work-area original source','2027-01-06',now);assert.equal(p.locations[0].collection.questions[0].reviewOn,'2027-01-06');assert.equal(p.collection.questions[0].reviewOn,'2027-01-05');
const req=reviewQueue(p,[changed],false,today).find(i=>i.target.type==='Requirement');p=recordReview(p,req,'Requirement remains open pending inspection','2027-01-08',now);assert.equal(p.collection.questions[0].requirements[0].status,'Open');assert.equal(p.collection.questions[0].requirements[0].reviewOn,'2027-01-08');assert(reviewQueue(p,[changed],false,today).find(i=>i.key===req.key).reasons.some(r=>r.kind==='Unresolved'));
const route=reviewQueue(p,[],false,today).find(i=>i.target.type==='Route');p=recordReview(p,route,'Reviewed map; passage remains unverified','2026-10-20',now);assert.equal(reviewQueue(p,[],false,'2026-10-20').find(i=>i.key===route.key).reasons.some(r=>r.kind==='Due'),true);assert.equal(p.routes[0].notes,'Unverified');
const aged=restorePortfolio({...p,collection:{purpose:'',questions:[{...q,evidence:[{...q.evidence[0],date:'2020-01-01'}]}]}});assert(reviewQueue(aged,[],false,today).find(i=>i.target.type==='Question').reasons.some(r=>r.kind==='Stale evidence'));
const undated=restorePortfolio({...p,collection:{purpose:'',questions:[{...q,evidence:[{...q.evidence[0],date:''}]}]}});assert(reviewQueue(undated,[],false,today).find(i=>i.target.type==='Question').reasons.some(r=>r.kind==='Undated evidence'));assert.equal(dateAge('unknown',today),null);
const long={...source,detail:'x'.repeat(3000)};const longP=restorePortfolio({...p,collection:{purpose:'',questions:[{...q,requirements:[],evidence:[evidenceSnapshot(long,'Source')]}]}});assert(!reviewQueue(longP,[long],false,today).find(i=>i.target.type==='Question').reasons.some(r=>r.kind==='Source changed'),'Snapshot truncation does not create false differences');
assert.deepEqual(restorePortfolio(portfolioExport(p).portfolio),p);assert.deepEqual(updateActive(p,s=>({...s,sections:{Terrain:'Updated'}})).reviews,p.reviews);
assert.throws(()=>restorePortfolio({...p,reviews:{...p.reviews,settings:{...p.reviews.settings,intervalDays:0}}}));assert.throws(()=>restorePortfolio({...p,reviews:{...p.reviews,history:[p.reviews.history[0],p.reviews.history[0]]}}));
assert.throws(()=>recordReview({...p,routes:[]},route,'Check removed route','2027-01-01',now),/no longer exists/);
assert.equal(reviewKey(item.target),item.key);console.log('Review checks passed: v9 migration, old-write protection, source identity/truncation, missing/stale records, acknowledgment and later changes, location isolation, due dates, untouched judgments/evidence, route scheduling, history validation and export.');
