import assert from 'node:assert/strict';
import {restorePortfolio,emptyContext,newLocation,updateActive,activeStudy} from '../lib/locations.ts';
import {makeBackup,parseBackup} from '../lib/backup.ts';
import {createSharedGroup,shareCandidates,stageContributions,makeSharedPackage,parseSharedPackage,previewSharedMerge,addSharedReview,reviewSummary,sharedMapRecords,MAX_SHARED_BYTES} from '../lib/sharing.ts';
import {isOlderStudyWrite} from '../lib/study-schema.ts';
const note={id:'fixture-note',name:'Footbridge inspection',lat:40,lng:-105,category:'Observation',source:'Field visit',date:'2026-10-01',detail:'Deck needs inspection',confidence:'Unverified',url:'https://example.org/bridge'};
const work=newLocation('Fixture work','Work'),other=newLocation('Fixture other','Other');
let a=restorePortfolio({...emptyContext(),schemaVersion:12,home:{address:'PRIVATE ADDRESS',point:[40,-105]},notes:[note],sections:{Terrain:'PRIVATE NARRATIVE'},locations:[{...work,notes:[{...note,id:'work-note'}]},other],routes:[{id:'fixture-route',name:'Walking route',destination:'PRIVATE DESTINATION',role:'Primary',fromLocationId:work.id,toLocationId:other.id,notes:'Inspect bridge',points:[[40,-105],[40.01,-105.01]],marks:[]}],activeLocationId:work.id});
assert.equal(a.schemaVersion,18);assert.deepEqual(a.sharing,{member:null,groups:[]});assert(isOlderStudyWrite(15,16));assert.equal(activeStudy(a).schemaVersion,18);
a=createSharedGroup(a,'Fixture colleagues','Contributor A');const groupId=a.sharing.groups[0].id;
assert(!shareCandidates(a).some(c=>c.key==='note:fixture-note'));assert(shareCandidates(a).some(c=>c.key==='route:fixture-route'));
a=stageContributions(a,groupId,['note:work-note','route:fixture-route']);const records=a.sharing.groups[0].records,recordId=records[0].id,revisionId=records[0].revisions[0].id;
const staged=stageContributions(a,groupId,['note:work-note']);assert.deepEqual(staged,a);
const pkg=makeSharedPackage(a,groupId,[recordId]),json=JSON.stringify(pkg);
assert(!json.includes('PRIVATE'));assert(!json.includes('locationId'));assert(!json.includes('links'));assert.equal(pkg.records.length,1);assert.deepEqual(parseSharedPackage(json),pkg);
assert.deepEqual(makeSharedPackage(a,groupId,[]).records,[]);assert.throws(()=>parseSharedPackage(json+'x'));assert.throws(()=>parseSharedPackage(' '.repeat(MAX_SHARED_BYTES+1)),/exceeds/);
assert.throws(()=>parseSharedPackage(JSON.stringify({...pkg,records:[pkg.records[0],pkg.records[0]]})));assert.throws(()=>parseSharedPackage(JSON.stringify({...pkg,home:{point:[0,0]}})));
const invalid=structuredClone(pkg);invalid.records[0].revisions[0].payload.point=[1000,0];assert.throws(()=>parseSharedPackage(JSON.stringify(invalid)));
const malicious=structuredClone(pkg);malicious.records[0].revisions[0].payload.url='javascript:alert(1)';assert.throws(()=>parseSharedPackage(JSON.stringify(malicious)));
let b=restorePortfolio({...emptyContext(),schemaVersion:12,locations:[newLocation('Recipient work','Work')],notes:[{...note,name:'Keep recipient private note'}],areas:{aor:[[40,-105],[40,-104.9],[40.1,-105]],aoi:[]},routes:[]});const bWork=b.locations[0].id;
const before=JSON.stringify(b),first=previewSharedMerge(b,pkg,bWork);assert.equal(JSON.stringify(b),before);assert.equal(first.added,1);assert.equal(first.newGroup,true);b=first.next;
assert.deepEqual(b.notes,[{...note,name:'Keep recipient private note'}]);assert.equal(b.areas.aor.length,3);assert.equal(sharedMapRecords(b).length,0);assert.equal(sharedMapRecords({...b,activeLocationId:bWork}).length,1);
const again=previewSharedMerge(b,pkg,bWork);assert.equal(again.added,0);assert.equal(again.revisions,0);assert.deepEqual(again.next,b);assert.throws(()=>previewSharedMerge(b,pkg,'home'),/another location/);
b=createSharedGroup({...b,activeLocationId:bWork},'Recipient private group','Contributor B');
b=addSharedReview(b,groupId,recordId,{revisionId,status:'Confirmed',observedAt:'2026-10-02T12:00:00Z',comment:'Checked deck in person',reviewBy:'2026-10-12T12:00:00Z'});
const reviewBundle=makeSharedPackage(b,groupId,[recordId],a.sharing.member.id);a=previewSharedMerge(a,reviewBundle,work.id).next;
assert.equal(reviewSummary(a.sharing.groups[0].records[0],revisionId,Date.parse('2026-10-09T12:00:00Z')).confirmed,1);
assert.equal(reviewSummary(a.sharing.groups[0].records[0],revisionId,Date.parse('2026-10-13T12:00:00Z')).confirmed,0);
const reviewAgain=previewSharedMerge(a,reviewBundle,work.id);assert.equal(reviewAgain.reviews,0);
a=updateActive(a,s=>({...s,notes:s.notes.map(n=>({...n,detail:'Deck repaired; needs new inspection'}))}));a=stageContributions(a,groupId,['note:work-note']);
const latest=a.sharing.groups[0].records[0].revisions[1].id;assert.equal(reviewSummary(a.sharing.groups[0].records[0],latest).confirmed,0);
const updateBundle=makeSharedPackage(a,groupId,[recordId]),newer=previewSharedMerge(b,updateBundle,bWork);assert.equal(newer.revisions,1);assert.equal(newer.next.sharing.groups[0].selected[recordId],revisionId);b=newer.next;
b=addSharedReview(b,groupId,recordId,{revisionId,status:'Disputed',observedAt:'2026-10-03T12:00:00Z',comment:'Damage remains on west end'});
const record=b.sharing.groups[0].records[0];assert.equal(record.reviews.length,2);assert.equal(reviewSummary(record,revisionId).disputed,1);assert.equal(reviewSummary(record,revisionId).confirmed,0);
const offsetRecord=structuredClone(record);offsetRecord.reviews[0].createdAt='2026-10-09T13:00:00+02:00';offsetRecord.reviews[1].createdAt='2026-10-09T12:00:00Z';
assert.equal(reviewSummary(offsetRecord,revisionId,Date.parse('2026-10-09T12:30:00Z')).disputed,1,'Review order must compare instants across timezone offsets');
const conflict=structuredClone(pkg);conflict.records[0].revisions[0].payload.detail='Changed same immutable ID';const saved=JSON.stringify(b);assert.throws(()=>previewSharedMerge(b,conflict,bWork),/different content/);assert.equal(JSON.stringify(b),saved);
const reordered=JSON.parse(json);reordered.records[0].revisions[0].payload=Object.fromEntries(Object.entries(reordered.records[0].revisions[0].payload).reverse());assert.equal(previewSharedMerge(b,reordered,bWork).revisions,0);
assert.throws(()=>previewSharedMerge(b,{...pkg,records:Array(201).fill(pkg.records[0])},bWork));assert.throws(()=>parseSharedPackage(JSON.stringify({...pkg,formatVersion:99})));
const roundtrip=parseBackup(JSON.stringify(makeBackup(b,[]))).backup.study;assert.deepEqual(roundtrip,b);
assert.throws(()=>restorePortfolio({...b,locations:[]}));
console.log('Shared studies passed: v16 migration, selective private-scope export, source dates, location mapping, preview without mutation, idempotent exchange, immutable collision rejection, revision-specific dated reviews, expired confirmations, disagreement history, validation limits and backup round trip.');
